### ISSUE TITLE
[MC1.8.9-0.0.2.2] Crash when browsing BC Facades in JEI

### ISSUE THREAD

**Issue by Xiaminou** [Chisel-Team/Chisel#100]
Crashes whenever I browse any of the buildcraft facades.

Crash Report: http://pastebin.com/3ehjC9D6

**Comment by minecreatr** [comment]
Are you sure this is a chisel related crash? It apears to be related to an obj model and we do not use those.

**Comment by tterrag1098** [comment]
Yeah I'd definitely report this to Buildcraft.

**Comment by Xiaminou** [comment]
I have, and yes I'm pretty sure it's chisel, it crashed right after I added it and was fixed when I removed it.

**Comment by tterrag1098** [comment]
I would have no idea how to fix this, I don't know the buildcraft code. The issue on their repo will be more productive.

**Comment by mezz** [comment]
This crash is suppressed in the latest JEI, and I don't think chisel is the cause.

**Comment by tterrag1098** [comment]
Yes, this is not a chisel issue
