### ISSUE TITLE
Blocks are gigantic when held in inventory

### ISSUE THREAD

**Issue by Alaric323** [Chisel-Team/Chisel#102]
Creative spawned, since Issue #96 exists.  Happens with at least 20 other blocks.
![capture](https://cloud.githubusercontent.com/assets/4038592/12329200/22243b2a-baad-11e5-85fe-be2599a5b059.PNG)

**Comment by ghost** [comment]
That's a lot of lead you have there.

**Comment by Drullkus** [comment]
Enough metal to make metal underpants to never float on top of water ever again :P

**Comment by tterrag1098** [comment]
This was fixed a few alphas ago
