### ISSUE TITLE
Chisel causes dev console spam

### ISSUE THREAD

**Issue by Alaric323** [Chisel-Team/Chisel#103]
The end of a huge amount of console spam (Final log is about 30 Megabytes in size):
http://puu.sh/my25X/aa0bec2c92.txt
Issue with JEI.  Only happens when chisel is added.

I figured you guys have enough code to look through, so that small chunk is enough.  I've saved the full log though, if you need it.

**Comment by tterrag1098** [comment]
This is the problem with logging errors without cleaning up their cause. However, seems like an issue with BC facades.

**Comment by Alaric323** [comment]
My bad.  I'll go post the issue with them then.
