### ISSUE TITLE
JEI Integration needs some polish

### ISSUE THREAD

**Issue by mezz** [Chisel-Team/Chisel#104]
![2016-01-16_15 59 02](https://cloud.githubusercontent.com/assets/916092/12375154/1fbaa3d8-bc6a-11e5-871a-a1e4a2e0a952.png)

Using Chisel-MC1.8.9-0.0.2.6
- [x] Items overflow the box
- [x] the recipe blocks the recipe paging at the top when the screen is small
- [x] there's some orange thing to the right side.

**Comment by Drullkus** [comment]
Güd jorb

**Comment by Shahelion** [comment]
What is that orange thing, anyway?

**Comment by TehNut** [comment]
It highlights the block you looked up the recipe for.

**Comment by Drullkus** [comment]
Issue still persists in Chisel's JEI thing (look at Factory Blocks)
