### ISSUE TITLE
[Minor] [1.7.10] Name Inconsistency

### ISSUE THREAD

**Issue by Shahelion** [Chisel-Team/Chisel#106]
Shouldn't it be Ender Bismuth? Doesn't really look like any of the other circuit-types.
https://i.gyazo.com/ba9e81b60e9f0b6016cba2ce2dabe35c.mp4

**Comment by Drullkus** [comment]
Ah, right. Will do :P

**Comment by Drullkus** [comment]
Ender Bismuth no longer exists
