### ISSUE TITLE
[1.8.9] ALL BLOCKS BREAK INSTANTLY <- LOOK IT'S ALREADY REPORTED

### ISSUE THREAD

**Issue by iarspider** [Chisel-Team/Chisel#108]
Chiseled blocks (at least cobblestone) are broken instanly with any tool (including empty hand). When broken with empty hand, there is a chance of them not dropping item (i.e. disappearing completely). 

Chisel 0.0.2.6
Forge 11.15.0.1699

**Comment by tterrag1098** [comment]
Updated title to include layman terms :P 

I'm working on a fix for this though, almost done. Soon.

**Comment by dmodoomsirius** [comment]
@tterrag1098 i know you mean soonTM

**Comment by Drullkus** [comment]
Soon™

**Comment by tterrag1098** [comment]
636916c75be060b8c62af049ee9713dfbd2ee145 at least partially addresses this issue. All blocks will by default have a hardness of 1.

**Comment by NarigudoBR** [comment]
just waiting to you order jenkins to build the jar

**Comment by HammerDave** [comment]
Is this going to be included in a build for 1.8.9?  Latest one seems to be from mid Jan.

**Comment by tterrag1098** [comment]
It already was, I believe. Just not posted to CurseForge. Either way, all development going forward will be on 1.9.

**Comment by HammerDave** [comment]
Wow, that was a quick comment, thanks.  Yes, it is in the #7 build on the Jenkins link.
If it were me, I'd want to release that (barring a reason not to) so that folks who prefer the N-1 release would have it, but up to your team how to handle it of course.  :)
I only did a quick test, On the surface it (0.0.2.7) worked ok in the context of FTB unstable 1.8.9.

**Comment by tterrag1098** [comment]
There is a good reason, about half the blocks have no model

**Comment by Paouis** [comment]
1.8.9 version Fix ???

**Comment by Drullkus** [comment]
Use 1.9 or 1.10

**Comment by Paouis** [comment]
i play in 1.8.9 because some mod have no 1.9 update --'

**Comment by Drullkus** [comment]
Feel free to dump that mod then. It's just one mod. You can live without just that one, trust me ;)

**Comment by Paouis** [comment]
You think i can convert the 1.8 in 1.8.9

**Comment by Drullkus** [comment]
I don't understand what you are saying, could you please rephrase?

What mod is so important that it prevents you from playing 1.9/1.10?

**Comment by Paouis** [comment]
Sorry i m french 
There are Mrcrayfish ,decocraft, ironbackpacks

**Comment by Paouis** [comment]
i try tu use the 1.8 version but there are bug

**Comment by TehNut** [comment]
IronBackpacks is definitely available for 1.10.

**Comment by Paouis** [comment]
Really where ?

**Comment by TehNut** [comment]
On Curse?
