### ISSUE TITLE
Chisel glass solid grey texture [1.8.9]

### ISSUE THREAD

**Issue by Avalonzo** [Chisel-Team/Chisel#109]
I just re-installed chisel as there is a way to make it work with ProjectE now and when ever I chisel glass it gets a solid grey texture instead of clear please see screenshot attached -

![2016-01-24_22 16 11](https://cloud.githubusercontent.com/assets/8142543/12539362/b312f9f8-c2e8-11e5-8f28-0edea0885e1b.png)

**Comment by JazParks** [comment]
I installed Chisel recently and have the same problem. Texture is see-through on my hot bar but when placed is a solid block.

**Comment by ghost** [comment]
Did this ever get fixed? Or was it just ignored and closed?

**Comment by tterrag1098** [comment]
This issue is 4 years old and for a version we no longer support. If you are having a similar issue please open a new report.
