### ISSUE TITLE
Disappeared recipes chisel to marble?

### ISSUE THREAD

**Issue by Bogdan-G** [Chisel-Team/Chisel#110]
Hello. MC 1.7.10. Forge 1614. Chisel 2.9.4.10 and no more mods.
Marble columns can not be created through the chisel or craft:
![](http://imgur.com/rHzCiS0.png)
![](http://imgur.com/41aJXvC.png)
I can change the existing marble columns, but can not create new ones.

**Comment by Bogdan-G** [comment]
the problem is solved in versions for MC 1.8/1.8.9/1.9.4?

**Comment by tterrag1098** [comment]
Yes
