### ISSUE TITLE
Chiseled glass rendering

### ISSUE THREAD

**Issue by xJon** [Chisel-Team/Chisel#113]
![image](https://cloud.githubusercontent.com/assets/8945347/12628232/d4a60ede-c54a-11e5-8cdf-75377ec2f346.png)
Whenever I get away from it in a certain distance it doesn't really render as expected.
Is this intended or configurable?

**Comment by tterrag1098** [comment]
I'm not sure what you're referring to...

**Comment by xJon** [comment]
![image](http://i.imgur.com/lPr4mxa.png)
In a certain distance from the player the chiseled glass render as a black block. Sorry if the other picture wasn't clear enough.

**Comment by tterrag1098** [comment]
That's mipmapping. Turn it off in the graphics menu if you don't like it.

**Comment by xJon** [comment]
Thanks for clarifying :)
