### ISSUE TITLE
[1.8.9] Game crashes and worldstate corrupted when trying to make a Fancy Fluids Strorage tank with chisel blocks

### ISSUE THREAD

**Issue by MattDahEpic** [Chisel-Team/Chisel#114]
Running FFS 1.8.9-1.4.5.69 and Chisel 1.8.9-0.0.2.6

Creating a FFS tank with chisel blocks causes render error and crashes client, shortly after dedicated server crashes and worldstate is corrupted. The attempted tank was made using Detailed Cobblestone Bricks and vanilla glass.

**Comment by tterrag1098** [comment]
This is a bug in FFS, FFS
