### ISSUE TITLE
[1.8.9] Diamond chisel has no model/texture

### ISSUE THREAD

**Issue by MattDahEpic** [Chisel-Team/Chisel#117]
![Diamond Chisel](http://i.imgur.com/ZUiOiEU.png)

Chisel 1.8.9-0.0.2.6

**Comment by Sempai77** [comment]
A similar problem.
Not displayed texture.
and blocs have no strength.
Break with a single blow, even in survival mode

**Comment by tterrag1098** [comment]
#108
