### ISSUE TITLE
Immibis' Connected Glass glassifies Transparent Technical blocks

### ISSUE THREAD

**Issue by Barhandar** [Chisel-Team/Chisel#12]
That is, instead of their correct texture they display as (connected) glass. Not sure if it's your issue or Immibis's.

**Comment by TheCricket** [comment]
"glassifies"
Screenshots maybe?

**Comment by asiekierka** [comment]
Overrides the renderer, somehow.

**Comment by ghost** [comment]
I think it does this to regular Chisel glass too. I removed Connected Glass since then though, so I can't get any screenshots atm.

**Comment by tterrag1098** [comment]
immibis mods are dead, and 1.7 is unsupported. Closing this

**Comment by asiekierka** [comment]
(For future reference: Actually, immibis fixed this in Connected Glass 59.0.3.)
