### ISSUE TITLE
Error when chiseling blocks in GUI

### ISSUE THREAD

**Issue by NdMSnIpEz** [Chisel-Team/Chisel#120]
The moment blocks are placed, the console is filled with spam. It's also worth mentioning that whenever a block within a new slot is selected a large error also appears in the console. This error is reproducible with all chisel blocks.
Version: Chisel 0.0.2.6 (MC 1.8.9)
Forge: 11.15.0.1715
http://pastebin.com/31fiuTDs
Full log here:
http://paste.feed-the-beast.com/view/8ed66f70

If you require any more information then please ask. This is a very minor bug but it's something worth paying attention to.

UPDATE: I will soon attempt to reproduce this in Unstable 3.0.17.

**Comment by tterrag1098** [comment]
We left the debug switch on, is all. The error in the GUI however is definitely a bug, and I'll look into it.
