### ISSUE TITLE
[Request] UBC Support

### ISSUE THREAD

**Issue by O13SC3N3** [Chisel-Team/Chisel#122]
Would like to see Underground Biome Construct Support with chisel

1.7.10

**Comment by LuigiHutch** [comment]
There was this: https://twitter.com/asiekierka/status/581774918339158016. Im not sure how much use that would be though :/

**Comment by O13SC3N3** [comment]
yeah its a bit outdated as well, looks like asie site is down too.

**Comment by Drullkus** [comment]
1.7.10 dropped
