### ISSUE TITLE
[1.8.9] Model crash with Botania Platforms

### ISSUE THREAD

**Issue by Darkhax** [Chisel-Team/Chisel#124]
When applying a chisel block to a platform from Botania, a pretty bad crash takes place. This crash also re-occurs every time the world is loaded up again. Not certain which mod would be responsible for fixing this issue, so I am reporting it to both. The crash log can be seen [here](https://gist.github.com/darkhax/9c4389ffe6134f209834) The Botania version of this crash report can be seen [here](https://github.com/williewillus/Botania/issues/108)

**Comment by williewillus** [comment]
Right now all I do is get the model from BlockModelShapes, then if it's a smartmodel, query it using the camo state. What else do I need to do in order to give the camo state the info it needs?

**Comment by tterrag1098** [comment]
You're missing contextual states, since you never call getExtendedState on the block. Ask @Lordmau5, I helped him with the same thing.

**Comment by williewillus** [comment]
@darkhax you can close this one, it's an issue on my end

**Comment by darkhax** [comment]
@williewillus Can you reference this issue when you fix it? I am having a similar issue with one of my blocks that is based off of the platform case study in the primer lol
