### ISSUE TITLE
No textures 1.8.9

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [Chisel-Team/Chisel#126]
Downloaded Chisel through Curse, originally on a instance with quite a few mods, booted the game, got a chisel and when I placed blocks in, nothing popped up. I checked JEI and none of the blocks had textures. I started a new modded instance with only Chisel, and same thing.
![chisel picture](https://cloud.githubusercontent.com/assets/14096186/12929161/4f37e8a4-cf3f-11e5-959e-a15e02c7a88b.png)

**Comment by tterrag1098** [comment]
This wasn't meant to be uploaded. Please downgrade to the previous version.
