### ISSUE TITLE
[1.8.9] Missing textures

### ISSUE THREAD

**Issue by michaelgaultjr** [Chisel-Team/Chisel#127]
I have this glitch I don't know if this has been reported yet or if very few people have it but it make all blocks and textures in chisel purple or invisible except the iron chisel which has its normal texture you can find a screenshot [Here](http://i.imgur.com/2zxdXUT.png)

**Comment by tterrag1098** [comment]
#126

**Comment by michaelgaultjr** [comment]
Ah ok thanks!
