### ISSUE TITLE
choices for chisel items dont show up

### ISSUE THREAD

**Issue by matthewray11** [Chisel-Team/Chisel#128]
when you place an item in the the chisel gui (for example birch planks) nothing comes up

**Comment by Drullkus** [comment]
Which chisel version?

**Comment by matthewray11** [comment]
1.8.9- 0.0.2.6

**Comment by whyo2** [comment]
when will this be fixed?

**Comment by Drullkus** [comment]
I think this was fixed. Not sure. [Try this build.](http://ci.tterrag.com/job/Chisel/branch/1.8%252Fdev/)

**Comment by HeinerGehtnoch** [comment]
Heya! I followed this thread so far and I have the same problem: the recipes don't show. But when in creative mode an already chiselled block is selected and put into the chisel-window, the alternatives are visible and can be extracted. I tried that last build but there I can't see the textures of any chisel-block. They're just pink and black. This mod is so cool. I'd hate to take it out of my modlist...

**Comment by tterrag1098** [comment]
Recipes are still being finalized. Be aware that you are using an alpha version and it is in no way representative of what the final version will be. We are not even guaranteeing compatible saves going forward until beta. This bug will be fixed in due time.

**Comment by tterrag1098** [comment]
What recipes exactly are you having an issue with? I did some brief testing and they seem to work fine.
