### ISSUE TITLE
Chisel's GUI Text issue when NEI not present

### ISSUE THREAD

**Issue by Glassmaker** [Chisel-Team/Chisel#13]
With NEI

![With NEI](https://cloud.githubusercontent.com/assets/5352172/9706283/8c5faac6-54e9-11e5-800e-3d0dbd7c98bf.png)

Without NEI

![Without NEI](https://cloud.githubusercontent.com/assets/5352172/9706286/abdfe67c-54e9-11e5-9aad-1c8049c0f510.png)

Effected Versions: 2.3 - 2.9.
Not effected version: 2.2.
Tested forge versions: 1291, 1408, 1448.

**Comment by minecreatr** [comment]
Not able to repeat in forge version 1481, might be a forge bug?

**Comment by Drullkus** [comment]
Forge tends to have... Font texture issues if on Mac and if the splash screen is enabled. Driver thing. Fixable by turning off the splash screen. I cried too when I learned this :(

**Comment by Glassmaker** [comment]
@minecreatr just tested it with forge 1481, it happens, make sure you have only the chisel in the hotbar, otherwise it will render correctly.

@Drullkus I have tested it with 1291 to rule out the splash screen.

**Comment by tterrag1098** [comment]
Confirmed myself, I'll have to look into this.

**Comment by tterrag1098** [comment]
Fixed in 2.9.2.X
