### ISSUE TITLE
Blocks in the same Series connect to each other

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#131]
![2016-03-17_18 39 08](https://cloud.githubusercontent.com/assets/5010174/13866129/a8760a66-ec6f-11e5-8d55-da8c12920a19.png)

![2016-03-17_18 45 08](https://cloud.githubusercontent.com/assets/5010174/13866225/7a3d3696-ec70-11e5-8a72-69f92baf60b4.png)

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/Chisel/blob/1.8/dev/src/main/java/team/chisel/client/render/ctm/CTM.java#L275-L276

_cough_
