### ISSUE TITLE
Colored Glass CTM doesn't connect

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#133]
![2016-03-17_18 47 59](https://cloud.githubusercontent.com/assets/5010174/13866262/cf1a8736-ec70-11e5-90ed-042ec4d6aa80.png)

**Comment by Drullkus** [comment]
There were never CTM files for these. Whoops.

**Comment by porteriscool** [comment]
GG

**Comment by Drullkus** [comment]
"GG" is correct. If I do retexture these... CTM is gonna get tossed in.
