### ISSUE TITLE
Weird behavior with defaulting or something

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#136]
Took me a while to realize this specific problem. 

While I was trying to write the CTX files for the glass, the glass wasn't recognizing the CUTOUT that was in the CTX files. I gave up and wrote every CTX file for the glass regardless of broken or not. Now I've done that, NOW they work. It cannot be coincidence.

**Comment by Drullkus** [comment]
Maybe related:

Doing:

![screen shot 2016-03-24 at 12 14 01 am](https://cloud.githubusercontent.com/assets/5010174/14010759/6289f446-f155-11e5-8412-a5581f753965.png)

Gives me the right transparent model that I wanted, but if I do:

![screen shot 2016-03-24 at 12 13 50 am](https://cloud.githubusercontent.com/assets/5010174/14010765/729909e4-f155-11e5-929a-11e8ed847c19.png)

It gives me a null model

**Comment by Drullkus** [comment]
@tterrag1098 You sure this is fixed?

**Comment by tterrag1098** [comment]
I remember doing something to fix this. Feel free to try and reproduce.
