### ISSUE TITLE
version 2.9.5.11 just doesnt work

### ISSUE THREAD

**Issue by Faenum** [Chisel-Team/Chisel#137]
Ive added the mod to my server and to my client, and neither recognize the mod, but i cant work out why.

**Comment by Drullkus** [comment]
Why did you close it? o.O

**Comment by Faenum** [comment]
cos i realized why it wasn't working, i thought it was for 1.8 with it being the new versions but its not

**Comment by Drullkus** [comment]
Ooooh.

We have some unstable builds here [on the build server](http://ci.tterrag.com/job/Chisel/branch/1.8%252Fdev/), but we cannot guarantee safety of your worlds...

**Comment by Faenum** [comment]
i know, ive gone back to the alpha version i had which was ok, its just a test server right now anyway
