### ISSUE TITLE
1.9/dev - Models without CTX contain strange face data.

### ISSUE THREAD

**Issue by AlgorithmX2** [Chisel-Team/Chisel#138]
https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/client/render/ModelChiselBlock.java#L77

Will return cached faces if no CTX is provided, best solution is to have it return default state without connections.

Another option would be to return no faces and require that people use the Item model instead.

Talked on IRC about this.

**Comment by tterrag1098** [comment]
Fixed
