### ISSUE TITLE
[Request]CTMlib for 1.8/1.9?

### ISSUE THREAD

**Issue by raymondbh** [Chisel-Team/Chisel#139]
Hi
Are going to make a CTMLib for 1.8/1.9 that can be imported like in 1.7?

**Comment by Drullkus** [comment]
We're working on it. :) 

It's going to be far more powerful than the 1.7 system. In fact, it's no longer about texture management, it involves models too. You can now put different texture types on model, including making them different for each side.

**Comment by raymondbh** [comment]
Sounds awesome :-)

**Comment by raymondbh** [comment]
Any news on this?

?

**Comment by raymondbh** [comment]
Bump... :-)

**Comment by Drullkus** [comment]
It's a thing we're looking to do for 1.11.

**Comment by raymondbh** [comment]
ok

**Comment by tterrag1098** [comment]
This exists now

**Comment by Drullkus** [comment]
https://minecraft.curseforge.com/projects/ctm/files
