### ISSUE TITLE
1.9 Issue

### ISSUE THREAD

**Issue by RayzoRayy** [Chisel-Team/Chisel#144]
I think the issue is with chisel considering it started happening when I chiseled my base.. Basically I chiseled my floor, walls, roof, etc.. and noticed that after doing so, any block I break, or place, even items such as a torch, my FPS will drop to 3 FPS, and go right back to 120.. So anytime I break or place anything, itll lag down to 3 FPS and go back up to 120, happens every time, also when I go away from the blocks(the chiseled ones) there is no lag when breaking or placing blocks or items.. such as in my mine. Pretty sure it's chisel, there is no crash report, just thought you might want to look into it. Thanks.

**Comment by minecreatr** [comment]
Yes, this is chisel. What is causing this problem is every time you place a block it causes the chunks render list to be reassembled and it runs ctm logic on every block in the chunk again. I will see if I can solve this by trying to implement a model caching system.

**Comment by OlexaKid64** [comment]
Any update coming soon to this problem or the mod itself? Some friends and I got the mod on a server and love it but the lag spikes are awful. Anything we can do to fix them?

**Comment by minecreatr** [comment]
Am currently working on fix.

**Comment by OlexaKid64** [comment]
Awesome! Any ETA? Thanks for the hard work. It doesn't go unappreciated

**Comment by minecreatr** [comment]
Hard to say, maybe a weekish, but that is a complete guess. I have to finish implementing the new code, but new problems might arise from it so there is really no good way to know.

**Comment by tterrag1098** [comment]
Performance has been improved drastically
