### ISSUE TITLE
Chisel 1.9 issue

### ISSUE THREAD

**Issue by RayzoRayy** [Chisel-Team/Chisel#145]
Hello again, sorry if this is already posted as a bug, I skimmed through and didin't see it but maybe it already was.. anywho, chiseled glass is see through on the bottom side, meaning I can see through the block under it down to my room below. Kinda hard to explain so i will post a screenshot

http://imgur.com/a/KqZSV

**Comment by Mach12** [comment]
It seems to affect all sides, actually.

[Screenshot](http://imgur.com/tzqlnB2)

**Comment by Drullkus** [comment]
Known issue

**Comment by tterrag1098** [comment]
This is fixed
