### ISSUE TITLE
Odd sidability for certain blocks

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#148]
![2016-04-20_23 04 14](https://cloud.githubusercontent.com/assets/5010174/14699411/64830532-074c-11e6-8f41-f7b3a7a22b81.png)

The Top and Bottom use the same TOP texture, but the test texture (Circle/Square/X) is consistent for each side... This should not happen.

Bug found by @ProfessorProspector

model.json

```
{
  "model": { "model": "cube"},
  "face":"chisel:grimstone/test.cf",
  "overrides":{
    "UP":"chisel:grimstone/chiseled-top.cf",
    "DOWN":"chisel:grimstone/chiseled-top.cf"
  }
}
```

test.cf

```
{
    "type":"R4"
}
```

**Comment by tterrag1098** [comment]
Is this still a problem?

**Comment by Prospector** [comment]
Probably unless you fixed it :P

**Comment by Drullkus** [comment]
Still a problem
