### ISSUE TITLE
[1.8.9] Textures don't render when block from Chisel is painted onto an EnderIO facade

### ISSUE THREAD

**Issue by MastaC729** [Chisel-Team/Chisel#149]
I understand that EnderIO is still not "publicly released," but I was curious as to why facades painted using any block from Chisel are not rendering properly. In other words, they render as the purple "cannot find texture" instead. Is this an issue on EnderIO's part, or is this due to how Chisel renders those blocks in the first place?

If this is an issue with Chisel and you would rather not fix this in 1.8.9, let me know where else besides the usual render classes I need to make changes to. Otherwise, if it's an EnderIO issue I'll do as they have been telling everyone else and wait until the 1.8.9 version is "publicly released."

**Comment by HenryLoenwind** [comment]
Painting with anything but dumb models is not yet finished on Ender IO's side.

**Comment by MastaC729** [comment]
OK, thanks for the heads up. Would you like me to open an issue on the EnderIO page and link to this, or would you rather me wait until you're ready?

**Comment by HenryLoenwind** [comment]
No issues for missing things, please. That's what we have our tracking sheet for.

But a heads up: I just tweaked some things and this **might** work in the next build.

**Comment by Drullkus** [comment]
This should be fixed. I saw it working at BTM 16.2

**Comment by HenryLoenwind** [comment]
Yes, it is. We also got connected textures working in both directions now.
