### ISSUE TITLE
[Suggestion] Add electrum block variants

### ISSUE THREAD

**Issue by FreneticScribbler** [Chisel-Team/Chisel#15]
Constantan and Electrum metal series would be very neat!

**Comment by Yulife** [comment]
I think mr_hazard wanted his Japanese Castle blocks to be implemented as well :)

**Comment by FreneticScribbler** [comment]
That too, but that's not quite IE related :P

**Comment by Drullkus** [comment]
Electrum, sure. Constantan isn't a common metal, no.

**Comment by Drullkus** [comment]
Electrum, along with some other metals, have been added in 1990de3. Cupronickel will be considered later.

**Comment by tterrag1098** [comment]
Once again, don't close issues until they are _released_.

**Comment by Drullkus** [comment]
Whoops.

**Comment by tterrag1098** [comment]
Considering 3.0 will probably never be released, this is done.

**Comment by Drullkus** [comment]
I'm still not sure if I want to add cupronickel. I don't think I will if I can't make up my mind on it.

**Comment by MarcusElg** [comment]
Why wont 3.0 ever be released?

**Comment by tterrag1098** [comment]
Because 1.7 is dead
