### ISSUE TITLE
Ender Chests from a standard chest?

### ISSUE THREAD

**Issue by Ra-Zim** [Chisel-Team/Chisel#150]
Yeah, this is a bit of an issue as you can use a chisel with a regular wooden chest to get a vanilla Ender Chest and basically turn 8 wooden planks into 8 obsidian. We're using version 2.9.5.11 for mc version 1.7.10.

**Comment by Ra-Zim** [comment]
Well, in an attempt to temporarily "fix" this problem, I went into the config and disabled presents, it definitely has stopped the problem, when you attempt to chisel a chest now, it results in a client-side crash. Please see the crash log here, if needed: http://pastebin.com/wwKWvWXC

**Comment by tterrag1098** [comment]
Someone must be adding the ender chest to the ore dictionary, which is now how it's meant to be used. This does not happen with only chisel.

**Comment by Ra-Zim** [comment]
Ahh, thanks, I'm not sure what is doing that, but I've got ModTweaker, I'll go remove the ender chest from the ore dictionary. :+1:
