### ISSUE TITLE
[1.9] Crash on Pre-Init from FTB Launcher

### ISSUE THREAD

**Issue by dannydjdk** [Chisel-Team/Chisel#152]
http://pastebin.com/mfKir558

Version: 1.9-0.0.4.13
Forge: 12.16.1.1887

The pasted crash log was generated when all other mods were disabled except Chisel.

This crash only occurs when launching using the FTB Launcher, and only occurs when Chisel is enabled. Same exact versions and configs work fine in Curse and vanilla launcher, but currently Chisel  does not seem to work with 1.9 packs on the FTB launcher.

**Comment by tterrag1098** [comment]
This is only because Chisel happens to trigger a crash caused by a missing library. Take this issue up with the FTB launcher.

**Comment by dannydjdk** [comment]
Reported to FTB (http://forum.feed-the-beast.com/threads/crash-on-pre-init-with-chisel-for-1-9.154519/).

**Comment by progwml6** [comment]
Upon further investigation... it looks like a jline import was used instead of a java one here
https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/client/render/ModelLoaderChisel.java#L7

**Comment by minecreatr** [comment]
Fixed in https://github.com/Chisel-Team/Chisel/commit/839e8fa05dd955249cf09612a4208c3d1596d09f

**Comment by minecreatr** [comment]
I messed up git. Sorry
