### ISSUE TITLE
(1.8.9 and 1.9) marble and limestone doesn't generate them

### ISSUE THREAD

**Issue by 0Navis0** [Chisel-Team/Chisel#153]
It seems that there is problem with the marble and the limestone wich doesn't generate them in the 1.8.9 and 1.9  version.
There are a lot of missing and broken textures too.

**Comment by Drullkus** [comment]
1.8 has lots of broken/missing textures. 1.9 is 99% fixed except for a few missing features that must be done in code first.

There is no worldgen as of yet.

**Comment by 0Navis0** [comment]
I toke some screenshots of the missing textures blocks on 1.9. The torch textures are bugged too.

![capture1](https://cloud.githubusercontent.com/assets/17103411/15234206/a1134092-18af-11e6-9ed2-9697bd9247aa.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17103411/15234207/a1143560-18af-11e6-87d6-6e7541e39071.PNG)
![capture3](https://cloud.githubusercontent.com/assets/17103411/15234209/a115227c-18af-11e6-85a1-1581282db800.PNG)
![capture4](https://cloud.githubusercontent.com/assets/17103411/15234208/a114f95a-18af-11e6-8034-d157a8689674.PNG)

**Comment by Drullkus** [comment]
Yes, the Iron+Glass Panes, anything stair-related, and torches are broken. We have to work on the backend for these

**Comment by B0bbyD0llar** [comment]
Hi, is there still an problem with marble and limestone generation at version MC1.9.4-0.0.5.29?

**Comment by Drullkus** [comment]
We still haven't yet added them to the worldgen.

**Comment by B0bbyD0llar** [comment]
ahhh. that means that is not a bug, this feature is still missing?

**Comment by Drullkus** [comment]
It's still an alpha. It's stable enough to be in modpacks but not feature complete. Go ahead and spawn your blocks via `/give @p chisel:basalt 64` or whatever block you needed. They will be made craftable, cheap in worldgen, and we're considering NPC trades.

**Comment by B0bbyD0llar** [comment]
Thanks for your explanation and your hint. Is there any schedule for add this feature. It is a question not a annoying ask :-)

**Comment by Drullkus** [comment]
We never know when stuff gets added. There's still things in the chisel core we're still trying to work out. :P

**Comment by Drullkus** [comment]
Worldgen added for Limestone marble basalt
