### ISSUE TITLE
1.9.4 crash

### ISSUE THREAD

**Issue by RayzoRayy** [Chisel-Team/Chisel#158]
Was testing the 1.9.4 version and i found that on the lastest version you've created, Chisel_DEV-MC1.9.4-0.0.4.17
The game crashes when trying to break a chiseled block.. not sure if it's because i have an older world from 1.9.4 and a previous version of Chisel, and the new one doesn't like that, or if it's just the new version, will create a new world and let you know. 

P.S. here is the crash log

http://pastebin.com/Kj9Fn1Fd

**Comment by RayzoRayy** [comment]
Okay, tested on a brand new world with chisel alone, it's the new version of chisel you've released which is causing this issue, as soon as you left click the block to start breaking it, it crashes immediately.

**Comment by tterrag1098** [comment]
Thanks for the report, fixed.
