### ISSUE TITLE
(feature suggestion) the slate 

### ISSUE THREAD

**Issue by 0Navis0** [Chisel-Team/Chisel#159]
I came with this idea since I saw it on a server and finded this idea really awesome. I wanted to suggest to add the slate to Quark, with the stairs and slabs. It's a block wich craft it with 4 flints and give an another utility to the flints. ;)
![d67cc144-277e-11e6-8656-a180386795eb](https://cloud.githubusercontent.com/assets/17103411/15795357/173ca31a-29f1-11e6-8d67-8be3fcc3267f.png)
![d9ee6f76-277e-11e6-9540-c8a1a200c8a7](https://cloud.githubusercontent.com/assets/17103411/15795358/19df6c4c-29f1-11e6-8b8a-1b6e3f0bb075.png)
![dd3ce3d8-277e-11e6-89fa-a43070697105](https://cloud.githubusercontent.com/assets/17103411/15795361/1cf6dc08-29f1-11e6-9604-1ceb7f3e918b.png)

**Comment by Drullkus** [comment]
Er... Wait, are you trying to suggest it to Quark or us?

**Comment by KnightMiner** [comment]
He did suggest it to Quark, Vazkii/Quark#44. The idea was rejected there, so it seems he wants to suggest it for chisel now.

**Comment by 0Navis0** [comment]
Yeah I had suggested it to Quark, but it has been rejected, so I suggest it here. And it seems that some people tracks me everywhere I go...

**Comment by jriwanek** [comment]
Could always make a lighter texture slate block texture available and suggest it again. (:

**Comment by Drullkus** [comment]
I'll make a block made from flint, but it will look entirely different and maybe gravelly. It will still look dark and will not be affected by gravity. (unlike gravel)

**Comment by Drullkus** [comment]
Will be implemented as Flint blocks; will look like black quartz
