### ISSUE TITLE
Futura Block is a little bit strange

### ISSUE THREAD

**Issue by gabor7d2** [Chisel-Team/Chisel#16]
The `chisel:futura:5` block (Uber Wavy) looks a little bit weird in some situations. I think it's not connecting correctly because you can't specify the textures in 4 picture in this case, but I don't really understand modding, so maybe not. Or maybe it is intended as it is.

Screenshot:
![2015-09-12_19 16 15](https://cloud.githubusercontent.com/assets/12859334/9832675/d2050b28-5982-11e5-97ab-e21a85845928.png)

Chisel Version: **2.9.0.3** (Sorry, I am a little confused about that you switched to regular Chisel again, and not Chisel 2, so I hope this is the last version)

If you need modlist, logs, or anything like that, tell me. Thanks for the help!

**Comment by Drullkus** [comment]
Oh, I know the problem... It's on my bucket list, haven't gotten around to it >.>

**Comment by Drullkus** [comment]
Fixed for 1.9/10
