### ISSUE TITLE
[1.7.10] NoClassDefFoundError

### ISSUE THREAD

**Issue by ferrari314** [Chisel-Team/Chisel#160]
Time: 04.06.16 14:32
Description: Initializing game

java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/Triple
    at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:194)
    at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:458)
    at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
    at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:201)
    at team.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:335)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:62)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.Triple
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 16 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.cricketcraft.chisel.api.rendering.TextureType$7.registerIcons(TextureType.java:194)
    at com.cricketcraft.chisel.api.rendering.TextureType$SubmapManagerDefault.registerIcons(TextureType.java:458)
    at com.cricketcraft.chisel.api.carving.VariationInfoBase.registerIcons(VariationInfoBase.java:61)
    at com.cricketcraft.chisel.api.carving.CarvableHelper.registerBlockIcons(CarvableHelper.java:201)
    at team.chisel.block.BlockCarvable.func_149651_a(BlockCarvable.java:71)
    at net.minecraft.client.renderer.texture.TextureMap.func_110573_f(TextureMap.java:335)
    at net.minecraft.client.renderer.texture.TextureMap.<init>(TextureMap.java:62)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 229062456 bytes (218 MB) / 555364352 bytes (529 MB) up to 6361972736 bytes (6067 MB)
    JVM Flags: 5 total; -Xmx6080M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 85 mods loaded, 85 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCH appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCH ivtoolkit{IvToolkit} [1.0.4](minecraft.jar) 
    UCH MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
    UCH NotEnoughItems{1.0.5.118} [Not Enough Items]([Utility] NotEnoughItems 1.0.5.118.jar) 
    UCH <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCH debug{1.0} [debug]([Mod] Denseores 1.6.2.jar) 
    UCH bdlib{1.9.4.109} [BD Lib]([Core] Bdlib 1.9.4.109.jar) 
    UCH CoFHCore{1.7.10R3.1.2} [CoFH Core]([Core] CoFHCore 3.1.2.jar) 
    UCH Enchiridion{1.3} [Enchiridion]([Core] Enchiridion 2.0.2a.jar) 
    UCH Enchiridion2{2.0.2a} [Enchiridion 2]([Core] Enchiridion 2.0.2a.jar) 
    UCH endercore{1.7.10-0.2.0.31_beta} [EnderCore]([Core] EnderCore 0.2.0.31.jar) 
    UCH grim3212core{V0.2 - 1.7.10} [Grim3212 Core]([Core] Grim3212 Core.jar) 
    UCH malisiscore{1.7.10-0.14.3} [MalisisCore]([Core] Malisiscore 0.14.3.jar) 
    UCH Mantle{1.7.10-0.3.2.jenkins184} [Mantle]([Core] Mantle 0.3.2.jar) 
    UCH IC2{2.2.733-experimental} [IndustrialCraft 2]([Mod] Industrialcraft-2-2.2.733.jar) 
    UCH AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels]([Mod] AdvancedSolarPanel 3.5.1.jar) 
    UCH appliedenergistics2{rv2-stable-10} [Applied Energistics 2]([Mod] Appliedenergistics2rv2s10.jar) 
    UCH ae2stuff{0.5.0.56} [AE2 Stuff]([Mod] AE2stuff 0.5.0.56.jar) 
    UCH BiblioCraft{1.11.5} [BiblioCraft]([Mod] BiblioCraft 1.11.5.jar) 
    UCH BiomesOPlenty{2.1.0} [Biomes O' Plenty]([Mod] BiomesOPlenty 2.1.0.1889.jar) 
    UCH BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition]([Mod] BiblioWoods 1.9.jar) 
    UCH malisisdoors{1.7.10-1.13.1} [Malisis' Doors]([Mod] Malisisdoors 1.13.1.jar) 
    UCH BigDoors{1.7.10-1.1.0} [Big Doors]([Mod] BigDoors 1.1.0.jar) 
    UCH BuildCraft|Core{7.1.14} [BuildCraft]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Builders{7.1.14} [BC Builders]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Transport{7.1.14} [BC Transport]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Energy{7.1.14} [BC Energy]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Silicon{7.1.14} [BC Silicon]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Robotics{7.1.14} [BC Robotics]([Mod] buildcraft 7.1.14.jar) 
    UCH BuildCraft|Factory{7.1.14} [BC Factory]([Mod] buildcraft 7.1.14.jar) 
    UCH Railcraft{9.8.0.0} [Railcraft]([Mod] Railcraft 9.8.0.0.jar) 
    UCH chisel{2.9.5.11} [Chisel]([Mod] Chisel 2.9.5.11.jar) 
    UCH EnderIO{1.7.10-2.2.8.381} [Ender IO]([Mod] EnderIO 2.2.8.381.jar) 
    UCH exnihilo{1.38-51} [Ex Nihilo]([Mod] Ex-Nihilo 1.38.51.jar) 
    UCH Waila{1.5.10} [Waila]([Utility] Waila 1.5.10.jar) 
    UCH TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct]([Mod] TinkersConstruct 1.8.8.jar) 
    UCH exastris{MC1.7.10-1.16-36} [Ex Astris]([Mod] Ex-Astris 1.16-36.jar) 
    UCH harvestcraft{1.7.10j} [Pam's HarvestCraft]([Mod] Pam's HarvestCraft Lb.jar) 
    UCH ExtraTiC{1.4.5} [ExtraTiC]([Mod] ExtraTiC 1.4.5.jar) 
    UCH Forestry{4.2.9.57} [Forestry for Minecraft]([Mod] forestry 4.2.9.57.jar) 
    UCH GardenContainers{1.7.10-1.6.8} [Garden Containers]([Mod] GardenStuff 1.6.8.jar) 
    UCH GardenCore{1.7.10-1.6.8} [Garden Core]([Mod] GardenStuff 1.6.8.jar) 
    UCH GardenStuff{1.7.10-1.6.8} [Garden Stuff]([Mod] GardenStuff 1.6.8.jar) 
    UCH GardenTrees{1.7.10-1.6.8} [Garden Trees]([Mod] GardenStuff 1.6.8.jar) 
    UCH GraviSuite{1.7.10-2.0.3} [Graviation Suite]([Mod] GraviSuite 2.0.3.jar) 
    UCH hearts{1.0} [Hearts]([Mod] HeartCrystal.zip) 
    UCH IronChest{6.0.62.742} [Iron Chest]([Mod] Ironchest 6.0.62.742.jar) 
    UCH JABBA{1.2.1} [JABBA]([Mod] Jabba-1.2.1a.jar) 
    UCH magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core]([Mod] Magicalcrops 4.0.05.jar) 
    UCH Mariculture{1.2.3d} [Mariculture]([Mod] Mariculture 1.2.3d.jar) 
    UCH MorePistons{1.7.10-1.5.1.3} [More Pistons]([Mod] MorePistons.jar) 
    UCH NetherOres{1.7.10R2.3.1} [Nether Ores]([Mod] NetherOres 2.3.1-22.jar) 
    UCH placeableitems{PreAlpha 2.0} [Placeable Items Mod]([Mod] Placeableitems 2.0.jar) 
    UCH RTG{0.7.0} [Realistic Terrain Generation]([Mod] RealisticTerrainGeneration 0.7.0.jar) 
    UCH AS_Ruins{13.4} [Ruins Spawning System]([Mod] Ruins.jar) 
    UCH simpleores{1.4.3} [SimpleOres 2]([Mod] SimpleOres.jar) 
    UCH aestheticsplugin{1.0.0} [SimpleOres 2 Aesthetics Plugin]([Mod] SimpleOres.jar) 
    UCH fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin]([Mod] SimpleOres.jar) 
    UCH netherrocks{1.1.2} [SimpleOres 2 Netherrocks Plugin]([Mod] SimpleOres.jar) 
    UCH StorageDrawers{1.7.10-1.9.3} [Storage Drawers]([Mod] StorageDrawers 1.9.3.jar) 
    UCH StorageDrawersForestry{1.7.10-1.1.2} [Storage Drawers: Forestry Pack]([Mod] StorageDrawersForestry 1.1.2.jar) 
    UCH Baubles{1.0.1.10} [Baubles]([Core] Baubles 1.0.1.10.jar) 
    UCH TravellersGear{1.16.6} [Traveller's Gear]([Mod] TravellersGear 1.16.6.jar) 
    UCH bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCH Treecapitator{1.7.10} [Treecapitator]([Mod] Treecapitator 2.0.4.jar) 
    UCH yegamolchattels{1.1} [Ye Gamol Chattels]([Mod] YeGamolChattels.jar) 
    UCH dualhotbar{1.5} [Dual Hotbar]([Utility] DualHotbars.jar) 
    UCH samsinvcrafting{1.7.10-1.0.0} [Inventory Crafting]([Utility] Inventory Crafting Grid.jar) 
    UCH journeymap{5.1.4p1} [JourneyMap]([Utility] Journeymap 5.1.4p1.jar) 
    UCH MSM3{3.0.0a} [More Swords 3]([Utility] MoreSwords.jar) 
    UCH NEIAddons{1.12.14.40} [NEI Addons]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables]([Utility] neiaddons 1.12.14.40.jar) 
    UCH NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo]([Utility] neiaddons 1.12.14.40.jar) 
    UCH neiintegration{1.1.2} [NEI Integration]([Utility] NEIIntegration 1.1.2.jar) 
    UCH neresources{0.1.0.ManuallyBuilt} [Not Enough Resources]([Utility] NotEnoughResources 0.1.0.121.jar) 
    UCH TiCTooltips{1.2.5} [TiC Tooltips]([Utility] TiCTooltips 1.2.5.jar) 
    UCH denseores{1.0} [Dense Ores]([Mod] Denseores 1.6.2.jar) 
    CoFHCore: -[1.7.10]3.1.2-325
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.1-22
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from [Mod] Appliedenergistics2rv2s10.jar
        \* Baubles|API (1.0.1.10) from [Core] Baubles 1.0.1.10.jar
        \* BiomesOPlentyAPI (1.0.0) from [Mod] BiomesOPlenty 2.1.0.1889.jar
        \* BuildCraftAPI|blocks (1.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|blueprints (1.5) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|boards (2.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|core (1.4) from [Mod] Railcraft 9.8.0.0.jar
        \* BuildCraftAPI|crops (1.1) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|events (2.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|facades (1.1) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|filler (4.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|fuels (2.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|gates (4.1) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|items (1.1) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|library (2.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|lists (1.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|power (1.3) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|recipes (3.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|robotics (3.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|statements (1.0) from [Mod] Railcraft 9.8.0.0.jar
        \* BuildCraftAPI|tablet (1.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|tiles (1.1) from [Mod] Railcraft 9.8.0.0.jar
        \* BuildCraftAPI|tools (1.0) from [Mod] buildcraft 7.1.14.jar
        \* BuildCraftAPI|transport (4.1) from [Mod] buildcraft 7.1.14.jar
        \* ChiselAPI (0.1.1) from [Mod] Chisel 2.9.5.11.jar
        \* ChiselAPI|Carving (0.1.1) from [Mod] Chisel 2.9.5.11.jar
        \* ChiselAPI|Rendering (0.1.1) from [Mod] Chisel 2.9.5.11.jar
        \* CoFHAPI (1.7.10R1.0.1) from [Mod] Railcraft 9.8.0.0.jar
        \* CoFHAPI|block (1.7.10R1.0.12) from [Mod] Ex-Astris 1.16-36.jar
        \* CoFHAPI|core (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|energy (1.7.10R1.0.2) from [Mod] forestry 4.2.9.57.jar
        \* CoFHAPI|fluid (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|inventory (1.7.10R1.0.3) from [Mod] EnderIO 2.2.8.381.jar
        \* CoFHAPI|item (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|modhelpers (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|tileentity (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|transport (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHAPI|world (1.7.10R1.1.0) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|audio (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|gui (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|gui|container (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|gui|element (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|gui|slot (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|inventory (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|render (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|render|particle (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|util (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|util|helpers (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|util|position (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|world (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* CoFHLib|world|feature (1.7.10R1.1.2) from [Core] CoFHCore 3.1.2.jar
        \* EnderIOAPI (0.0.2) from [Mod] EnderIO 2.2.8.381.jar
        \* EnderIOAPI|Redstone (0.0.2) from [Mod] EnderIO 2.2.8.381.jar
        \* EnderIOAPI|Tools (0.0.2) from [Mod] EnderIO 2.2.8.381.jar
        \* ForestryAPI|apiculture (4.8.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|arboriculture (4.2.1) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|circuits (3.1.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|core (5.0.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|farming (2.1.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|food (1.1.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|fuels (2.0.1) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|genetics (4.7.1) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|hives (4.1.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|lepidopterology (1.3.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|mail (3.0.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|multiblock (3.0.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|recipes (5.4.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|storage (3.0.0) from [Mod] forestry 4.2.9.57.jar
        \* ForestryAPI|world (2.1.0) from [Mod] forestry 4.2.9.57.jar
        \* GardenCoreAPI (1.0.0) from [Mod] GardenStuff 1.6.8.jar
        \* IC2API (1.0) from [Mod] Industrialcraft-2-2.2.733.jar
        \* neresources|API (1.0) from [Utility] NotEnoughResources 0.1.0.121.jar
        \* RailcraftAPI|bore (1.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|carts (1.5.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|core (1.4.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|crafting (1.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|electricity (1.6.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|events (1.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|fuel (1.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|helpers (1.1.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|items (1.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|locomotive (1.0.1) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|signals (1.3.4) from [Mod] Railcraft 9.8.0.0.jar
        \* RailcraftAPI|tracks (2.0.0) from [Mod] Railcraft 9.8.0.0.jar
        \* StorageDrawersAPI (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|config (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|event (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|inventory (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|pack (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|registry (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|render (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|storage (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from [Mod] StorageDrawers 1.9.3.jar
        \* Thaumcraft|API (4.2.2.0) from [Mod] Railcraft 9.8.0.0.jar
        \* TravellersGear|API (1.0) from [Mod] TravellersGear 1.16.6.jar
        \* WailaAPI (1.2) from [Utility] Waila 1.5.10.jar
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Launched Version: ForgeOptiFine 1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 570/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by tterrag1098** [comment]
Update forge

**Comment by ferrari314** [comment]
forge-1.7.10-10.13.4.1614 is latest 1.7.10 version in forge official website

**Comment by tterrag1098** [comment]
Well your libraries are not all there. This was a typical problem with older forge versions. It's not a chisel bug

**Comment by ferrari314** [comment]
This bug I get when i get chisel in my libraries. Without chisel game working good.

**Comment by tterrag1098** [comment]
Chisel is not a library. Libraries are downloaded by forge to run the game. You must be missing some.
