### ISSUE TITLE
Left-click function not working.

### ISSUE THREAD

**Issue by jeridan** [Chisel-Team/Chisel#162]
Using Chisel-MC1.9-0.0.4.14, forge 1.9-12.16.1.1907, and MC 1.9.

The left-click function to replace placed blocks with the chisel doesn't change the block.
This is using the iron chisel as there is no other chisel recipe listed.

**Comment by MichaelDays** [comment]
Experienced this in Chisel-MC1.9.4-0.0.5.29, forge-1.9.4-12.17.0.1976, MC 1.9.4 (modpack: "All The Mods", with the diamond chisel, and the iron chisel (chisel.cfg has B:ironChiselCanLeftClick=true).

**Comment by Drullkus** [comment]
We actually haven't coded this function yet. It will come when we finish the durability code.

**Comment by MichaelDays** [comment]
Thanks for the update, I didn't realise that. :)

Maybe the config file could have a comment marking which options aren't yet available?

**Comment by aravol** [comment]
Could the tooltip line indicating this functionality be removed? It's perplexing having to find our way to this bug when the game says it's there but it actually isn't

**Comment by tterrag1098** [comment]
This works now
