### ISSUE TITLE
[1.9.4] lines and lines of forge log spam about missing textures/files

### ISSUE THREAD

**Issue by b0bst3r** [Chisel-Team/Chisel#163]
Forge 1954 (although happened with prev Forge versions)
Chisel_DEV-MC1.9.4-0.0.4.18 (I know it's DEV and not released)

Forge log - http://pastebin.ubuntu.com/17087013/

Relevant lines - 
278 to 2272
2474 to 3144
3359 to 3373
3791 to 6478
7785 to 11791

**Comment by tterrag1098** [comment]
They should now be removed if debugging is off (which it is)
