### ISSUE TITLE
[1.8]Chisel glass texture transparency issue.

### ISSUE THREAD

**Issue by tatsu011** [Chisel-Team/Chisel#164]
A friend of mine was working on a decoration pack.  Chisel was added and a few days ago it began to not render any kind of textures.  Attached is a screenshot and a Curse modpack file for testing.  
![2016-06-10_21 28 56](https://cloud.githubusercontent.com/assets/3756710/15982738/2eaaa398-2f56-11e6-9c09-857c5409f5d2.png)
[Zombie-1.0.zip](https://github.com/Chisel-Team/Chisel/files/310060/Zombie-1.0.zip)

**Comment by TehNut** [comment]
#109

**Comment by ghost** [comment]
Did this ever get fixed? Or was it just ignored and closed?
