### ISSUE TITLE
Obsidian Chisel does not show the Block that is in it

### ISSUE THREAD

**Issue by gabor7d2** [Chisel-Team/Chisel#17]
The Obsidian Chisel does not show the item that is currently in it, as other Chisels show it.

Screenshot:
![2015-09-12_19 22 54](https://cloud.githubusercontent.com/assets/12859334/9832710/c2c9a910-5983-11e5-8025-4b9360d7c8a4.png)

Chisel Version: **2.9.0.3**

If you need modlist, logs, or anything like that, tell me. Thanks for the help!

**Comment by TheCricket** [comment]
We have known about this for a long time, Its just never been a priority

**Comment by tterrag1098** [comment]
Obsidian chisel's future is uncertain, I may not be keeping it around.

**Comment by TheCricket** [comment]
Why get rid of it?

**Comment by Shahelion** [comment]
Is the Obsidian Chisel different in any way from the Diamond Chisel?

**Comment by Drullkus** [comment]
It does everything the demand chisel does but has half the durability IIRC.

**Comment by Drullkus** [comment]
Obsidian Chisel removed
