### ISSUE TITLE
[1.9.4] All Chisel Blocks let light throught

### ISSUE THREAD

**Issue by Xiaminou** [Chisel-Team/Chisel#171]
Torch on one side of the wall gives light on the other side.

![2016-06-22_15 05 39](https://cloud.githubusercontent.com/assets/8670392/16267650/4094da04-388b-11e6-84ab-47b3018ae598.png)
![2016-06-22_15 05 43](https://cloud.githubusercontent.com/assets/8670392/16267649/4090dfda-388b-11e6-9e99-a4f575efb649.png)

**Comment by Ozzymud** [comment]
Chisel-MC1.9.4-0.0.5.27
forge:1.9.4-12.17.0.1965

Can confirm as my mob spawner wasn't working, light level inside was as it is outside.

**Comment by tterrag1098** [comment]
Fixed in 54b6ea00ef41a328f8ef828afb6641495cf93e69
