### ISSUE TITLE
(1.9.4)(Feature Request) Compatability with shaders.

### ISSUE THREAD

**Issue by ZiggyAdventures** [Chisel-Team/Chisel#172]
#### Feature Description:

Feature request to not crash in the following ways:
Crash when using Shaders(tried Sues, Chocopic and Slider's on multiple settings) when viewing chisel blocks in JEI with Optifine B5. Cannot see non vanilla chisel blocks in JEI or chisel GUI with Optifine B6.

Crash when using Shaders(tried Sues, Chocopic and Slidur's on multiple settings) when viewing chiseled blocks in the world with Optifine B5 and B6.

---
#### Crash Reports

When loading into a world with chisel blocks placed and Shaders On with Optifine B6
http://pastebin.com/Ce07Fxxj
When viewing Chisel Blocks with Optifine B5 and Shaders On with no Chisel Blocks placed
http://pastebin.com/6TF52NH2
When loading Shaders while already in a world with Chisel Blocks placed and Optifine B6
http://pastebin.com/xQRC1HLh

---
#### Affected Versions
- Optifine: Optifine_1.9.4_HD_U_B6.jar and Optifine_1.9.4_HD_U_B5.jar
- Chisel: Chisel-MC1.9.4-0.0.5.27.jar
- JEI:jei_1.9.4-3.6.7.216.jar
- Minecraft: 1.9.4
- Forge: forge-12.17.0.1970

As a possible help to solution: Chisel and Bits works somewhat with Shaders, instead of crashing, a chisel and bit block with more then 4 modifications just disappears. Also Chisel 3 seems to work with Shaders but not every block, might also hold a solution.

**Comment by Drullkus** [comment]
See sp614x/optifine#185
