### ISSUE TITLE
Chisel 0.0.5.28 Dupe Bug

### ISSUE THREAD

**Issue by oitsjustjose** [Chisel-Team/Chisel#173]
Easy bug to replicate - putting an item in the chisel slot, leaving it there and then closing the GUI makes the itemstack drop in front of you, but stays in the GUI too. Can be repeated easily multiple times - simple bug though!

EDIT: Doesn't seem to be consistent with what items it does it with - doesn't do it with tools, but does do it with normal items and blocks?

**Comment by Drullkus** [comment]
Thought this was fixed. Pending investigation by @tterrag1098

**Comment by tterrag1098** [comment]
I cannot reproduce this. What items specifically cause it? Which chisel? What MC version?

**Comment by oitsjustjose** [comment]
Either of the two Chisels do it - most items seem to cause it. I'm on Chisel 0.0.5.28 on MC 1.9.4.

[Here's a video demonstration](https://www.youtube.com/watch?v=PXHIMsA8Pw8&feature=youtu.be)

EDIT: Uploaded to YouTube, MP4 was too long for most services.

**Comment by Drullkus** [comment]
The chisel container code will be rewritten anyways... IIRC.

**Comment by oitsjustjose** [comment]
True. Not like this bug makes Chisel Literally Unplayable :P

**Comment by Drullkus** [comment]
We were trying to mess around with durability on chiseling but that appears to be broken with the ancient container code.
