### ISSUE TITLE
[1.9] Rusty Scaffolding occlusion culling is broken

### ISSUE THREAD

**Issue by Daomephsta** [Chisel-Team/Chisel#174]
The factory block variant, rusty scaffolding does not do occlusion culling properly.
![2016-06-24_22 14 24](https://cloud.githubusercontent.com/assets/10936237/16335227/9b3c332e-3a59-11e6-8da0-5b13d4982b0f.png)

**Comment by Drullkus** [comment]
Oh ffs!

@tterrag1098 ? How do we fix this

**Comment by tterrag1098** [comment]
The same way it was fixed for glass etc?

**Comment by Drullkus** [comment]
But I set the transparency for all of the blocks by setting it before starting variations. I'm guessing if I set it on one variation, it does that for that just one variation.

**Comment by tterrag1098** [comment]
Yes

**Comment by Drullkus** [comment]
Fixed
