### ISSUE TITLE
Lighting bugs . 3.

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#177]
Put a torch down, redstone or coal torch, either one works.
Put chisel blocks on the north, south, east, and west sides of the torch.
The block on the north side has a shading glitch. All sides visible turn the same shade.

**Comment by tterrag1098** [comment]
Screenshots?

**Comment by tterrag1098** [comment]
Anything on this?

**Comment by Rodg88** [comment]
I got a video of this happening to basalt in 1.10.2 FTB Unstable pack (with a couple of mod updated from the vanilla pack), chisel 0.0.6.33 forge 2026
https://www.youtube.com/watch?v=5veGEp5v-Q8

**Comment by Drullkus** [comment]
I still see this issue persisting

**Comment by Drullkus** [comment]
@minecreatr I really think you might want to investigate this. Maybe you'll find out why and even find a solution to making the blocks glow when we want them to.

**Comment by Drullkus** [comment]
So far we've established that this is the result of the Forge Lighting pipeline. Works fine with vanilla's.

**Comment by Drullkus** [comment]
Is this still even happening? Poke this issue if yes. :P
