### ISSUE TITLE
[1.9.4] Only one block chisels at a time/disappearing styles

### ISSUE THREAD

**Issue by cactusbee** [Chisel-Team/Chisel#178]
Hi, we're using Chisel in a private modpack for 1.9.4 and since updating to the latest build, **1.9.4-0.0.5.29**, we've encountered a problem trying to chisel any quantity of blocks from the GUI. Only one block may be changed at a time. On the prior version we were using, **1.9.4-0.0.5.27**, this feature worked perfectly. Here is a list of the mods we are currently using: http://pastebin.com/rdNTTNpk

And here are some pictures of the issue: 

http://puu.sh/pSqK9/5fbae61bc4.png
This is how I would normally start to chisel a stack of blocks. 

http://puu.sh/pSqNg/dcb87c367f.png
Trying to shift-left-click the style I want chisels exactly 1 block of the stack, instead of the entire stack.

http://puu.sh/pSqQB/7f8a7ae0a1.png
Shift-left-clicking again _appears_ to chisel another block, but this block acts like a ghost, as it vanishes when the GUI is closed. Furthermore, the _chisel style_ vanishes after that second click, so that no more blocks can be chiseled until re-opening the GUI.

http://puu.sh/pSqUB/2746959538.png
Here is what it looks like after I open the GUI again. You can see I'm less one chiseled block, as it has returned to the unchiseled stack. After the style vanishes, another style can be selected and chiseled, but it too disappears and the previous vanished one re-appears. As expected, the actual number of the chiseled blocks is halved once I close the GUI again. 

This occurs with any stack of blocks greater than 1. Blocks can still be chiseled en masse without closing the GUI, but _only_ by manually clicking and dragging 1 block at a time into the inventory.

**Comment by Drullkus** [comment]
Potentially invalid in future due to future Gui rewrite

**Comment by Drullkus** [comment]
I can chisel full stacks
