### ISSUE TITLE
EMC Support for ProjectE does not work

### ISSUE THREAD

**Issue by gabor7d2** [Chisel-Team/Chisel#18]
In the previous versions of Chisel 2 (2.5.0), the EMC Registration for ProjectE worked. I think it is not working because you changed the Mod ID from `Chisel2` to `Chisel`. It does work in Equivalent Exchange 3, I tested it. I don't want to Custom EMC in all the Chisel things manually.
Sorry if I wrote the Chisel versions and branches etc. incorrectly, but these versions became very confusing to me.

Screenshots:
![2015-09-12_22 11 31](https://cloud.githubusercontent.com/assets/12859334/9833560/7332c5d6-599b-11e5-9e22-96399c830f96.png)
![2015-09-12_22 12 27](https://cloud.githubusercontent.com/assets/12859334/9833561/73358438-599b-11e5-8d53-cf908b50d62f.png)

Chisel Version: **2.9.0.3**

I will report it to ProjectE as well if you can't fix it.
If you need modlist, logs, or anything like that, tell me. Thanks for the help!

**Comment by TehNut** [comment]
The modid for Chisel has literally never changed. Not even from the original version that AM released.

**Comment by TheCricket** [comment]
There was never Project E compatibility. I think the whole mod was a bad idea so I never added support for it

**Comment by gabor7d2** [comment]
Okay, you are right. But in 2.5 I saw EMC values for most of the things, I may check it later. But can I ask you another question: Why there is 2 version branches then, like the `Chisel` with `235279` ID and the `Chisel 2` with `225236`? Because I don't understand for example that the latest `Chisel 2` version does fixes the false repeating issue when opening a chisel, but the latest `Chisel` does not, because that version is not in the other... Anyway.

EDIT: I checked the EMC values in `2.5.1.44` and in `2.5.0.43` and it is working correctly there. Maybe ProjectE added support for EMC values, but only for the `Chisel 2` modname. Because the modname changed, I can see that in WAILA and in the `mcmod.info` file. I may report it to they than. Thanks for the help! :smile:

**Comment by tterrag1098** [comment]
https://github.com/sinkillerj/ProjectE/blob/f7e188294cf10c9df842f7b4da4a3ce6567ffa2d/src/main/java/moze_intel/projecte/emc/mappers/Chisel2Mapper.java#L39

*facepalm*

**Comment by gabor7d2** [comment]
Okay, so I just have to wait for they to merge the pull request :smile:

**Comment by gabor7d2** [comment]
A New Update came out for ProjectE that fixed the problem. Thanks for your help! :smile:
