### ISSUE TITLE
Chisel API jar is missing Javadoc

### ISSUE THREAD

**Issue by Voidi** [Chisel-Team/Chisel#180]
It seems that javadoc is striped from the API jar (1.9 Builds) . Shouldn't they be included or should i use another version in my dev enviroment? (I only want to use the API)

**Comment by Drullkus** [comment]
I don't thing the API is considered stable, but idk, @tterrag1098 ?

**Comment by tterrag1098** [comment]
It's not, but it should still be building properly. The api jar should have source in it, but even if not, we do publish a source jar which gradle should download and attach automatically.

**Comment by Voidi** [comment]
Ok, i deleted and readded the API in the IDEA Project settings and now it seems to work.
Sorry for the inconvenience.
