### ISSUE TITLE
[1.10.2] Crash on server startup

### ISSUE THREAD

**Issue by kwpugh** [Chisel-Team/Chisel#182]
Crash report: http://pastebin.com/raw/L8ZHHSLw

Forge: 2008
Mod: Chisel-MC1.9.4-0.0.6.30.jar

**Comment by C0rn3j** [comment]
Crashes on Forge 2010 too

**Comment by tterrag1098** [comment]
This should be fixed in the latest release

**Comment by C0rn3j** [comment]
Can confirm it works.(Chisel-MC1.9.4-0.0.6.33)

**Comment by kwpugh** [comment]
Confirmed, working on Forge 2011.
