### ISSUE TITLE
1.10.2 Crash with Shaders and Optifine

### ISSUE THREAD

**Issue by Redlotus99** [Chisel-Team/Chisel#183]
This may be related to https://github.com/Chisel-Team/Chisel/issues/172 or https://github.com/Chisel-Team/Chisel/issues/170 but wanted to open a new ticket as I don't see this exact same issue listed. It may also be a dupe from a few of the Optifine issues.

Here is the paste bin of the client crash I am getting. It seems server runs fine.

http://pastebin.com/drt5nuqh

Chisel - 0.0.5.29 also occurs in 0.0.6.32
Forge - 2008

**Comment by 0Navis0** [comment]
Now it crashs again with the new chisel version, the 0.0.6.33. :(

**Comment by tterrag1098** [comment]
Optifine is not supported

**Comment by 0Navis0** [comment]
Will it be supported one day ?

**Comment by tterrag1098** [comment]
Likely not. As our code works on vanilla, Optifine should be assuring that our code works with whatever nasty hacks they are doing to cause this crash. Chisel is a forge mod, and it works with forge.

Consider this. If you added chisel to a game with lots of other mods, and it started causing crashes in all of them (crashes that don't necessarily point to chisel, but go away when chisel is not there) you would blame these crashes on chisel right? Treat optifine the same way. Chisel works in all other circumstances EXCEPT for when optifine is present. So the blame is clear.

**Comment by 0Navis0** [comment]
Yeah I understand it, but you have to tell that to the optifine owner, because you both shift the blame on the other.
