### ISSUE TITLE
Crash when generating terrain on server

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/Chisel#187]
Server crashed when flying into new terrain after updating to the latest version of your mod. Tried logging in again after rebooting the server and it instantly crashed again. I'll downgrade the mod to a version that doesn't include world gen on my server until the issue is fixed.

Minecraft version: 1.10.2
Forge version: 12.18.0.2010
Mod version: [0.0.6.33](http://minecraft.curseforge.com/projects/chisel/files/2315165)

Crash report: http://pastebin.com/Lj6W6ER1

**Comment by tterrag1098** [comment]
Hm. Did you disable the basalt feature?

**Comment by ChloeDawn** [comment]
No, but I've set specialGen to false now and I'm going to try logging in again. Would I need to downgrade and then upgrade to remove existing world gen? Or will disabling the basalt feature fix the issue?

**Comment by tterrag1098** [comment]
I'd rather resolve this issue than avoid it. Could you post your entire fml client log?

**Comment by ChloeDawn** [comment]
I disabled specialGen and it seems to have solved the issue. Maybe you could have it set to false by default until the feature is less WIP? 

My client log exceeds the limit on pastebin so I had to upload the file itself to my dropbox.

https://www.dropbox.com/s/i10gfo77u9daadc/fml-client-latest.log?dl=0

**Comment by tterrag1098** [comment]
But that's the thing. The code the normal gen uses is here:

https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/Features.java#L188

And the code the special gen uses is here:

https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/common/util/GenerationHandler.java#L93

Notice that they are the exact same bit of code?

**Comment by ChloeDawn** [comment]
The crash report says its struggling on this line though , which needs to be processed before the actual generation happens, right? https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/common/util/GenerationHandler.java#L76

**Comment by ChloeDawn** [comment]
I don't personally know enough about world gen code to help out, I'm merely reporting a crash involving your mod :P

**Comment by tterrag1098** [comment]
The actual exception spawns from

```
    at team.chisel.common.util.GenerationHandler.replace(GenerationHandler.java:93)
```

Which is called from the line you linked.

**Comment by ChloeDawn** [comment]
I realise that I am using Vazkii's realistic terrain wrapper from Quark, but I don't think that would affect how Chisel interacts with the world? Here's the values for lava lakes in the realistic world type.

`\"useLavaLakes\":true,\"lavaLakeChance\":80,\"useLavaOceans\":false,`

And here's the class that handles the wrapper: [WorldTypeRealistic.java](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/world/world/WorldTypeRealistic.java)

**EDIT:** I tried loading a singleplayer world with default world type, and it caused the same problem, except my client hasn't crashed, it's just frozen.

**Comment by tterrag1098** [comment]
~~Ok, this is undoubtedly involved. @Vazkii are you causing the PopulateChunkEvent.Post event to be fired before worldgen somehow?~~

On second thought I doubt this.

**Comment by tterrag1098** [comment]
So this is a dedicated server? I will admit I haven't specifically tested that. I'll see if I can reproduce it.

**Comment by ChloeDawn** [comment]
Here's a crash report I got from trying to generate a singleplayer world using default world type. It's having trouble with other mods' world gen now too? http://pastebin.com/rmKNk2JA

The initial crash I reported was from connecting to an existing world after updating the mod, this crash was caused whilst trying to generate an entirely new world, which might explain why its also causing issues for other mods.

I have my Forge server running on my VPS, which is hosted by OVH.

**Comment by tterrag1098** [comment]
No, it's just that other mods (Pam's) are cascading their generation into other chunks, causing a recursive chunk load.

**Comment by tterrag1098** [comment]
Tested out of dev, in latest forge for 1.10.2, working just fine. 

![](http://i.imgur.com/zCLCBu6.png)

This must be caused by one of the many mods you have installed alongside chisel. I would recommend doing a binary search. Remove half of the mods (other than chisel) and test. If it works, then you know the problem mod is in the half you removed. If it's still broken, you know it's not. Repeat until you are left with one mod.

**Comment by ChloeDawn** [comment]
Okay, so. I have been through my _entire_ pack, and by the end of testing I have disabled every single mod except for Chisel, lost a bit of sanity.. and it's still crashing. So it must be how I have my config. I have a lot of the WIP blocks disabled in my pack.. And up until this update I've had Basalt, Limestone, and Marble disabled among other blocks such as Copper. So something is causing it to crash when I have the features disabled, I guess? That is literally the only possible explanation I can think of right now. Either that, or the fact that I'm too good for block descriptions is causing a problem.

`# For those people who just hate block descriptions on the world gen!
    B:imTooGoodForBlockDescriptions=true`

Here's a copy of my config that I have setup for my modpack: [pastebin.com/6gNXeEY5](http://pastebin.com/6gNXeEY5)

**Comment by ChloeDawn** [comment]
Can confirm: Enabling the basalt feature fixed the issue. So maybe it's not checking to see if the feature is actually enabled when it tries to use specialGen?

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/Chisel/issues/187#issuecomment-231789320

You mean _literally_ the first thing I asked you?

**Comment by ChloeDawn** [comment]
Shit I'm so sorry I thought you were talking about the specialGen feature for basalt D:
