### ISSUE TITLE
[Ore Dict] Basalt. Marble, and Limestone should be registered in the Ore Dictionary

### ISSUE THREAD

**Issue by Peach774** [Chisel-Team/Chisel#188]
Similar to andesite, diorite and granite, basalt and limestone should be respectively registered as 'stoneBasalt' and 'stoneMarble' and 'stoneLimestone'. This will increase mod compatibility.

**Comment by Drullkus** [comment]
What other mods use those oredict names?

**Comment by Peach774** [comment]
This is how stone is registered in vanilla minecraft. stone, stoneAndesite, etc. Quark currently uses stoneBasalt and I am trying to get Environmental Technology to use it also because having 3 types of basalt is ridiculous.

**Comment by Drullkus** [comment]
Excellent. I will use `stoneBasalt`, `stoneMarble`, and `stoneLimestone` then!

**Comment by Peach774** [comment]
Thank you so much!

**Comment by oitsjustjose** [comment]
Hey @Drullkus, any chance for adding the plank variants to the OreDict too?

**Comment by Keridos** [comment]
Hm, my Hitech diamond chisel apparently does not check for oredictionary alternatives for those items, too. Used Minetweaker to add them all to ore:basalt and ore:stoneBasalt and I cannot chisel the other mods basalt with the chisel.

**Comment by Drullkus** [comment]
We don't have oreDict handled yet.
