### ISSUE TITLE
special effects on facades not showing

### ISSUE THREAD

**Issue by wackoamd1** [Chisel-Team/Chisel#19]
the special color effects like on water blocks or futura blocks are invisible on facades.

conduit facades from ender io or the cable facades from ae2 dont show the special color.

if u "paint" the facade with the waterblocks the icon of the facade shows the correct color setting but assoon as u place the facade it turns see through or completely blue ( in case of the water blocks)

 this is on 1.7.10 with 2.9.0.3 chisel

**Comment by tterrag1098** [comment]
Try updating EnderIO. Also AE2 facades will never work with these kinds of blocks, it's not feasible. This is an issue for those respective mods, not us.
