### ISSUE TITLE
Crash when any Chiseled Block is rendered with Shaders

### ISSUE THREAD

**Issue by Kyyndle** [Chisel-Team/Chisel#190]
After a lot of trial and error, I discovered that frequent crashes were occurring when any Chiseled Block was rendered while Shaders were enabled. 

Additionally, Textures for Chiseled Blocks in the Chisel GUI's were also not rendered while Shaders were active. However, this did not cause a crash.

When Shaders were disabled, Chisel worked perfectly. 

Here's my latest crash log:
http://pastebin.com/raw/N2jawJeC

**Comment by tterrag1098** [comment]
Optifine/Shaders are not supported.

**Comment by Kyyndle** [comment]
Ah I see, thank you for the really quick reply!

Is it listed anywhere that Chisel isn't compatible with Optifine Shaders? Maybe I'm missing something. I've noticed you guys seem to get a lot of annoying tickets regarding this issue. It could save you a lot of headaches to add a disclaimer.

I'm still going to use this mod regardless. I just didn't know if it was an issue or not!

**Comment by tterrag1098** [comment]
Read my comment here. https://github.com/Chisel-Team/Chisel/issues/183#issuecomment-231745710

In my mind, it doesn't need a disclaimer, as it is obvious that this crash is caused BY Optifine, not Chisel. They are incompatible with us, not the other way around.

**Comment by Kyyndle** [comment]
Thanks for putting things in perspective, much appreciated. :)
