### ISSUE TITLE
"Tesselating block model" crash when entering new world

### ISSUE THREAD

**Issue by LlubNek** [Chisel-Team/Chisel#192]
I got an NPE "Tesselating block model" crash when entering a new world (just as Minecraft starts trying to render the world).

I'm using Chisel-MC1.9.4-0.0.6.33.jar, Forge 12.18.1.2013 and Minecraft 1.10.2.  I'm not using Optifine or any MCPatcher mods.

crash report:  [crash-2016-07-13_17.05.29-client.txt](https://github.com/Chisel-Team/Chisel/files/362461/crash-2016-07-13_17.05.29-client.txt)
log:  [latest.log.txt](https://github.com/Chisel-Team/Chisel/files/362462/latest.log.txt)

**Comment by tterrag1098** [comment]
This commit may improve things, though I'm not sure how this could have happened. It seems to be implying that the model got a null icon, but the block being drawn is a marble block (from worldgen) which works fine for plenty of other people. Could you try removing some of the many mods you have to see if the crash still occurs? You have far to many for me to attempt to reproduce this.

**Comment by LlubNek** [comment]
Just got a similar crash with a different mod set after adding environmental tech and base metals (and their dependencies).  Might be an issue with one of those two mods (I'd guess environmental tech... maybe a conflict with their basalt?).  I'll try a couple tests.

[crash-2016-07-22_16.24.11-client.txt](https://github.com/Chisel-Team/Chisel/files/379002/crash-2016-07-22_16.24.11-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379004/latest.log.txt)

**Comment by LlubNek** [comment]
With just these mods there's no crash (added a few rendering-related mods incase they're involved):

> AdditionalLootTables_1.9.4-1.05.jar
> BaseMetals_1.9.4-2.3.2.6.jar
> Chisel-MC1.9.4-0.0.6.33.jar
> chiselsandbits-11.5.jar
> environmentaltech-1.10.2-0.10.2c.jar
> jei_1.10.2-3.7.8.234.jar
> MCMultiPart-1.2.0-universal.jar
> OreSpawn_1.9.4-1.0.3.jar
> valkyrielib-1.10.2-0.10.2.jar
> Waila-1.7.0-B3_1.9.4.jar

**Testing repeatability**

Reentering the crashed world (from the comment above) with the same mod set as when it first crashed crashes again.
[crash-2016-07-22_17.05.02-client.txt](https://github.com/Chisel-Team/Chisel/files/379077/crash-2016-07-22_17.05.02-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379078/latest.log.txt)

Creating a new world (different seed) with the crashing mod set I get a different crash in McJtyLib (that's new... probably unrelated, I'll report it to McJty).
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379091/latest.log.txt)
[crash-2016-07-22_17.14.31-server.txt](https://github.com/Chisel-Team/Chisel/files/379094/crash-2016-07-22_17.14.31-server.txt)

Trying again (another seed, same mods), I get the Chisel crash again. but the minecraft launcher also stalled before it could show the crash report... (probably to much log file text accumulated, I need to restart it more often).
[crash-2016-07-22_17.35.06-client.txt](https://github.com/Chisel-Team/Chisel/files/379126/crash-2016-07-22_17.35.06-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379127/latest.log.txt)

It is repeatable, and not just for particular seeds.

**Comment by LlubNek** [comment]
**Removing base metals, environmental tech, and their dependencies**

Creating a new world (different seed) after removing mods doesn't crash.
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379140/latest.log.txt)

Recreating a world that previously crashed (same seed as in comment 3) doesn't crash.
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379155/latest.log.txt)

Definitely one of these two mods + something else...

**Readding base metals and dependencies**

Creating a new world (different seed) after readding base metals and its dependencies got a @McJty crash...
[crash-2016-07-22_18.23.10-server.txt](https://github.com/Chisel-Team/Chisel/files/379167/crash-2016-07-22_18.23.10-server.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379169/latest.log.txt)

Trying again (another seed) crashes.
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379180/latest.log.txt)
[crash-2016-07-22_18.35.00-client.txt](https://github.com/Chisel-Team/Chisel/files/379182/crash-2016-07-22_18.35.00-client.txt)

So looks like it's Base Metals or one of its dependencies, but I noticed a lot of this (shows up in other crashed logs too):

```
[18:34:47] [Server thread/ERROR]: Failed to save chunk
net.minecraft.util.ReportedException: Saving entity NBT
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1611) ~[rw.class:?]
    at net.minecraft.entity.Entity.func_70039_c(Entity.java:1515) ~[rw.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:360) ~[atj.class:?]
    at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:175) [atj.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:199) [lr.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:227) [lr.class:?]
    at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1011) [ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:355) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:216) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:393) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:328) [bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.IllegalStateException
    at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:83) ~[PheneList.class:?]
    at com.rwtema.zoology.phenes.PheneList.serializeNBT(PheneList.java:22) ~[PheneList.class:?]
    at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:121) ~[CapabilityDispatcher.class:?]
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1580) ~[rw.class:?]
    ... 12 more
```

... which suggests zoology is involved.

**Comment by LlubNek** [comment]
Using just these mods doesn't crash:

> AdditionalLootTables_1.9.4-1.05.jar
> BaseMetals_1.9.4-2.3.2.6.jar
> Chisel-MC1.9.4-0.0.6.33.jar
> chiselsandbits-11.5.jar
> jei_1.10.2-3.7.8.234.jar
> MCMultiPart-1.2.0-universal.jar
> OreSpawn_1.9.4-1.0.3.jar
> Waila-1.7.0-B3_1.9.4.jar
> zoology-1.10-alpha-1.0.0.jar
> [latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379205/latest.log.txt)

**Removing zoology**

Creating a new world with the crashing mod set after removing zoology and readding environmental tech crashes.
[crash-2016-07-22_19.23.29-client.txt](https://github.com/Chisel-Team/Chisel/files/379220/crash-2016-07-22_19.23.29-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379221/latest.log.txt)

Trying again without environmental tech crashes.
[crash-2016-07-22_19.36.37-client.txt](https://github.com/Chisel-Team/Chisel/files/379225/crash-2016-07-22_19.36.37-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379226/latest.log.txt)

So while something's going on with zoology, it's not what's causing this crash.  I don't think environmental tech is involved at this point.

**Comment by LlubNek** [comment]
Since McJtyLib has been crashing occasionally, I'll see if that's related (maybe there's a race condition to see whether Chisel or McJtyLib crashes first).

Using just these mods doesn't crash:

> AdditionalLootTables_1.9.4-1.05.jar
> BaseMetals_1.9.4-2.3.2.6.jar
> Chisel-MC1.9.4-0.0.6.33.jar
> chiselsandbits-11.5.jar
> deepresonance-1.9.4-1.2.0beta35.jar
> ElecCore-1.9.4-1.5.292.jar
> jei_1.10.2-3.7.8.234.jar
> mcjtylib-1.10-1.9.8.jar
> MCMultiPart-1.2.0-universal.jar
> OreSpawn_1.9.4-1.0.3.jar
> rftools-1.10-5.06.jar
> rftoolsdim-1.10-4.30beta46.jar
> Waila-1.7.0-B3_1.9.4.jar
> [latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379237/latest.log.txt)

**Removing mcjtylib**

Creating a new world with the crashing mod set after removing mcjtylib and its dependents crashes.
[crash-2016-07-22_20.04.18-client.txt](https://github.com/Chisel-Team/Chisel/files/379252/crash-2016-07-22_20.04.18-client.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/379253/latest.log.txt)

So it's not mcjtylib...

Anyway, this crash involves Chisel + Base Metals + something else I haven't identified yet.  Any ideas?

**Comment by Drullkus** [comment]
I wonder if it's caused by some mod screwing around with the Model Registry that causes our mod to have a.... hiccup.

**Comment by Continous** [comment]
Check chisels and bits. This may also fix the crash relating to shaders and optifine.

**Comment by LlubNek** [comment]
Remember chisels and bits was in the trimmed down tests, which didn't crash.

**Comment by tenten8401** [comment]
I'm getting a very similar error when using Optifine w/ shaders enabled. (on 1.10)

**Comment by Drullkus** [comment]
> "[I wonder if it's caused by some mod screwing around with the Model Registry that causes our mod to have a.... hiccup.](https://github.com/Chisel-Team/Chisel/issues/192#issuecomment-234726756)"

Or a combination of them, perhaps. Would be harder to isolate.

**Comment by tterrag1098** [comment]
@tenten8401 Optifine is not supported.

**Comment by tenten8401** [comment]
@tterrag1098 I know, I've seen you post that on a few other issue reports already, and know that you both keep shifting the blame. I'm just stating the fact that I am getting a very similar error with it.

**Comment by Drullkus** [comment]
@tenten8401 @tterrag1098 Optifine is not the cause of this issue.

Regardless, we still don't exactly support Optifine. It's simply too high-maintainence for us.

**Comment by Drullkus** [comment]
Is this still happening?

**Comment by Drullkus** [comment]
Poke this issue if this is still happening.
