### ISSUE TITLE
(feature suggestion) Quartz variants

### ISSUE THREAD

**Issue by 0Navis0** [Chisel-Team/Chisel#194]
I realized recently that Chisel didn't add any variants for Quartz, I told me it would be a nice idea if Chisel added more Quartz blocks. This idea came when I saw the mod Quartzly. http://minecraft.curseforge.com/projects/quartzly?gameCategorySlug=mc-mods&projectID=247159

**Comment by KnightMiner** [comment]
If you read the comments of #193, quartz is planned.

**Comment by Drullkus** [comment]
Yep. We'll also have chiseled flint which will look like black Quartz. I looked at that mod you linked and we'll be having most of those patterns and then many more.

**Comment by 0Navis0** [comment]
It's awesome ! And the chiseled flint has been suggested by me if I remember. Anyway I can't wait to see it. :)

**Comment by Drullkus** [comment]
Added
