### ISSUE TITLE
[1.10.2][Shaders][Optifine]

### ISSUE THREAD

**Issue by Rushmead** [Chisel-Team/Chisel#196]
Hi all,

Getting this crash when joining a server / world with shaders on. If you could fix this, would be great. I love myself some shaders in my trailers :)

http://pastebin.com/62RaxcrD

Thanks
Rushmead

**Comment by LuigiHutch** [comment]
See https://github.com/sp614x/optifine/issues/185

**Comment by Redlotus99** [comment]
Obviously Optifine folks aren't going to fix this is there anything you ac do at all about this? Config option, anything?

**Comment by tterrag1098** [comment]
As I don't know what causes it, no.
