### ISSUE TITLE
Invisible Blocks with Optifine

### ISSUE THREAD

**Issue by acanady** [Chisel-Team/Chisel#198]

**Comment by acanady** [comment]
As it says I'm using the lates Optifine 1.10.2 Ultra C2 version with Chisel version 0.0.6.33 and the chisel blocks don't show up in JEI or the Chisel. If I use the Chisel and try to say transform a piece of cobble to a chiseled variant buy guessing where it is on the GUI the game crashes horribly. Removing Optifine fixes this issue. Normally I would just remove Optifine but my shaders wouldn't work then. Has anyone else had this issue with Optifine, is there a fix?

**Comment by Drullkus** [comment]
Wait.

**Comment by Drullkus** [comment]
Nvm, I'm bad at reading. Duplicate of #170.

**Comment by acanady** [comment]
Thanks
