### ISSUE TITLE
[1.10.2] No HolyStone

### ISSUE THREAD

**Issue by acanady** [Chisel-Team/Chisel#199]
I'm not seeing any holystone recipe or block in JEI. Is holystone not yet implemented in this version of Chisel or am I missing something?

**Comment by Drullkus** [comment]
Removed, use ~~Marble/Quartz (Quartz coming in a future update)~~ Chiseled Cobblestone as a replacement. Chiseled Cobblestone looks nearly identical.

**Comment by Drullkus** [comment]
If lots of people ask, we're release a Chisel blockpack in the future re-adding all of the legacy blocks.
