### ISSUE TITLE
Chisel 2.9.1 Crashes on Server-side when loading.

### ISSUE THREAD

**Issue by 1n5aN1aC** [Chisel-Team/Chisel#20]
Crash Report:  http://pastebin.com/vFMMXPkh

Appears server is trying to do something that is only provided client-side:

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister

**Comment by 1n5aN1aC** [comment]
....I guess you fixed this in https://github.com/Chisel-Team/Chisel/commit/ce44355dcfb71c9e2c519cee5a3296f95f2a451b

Sorta wish someone had said something, We've been waiting for it to be fixed.

**Comment by tterrag1098** [comment]
My bad, I forgot to reference the issue. But it was in the changelog.
