### ISSUE TITLE
Dupe Bug With Items Being Chiselled

### ISSUE THREAD

**Issue by Apocryphai** [Chisel-Team/Chisel#200]
If I use a chisel to carve some items, [REDACTED] they duplicate in my inventory. Mostly it doubles the item stack but sometimes it creates more than that.

This is in AllTheMods pack 1.10.2 v1.7, Chisel-MC1.9.4-0.0.6.33 and tested with Diamond Chisel.

**Comment by Apocryphai** [comment]
Update: it's to do with right-clicking to use the chisel straight after logging in. [REDACTED]. You can even do it with blocks that can't be chiselled, [REDACTED].

**Comment by ghost** [comment]
Blocks and Items are two different things.
You may or may not have confused one of the devs with this.

**Comment by Apocryphai** [comment]
My bad, it's blocks only.

**Comment by tterrag1098** [comment]
I'm not 100% clear on how to reproduce this. Would it be possible for you to record a video/gif of it happening?

**Comment by Apocryphai** [comment]
Here you go:  [REDACTED]

**Comment by tterrag1098** [comment]
~~I could not reproduce this on the laggiest server I know of (BTM). I suspect another mod might be playing a role here.~~

Nevermind.

**Comment by tterrag1098** [comment]
Fixed

**Comment by tterrag1098** [comment]
To prevent the spread of (fixed) dupe bug information, I have censored some portions of this issue.
