### ISSUE TITLE
1.7.10 Chisel 2.9.5.11 Carpet vanishes

### ISSUE THREAD

**Issue by Ryudragon2** [Chisel-Team/Chisel#201]
I like your guys carper and wanted to use them but half of it vanishes and now i cannot use it
![2016-07-30_11 32 54](https://cloud.githubusercontent.com/assets/10014757/17271732/84dc2952-5649-11e6-93cc-ae6404d14636.png)

**Comment by Ryudragon2** [comment]
![2016-07-30_11 45 08](https://cloud.githubusercontent.com/assets/10014757/17271785/1b75e55a-564b-11e6-8ffb-47af652b1780.png)

**Comment by tterrag1098** [comment]
Optifine?

**Comment by Drullkus** [comment]
Is this still happening?

**Comment by tterrag1098** [comment]
Unresponsive.
