### ISSUE TITLE
[Suggestion] [1.10.2] Make Basalt drop a flame-retardant ItemStack

### ISSUE THREAD

**Issue by oitsjustjose** [Chisel-Team/Chisel#202]
Pretty straight forward suggestion - it'd be super helpful if Basalt didn't burn in lava. Could you change basalt to spawn an ItemStack that isn't flammable? I know stuff like this is possible, ExU's Ender Pearls and Ender Lilly Seeds don't get destroyed by the Ender Lilly plants by a similar mechanic. In fact, I could probably write up a PR if it'd save you guys some time.

**Comment by Drullkus** [comment]
Not bad, I guess. A PR would be nice!

**Comment by oitsjustjose** [comment]
Well crap, I thought I'd be able to figure it out, but I tried and tried and tried. While I can get the ItemStack to technically live through fire damage, it stops rendering after it's been caught on fire (so it's as though on the client the item dies, but on the server it does not). 

Closing since I wasn't able to provide my own solution and it's not a big enough deal to inconvenience you guys for :smile:
