### ISSUE TITLE
[1.10.2] Crash when picking blocks from the chisel GUI with mouse wheel (ItemScroller Mod)

### ISSUE THREAD

**Issue by VsnGamer** [Chisel-Team/Chisel#205]
(Not sure if its ItemScroller Mod or Chisels bug)
Heres the crash log.

[crash-2016-08-09_20.11.46-client.txt](https://github.com/Chisel-Team/Chisel/files/409733/crash-2016-08-09_20.11.46-client.txt)

**Comment by tterrag1098** [comment]
The stack in the target slot is somehow null. This should never be possible with vanilla, so I have to blame ItemScroller. @masa ?

**Comment by tterrag1098** [comment]
Wrong ping. @maruohon

**Comment by maruohon** [comment]
This is now fixed in Item Scroller 0.6.2+ (release some time tomorrow, hopefully).

**Comment by VsnGamer** [comment]
nice

**Comment by Drullkus** [comment]
👍
