### ISSUE TITLE
2.9.5.11 crash on server start

### ISSUE THREAD

**Issue by Felkey** [Chisel-Team/Chisel#206]
http://pastebin.com/Pj3CzxHz

when i try and install chisel it first always asks me to do /fml confirm because forge detects the backup level.dat is being used

i also tried updating automagy to the most recent version as that seems to show up a lot in the crash report

EDIT: i should also point out that my client works fine with these mods

**Comment by tterrag1098** [comment]
>    at tuhljin.automagy.blocks.BlockRedcrystal.canReceiveRedstoneSignalFromDirection(BlockRedcrystal.java:1061)

What in the world makes you think this is caused by chisel?

**Comment by Felkey** [comment]
because i never had this issue until i installed chisel, works fine without

**Comment by tterrag1098** [comment]
Take it up with automagy
