### ISSUE TITLE
Dupe bug using chisel

### ISSUE THREAD

**Issue by AtomicBlom** [Chisel-Team/Chisel#212]
Steps to reproduce:
- Give yourself a diamond ore block
- Give yourself a piece of redstone dust
- Open the gui for a chisel or diamond chisel
- Place the diamond ore block in the preview slot
- Close the gui
- Open the gui
- Pick up the redstone
- Replace the diamond ore in the preview slot
- Place the diamond ore back in your inventory
- Close the gui
- Open the gui

You should have a second diamond ore block that you can swap again with more dust, or just grab it.

Environment:
- Mincraft 1.10.2
- Chisel MC1.9.4-0.0.6.37
- Forge 12.8.1.2064
- Windows 10 x64

Other mods:
- Chisel Sheep (unreleased)

Tested in Single player

Log:
https://gist.github.com/AtomicBlom/001942309356be85544e218b376e1fb1

**Comment by Drullkus** [comment]
Reproduced. @tterrag1098 you said this old GUI was up for a re-write?

**Comment by EverNife** [comment]
maybe related https://github.com/Chisel-Team/Chisel/issues/216
