### ISSUE TITLE
[1.10.2] Crash when entering a Cavern Dimension

### ISSUE THREAD

**Issue by MrAmericanMike** [Chisel-Team/Chisel#213]
Trying to enter the Cavern dimension in 1.10.2 in presence of the mod Chisel and Caverns the pack hangs with this errors on console.

http://pastebin.com/TmUhQYnB

Please if you need any fiurther information let me know, but mods versions and Forge version should be there on the log ;) Thanks.

**Comment by tterrag1098** [comment]
Considering I have no reports of this for vanilla dimensions, I am inclined to blame the mod that adds the Cavern Dimension.

However, I know very little about worldgen, so if the dev of that mod wants to explain why I am wrong, I'd listen.

**Comment by MrAmericanMike** [comment]
I have reported the issue on their GitHub also, I will let you know if I get any answer from the devs there ;)

**Comment by Drullkus** [comment]
Anything on kegare/Cavern#10 ?

**Comment by MrAmericanMike** [comment]
On the last worlds with both mods in the pack, the crash didn't happened again, so I guess it was some temporary bug or something. Will let you guys know if it happens again at some point.
