### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#214]
dont know if its Chisel or Forge related crash

crashlog

http://pastebin.com/eqZkj9Dq

**Comment by Drullkus** [comment]
What were you doing before this crash happened?

**Comment by ghost** [comment]
nothing special placing a torch on a redstone block

**Comment by ghost** [comment]
its probably a issue with enderzoo mobs in combo with light updates , a enderzoo mob spawned a few blocks next to me and my game crashed with the same crashlog. and i tested it in creative world and used a spawn egg from enderzoo and my game crashed with same log as in the first post

**Comment by Drullkus** [comment]
I think this was fixed when #215 was fixed. I tried reproducing just now, looked at all entities, and slew them with a diamond sword.
