### ISSUE TITLE
Crash at loading assets [1.7]

### ISSUE THREAD

**Issue by univalent-universe** [Chisel-Team/Chisel#217]
Everytime I start a modpack with Chisel, the game crashes before even on the menu screen.
It tries to load the asset and then crashes with the following error:
net.minecraft.client.renderer.StitcherException: Unable to fit: chisel:factory/wireframewhite - size: 16x16
Full crash log here: https://gist.github.com/THE-MegaMan/b3d7bb66ae12d6af103ed17efef0944e

**Comment by tterrag1098** [comment]
You didn't even read the log? It says right there "Maybe try a lower resolution resource pack." If you aren't using a resource pack at all, then your GPU simply can't handle the size of all the textures in the game.

**Comment by univalent-universe** [comment]
I did. The GPU I'm using is really not good, I don't use a resource pack.

**Comment by tterrag1098** [comment]
You're out of luck then. Try disabling some of the chisel modules you don't use in the config.
