### ISSUE TITLE
Crash when using chisel in world 

### ISSUE THREAD

**Issue by gigabit101** [Chisel-Team/Chisel#22]
This dose not happen all the time and it seems to be more if holding shift  
http://pastebin.com/PKRPRXgt

**Comment by hilburn** [comment]
The code at fault is:

https://github.com/Chisel-Team/Chisel/blob/1.7/dev/src/main/java/team/chisel/item/chisel/ChiselController.java#L90

In java `-1 % 2 == -1`

You'd need to do: `idx = (i + variations.length - 1) % variations.length;` or: `if (--i < 0) i+= variations.length;`

**Comment by TheCricket** [comment]
My bad

**Comment by tterrag1098** [comment]
Er...whoops

**Comment by tterrag1098** [comment]
Fixed in 2.9.2.X
