### ISSUE TITLE
[Bug] Naming compatibility

### ISSUE THREAD

**Issue by drakray** [Chisel-Team/Chisel#220]
Some [mods](https://minecraft.curseforge.com/projects/ruins-structure-spawning-system) do not support having a block/item with an hyphen in it, like the chisel:sandstone-scribbles block, it should be named chisel:sandstone_scribbles, to follow naming convention

**Comment by drakray** [comment]
any news on that?

**Comment by TehNut** [comment]
Why wouldn't they support it? That is a perfectly valid registry character

**Comment by drakray** [comment]
because Ruins use hyphen to split block name from metadata(I know, not a standard way of doing things either)
and as far as I know, only Chisel use hyphen in block name, and not even for that many block(wood planks and sandstone only)
changing to underscore would fix this very quickly, and normalize name

**Comment by tterrag1098** [comment]
That would break worlds. I'm not doing that just because one mod has broken parsing. This is a bug on their end.

**Comment by drakray** [comment]
no problem, issuing AtomicStryker for that then

**Comment by Drullkus** [comment]
For his end I recommend using the Pipe character.

**Comment by Drullkus** [comment]
Jesus Christ. GitHub doesn't accept formatting from emails. Pipe character `  |  `
