### ISSUE TITLE
[1.10.2] Crash When Entering New Chunks

### ISSUE THREAD

**Issue by xlxAciDxlx** [Chisel-Team/Chisel#222]
For some reason, any time I go into a new chunk my game crashes. I was originally thinking it was Biomes O Plenty at fault as I had just updated it, but disabling Chisel makes the error non reproducible and I can then enter new chunks without crashing. It may be a Biomes O Plenty issue as well, if it is please let me know and I can post on their GitHub as well. :)

[Crash Log](http://pastebin.com/TXjbzU68)

**Comment by Drullkus** [comment]
Related to #213

**Comment by tterrag1098** [comment]
I might know what causes this. Will make the change, and let it get tested

**Comment by tterrag1098** [comment]
Wait. This report is strange. Did you disable the basalt feature?
