### ISSUE TITLE
Light can travel through all blocks

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#223]

**Comment by tterrag1098** [comment]
As of what version? This duplicates #171

**Comment by ghost** [comment]
0.0.6.3 I believe, I'll double check the version and issue in a minute.

**Comment by ghost** [comment]
Light from the sky just passes through them and zombies burn under them

![](http://i.nentify.me/ooEza5gQ.png)

Note no shadows on the floor and burning zombies compared to the minecraft stone on the right

**Comment by phit** [comment]
this is still an issue in 1.10.2-0.0.7.3, made a darkroom out of chiseled blocks and no mobs would spawn

**Comment by phit** [comment]
@tterrag1098 still an issue over half a year later Chisel-MC1.10.2-0.0.13.29
