### ISSUE TITLE
Disappearing blocks

### ISSUE THREAD

**Issue by TheRedcode8821** [Chisel-Team/Chisel#224]
![2016-09-04_13 51 27](https://cloud.githubusercontent.com/assets/21981691/18229545/5397586a-72a7-11e6-8bfd-b445eb1b1c3b.png)
Some blocks keeps disappearing and re-appearing

**Comment by TehNut** [comment]
Do you have Optifine installed?

**Comment by TheRedcode8821** [comment]
Yes i do

**Comment by SephirothWS** [comment]
Disable Optifine, and see if the blocks disappear and re-appear. If they don't, its a conflict with Optifine's rendering code, and not a bug with Chisel.
