### ISSUE TITLE
better optimized rendering of chisel blocks

### ISSUE THREAD

**Issue by ilordnightmarei** [Chisel-Team/Chisel#227]
rendering of chisel blocks like the connected ones glass chisel block and metal chisel blocks  rendering seems slow and rather unoptimized implemented block can be probably  just youse base  minecraft rendering for  non connected blocks and maby  connected blocks can  try to use a  more nicer method of connecting  and rendering  as in not rendering unseen faces and  fixing some of the scafold factory block it makes the terrain under it see through

**Comment by tterrag1098** [comment]
> can be probably just youse base minecraft rendering for non connected blocks

For the most part, we do. However what we add on top of the vanilla system allows for resource packs to change how our blocks render easily.

> and maby connected blocks can try to use a more nicer method of connecting and rendering as in not rendering unseen faces

This already happens.

> and fixing some of the scafold factory block it makes the terrain under it see through

#197
