### ISSUE TITLE
uncraftble carpet blocks 1.10.2 and  ore ditionary  detection for certan blocks

### ISSUE THREAD

**Issue by ilordnightmarei** [Chisel-Team/Chisel#228]
ya really no crafting recipe for carpet block those are my favorite  and  ore dictionary detection for  metal blocks  as in  copper tin aluminum uranium ect automatic ore dictionary

**Comment by Drullkus** [comment]
Oredict added

**Comment by ilordnightmarei** [comment]
excellent now all that's left is missing recipes and  texture fixes

**Comment by ilordnightmarei** [comment]
um the carpet blocks  are you going to add a recipe to them cause i love the carpet blocks

**Comment by Tony1l** [comment]
the carpet is mind blowingly good in this mod, hope you get around to making a base carpet recipe for 1.10 for us survivalist purists. : )

**Comment by Drullkus** [comment]
Carpets added. Tossed in some [new variations](https://twitter.com/Drullkus/status/781472596575477760) as well. Have fun! 👍
