### ISSUE TITLE
[1.10.2] Chisel and CraftTweaker or Modtweaker support?

### ISSUE THREAD

**Issue by Stapleton** [Chisel-Team/Chisel#229]
Just curious at this point.
Is there a plan to get CraftTweaker or ModTweaker support for 1.10.2 Chisel?
I did some oredict fixing and now the blocks that I have fixed arent able to be used in the Chisel.
The fix I had in mind was to use one of the before mentioned mods to add the blocks back into the groups.
The unchiselable blocks being all the metals from Substratum that compat with the Chisel mod.

Any enlightenment on the topic would be greatly appreciated!
Thanks.

**Comment by Stapleton** [comment]
The metal blocks that arent able to be added is Aluminum, Copper, Cobalt, Bronze, Electrum, Invar, Lead, Nickel, Platinum, Silver, Steel, Tin, and Uranium.
I added this info just incase it helps the situation.

**Comment by starg09** [comment]
Any updates on this feature? This would come pretty handy in a 1.11.2 modpack we're developing, where we'd like to integrate some variants from a mod's blocks through chisel (which would make using them a lot easier).

**Comment by tterrag1098** [comment]
#586
