### ISSUE TITLE
Client side Concrete crash

### ISSUE THREAD

**Issue by lilmoefow** [Chisel-Team/Chisel#23]
Not sure how it happened. I have not made any concrete and there is none placed around me in the world. I was just standing on top of an Ancient Warfare Light Torque Shaft when the crash occurred.

http://pastebin.com/gzj6i9Es

**Comment by tterrag1098** [comment]
Duplicate of #21

**Comment by lilmoefow** [comment]
I dont have Morph on the server or any of Ichuns mods so is it actually a duplicate??

**Comment by tterrag1098** [comment]
It's the same exact error, which has already been patched. Next release will fix it.

**Comment by lilmoefow** [comment]
alright thanks
