### ISSUE TITLE
glowstone textures missaligned or  not  resized peoperly

### ISSUE THREAD

**Issue by ilordnightmarei** [Chisel-Team/Chisel#231]
http://imgur.com/44t0Czk   really that looks ugly please make it border less  and the other ones do this as well  the glow stone blocks

**Comment by Drullkus** [comment]
It's how the texture style goes and the way it's formatted. I already spent too long of time working with those. Feel free to PR alternative textures but I can't guarantee accepting.

These are my babies and you called it ugly :'(

**Comment by ilordnightmarei** [comment]
im sorry but some of them   look beter borserless and  they just dont look aligned right dosnt fit thats all :P they just need minor tweaks and ya ill gladly make some  textures

**Comment by Drullkus** [comment]
If you do make the textures, PR them to the [Textures Repo](https://github.com/Drullkus/Chisel-Textures)

**Comment by ilordnightmarei** [comment]
will do ya  ill  prolly send u border less  versions of some i mean i love the textures but some of the borders  make it look odd and some textures need rotated to match the top bottom  small changes but ya ill defenetly  bring some nice textures to the tables 🌴
