### ISSUE TITLE
Right click dupe bug

### ISSUE THREAD

**Issue by Bennyboy1695** [Chisel-Team/Chisel#232]
If you right click the chisel onto the ground after removing a chiseled block it will then have the chiselable block in the chisel inventory aswell as in your own.
Version - Chisel-MC1.9.4-0.0.6.44

**Comment by Drullkus** [comment]
Can you please clarify a little more of how you're doing it? What version are you using? What minecraft version? What mods are involved?

**Comment by Bennyboy1695** [comment]
Simply right clicking the chisel to open it again will essentially rollback the inventory of the chisel to before you chose and removed a chiseled block, but will keep the chiseled block in your inventory therefor duping it.
MC Version - 1.10.2
Mod Version - Chisel-MC1.9.4-0.0.6.44
Mod list - https://minecraft.curseforge.com/projects/all-the-mods/files/2331445

**Comment by tterrag1098** [comment]
This might be fixed in latest. Can you confirm?

**Comment by Drullkus** [comment]
They're on .44? Damn, they're fast about updating!

Can you please record this happening? You could just record a gif too. I'm trying to reproduce but it's not happening.

**Comment by Bennyboy1695** [comment]
https://www.youtube.com/watch?v=DdPHKI8P1mI heres a video, the chisel had durability but it didnt matter if it was brand new or used would still do the same thing

**Comment by Drullkus** [comment]
Wow... that is super bad. I reproduced it.

**Comment by tterrag1098** [comment]
Oh I know why this happens...will fix tonight
