### ISSUE TITLE
Crash on startup (1.10.2)

### ISSUE THREAD

**Issue by Not-February** [Chisel-Team/Chisel#234]
The log points to Chisel as the culprit. At first it was throwing this error for aluminum, and since that material doesn't exist in my set of mods, I tried disabling that feature(and others for materials not present in the pack) from the config - only for it to then throw the same thing for basalt. Which should definitely be present from this mod.

https://paste.ee/p/ufnQ1

**Comment by Slither88** [comment]
Getting the same crash. First Aluminium then basalt. Have several mods that have basalt in.

http://pastebin.com/1SzmAgL9 - Alu

http://pastebin.com/F0SX1W03 - Basalt

**Comment by trevpan** [comment]
I'm also throwing this error.
http://pastebin.com/hMzT5eXH

**Comment by jensz12** [comment]
Same issue here :-) 
[crash-2016-09-22_13.51.11-server.txt](https://github.com/Chisel-Team/Chisel/files/487186/crash-2016-09-22_13.51.11-server.txt)

**Comment by 0Navis0** [comment]
I have exactly the same problem too.

**Comment by tterrag1098** [comment]
Sorry about this. I'm working on a fix now.

**Comment by 0Navis0** [comment]
It's fine don't worry, it happens to everybody to make errors. ;)
