### ISSUE TITLE
Missing Textures on Factory Blocks

### ISSUE THREAD

**Issue by GreenWolf13** [Chisel-Team/Chisel#236]
Exactly what it says in the title. Since the latest update, the side textures for the "metal box" factory block have been missing.
![q8ivcdf7](https://cloud.githubusercontent.com/assets/2723312/18849536/44bcddc2-83e8-11e6-962d-e7284bfeca38.png)

**Comment by Drullkus** [comment]
Whoops. Didn't mean that to get into the release.
