### ISSUE TITLE
iChisel not creating blocks.

### ISSUE THREAD

**Issue by jelaw21** [Chisel-Team/Chisel#238]
Crafted an iChisel, selected the block, selected the pattern hollow, clicked chisel and nothing. Tried all patterns, nothing. 1.10.2 Chisel 6.46.

**Comment by tterrag1098** [comment]
Pattern has nothing to do with crafting. Select the variant you want in the list, it changes the block in your inventory in place.

**Comment by jelaw21** [comment]
Will test tomorrow.

**Comment by Drullkus** [comment]
[Works fine for me](https://gfycat.com/DishonestHomelyIndianjackal). What version of Chisel are you using?

**Comment by jelaw21** [comment]
Alright, close this ticket.
