### ISSUE TITLE
Optifine - connected texture chisel block not appearing at all

### ISSUE THREAD

**Issue by CorneliusCornbread** [Chisel-Team/Chisel#24]
The connected texture on any block doesn't show up when a block update happens but it can be fixed when you reload the world. I have updated optifine chisel and it still happens. Plz halp.
![2015-09-26_13 41 38](https://cloud.githubusercontent.com/assets/8294697/10119309/6a072cb4-6458-11e5-9385-6b7b9c4b6804.png)

**Comment by TheCricket** [comment]
its optifines fault, the mod sucks just don't use it

**Comment by CorneliusCornbread** [comment]
Then would you mind at least where I can report this bug to optifine?

**Comment by TheCricket** [comment]
I don't know where you would do that because I never used it. If you are someone who thinks they can't run a pack without optifine then you can't run the pack at all. IMO

**Comment by CorneliusCornbread** [comment]
Well having a world with over 50 chunk updates per second I think optifine would help, and you really don't give two shits on helping me do you? And I'm sorry I trying to fix something is a problem, just because a mod has problems doesn't mean that it's a bad mod. Funny thing is it's only on your connected texture blocks hmm sound more like a chisel problem.

**Comment by TheCricket** [comment]
Funny thing is optifine has never worked with chisel, We write code for Minecrafts rendering system. Not my fault Optifine rewrites the render system. You are correct I will not help fix your optifine problem. Because its optifine not chisel at all

**Comment by squarism** [comment]
Anyone wondering beyond what's been said here ...
`Video Settings -> Chunk Loading: Default`
fixed it for me with optifine installed (sry to hear it's annoying @TheCricket)  :partly_sunny:

**Comment by TheCricket** [comment]
Once you hear it for the 100th time you just kinda ignore the issues and say geez another optifine peasant

**Comment by Drullkus** [comment]
> geez another optifine peasant

xD

**Comment by melekaiah** [comment]
optifine is one really popular mod you know. if you keep hearing about optifine issues, it means, that your mod is getting very much attention, its been one of the staples of my own modpacks for quite some time. optifine however is acutally needed by quite a few players as well to help run it a bit faster. 

couldnt you talk to the optifine devs and figure it out rather than just dismiss it?. 

as previously said however, the default chunkloading fixes the issues. put it as a notice somewhere that it DOES work with optifine, just that it requires the default chunkloading.

**Comment by Drullkus** [comment]
We're **NOT** dealing with Optifine's crap. You bring it to them.

**Comment by Drullkus** [comment]
If you can't run the modpack without optifine yet you can with Optifine, you shouldn't be running the modpack in the first place.
