### ISSUE TITLE
Causing Other Mod Blocks to go Invisible!

### ISSUE THREAD

**Issue by RobertLSnead** [Chisel-Team/Chisel#242]
The latest update Chisel-MC1.9.4-0.0.6.48 is causing several headache to the following mods:
Thut's Elevator
Malisis Door's
Storage Network

Most if not all the blocks are going invisible and downgrading the update fixes the issue!
I have addressed all the mods listed and have come to the conclusion something changed that caused this issue!

**Comment by Drullkus** [comment]
What mods do you have? All of them?

**Comment by RobertLSnead** [comment]
Yes and then some!
I have only loaded the select few and have done several trouble shooting, I had help from the owner from Thut's that helped me determine this!

**Comment by Drullkus** [comment]
No optifine?

**Comment by RobertLSnead** [comment]
Yes! Sorry!

**Comment by RobertLSnead** [comment]
Can not run mc without it!

**Comment by RobertLSnead** [comment]
I can try leaving all and removing optifine that I can do?

**Comment by Drullkus** [comment]
Please try seeing if the problem persists without Optifine

**Comment by RobertLSnead** [comment]
will do, doing that now!

**Comment by RobertLSnead** [comment]
Removing Optifine does not help!  The problem still persists!

**Comment by RobertLSnead** [comment]
Also I noticed your file description still shows 1.9.4 but is released for 1.10.2 nothing major though!

**Comment by Drullkus** [comment]
Yes, the 1.9.4 mod jar works with both 1.9.4 and 1.10.2. I'll personally look at the issue later

**Comment by RobertLSnead** [comment]
I have also notified all the mod authors as well!  Thut is seeing what he can do on his end, not sure if that will help much though.

**Comment by RobertLSnead** [comment]
I should add it is also affecting redstone paste and MalisisSwitches more to be discovered!

**Comment by SiblisCu** [comment]
It also affects Ender IO facades painted like chisel blocks.

**Comment by tterrag1098** [comment]
Revert to previous release for now. Fix is in the works.

**Comment by Alexusexcel** [comment]
I can't downgrade Chisel to prev. 6.46 version! My world is crushing!! Can you fix the trouble? 6.48 still not working with Malisis doors and seems to conflict with other mods as well(((

**Comment by trabpukcip** [comment]
I noticed that build 48 was pulled from CurseForge after already downloading it to use in a modpack, so ducked that one.

**Comment by MrNinja93** [comment]
May be related, Blood Magic mimic blocks used on Chisel blocks causes them to render invisible, though this happens in versions of Chisel prior to 48. Currently running chisel 46 with this happening (No optifine)

**Comment by tterrag1098** [comment]
Should be fixed by .50
