### ISSUE TITLE
Huge duping bug! [1.10.2]

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [Chisel-Team/Chisel#245]
If you combine two nearly broken chisels in a crafting grid, and then use the new chisel it provides, It will dupe whatever block you try and chisel, This needs to be fixed, I sent TTERRAG a video of this bug

Thank you :)

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-Team/Chisel/commit/069efe64451668b3205cc67110631c63f4cb9f08
