### ISSUE TITLE
Unable to set public static team.chisel.common.block.BlockCarvable 

### ISSUE THREAD

**Issue by C0rn3j** [Chisel-Team/Chisel#246]
Errors: http://pastebin.com/7Har8wRQ

Forge 2095, happens in server startup log.

Modlist: https://rys.pw/Minecraft#Modlist

**Comment by tterrag1098** [comment]
@Drullkus are carpets not inheriting from BlockCarvable? If so, then the field in ChiselBlocks cannot be of type BlockCarvable.

**Comment by Drullkus** [comment]
This makes no sense. BlockCarvableCarpet does inherit from BlockCarvable. [Code](https://github.com/Chisel-Team/Chisel/blob/1.9/dev/src/main/java/team/chisel/common/block/BlockCarvableCarpet.java#L15)

**Comment by Drullkus** [comment]
Can you please isolate what other mods besides Chisel are causing this? I'm suspecting a mod causing problems alongside chisel.

**Comment by AtomicBlom** [comment]
I would also like to see a full server log, as opposed to just the exception so I can check for warnings that would have happened earlier.

**Comment by C0rn3j** [comment]
http://pastebin.com/fBYAHXiN

**Comment by LemADEC** [comment]
We're having same issue in our modpack. Common mods are:
ActuallyAdditions
AppleCore
armorplus
AutoRegLib
Baubles
bdlib
Botania
Chameleon
Chisel (obviously)
CookingForBlockheads
CraftingTweaks
FastLeaveDecay
forestry
gendustry
ImmersiveEngineering
InventoryTweaks
jei
journeymap
JurassiCraft
llibrary
MCMultiPart
Morph-o-Tool
Morpheus
NoMoreRecipeConflict
Pam's HarvestCraft
Quark
RoguelikeDungeons
StorageDrawers
TConstruct
thedragoncore
Tinkers' Addons
TrashSlot
Waila
Wawla
worldedit-forge

From the logs, it says:

```
Caused by: java.lang.IllegalArgumentException: Can not set static team.chisel.common.block.BlockCarvable field team.chisel.common.init.ChiselBlocks.carpet to net.minecraftforge.fml.common.registry.PersistentRegi
stryManager$BlockDummyAir
```

Looks like BlockDummyAir isn't a BlockCarvable...

**Comment by LemADEC** [comment]
Issue is related to the map itself.
Maybe an old chisel registry name isn't converting properly?

**Comment by LemADEC** [comment]
Issue is reproduced with just Chisel and Forge provided the map level.dat includes a "chisel:carpet" registered block.
Forge version tested: forge-1.10.2-12.18.1.2094-universal.jar

Here's a level.dat that reproduces the issue (I've renamed one of chisel carpet_xxx blocks to just carpet):
[level.zip](https://github.com/Chisel-Team/Chisel/files/517920/level.zip)

**Comment by tterrag1098** [comment]
That's not a crash

**Comment by C0rn3j** [comment]
I never claimed it was. It's an error happening in the server startup phase. 

Was the bug fixed since you closed the issue?

**Comment by tterrag1098** [comment]
The error can be ignored. It was caused by downgrading and missing blocks.

**Comment by C0rn3j** [comment]
So unless I create a new world I will keep seeing this error in the console?

**Comment by tterrag1098** [comment]
Sadly yes, it is a bug in the Registry/@ObjectHolder system

**Comment by C0rn3j** [comment]
Wouldn't it be possible to detect broken blocks and fix them instead of just letting them stay broken?

**Comment by tterrag1098** [comment]
That's not up to us, Forge manages the registries
