### ISSUE TITLE
Chisel 1.8?

### ISSUE THREAD

**Issue by ph1823** [Chisel-Team/Chisel#248]
Hello, i see chisel on Minecraft 1.7.10 and 1.10 not in 1.8 the chisel version 1.8 isn't exit?

**Comment by MyNameIsKodos** [comment]
No it does not, and it won't as far as I know.  1.10 is the current version of modded Minecraft, and there are plenty of mods on it so I'd suggest moving to it

**Comment by ph1823** [comment]
Ok thank.
