### ISSUE TITLE
Crash w/ Better Foliage 1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Chisel-Team/Chisel#249]
Forge 2092
[Better Foliage 2.1.0](https://minecraft.curseforge.com/projects/better-foliage)
Better Foliage Config: [BetterFoliage.txt](https://github.com/Chisel-Team/Chisel/files/516988/BetterFoliage.txt)
It crashes on world load with this mod. 
[Crash Log](http://pastebin.com/mR3m7eQB)

**Comment by tterrag1098** [comment]
There is a reason .48 was pulled, please downgrade to .46 until a fix is released.

**Comment by WenXin20** [comment]
Ok, thanks, I didn't realize that version had been pulled.
