### ISSUE TITLE
build.gradle fails when using netbeans (working directory != project directory)

### ISSUE THREAD

**Issue by Mysteryem** [Chisel-Team/Chisel#25]
This is rather minor, but build.gradle fails on line 166 due to line 162 https://github.com/Chisel-Team/Chisel/blob/1.7/dev/build.gradle#L162 using `new File('changelog')` as the working directory for netbeans is %netbeans install path%\bin. Changing it to use `file('changelog')` fixes this problem as file() is evaluated relative to the project directory and not the working directory. See 15.1 at https://docs.gradle.org/current/userguide/working_with_files.html

**Comment by tterrag1098** [comment]
Why not make a PR for this?
