### ISSUE TITLE
Some blocks still invisible and missing textures (Ender IO Paited!!)

### ISSUE THREAD

**Issue by Susjin** [Chisel-Team/Chisel#253]
In the first image is some conduit facades painted with tyrian, and the second is a glowstone block painted with a chiseled stone that have connected textures (other glowstone painted with chisel blocks are working fine)

I didn't saw other blocks with that problem

EDIT: all the chiseled stones are with that missing texture (just with painted blocks) and facades painted Laboratory blocks are with the same issue of the Tyrian

Screenshot:
https://imgur.com/a/Prrpr

**Comment by Watchful1** [comment]
I can confirm this still happens in latest chisel and ender io. 0.0.6.53 and 3.0.1.120 respectively.

**Comment by plutocracy** [comment]
also happening to me with latest version of both Chisel and EnderIO (0.0.6.53 and 3.0.1.120), any Chiseled block used with the painting machine produces a painted block with a broken texture when placed

**Comment by tterrag1098** [comment]
@HenryLoenwind was working on a fix for this from EIO's end. I'm not sure if it's been released yet.

**Comment by HenryLoenwind** [comment]
It's in build 121.

**Comment by Watchful1** [comment]
Any idea when that would get pushed to curseforge?

**Comment by Drullkus** [comment]
No idea, I know @tterrag1098 and @minecreatr are occupied with Civ 6:

<img width="240" alt="screen shot 2016-10-26 at 6 33 42 pm" src="https://cloud.githubusercontent.com/assets/5010174/19750993/c1ae92ce-9baa-11e6-817b-3fdcbe58aeac.png">

**Comment by Rezrazi** [comment]
Having the same issue
Working in build 0.6.46, broken starting from 0.6.50

**Comment by Drullkus** [comment]
Issue appears to be resolved.
