### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by utoc** [Chisel-Team/Chisel#254]
Greetings,

I've updated to MC1.9.4-0.0.6.50 (FML2095) and with this version I get this error each time we start the server: http://pastebin.com/yQeKsMP2

Full log here: https://gist.github.com/utoc/1b35494286c2d35043c42ea86aa92cec

Just passing the issue on.. We have not noticed any ill side effects yet; close out this ticket as needed.

**Comment by tterrag1098** [comment]
See #246
