### ISSUE TITLE
Using CTM Loader replaces *ALL* quads of a cuboid face.

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#256]
![2016-10-12_17 17 54](https://cloud.githubusercontent.com/assets/5010174/19332325/d28c194c-909f-11e6-8971-a5f3665024fd.png)

That's a beacon.

```
{
    "parent": "block/beacon_model",
    "textures": {
        "glass": "blocks/glass"
    },

    "ctm" : {
        "model": { "model": "beacon_model", "glass": "minecraft:glass.cf" },
        "face": "minecraft:glass.cf"
    }
}
```

beacon_model.json is the exact copy of the vanilla beacon.json.

Also: Item Model Broken

**Comment by Drullkus** [comment]
@tterrag1098

**Comment by tterrag1098** [comment]
No longer an issue when using ConnectedTexturesMod
