### ISSUE TITLE
Version 0.51 and Inventory pets (missing textures)

### ISSUE THREAD

**Issue by BrelanAllin** [Chisel-Team/Chisel#257]
Works fine with version 0.50.

No update to inventory pets in months.

Most items are missing textures.

**Comment by capnkirok** [comment]
Can confirm, 4 separate reports since yesterday.  (Hi @Drullkus!)

**Comment by Drullkus** [comment]
Wait... what?

I know we changed our way of loading our resources, are you talking about InvPet's Item icons being missing? Weird...

**Comment by Drullkus** [comment]
~~I'm gonna go ahead and look at how you handle resources in your json files, there might be some weird stuff happening.~~ Your Git Repo is empty! :(

**Comment by capnkirok** [comment]
Could be. Let me know if you find anything. I'll also look tomorrow.

**Comment by capnkirok** [comment]
OK, so you were RIGHT! It was the JSON... I found that one texture was working: The Anvil Pet. So I reviewed the Anvil Pet JSON side by side with the Apple Pet. ~~There was no difference other than the file name (e.g., not smart quotes or a missing character).~~ I then re-saved the file and tested again. Now the Apple Pet worked, with no changes other than re-saving. Seems like Chisel/Forge didn't like something about the file format.

Why Chisel had problems but other mods didn't is quite strange to me. I mean you aren't reading the raw JSON are you? Perhaps it's having trouble interpreting the file format? I'm uploading a JSON file that has 'troubled' formatting in case you want to do some error trapping.
[banana_pet.zip](https://github.com/Chisel-Team/Chisel/files/530826/banana_pet.zip)

Anyway, thanks for the pointer. I'll get an update today. And... yes, I need to publish my code on git.

**Comment by capnkirok** [comment]
EDIT: If you look at that JSON file you will see there is in an extra closed bracket '}', which is being fixed when I re-save. Mea Culpa! Forge seems to ignore this, but Chisel has an issue.

Curious to know what you are doing with the JSON. I will poke around your repo.

**Comment by Drullkus** [comment]
Glad to hear the problem has been found :)

Yes, so we've got a custom json loader in front of our custom asset system, that enables us to put CTM on not only our Chisel's blocks, but blocks from other mods. :)

It even works on models! There's a few kinks @tterrag1098 needs to fix is all before I make a real announcement and push resourcepack creators to try it out

**Comment by capnkirok** [comment]
That is very cool. I've only recently discovered the power of JSON to open up new connections with other mods. Awesome idea.

**Comment by capnkirok** [comment]
Friends again: 

![friends_agai](https://cloud.githubusercontent.com/assets/9628379/19408548/244879de-92c0-11e6-9aed-9fe2d23fc64f.png)

**Comment by minecreatr** [comment]
Yay Friends :D

**Comment by Drullkus** [comment]
Issue resolved, we can all be friends now :D
