### ISSUE TITLE
Connected textures of other mods are broken

### ISSUE THREAD

**Issue by MySideYourSide** [Chisel-Team/Chisel#259]
Using .50 or .51, connected textures controlled by Optifine are not working (glass, bookshelves, Conquest Reforged blocks, etc). I'm not sure of your support or stance on Optifine. Versions .46 and earlier do not break other connected textures, but I cannot downgrade because of world corruption. I will also mention this problem on Optifine's MC forum thread.

**Comment by tterrag1098** [comment]
I don't know what optifine does, and I have no way to test this issue. If anyone from their side has a suggestion I'm open to it, but there's not much I can do now.

**Comment by tterrag1098** [comment]
This is superceded by #273
