### ISSUE TITLE
Texture Pack Conflict

### ISSUE THREAD

**Issue by eidalac** [Chisel-Team/Chisel#263]
For some reason, this mod conflicts with the stone/gold/diamond tool textures from LithosCore resource pack (https://mods.curse.com/texture-packs/minecraft/lithos-core-32x-1-6-1-10-complete).  

All of those tools have a "no texture" icon.

It uses a json file to change the texture based on durability on all tools, so I'm not sure why it's specific to those 3 types only.  No other tools are affected.

**Comment by tterrag1098** [comment]
His json files are broken, Chisel is choking on them. I don't see a need to allow chisel to parse invalid json like vanilla apparently does.

For reference, all the affected models have an extra brace at the end.

**Comment by tterrag1098** [comment]
On second thought, I'll add some safeguarding around this, and let vanilla handle the errors. But he should still fix his json.

**Comment by eidalac** [comment]
Ok, I'll let him know about the problem.  Thanks,
