### ISSUE TITLE
Freezes Game w/ Xaero's Minimap Mod

### ISSUE THREAD

**Issue by WenXin20** [Chisel-Team/Chisel#264]
When I have the Xaero's Minimap Mod installed with Chisel, I get extreme lag and then the game freezes. It also causes rendering issues with the Minimap.
Chisel v0.0.6.53
[Xaero's Minimap v1.10.6](http://www.planetminecraft.com/mod/xaeros-minimap/) and up
Forge 2094 and up
Log:
[fml-client-latest.txt](https://github.com/Chisel-Team/Chisel/files/536877/fml-client-latest.txt)

**Comment by Drullkus** [comment]
Pretty sure the problem is in the minimap. Our mod is just exposing the problem with that mod. Try using Journeymap :)

**Comment by WenXin20** [comment]
Ok, I'll report this to that mod, although this only happens with chisel, even with a lot of other mods installed, it only freezes when the chisel and map mods are installed. The minimap worked fine with chisel before v0.0.6.53.

**Comment by WenXin20** [comment]
Ok, xaero96 fixed the bug. (It will be v1.11.1)
He also said to tell you this: 

> With the Chisel mod installed, getting the IBlockState straight from the world/chunk and using the following method:
> Minecraft.getMinecraft().getBlockRendererDispatcher().getBlockModelShapes().getModelForState(state)
> to get the block model does not return the correct model. It only works with states gotten from the state ids:
> getModelForState(Block.getStateFromId(Block.getStateId(state))) works, believe it or not.
