### ISSUE TITLE
Carpet Suffocates 1 Block Tall Mobs

### ISSUE THREAD

**Issue by pkfortis** [Chisel-Team/Chisel#265]
The new carpet blocks kill short mobs. It seems like they're suffocating, but I'm not sure. Discovered with cats (RIP Gumdrop), replicated with spiders, cave spiders, endermites, chickens, wolves, small slimes, and silverfish. 2-block high mobs aren't affected.

**Comment by ghost** [comment]
@Drullkus you owe this person a new cat.
You also may possibly owe everyone a new bugfix.

**Comment by Drullkus** [comment]
It's not a bug. It's a feature. That kills bugs. /s

Will look into why this is happening.

**Comment by tterrag1098** [comment]
Fixed!

![](http://i.imgur.com/GsFUirw.png)
