### ISSUE TITLE
Models Don't work properly work with Forge Blockstates

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#266]
I need absolute concrete evidence because I refuse believe in a different way, that some how forge block states are screwing up our models.

Launch this [fork of Immersive Engineering](https://github.com/Drullkus/ImmersiveEngineering/commits/master) after downloading [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) (Place it into your `libs` folder), and place the second Aluminum Scaffold Block that has the grate on top of it. The whole block will appear invisible in the world. 

![2016-10-20_03 37 12](https://cloud.githubusercontent.com/assets/5010174/19557727/eaac957e-967b-11e6-8b1d-58a3ff65917e.png)

**Comment by Drullkus** [comment]
Worked on some Isolation. It appears those are broken on just Scaffolding and not sure what else. When I put the textures onto a solid block, they started working fine. WTF is happening?

**Comment by Drullkus** [comment]
Something is horribly horribly broken.

For some reason, Immersive Engineering's Aluminum Scaffolding doesn't render. AT ALL. Uses the `"ctm":{}` option but it simply does not render. Other BlockStates in its group are working fine since they don't contain `"ctm":{}`.

![2016-10-20_10 53 49](https://cloud.githubusercontent.com/assets/5010174/19571640/b14d6c1c-96b3-11e6-80a7-351fed85e7ad.png)

I've pasted the same model onto Immersive Engineering's Copper Block. It doesn't render as well if the .cf textures use CUTOUT, but if I just remove `"layer"`, it comes with a different problem. For some reason, the model DOES render but is does not obey the `"overrides":{}` at all.

![2016-10-20_10 59 00](https://cloud.githubusercontent.com/assets/5010174/19571828/61baa9c0-96b4-11e6-9c79-2b259a5102b2.png)

![2016-10-20_10 59 03](https://cloud.githubusercontent.com/assets/5010174/19571853/7ddc5de2-96b4-11e6-8fe2-18e28561effe.png)

**Comment by Drullkus** [comment]
What drives me even crazier is that somehow @BluSunrize somehow [got them working just fine](https://twitter.com/BluSunrize/status/789123637668372480) without a hitch.

**Comment by Drullkus** [comment]
Loaded in [our resourcepack](https://github.com/Chisel-Team/CTM-Resources). I've made is so that the Copper Block uses the vanilla Glass block model, which has CTM. It appears it is not rendering at all. In the back you can see the real vanilla Glass which DOES work.

![2016-10-20_11 40 52](https://cloud.githubusercontent.com/assets/5010174/19573220/2841b890-96ba-11e6-90f0-f74635dd5fe6.png)

If I remove the `"layer":` tag, this happens.

![2016-10-20_11 45 43](https://cloud.githubusercontent.com/assets/5010174/19573343/c0f2b116-96ba-11e6-83d7-cc7d68b4315e.png)

The glass itself disappeared. OH COME ON!

**Comment by Drullkus** [comment]
NOW I have an answer. I thank @BluSunrize for pushing to his IE repo. I replaced the model for Light Engineering Block with the Glass Model and I now got progress in isolating the problem. There is something wrong with the files I'm writing, as Blu's files are working fine and somehow mine are not.

Considering all above observations, I now have made progress in tracking down the issue. This is what happens if I replace the Light Engineering Block's model with Glass's.

![2016-10-21_21 12 24](https://cloud.githubusercontent.com/assets/5010174/19616832/12e84bc0-97d3-11e6-9fb9-7bb53fb83b16.png)

**Comment by Drullkus** [comment]
And I believe I lost all progress. 

![2016-10-21_21 27 17](https://cloud.githubusercontent.com/assets/5010174/19616906/28680ed4-97d5-11e6-9d55-a2a629da81c7.png)

Left is IE's Blocks of Copper, and Right is Minecraft's Glass. (not rendering at all) This is what happens if I make the glass model use file `immersiveengineering:ctm/metalDecoration0_lightEngineering.cf`. (Copper blocks are using the glass model)

These mother fucking cheeky bastards are working just fine.

![2016-10-21_21 31 06](https://cloud.githubusercontent.com/assets/5010174/19616920/bc952b78-97d5-11e6-9c20-2c6529edd7bf.png)

This bug is made of quantum mechanics, able to bend itself and spin in extra dimensional parameters that are of no coherence to me.

**Comment by Drullkus** [comment]
Glass now uses its own model again. Reverts back to normal. Copper blocks continue to use the Glass model, which is it's proper model again. Does not render, expected as given the past behavior it has performed thus far. 

This test now has modified file `immersiveengineering:ctm/metalDecoration0_lightEngineering.cf`, which is the Chisel-Face file for the light engineering blocks. Its format as follows:

```
{
    "textures":[
        "immersiveengineering:ctm/metalDecoration0_lightEngineering.ctx",
        "minecraft:glass.ctx"
    ]
}
```

Here, we observe that the **Minecraft Glass** is rendering perfectly, fine, while the Block of Copper remains to be broken, as observed before in its same conditions, and is not touched by the Light Engineering Block's .cf file. However, the glass does not render at all on the Light Engineering Block? The glass fails to render on the Engineering Block.

![2016-10-21_21 39 26](https://cloud.githubusercontent.com/assets/5010174/19616955/e1b10c1e-97d6-11e6-8ab5-90f4e1c3d619.png)

I can now treat this as progress, it appears there is no problem with the model itself at all, but rather the _faces_ of it.

**Comment by Drullkus** [comment]
I think I've got the issue almost pinned.

It appears @BluSunrize used `TRANSLUCENT` instead of `CUTOUT` for `layer` in the `.ctx` file, which would have been appropriate for the `immersiveengineering:ctm/metalDecoration0_lightFrame.ctx` file. It appears changing `layer`'s value to `CUTOUT` causes it to not render at all!

```
{
    "type":"CTM",
    "textures":[
        "./metalDecoration0_lightFrame",
        "./metalDecoration0_lightFrame_ctm"
    ],
    "layer":"CUTOUT"
}
```

The issue is somewhere with rendering layers. Models are 100% OK, Faces are 100% OK, Issue is pin-pointed in CTX.

With `TRANSLUCENT`:

![2016-10-21_21 59 22](https://cloud.githubusercontent.com/assets/5010174/19617058/9879561a-97da-11e6-96f9-8ce58c03cdd0.png)

With `CUTOUT`:

![2016-10-21_22 00 53](https://cloud.githubusercontent.com/assets/5010174/19617062/a3f2c1de-97da-11e6-9409-e25d7536c81a.png)

**Comment by BluSunrize** [comment]
I used "TRANSLUCENT" because the frame applies a 10% alpha'd black border to the layer below it. Cutout doesn't allow semi-transparency, hence why the transparent layer exists for coloured glass, ice and stuff. I added said black border to give a depth effect.
I also found out that even when chisel specify's stuff to render on a specific pass, said stuff will only render if the block is allowed to render on that pass. Hence why I do this:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/ChiselHelper.java#L13
That activates the translucent layer for my engineering blocks only when chisel is installed. For performance optimization.
Technically I could even use my meta-based call to make it only use the layer for RS, light and heavy engineering blocks, since radiator and generator don't need it.

**Comment by tterrag1098** [comment]
@BluSunrize That all shouldn't be necessary. Just make sure to call super for `canRenderInLayer`.

**Comment by Drullkus** [comment]
> 10% alpha'd black border

Ah, I did not notice that. Keep using `TRANSLUCENT` then :)

**Comment by Drullkus** [comment]
> [`immersiveengineering:models/block/ctm/aluminum_grate.cf`](https://github.com/Drullkus/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/models/block/ctm/aluminum_grate.cf#L1)

# (┛ಠ益ಠ)┛彡┻━┻

**Comment by Drullkus** [comment]
> I also found out that even when chisel specify's stuff to render on a specific pass, said stuff will only render if the block is allowed to render on that pass.

@tterrag1098, he's actually right. Also in a very interesting way.

If I add this line of code to [ChiselHelper.java](https://github.com/Drullkus/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/ChiselHelper.java#L14)

```
IEContent.blockMetalDecoration1.setBlockLayer(BlockRenderLayer.CUTOUT,BlockRenderLayer.CUTOUT);
```

It appears the top side is now working. But not the sides. The sides are still vanilla textures without .ctx files, so I am assuming they are being assigned the value `SOLID` for RenderLayer.

![2016-10-22_11 03 18](https://cloud.githubusercontent.com/assets/5010174/19621458/4a122930-9847-11e6-9bf1-e057bc191506.png)

**Comment by Drullkus** [comment]
Issue located.

As posted by @tterrag1098:

> Just make sure to call super for canRenderInLayer.

**Comment by Drullkus** [comment]
Compat label added due to fault being in other mod, it will be a super easy fix for the other mod.
