### ISSUE TITLE
Aether foliage

### ISSUE THREAD

**Issue by Zekken01** [Chisel-Team/Chisel#268]
I know the aether rewrite is in beta and all but I was wondering if you can add support for it? Also, could we have options to disable things for a certain dimension? This doesn't belong in the aether.

http://i.imgur.com/M0F9eCD.png

**Comment by tterrag1098** [comment]
Sorry, I have no idea what you are asking for...

**Comment by Drullkus** [comment]
We don't add any decorative content related to plants at all, besides for Chiseled Planks for Vanilla Wood Types. I don't even see any of our blocks in that screenshot.

As for Chiseled Variations for Aether II blocks... I may look into it in the future.

**Comment by Drullkus** [comment]
What doesn't belong in the Aether? Those plants in the water? They're not ours. How are they ours? We don't even have any related to plants except wood planks and mossy cobble.
