### ISSUE TITLE
[Suggestion] More Nether Brick Variants

### ISSUE THREAD

**Issue by SkeletonPunk** [Chisel-Team/Chisel#27]
Made some nether brick textures last night for no reason, then a friend suggested I bring it here as a suggestion. These textures were designed to be the same block but have a random texture based on location using the variant system in 1.8's blockstate jsons.

![netherbrick](https://cloud.githubusercontent.com/assets/8498022/10203267/ce3aeaf4-6769-11e5-8940-c23dadba2051.png)
![2015-09-30_11 50 27](https://cloud.githubusercontent.com/assets/8498022/10203271/d0fadf74-6769-11e5-9b22-cf1867382f8b.png)

(sorry if they are a little too dark, I tried to make it as close to the nether brick texture as I could) here are some brighter ones I made as well
![netherbrick](https://cloud.githubusercontent.com/assets/8498022/10201933/62940c28-6763-11e5-9870-c76974f94394.png)

**Comment by minecreatr** [comment]
@Drullkus ^

**Comment by tterrag1098** [comment]
I like these textures, but the way you have it set up is not how chisel does randomized textures. It can only work in a square layout (2x2 or 3x3) and you have 5.

**Comment by SkeletonPunk** [comment]
I can modify them if necessary.

**Comment by SkeletonPunk** [comment]
![netherbrick](https://cloud.githubusercontent.com/assets/8498022/10204741/56ac0532-6772-11e5-99b5-3b74a80cfbc5.png)

**Comment by Drullkus** [comment]
_Approving intensifies_

**Comment by tterrag1098** [comment]
That texture is possible to work with. Drullkus you can add it if you like.

**Comment by Drullkus** [comment]
I'll put a tiny modification and then ship it.

**Comment by tterrag1098** [comment]
I added the texture, but I don't want to add a whole new block for one variant

**Comment by Drullkus** [comment]
Added in commit c05b85d
