### ISSUE TITLE
Chisel is rudely doing world Gen. 

### ISSUE THREAD

**Issue by StoneLegion** [Chisel-Team/Chisel#270]
It seems Chisel breaks one of the most fundamental rules and overwrites world gen rather then weight it into the game. Meaning that if you cave special world gen that adds new type of caves and such that chisel might place their crap floating inside of it.

Also means that chisel will overwrite and replace other world gen like say you find diamonds and chisel is a block away. Bet your ass it just ate the diamonds up.

**Comment by tterrag1098** [comment]
It should not. It only replaces stone. Else you would see it sticking into the dirt/grass

**Comment by StoneLegion** [comment]
Will close this then that does make sense. It might just been some bad luck or maybe something else causing it.
