### ISSUE TITLE
[1.10.2] Marble has incorrect texture displayed

### ISSUE THREAD

**Issue by Morpheus1101** [Chisel-Team/Chisel#271]
Forge vers *.2114
Chisel vers  *.6.53

Modpack Mods list @ https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/254

![2016-10-25_20 09 31](https://cloud.githubusercontent.com/assets/10524952/19682117/857b9ac4-9aef-11e6-991b-f96a02227336.png)

**Comment by Drullkus** [comment]
What the hell?

Relaunch your game. You probably changed a video setting or switched a resource pack and it screwed up the texture atlas.

**Comment by tterrag1098** [comment]
If that's the case, it's a bug on our part. However, we don't cache any UVs outside models so I doubt that....unless something modified the atlas without causing a resource refresh.

**Comment by tterrag1098** [comment]
Ok, the issue here is that changing the mipmap setting ingame is changing UVs, and our model cache is not being refreshed. This issue should actually fix itself if you don't update the blocks for a minute ;)

Easy fix, will do it tonight.

**Comment by tterrag1098** [comment]
Fixed via a68d230516bb747b93b4dd09404ac4702ab7f68a
