### ISSUE TITLE
TRANSPARENCY

### ISSUE THREAD

**Issue by LunyashaRu** [Chisel-Team/Chisel#272]
Guys, i know what you did a great job with mod, but why ALL of the blocks are using TRANSPARENCY, even if they do not have a transparent texture?! This is a huge hit for client performance. And it causes a very annoying micro-freeze bug, occurs when you placing the block from chisel on the block from chisel, associated with the calculation of the shadows.

![2016-10-25_17 42 47](https://cloud.githubusercontent.com/assets/22874697/19691281/64cb115a-9adc-11e6-9bf8-3dfe219ea67c.png)
![2016-10-25_17 43 20](https://cloud.githubusercontent.com/assets/22874697/19691300/6f8ade22-9adc-11e6-80d3-16238253e9be.png)
Please, fix it.

**Comment by Drullkus** [comment]
What version are you using?

**Comment by LunyashaRu** [comment]
Chisel 0.0.6.53 оn Minecraft 1.10.2 with Forge 2099.

**Comment by tterrag1098** [comment]
Hi. Can you try http://ci.tterrag.com/job/Chisel/branch/1.10%252Fdev/2/ ?

**Comment by LunyashaRu** [comment]
Thanks. It totally fix it. (FPS from 120 to 350)
