### ISSUE TITLE
Incorrect Block Model Method?

### ISSUE THREAD

**Issue by WenXin20** [Chisel-Team/Chisel#275]
I mentioned this in issue #264, but I decided put it here just in case.
Xaero96, the author of Xaero's Minimap, said to tell you this:

> With the Chisel mod installed, getting the IBlockState straight from the world/chunk and using the following method:
> Minecraft.getMinecraft().getBlockRendererDispatcher().getBlockModelShapes().getModelForState(state)
> to get the block model does not return the correct model. It only works with states gotten from the state ids:
> getModelForState(Block.getStateFromId(Block.getStateId(state))) works, believe it or not.

**Comment by tterrag1098** [comment]
Wrong, we use that method in our own code just fine. I'm not sure what issue he is having, but it's not on our end.

**Comment by WenXin20** [comment]
Ok, thanks
