### ISSUE TITLE
Rendering occasionally breaks on nearly all of the chisel blocks.

### ISSUE THREAD

**Issue by Lumindia** [Chisel-Team/Chisel#276]
Version: Chisel_MC1.9.4-0.0.6.53.jar
Minecraft Version: 1.10.2

http://puu.sh/rXBkJ/e857272913.jpg

Occasionally when I look at certain blocks in the world, the rendering on nearly all of the blocks just... stops... There's no crash involved, it's just that the rendering stops. 

Unaffected Blocks
-Stained Glass
-Ice Pillar

Partially Affected

-Lavastone
-Waterstone
(With these, the water and lava textures don't get placed on the block, instead just leaving a grey pattern)
http://puu.sh/rXE1R/4f9fbb0066.jpg

Fully Affected
-Everything Else

It seems to be sporadic as to when it happens. As for getting the textures to come back, sometimes just throwing the block on the ground is enough, sometimes placing the block fixes it, and sometimes placing it doesn't fix it at all.

**Comment by lixyth** [comment]
That has been happening to me too [for a little while now](https://www.reddit.com/r/HermitPack/comments/58t42d/missing_invisible_chisel_textures/).

**Comment by tterrag1098** [comment]
Some block in the world must be ruining the GL state. Nothing we can do here, it's impossible to know what exactly is throwing our rendering off.

**Comment by Lumindia** [comment]
Hmm.... I think it MIGHT be immersive engineering, since it only seems to happen when one of its complex machines is actively being rendered on screen

**Comment by lixyth** [comment]
Of course it's not impossible that that's the culprit for you, but there's no immersive engineering in the modpack I'm playing. If I find time later, I'll make a copy of my world and remove blocks one by one to see when the chisel textures show up.

**Comment by lixyth** [comment]
Okay the block that is doing it is the Enderman Head by Ender IO

**Comment by Lumindia** [comment]
I just confirmed this myself. Removed that block and nothing else has been setting it off

**Comment by MrNinja93** [comment]
It's been reported to EnderIO devs so hopefully a fix soon https://github.com/SleepyTrousers/EnderIO/issues/3770

**Comment by Drullkus** [comment]
Closing, this isn't our issue and already been since fixed. 👍
