### ISSUE TITLE
[Bug/Suggestion] The fans (factory block) are 32x32 instead of 16x

### ISSUE THREAD

**Issue by MarcusElg** [Chisel-Team/Chisel#281]
It looks really wierd when different textures have a different amount of pixels and it also doesn't look good with the vanilla blocks. It this intended or will it change? Change the title if it isn't a bug

**Comment by Drullkus** [comment]
Intended

**Comment by MarcusElg** [comment]
Why do you want 32x32 that doesn't look good next to any other blocks? Please change it

**Comment by Drullkus** [comment]
They look crap in 16x16 and are hard to do. If you want it changed, do it yourself in a resource pack. That is why they exist.
