### ISSUE TITLE
[Suggestion] Chiselable lettering

### ISSUE THREAD

**Issue by Alaisx** [Chisel-Team/Chisel#283]
Would be pretty cool if we could use the chisel to add lettering to blocks. Maybe uppercase, lowercase, and a few symbols? If you wanted to get fancy, you could even add multiple fonts. Anyway, text with one letter per block would be the perfect size for readability, and would look much more stylish than plastering the walls with vanilla signs.

**Comment by tterrag1098** [comment]
How would this work, a state for each letter? Meaning each set of letters would use 2 blocks?

**Comment by Drullkus** [comment]
I don't have the patience for creating 26 letters \* 2 cases \* 15 (and growing) block groups that use the same pattern sheet. That's +780 textures to add, with another 52 to add each time I add a new block that uses the sheet. 4 dedicated blockstate groups plus partial 5th blockstate group.

Gonna say no. It will take too many textures on the atlas, even worse if it uses CTM.

**Comment by Alaisx** [comment]
You are probably right. Perhaps Carpenters' Blocks would be a better place for this - its chisel tool appears to add overlays on top of the underlying texture, so should only need one texture per letter. Thanks for the quick response.
