### ISSUE TITLE
1.10.2 - Chisel causes weapon rendering json edits by resource packs to fail

### ISSUE THREAD

**Issue by Nazenn** [Chisel-Team/Chisel#284]
For some reason, Chisel is breaking the rendering of items that are assigned alternative textures according to damage through the vanilla json system. 

Screenshots of the issue and proof its chisel:
https://www.dropbox.com/s/nau4q9tmiuep4nf/Screenshot%202016-11-01%2001.50.20.png?dl=0
https://www.dropbox.com/s/5jntduf5aeio3s6/Screenshot%202016-11-01%2001.50.27.png?dl=0

Copy of the json involved with one of these items from the Lithos texture pack:

`{
    "parent": "item/handheld",
    "textures": {"layer0": "items/gold_axe"},
	"overrides": [
        {"predicate": {"damage": 0.55},"model": "item/golden_axe_2"},
        {"predicate": {"damage": 0.9},"model": "item/golden_axe_3"}
    	]
	}
}

//In golden_axe_2

{
    "parent": "item/handheld",
        "textures": {"layer0": "items/gold_axe_2"}
}

//In golden_axe_3
{
    "parent": "item/handheld",
        "textures": {"layer0": "items/gold_axe_3"}
}
`
Issue hasn't been recorded with any other mods I know of, and the resource pack works fine with forge alone, even the latest version.

**Comment by TehNut** [comment]
The first json block has an extra `}` unless I'm mistaken.

**Comment by tterrag1098** [comment]
Yes, see #263

**Comment by Nazenn** [comment]
Thank you for letting me know. The other guy didn't actually ever let us know....
