### ISSUE TITLE
Concrete is missing

### ISSUE THREAD

**Issue by dpeter99** [Chisel-Team/Chisel#286]
Problem:
I can't get concrete in game (only the Immersive Eng. one)

Using:
Latest curse version.

Also I checked the config and it is not disabled.

**Comment by dpeter99** [comment]
So why the concrete is not added?

**Comment by dpeter99** [comment]
[Line](https://github.com/Chisel-Team/Chisel/blob/eddd8aed5ca2374d535bd55248844dce66510ac0/src/main/java/team/chisel/Features.java#L481)

But why does it need re-texturing?

**Comment by Drullkus** [comment]
Because the current concrete textures are brown but real concrete isn't. I need to fix it to Brown Stone but I will need to add real gray Concrete in exchange as well.
