### ISSUE TITLE
[1.10.2] Crash when creating the Chisel

### ISSUE THREAD

**Issue by mr-dreich** [Chisel-Team/Chisel#289]
When using version MC1.10.2-0.0.7.3, I get a rendering crash when creating the Chisel in a Vanilla Workbench or Tinkers Crafting Station. It works just fine in single-player but crashes in multi-player. I have quite a few mods present but the issue seems to be related to Chisel as rolling back to version "MC1.9.4-0.0.6.53" fixes the issue.

Crash Report with Optfine installed:
http://pastebin.com/raw/BxJn5cUN

Crash Report without Optfine installed:
http://pastebin.com/raw/GMKgHN0K

**Comment by tterrag1098** [comment]
This crash is clearly inside Minetweaker code. I'd report it to them.

**Comment by mr-dreich** [comment]
Damn, that was a super fast response. I'll also shoot them a report, thanks a bunch!

**Comment by mr-dreich** [comment]
Alright, I posted on their Bug tracker forum. But it doesn't seem too active sadly. :(

http://minetweaker3.powerofbytes.com/forum/viewtopic.php?f=16&t=936

**Comment by tterrag1098** [comment]
I wasn't even aware the official version of Minetweaker existed on 1.10.

**Comment by mr-dreich** [comment]
Ahh damn, you're right! I'm using [Crafttweaker](https://minecraft.curseforge.com/projects/crafttweaker?gameCategorySlug=mc-mods&projectID=239197), not Minetweaker... :(

**Comment by Lanse505** [comment]
@tterrag1098 @MrBlackswordsman 
Crafttweaker is the "official" continuation of Minetweaker from 1.8 and forward.
Also @MrBlackswordsman Don't post issues on the Minetweaker Forums, That's hardly ever used :P

**Comment by mr-dreich** [comment]
I guess this issue can be closed, as the maintainer of Crafttweaker has created a fix release that addresses this issue.
