### ISSUE TITLE
Feature Request - Stairs

### ISSUE THREAD

**Issue by tterrag1098** [Chisel-Team/Chisel#29]
_From @aldra2012 on December 25, 2014 8:14_

i was wondering if you could add grimstone stairs, or even more stairs. Btw love everything you have done with chisel keep up the great work!

_Copied from original issue: Chisel-2/Chisel-2#69_

**Comment by tterrag1098** [comment]
_From @TheCricket on December 25, 2014 16:29_

Ok

**Comment by tterrag1098** [comment]
_From @Adaptivity on January 13, 2015 12:40_

Also, would be cool to see smooth variants of vanilla stairs.

**Comment by tterrag1098** [comment]
This is from the old repo...mostly was just testing out migrating. I won't be doing any more.

**Comment by Drullkus** [comment]
1.8 and above - Chisels and Bits.
1.7 - Carpenter's Blocks
