### ISSUE TITLE
Wont Load

### ISSUE THREAD

**Issue by Gengi0927** [Chisel-Team/Chisel#290]
This mod looks like it would be great, especially when combined with chiselsandbits, however, when i enter Minecraft, the game will not load the mod, for further information, i am using forge to run Minecraft 1.10.2, CTMLib is present, and there are no crash, lag or other issues with the mod, I would apprectiate it if someone would/could help, Thanks!

EDIT: By wont load i mean the mod will not show up in the game, when i enter the game it tells me i have 5 mods loaded, including Chisel, there would be 6, the chisels will not show up in NEI or JEI menus.

**Comment by Drullkus** [comment]
Did you download from Chisel from [our Build server](http://ci.tterrag.com/job/Chisel/branch/1.10%252Fdev/), [Curse](https://www.curse.com/project/235279), or [Curseforge](https://minecraft.curseforge.com/projects/chisel)? If you are downloading from any other website, it's not from us, and may potentially be riddled with malware and we are not responsible for the damage caused.

What version of Forge are you using? What version of Chisel?

**Comment by Gengi0927** [comment]
I downloaded the mod from Curseforge, forge 12.1.8.2.2103, and Chisel 2.9.5.11.

**Comment by Drullkus** [comment]
...Dude, gg. You somehow grabbed the version of Chisel for 1.7.10. Go to the curseforge page and scroll down until you see the 'Recent Files' menu. You should be using Chisel 0.0.7.3.

**Comment by Gengi0927** [comment]
Woops, I have no idea how that happened, thanks for the help though!
