### ISSUE TITLE
Crash Problems

### ISSUE THREAD

**Issue by Gengi0927** [Chisel-Team/Chisel#291]
I have had problems with a mod, it seems that Chisel is what is causing the crash, i have provided a log.

Paste in the searchbar: 

EDIT: I fixed the crash, but now i cant open my inventory, and if i do, the game crashes.

**Comment by alexbegt** [comment]
Please give them the log that shows the crash for when you open your inventory.

**Comment by Drullkus** [comment]
....Where's the crash log?

**Comment by Gengi0927** [comment]
Sorry for the wait, i had previously resolved the issue, but now i can't get into any of my worlds before the game crashes Log: http://pastebin.com/LNucihYe

Edit: It looks like it was compat problems between Jei and another mod i have, sorry for the wait.
