### ISSUE TITLE
Crash due to block render (Tessellation?)

### ISSUE THREAD

**Issue by SirChamomile** [Chisel-Team/Chisel#292]
Not exactly sure what's going wrong but when I tried to reload the resourcepack this happened:

[crash-2016-11-04_23.13.20-client.txt](https://github.com/Chisel-Team/Chisel/files/573013/crash-2016-11-04_23.13.20-client.txt)

**Comment by Drullkus** [comment]
Would you mind trying to isolate this issue. First try it without any other mod, only Chisel. Then start re-adding mods in groups of five, until you get the crash to occur.

**Comment by SirChamomile** [comment]
I'll have some time tomorrow, I'll give it a shot. My hunch is that the crash is specific to Optifine, but we'll see.

**Comment by SirChamomile** [comment]
Can't seem to reproduce.
