### ISSUE TITLE
Chisel Gui not working

### ISSUE THREAD

**Issue by skyewolfe** [Chisel-Team/Chisel#294]
I have chisel installed on my 1.8.9 server and I can't seem to get the chisel gui to work. I hold the chisel, right click with it and the gui opens. I put the block in it and it gives no choices as seen in the screenshot.

My server runs the following mods:

Bibliocraft[v2.0.1][MC.1.8.9]
BiomesOPlenty-1.8.9-3.0.0.1603-universal
Birds-Nests-Mod-1.8.9
Chisel-Mod-1.8.9
FoxLib-1.8.90-0.8.2
Guide-Book-Mod-1.8.9
HarvestCraft-Mod-1.8.9
journeymap-1.8.9-5.2.4-unlimited
MysteryGift-1.8.9-0.2.1-universal
Pixelmon-1.8.9-4.2.7-universal
SpawnOfPsyduck-1.8.9-2.1.2-universal
Gym_Wars_2-Feebas_Unleashed-1.8.9-1.2.
PixelExtras-1.8.9-2.1.4-universal
spongeforge-1.8.9-1890-4.2.0-BETA-1693
![chisel](https://cloud.githubusercontent.com/assets/15220996/20033498/ecadb9b2-a377-11e6-9ccc-fe4271a8c721.png)

**Comment by tterrag1098** [comment]
1.8.x is unsupported.
