### ISSUE TITLE
Crash when logging of

### ISSUE THREAD

**Issue by MakerTim** [Chisel-Team/Chisel#295]
I was switching between worlds, and when i logged off my server i crashed back to desktop

Crashlog
http://pastebin.com/XPSXHngN

ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.7.3.jar
Forge 12.8.2.2121

**Comment by Dijkstra1-zz** [comment]
Getting the same crash sometimes when joining a server it is down to tesselating block modes, @MakerTim question, are you using optifine.

**Comment by Drullkus** [comment]
"MakerTim" seems familiar... 

There's no optifine here in the log, from what I've skimmed. Weird.

**Comment by tterrag1098** [comment]
Something is calling a render while the client world is null. AFAIK this is invalid, though it could be a race condition.

**Comment by Drullkus** [comment]
Well, I see CCLoader in the stacktrace. Relevant?
