### ISSUE TITLE
[Suggestion] WAILA Integration

### ISSUE THREAD

**Issue by ChloeDawn** [Chisel-Team/Chisel#296]
**Basic WAILA integration to display the style name of the chiselled block in the HUD tooltip.**

For example, this tooltip information:

![2016-11-11_16 26 45](https://cloud.githubusercontent.com/assets/9869940/20222075/dfa9fd62-a82b-11e6-9cce-f09507956dc3.png)

Would also be displayed in WAILA when looking at that block in the world: 

![2016-11-11_16 32 30](https://cloud.githubusercontent.com/assets/9869940/20222251/73645da4-a82c-11e6-8d4e-b47081686e28.png)

##### This is a mockup, I have not implemented any code for this screenshot.

**Comment by xenoflot** [comment]
It would be nice if TheOneProbe was also supported for this, since WAILA is so infrequently updated.

**Comment by tterrag1098** [comment]
[HWYLA](https://minecraft.curseforge.com/projects/hwyla)
