### ISSUE TITLE
Chisel forces crafting with wood to be locked to one wood type

### ISSUE THREAD

**Issue by nateranda** [Chisel-Team/Chisel#297]
When I chisel one wood type, all crafting recipes involving wood are changed to only that wood type.

I am using Chisel 2.9,3.9 for Minecraft version 1.7.10.

I'm using these mods in a custom modpack:
![mods](https://cloud.githubusercontent.com/assets/23443027/20251708/4d73a050-a9e9-11e6-833b-9fdb1bf80e87.png)

**Comment by tterrag1098** [comment]
What? I'm not sure what you mean.

**Comment by Banjooie** [comment]
I think what's saying is: If you use chisel to turn a wood plank into a vertical wood plank, all recipes suddenly require the vertical wood plank explicitly.

**Comment by Drullkus** [comment]
I'm not seeing this issue.
