### ISSUE TITLE
Can't Craft Chisel

### ISSUE THREAD

**Issue by kalmondo** [Chisel-Team/Chisel#299]
Hello! I tried to craft a chisel in Multiplayer and I could not take out out to put it in to my inventory. Eventually I tried Shift Clicking it, it ended up in the slot in my hand and it crashed my client. Log: http://paste.ee/p/ZwdNK

**Comment by tterrag1098** [comment]
The mod is not installed on the server.

**Comment by kalmondo** [comment]
Oh . . . Must have accidentally left the 1.7.10 version on the server side . . .  Thank you for the quick response, sorry for my mistake ^_^
