### ISSUE TITLE
[Request/Suggestion] Allow in-world chiseling in creative mode

### ISSUE THREAD

**Issue by kimfy** [Chisel-Team/Chisel#3]
Right now you can't chisel blocks in world while in creative, well you can but it breaks the block you're targetting. 
Version: 2.9.0.3

**Comment by TheCricket** [comment]
I can do this tomorrow

**Comment by TheCricket** [comment]
done

**Comment by kimfy** [comment]
Awesome

**Comment by tterrag1098** [comment]
Done in 2.9.2.X
