### ISSUE TITLE
Can't Chisel - Several 1.11 Issues

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#300]
- [Shift-clicking the Item into Chiseling slot](http://hastebin.com/ikuzolatal.txt)
- [Shift-clicking the Item from Chiseling slot (Different Crash)](http://hastebin.com/wibonamobe.txt)
- Can't take items out of list of results (no crash, simply no action)

**Comment by tterrag1098** [comment]
Just some lingering null-stack bugs. I mostly tested with the iChisel so that's on me.

**Comment by Drullkus** [comment]
Yep, the iChisel works perfectly and as intended. Weren't we going to overhaul the normal chisel GUI as well?

**Comment by tterrag1098** [comment]
These should all be resolved at this point. Reopen if not
