### ISSUE TITLE
[Request] Setting to let iChisel use RF

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#302]
Would it be possible to get an RF option for the iChisel?

**Comment by Drullkus** [comment]
It uses no power. There is no point.

**Comment by ghost** [comment]
Use RF instead of durability.

**Comment by tterrag1098** [comment]
No, Chisel won't be pulling in any power APIs. Addons can handle that.

**Comment by Drullkus** [comment]
@Tehnut, we recently re-added IChiselTool or whatitscalled, it might be a good time to update https://minecraft.curseforge.com/projects/morechisels?gameCategorySlug=mc-mods&projectID=227904 :)
