### ISSUE TITLE
Chisel only uses the first Oredict name when chiseling a block.

### ISSUE THREAD

**Issue by AfterRebelion** [Chisel-Team/Chisel#303]
When trying to chisel a modded block with 2 Ore Dictionary names, chisel only picks the first, so it doesn't detect other variants.
Example 1, with a Basalt stone:
![image](https://cloud.githubusercontent.com/assets/559819/20447478/582f202e-addf-11e6-8034-f67214f8d6ba.png)
Example 2, with Marble stone:
![image](https://cloud.githubusercontent.com/assets/559819/20447519/a4fd130c-addf-11e6-9ce6-04b7cdbcaf73.png)

**Comment by tterrag1098** [comment]
Yes, because it makes no sense for one block to be in-between two groups. There are two parts to this limitation:
1. There's not enough space in the GUI for both oredict groups
2. This would allow changing ANY stone into ANY marble (etc for other doubly-registered blocks) using this block as a proxy. 

Whatever mod adds these blocks is using the oredict incorrectly.

**Comment by AfterRebelion** [comment]
Well, the oredict is a forge thing, and they do exactly this a few times.
![image](https://cloud.githubusercontent.com/assets/559819/20452571/4b13d906-ae0d-11e6-9ba9-b2c813a17d93.png)

The mod that does this is a special version of [Mineralogy](https://mods.curse.com/mc-mods/minecraft/240974-minecraft-mineralogy), a mod that overrides stone generation with it own stone types.
For that matter, it needs to have at least the "stone" oredicted, so you can make stone tools and things that require stone in crafting, as there is no stoneBlock in the world. And I need the stone type oredicted to be able to use mineralogy variants in other mods.

If it where posible to specify a order in the oredictionary it really wouldn't be a problem, as the only thing I need in this case is to be able to change each stonetype to chisel it, [but as forge implementation on getOreIDs uses a HashSet](https://github.com/MinecraftForge/MinecraftForge/blob/c177219ff3742c9dd9c383f99e2670635e28088f/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L436) (or any other reason that I really can't understand), the order is practically random.

**Comment by Baughn** [comment]
It's an odd heuristic, but perhaps it'd work to use the longest name instead of the first?

The way people use the ore dict, that would usually be the most specific one. And if nothing else, at least it'd usually make the registration mostly predictable. Sort the list to fix the 'mostly'...
