### ISSUE TITLE
marble and limestone clusers generate them in Quark undergardens

### ISSUE THREAD

**Issue by 0Navis0** [Chisel-Team/Chisel#304]
Marble and limestone clusers generate them in Quark undergarden (a kind of big cave with trees, flowers and grass). It means that there is marble and limestone clusters in the void.

**Comment by tterrag1098** [comment]
Not sure, because we only replace stone when generating. Must mean that the cave generation comes later and only removes the stone. Not sure who to blame here. @Vazkii can you enlighten?

**Comment by 0Navis0** [comment]
It could come from Quark side since it happens with Basalt too that is added by Quark itself.
