### ISSUE TITLE
[Bug] Chisel glowstone has no drops

### ISSUE THREAD

**Issue by MysticAura** [Chisel-Team/Chisel#305]
MC: 1.10.2
Forge: 2121
Mod: Chisel-MC1.10.2-0.0.7.3

Issue: When a chisel version of glowstone is broken, neither the block nor glowstone dust drops.

**Comment by Drullkus** [comment]
Probably solved a while back. What happens now is that if you break glowstone with bare fists, it drops dust, if you break with silk, it drops the chiseled block.
