### ISSUE TITLE
antiblock does not glow anymore?

### ISSUE THREAD

**Issue by rahangar** [Chisel-Team/Chisel#307]
I'm running hermitpack 1.2.

Much of my design depends on antiblocks.  Unfortunately, they don't seem to glow anymore (compared to 1.7.10 version...bevo's tech pack)

Was this intentional? or is it a bug?

thanks

**Comment by Drullkus** [comment]
The glowy thing is not implemented yet, go yell at @minecreatr

**Comment by ChloeDawn** [comment]
\*pokes this issue with a stick*

**Comment by tterrag1098** [comment]
This is now implemented

**Comment by Artemis-E** [comment]
What happened? Playing Stoneblock modpack 1.12.2 and they visibly glow, but the light map is applied and they are spawnable blocks again.

**Comment by ChloeDawn** [comment]
The glow effect does not produce actual light and therefore does not prevent mob spawning.
