### ISSUE TITLE
swaping wand - chisels and bits blocks swapped out, become invisible in inventory

### ISSUE THREAD

**Issue by rahangar** [Chisel-Team/Chisel#308]
Not sure if this is a Chisels & Bits issue or a NotEnoughWands issue, so I'm posting in both places. If there is a better way of doing this so that both mod authors become aware of the issue, please advise.

It looks like I've pushed my graphics card beyond the number of chiseled blocks that it can support, So I'm using the Swapping Wand to replace some C&B blocks with non-C&B blocks. The blocks get replaced, but the C&B blocks that are swapped out and end up in my inventory are invisible! - the number of blocks is visible, but not the block itself. I can move those invisible blocks within my inventory, but I cannot place the invisible blocks.

In terms of swapping, in the image below, the new block is in slot 1, the old block is in slot 2.  I expect to see an image of the old block, in slot 4, but as you can see it is invisible.

Can you please have a look at this?

Here are is the version information:
Minecraft: 1.10.2
Forge: 12.18.2.2124
Modpack: FTB presents HermitPack version 1.4.0
Chisels & Bits: 12.7
NotEnoughWands: 1.10-1.4.0

![image](https://cloud.githubusercontent.com/assets/3137077/20567610/f437fb62-b15e-11e6-8860-b323f6b83a1f.png)

The tool tip for the invisible blocks:
![image](https://cloud.githubusercontent.com/assets/3137077/20567891/04d978f0-b160-11e6-9c75-224c51a66b59.png)

The tool tip for the expected blocks:
![image](https://cloud.githubusercontent.com/assets/3137077/20567932/32a89086-b160-11e6-866a-647fcaa3c4c7.png)

**Comment by Drullkus** [comment]
You've got the wrong Chisel, you want the Chisels And Bits repo, not Chisel.

https://github.com/AlgorithmX2/Chisels-and-Bits

**Comment by rahangar** [comment]
oops.  Sorry about that.
