### ISSUE TITLE
Chisel Renderer Spamming Console

### ISSUE THREAD

**Issue by oitsjustjose** [Chisel-Team/Chisel#309]
Log was too big to upload via Puush or Pastebin, but 

`[17:08:31] [Client thread/INFO]: [team.chisel.client.render.ModelChiselBlock:func_188616_a:108]: ItemOffsetTool.OffsetData(offset=BlockPos{x=0, y=0, z=0})
`
Is spammed literally constantly.

Looks like someone left some debug code in! D:

Running Chisel 0.0.7.4 & MC Forge 12.18.2.2166

**Comment by tterrag1098** [comment]
Release archived and a new one is up.
