### ISSUE TITLE
API jar is a requested download on Curse Voice Launcher

### ISSUE THREAD

**Issue by AlexPlus117** [Chisel-Team/Chisel#31]
Hi, I'm using Curse Voice Launcher to make modpack, so it tells me to update your mod, but it downloads the api jar, instead of downloading the real mod jar, so can you remove the API and the other jars, which aren't the mod itself, from your files list, please?

**Comment by TehNut** [comment]
> can you remove the API and the other jars

Those are there for a reason...

**Comment by TheCricket** [comment]
Those are optional jars for developers so that they can better use chisel. They shouldn't be pulled by curse. Also api is the only "non mod" file there the others are just versions you can't use

**Comment by AlexPlus117** [comment]
Ok, but at least can you put the mod itself as the latest release? Curse downloads the latest jar that finds here, which is the API, at the moment: 
![immagine2](https://cloud.githubusercontent.com/assets/8421361/10269238/41d0e4ea-6ad1-11e5-9ea6-7dc9db086460.png)

**Comment by TheCricket** [comment]
The main jar is the release, the others are sub-jars

**Comment by AlexPlus117** [comment]
I know it, but if I click the download button, it automatically downloads the API:
![immagine](https://cloud.githubusercontent.com/assets/8421361/10269259/e696ae10-6ad1-11e5-9369-1537fa85d8e8.png)
I had to download the mod manually, but Curse tells me I should upgrade your mod again.

**Comment by AlexPlus117** [comment]
Here's the result:

**Comment by AlexPlus117** [comment]
If I click the download button, here's what happens:
![immagine2](https://cloud.githubusercontent.com/assets/8421361/10269281/6d919704-6ad2-11e5-90a7-51a38b6a1730.png)

**Comment by TheCricket** [comment]
Thats curses fault

**Comment by AlexPlus117** [comment]
I sent them a ticket, but somehow the problem's gone.

**Comment by tterrag1098** [comment]
This has been fixed by the curse team
