### ISSUE TITLE
Crash on clicking on missing texture in the Chisel's GUI

### ISSUE THREAD

**Issue by Aquahatsche** [Chisel-Team/Chisel#312]
I chiseled a Prismarine block from vanilla. There was a missing texture in the Chisel's GUI (the magenta/black ckeckerboard). I clicked on it and the whole game crashed.

[crash-2016-12-03_02.18.15-client.txt](https://github.com/Chisel-Team/Chisel/files/628614/crash-2016-12-03_02.18.15-client.txt)

**Comment by tterrag1098** [comment]
This should be fixed in the latest release, you are 2 behind.
