### ISSUE TITLE
[Bug] Left clicking a chisel on a Crossroad's gear hitbox causes a crash

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#313]
So, I did this on accident, and my client crashed :P 

Playing on SSP, no idea if it affects servers or not.

Using version 0.0.7.7, on forge build 2171, and Crossroads 1.1.8 (This was on the ATM:Expert modpack v1.0.4)

[The crash report](http://paste.feed-the-beast.com/view/de4c9900)

[The moment it happened](https://clips.twitch.tv/starg09/AliveLeopardNoNoSpot)

**EDIT:** Oh, also please let me know if I should report it to Crossroads' author as well \^^

**Comment by trillllian** [comment]
This also happened to me when I accidentally left clicked a illumination orb (created by the illumination wand from not enough wands), and judging from the crash log it probably happens when you left click on a block that doesn't have any chisel variants.

**Comment by tterrag1098** [comment]
This was fixed via 553fe1932542681e6cb26598ffafaf0c3ea40c0e

**Comment by tterrag1098** [comment]
Released fix in 0.0.8
