### ISSUE TITLE
Cannot re-chisel blocks after they have been chiseled once.

### ISSUE THREAD

**Issue by SephirothWS** [Chisel-Team/Chisel#314]
Running Chisel-MC1.10.2-0.0.7.7.jar

After chiseling a block once, for example; Chisel's Basalt. I chiseled it to the Jellybean type. I decided I didn't want this variant, and went to re-chisel it like I always have been able to, but after selecting the jellybean basalt in the iChisel interface, it didn't bring up the other chisel blocks for me to select and change it. This problem exists with ALL chisel-able blocks.

Before Chiseling:
![Image](https://i.imgur.com/bXETZWj.png)

After Chiseling, and re-selecting to re-chisel:
![Image](https://i.imgur.com/Kv3l1dt.png)

**Comment by primetoxinz** [comment]
Can confirm with Chisel-MC1.10.2-0.0.7.7.jar

**Comment by Drullkus** [comment]
It works just fine on latest 1.10.2. We probably patched it some point and never closed this.
