### ISSUE TITLE
Textures/bocks going invisible: 1.7.10 (Using different version of Chisel)

### ISSUE THREAD

**Issue by Vetpetmon** [Chisel-Team/Chisel#317]
![2016-12-20_19 49 56](https://cloud.githubusercontent.com/assets/10699805/21373577/019f213c-c6ee-11e6-90e0-55c57e0e0599.png)
So, I've tried the latest version of Chisel and certain blocks (especially the factory blocks) would not appear visible most of the time. So, I tried version 2.9.8.2 and it was working perfectly fine until I found that other blocks, when in the player's hands or when the blocks were placed: The blocks turned invisible! I had to place or remove a factory block to make it visible again.
![2016-12-20_19 50 00](https://cloud.githubusercontent.com/assets/10699805/21373576/019d1518-c6ee-11e6-83f3-94d4374edbb6.png)
As you can see here, from the first screenshot, there's one dry tilled soil. as soon as it turns into wet tilled soil, the blocks instantly turned invisible again. (Second screenshot.)

Any help on fixing this or having a later update fix this will be greatly appreciated!
EDIT: 
Item not in hand:
![2016-12-20_20 24 41](https://cloud.githubusercontent.com/assets/10699805/21374139/8194ece2-c6f2-11e6-8f22-cb5c934437d1.png)
Item in hand:
![2016-12-20_20 24 43](https://cloud.githubusercontent.com/assets/10699805/21374140/81998a22-c6f2-11e6-907e-6dbfc04a094e.png)

**Comment by Drullkus** [comment]
Turn off Optifine's multithreaded chunk rendering. If that doesn't work, remove optifine.

**Comment by tterrag1098** [comment]
Duplicates #224
