### ISSUE TITLE
iChisel Dupe

### ISSUE THREAD

**Issue by Whazaaaaa** [Chisel-Team/Chisel#319]
It seems that people are able to Dupe any block they want with the iChisel tool.
Here is an explenation on how it works:
http://imgur.com/a/ZhgqQ

This is Hermitpack 1.5.1
Chisel-MC1.10.2-0.0.7.7
FTBserver-1.10.2-12.18.3.2185-universal
spongeforge-1.10.2-2171-5.1.0-BETA-2005

**Comment by tterrag1098** [comment]
Cannot reproduce in a standalone environment. Please report to your modpack's author.
