### ISSUE TITLE
Crashing during Right-Click with combined Direwolf and Hermitcraft packs

### ISSUE THREAD

**Issue by RepoDraghon** [Chisel-Team/Chisel#321]
I know there's another issue with the game using Zyin'sHUD and the FOV but this seems to be a separate issue with the Chisel, umm level 2 diamond chisel

[crash-2016-12-31_23.48.18-client.txt](https://github.com/Chisel-Team/Chisel/files/679936/crash-2016-12-31_23.48.18-client.txt)

**Comment by tterrag1098** [comment]
Duplicates #311
