### ISSUE TITLE
Request: Template for added modded stones

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#323]
There's a consistency in design among the chiseled stone offerings. Would it be reasonable to add a template (transparency and defining lines) so that modded decorative stones could be easily given chisel variants either by the mod author, a chisel config, or mod tweaker? (I know the quality results would very with the stone texture.)

**Comment by Drullkus** [comment]
> There's a consistency in design among the chiseled stone offerings

wat

I have _LITERALLY_ been doing consistent patterns for each new stone. What the heck are you talking about?

**Comment by ghost** [comment]
I'm talking about chiseling modded stone without having to make a whole new chisel. I'm building a modpack with Underground Biome Constructs and a couple of others and I thought having chiseled versions would be nice. You've done a great job with the textures and I didn't want to just insert my ham-fisted attempts without reaching out first.

**Comment by Drullkus** [comment]
Ah. You should bug the UBC devs about Chisel integration, adding chiseling variants of their blocks. They simply have a crapton of textures and I'm not gonna do it.

[You can find some of my texture grayscales here](https://github.com/Drullkus/Chisel-Textures/tree/master/lib).

**Comment by ghost** [comment]
Fair enough. Thanks for the mod and the response.
