### ISSUE TITLE
Many, many blocks show flowing water texture on sides when in water.

### ISSUE THREAD

**Issue by chokoth** [Chisel-Team/Chisel#324]
When most blocks are placed underwater, they show water flowing down beside them, even though that block is a source block, similar to the behavior of slabs in water.

This seems to mostly affect transparent chisel blocks, though minecraft glass and stained glass does not behave the same way.

**Comment by Drullkus** [comment]
Could you please show us a screenshot?

**Comment by Drullkus** [comment]
Hello?

**Comment by tterrag1098** [comment]
This is a vanilla bug, they have glass hardcoded not to have this effect, but any other transparent block will do this.
