### ISSUE TITLE
Chisel allows conversion between any cobblestones ignoring hardness and blastresistanse

### ISSUE THREAD

**Issue by Krysinski** [Chisel-Team/Chisel#329]
Chisel allows conversion between any cobblestones of  mod "geologica" and also between std chisel's list of cobblestone. I mean that granite cobblestone with resistance 9 (hardness 3) cant be converted in diorite cobblestone with resistance 12 (hardness 4). Blastresistance of meterials is very important for building on hardcore-tech servers and diorite is more difficult to mine material as granite. Only blocks with same hardness/resistance can be chiseled i think. Disabling cobblestone feature in Chisel2 conf isnt "real" fix of this issue.
Refer to https://github.com/lawremi/PerFabricaAdAstra/issues/58
mc: 1.7.10
mod: Chisel2-2.3.10.37
forge: 1614
servercore: Thermos-1.7.10-1614-56

**Comment by Drullkus** [comment]
When you put something in the oredict, you are implying equivalence. This is their problem.

**Comment by Krysinski** [comment]
Geologica cobblestones must be in oredict than you can use (but not convert!!!) any cobblestones for crafting. There you can use normal or more costly material to get same thing.  When you convert something you create one block from other, and there you can get more costly material from normal. Thats not right.
Can you add a user configurable blacklist so the user can decide whether or not some stone types are convertible?

**Comment by Krysinski** [comment]
@Drullkus Please, visit  lawremi/PerFabricaAdAstra#58 for more detailed explanations about.

**Comment by Krysinski** [comment]
reopen pls.

**Comment by TehNut** [comment]
All iteams listed under an oredict entry are to be considered 100% equal. That is literally the point of it. Chisel chooses to separate planks because it makes more sense to then end user. It also isn't possible to convert woods in Vanilla. 

If you must separate the cobbles, use Mine/Mod Tweaker.

**Comment by Krysinski** [comment]
Ok, pls tell me wich code can i separate cobblestone for chisel in MT script?

**Comment by TehNut** [comment]
Look on their wiki?

**Comment by Krysinski** [comment]
wiki ModT (http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Chisel_2_Support):
mods.chisel.Groups.addVariation("hardenedclay", <minecraft:stained_hardened_clay:*>);
Guess i need some that:
mods.chisel.Groups.removeVariation("hardenedclay", <minecraft:stained_hardened_clay:*>);
But for removeVariation there on WIKI only this **without groups**: mods.chisel.Groups.removeVariation(<chisel:hexPlating>);
So, removeVariation for group is work?

**Comment by Krysinski** [comment]
ModT not working with chise2! I try this:
`mods.chisel.Groups.removeVariation(<PFAAGeologica:strongCobble:3>); `
no changes. 
And `/mt chiselVariations` wont give me full list)))) WTF? I waste too many time for all that bugs, thanks for that adventure.
