### ISSUE TITLE
Update Notification Tab & Info Tab

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#33]
We should add an update notifier into the Chisel GUI... It'll help the users know that there's an update to Chisel but non-invasively unlike _most_ mods who use the in-game chat...

**Comment by Drullkus** [comment]
I'm thinking we could do a slide-out tab for this (Kinda like the Thermal Expansion Tabs, for their Redstone Control/Augments/Machine Side Config)

**Comment by Drullkus** [comment]
One other thing we could consider is adding another tab above the update tab that gives a short info on how the Chisel is used. It'll be short because using the Chisel is easy.

**Comment by Drullkus** [comment]
@tterrag1098 What do you think?

**Comment by tterrag1098** [comment]
I'm not generally a fan of update notifications, but if it's merely a GUI sidebar (with a ONE TIME dismiss) then maybe.

**Comment by Drullkus** [comment]
I mean just a tab on the Chisel GUI. So it's out of your face unless you click on it.

**Comment by tterrag1098** [comment]
This will be done with forge system eventually
