### ISSUE TITLE
[Feature Request] Auto-Chisel for 1.10.2 and higher

### ISSUE THREAD

**Issue by Xiaminou** [Chisel-Team/Chisel#330]
Are there any plans to bring back the auto-chisel? I know the i-chisel makes it easy to chisel a large amount of blocks but nothing beats automation.

**Comment by tterrag1098** [comment]
Yes

**Comment by vinixd1997** [comment]
any idea when we can expect the feature ?

**Comment by Xiaminou** [comment]
It's been implemented, thank you.
