### ISSUE TITLE
Mobs spawn in chisel blocks even on daylight.

### ISSUE THREAD

**Issue by AfterRebelion** [Chisel-Team/Chisel#334]
Forge: 12.18.3.2221
Chisel: 0.0.7.7

![image](https://cloud.githubusercontent.com/assets/559819/22121380/1ec839ee-de84-11e6-89cc-f6fa3d6ec098.png)
It seems like chisel blocks are not totally solid blocks, so mobs can spawn on the block below them. And as they make de block space into 0 lightlevel, mobs can always spawn, even on daylight.

**Comment by Drullkus** [comment]
I'm not seeing this problem. Poke this issue if it happens on latest.
