### ISSUE TITLE
Issue starting Minecraft (1.7.10)

### ISSUE THREAD

**Issue by uwuwu** [Chisel-Team/Chisel#336]
[log.txt](https://github.com/Chisel-Team/Chisel/files/725004/log.txt)
There is no crash log, the game simply doesn't start.
Minecraft doesn't open and it quickly goes from "Already Playing" to "Play" (as if it closed) through the time it goes through this repetitive log.
There is no note of other mods causing issues as far as I know, is it a problem with forge/chisel versions?
EDIT: Removed the mod, still happening, although Chisel is the only changes I've done..

**Comment by tterrag1098** [comment]
Not caused by chisel, what would lead you to think it was? There is a serious problem with your setup if you are getting this error. I'd suggest reinstalling forge.
