### ISSUE TITLE
Block Duplication with Draconic Evolution and Chisel

### ISSUE THREAD

**Issue by lanman14444** [Chisel-Team/Chisel#337]
Issue description: If you left click with a chisel on a chiselable block that has been placed with Draconic Evolution's "Place Item in World" feature. The chisel chisels the placed block and drops another as an item.

What happens: http://imgur.com/a/JBxGk

What you expected to happen:
The chisel not to chisel the chiselable block placed with Draconic Evolution.
Steps to reproduce:
Place a chiselable block by using Draconic Evolution's "Place Item in World" feature by pressing P, by default.
Left click the placed block with any chisel.
Version (Make sure you are on the latest version before reporting):

Minecraft: 1.10.2
Forge: 2221
Chisel: 0.0.7.7
Draconic Evolution 2.0.7-168
(Tested with only these two and their dependencies 
Does this issue occur on a server? Yes

**Comment by Drullkus** [comment]
@brandon3055
