### ISSUE TITLE
New Chisel Version on old Minecraft Version

### ISSUE THREAD

**Issue by Artemis2017** [Chisel-Team/Chisel#341]
Hello,

i want too use the new Chisel Version on my old Minecraft Version (1.7.10), because the new one (1.10.2) has texture for Hardened Clay or other Blocks, which exists in 1.7.10, but the Chisel Version for 1.7.10 hasn`t textures for them. Give it a chance that i can import the textures from 1.10.2 into 1.7.10? Or that i can play Minecraft 1.7.10 with Chisel for 1.10.2?

Regards

Artemis

**Comment by MCrafterzz** [comment]
I don't think 1.7.10 is supported so you need to update to get the newer blocks and new updates.

**Comment by Drullkus** [comment]
1.7.10 is on feature freeze
