### ISSUE TITLE
NullPointerException when Right-Clicking an EnderIO Conduit with a Chisel

### ISSUE THREAD

**Issue by MastaC729** [Chisel-Team/Chisel#343]
Chisel version: 1.10.2-0.0.7.7
Forge version: 2221

The following stacktraces were produced when a user on our server right-clicked an EnderIO conduit with a chisel:

http://pastebin.com/XhPXBRx6

Let me know if you need any additional information.

**Comment by tterrag1098** [comment]
The stack trace says it was a *left* click, and this seems to be caused by either EIO or sponge (can't tell which) putting a null hitVec into the event.

**Comment by MastaC729** [comment]
OK, I'll redirect this to either repo then, Thanks for the info.
