### ISSUE TITLE
Several broken textures on latest build

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#348]
Mods and versions used:

* Forge 2221 (MC 1.10.2)
* Chisel 0.0.8.9
* JEI 3.14.6.408

Broken textures include:

* Several Resource Blocks:
  - Aluminum
  - Bronze
  - Cobalt
  - Copper
  - Electrum
  - Gold
  - Invar
  - Iron
  - Lead
  - Nickel
  - Platinum
  - Silver
  - Steel
  - Tin
  - Uranium
* "Purple ME Controller" variant from Futura Block.
* Iron Bars textures (Included this one just in case, although it does say it being a WIP):
  - Frameless Bars (Invisible texture, allows xraying)
  - Thick grid (No transparent sections, has a plain white occupying them)
  - The other variants have missing textures.
* 9 variants of Factory Blocks
* All variants of Primal Voidstone
* All variants of Runed Voidstone

**Comment by tterrag1098** [comment]
Fixed in .10
