### ISSUE TITLE
[Suggestion] Stair Recipies for Chisled Stone patterns

### ISSUE THREAD

**Issue by mikeloeven** [Chisel-Team/Chisel#35]
This has more than likely already been suggested however i would like to be able to make cosmetic stairs from chiseled stone variations

**Comment by Stormalisk** [comment]
Right now, a good option for this is immibis's microblocks or carpenter's blocks.

**Comment by Drullkus** [comment]
Honestly, all of my yes with @Stormalisk's response

**Comment by Drullkus** [comment]
[See this comment](https://github.com/Chisel-Team/Chisel/issues/29#issuecomment-248475260)
