### ISSUE TITLE
wool is carpet there is not carpet...

### ISSUE THREAD

**Issue by jprocket45** [Chisel-Team/Chisel#351]
soooo I update chisel to 1.10.2-0.0.8.10 there is no carpet anymore only wool I went into my world and the carpet that was laid became wool had to revert thankfully it went back to carpet or that would of been a mess... please fix this!  There is a label for carpet but its the wool block im not sure if this is the only issue but this is what i found between carpet and wool.

**Comment by Drullkus** [comment]
Er... I'm confused. Screenshot?

**Comment by Drullkus** [comment]
Seems you cheated in these carpets in when they were handled differently in an earlier version. When I added new carpets, I reformatted the way these were registered and that caused your problem. Please keep in mind that Chisel for MC Versions 1.8 to 1.11 are still in Alpha and things are still in flux. If you can't craft or obtain something through survival, we most likely haven't finished messing with the thing and may change unexpectedly in the future. There unfortunately isn't a fix for the issue you're having.

Thank you for understanding.

**Comment by jprocket45** [comment]
Before update

https://cdn.discordapp.com/attachments/119603573880389633/280884649977184256/unknown.png

After update this would happen 

![image](https://cloud.githubusercontent.com/assets/11837257/22912255/3745e838-f232-11e6-9e3f-98de34db413e.png)


hopefully the images show basically there is no carpet anymore

**Comment by Drullkus** [comment]
Ooooh... Are they full-sized blocks instead of 1/16th blocks?

**Comment by jprocket45** [comment]
yes

**Comment by jprocket45** [comment]
totally messed up my carpet in my castle lol but luckily reverting back to the old ver fixed it

**Comment by Drullkus** [comment]
Collusionboxes and Hitboxes are fine, looks like models were busted, probably by the recent model optimizations.

![2017-02-13_18 26 56](https://cloud.githubusercontent.com/assets/5010174/22912435/243801e4-f21a-11e6-98c1-47f86c2bf1f2.png)

**Comment by jprocket45** [comment]
alright well ill just wait for the next update hehe
