### ISSUE TITLE
Connected texture issues with multiple blocks in 1.10.2-0.0.8.10

### ISSUE THREAD

**Issue by ate0ate** [Chisel-Team/Chisel#352]
In build 0.0.7.7 the connected textures were working perfectly but after updating to 0.0.8.10 there seems to be something odd happening. Here are some screenshots of the issue. It looks like some of the connected textures are broken, but only in certain areas, or facings/directions. I'm not sure really. It looks random. Breaking and replacing has no effect. Reverting to 0.0.7.7 results in things looking correct again.

http://i.imgur.com/pcFHgbH.png
http://i.imgur.com/EhixtaC.png
http://i.imgur.com/UrjmCIV.png
http://i.imgur.com/R5Y6h21.png
http://i.imgur.com/q6gKQX1.png

This is all using forge 12.18.3.2221

**Comment by tterrag1098** [comment]
Probably caused by the recent attempts to improve model caching. There must be a cache miss somehow, loading the wrong model. I'll look into it soon.

**Comment by tterrag1098** [comment]
Actually, I have a hunch. Could you try with this custom version?

**Comment by ate0ate** [comment]
I can, but is that the right link there? Couldn't find anything other than a tmpworld.

**Comment by tterrag1098** [comment]
https://drive.google.com/file/d/0BwDDNuT6abxISXROQ1NVd3VyWTQ/view?usp=drivesdk

Sorry, wrong link

**Comment by ate0ate** [comment]
Looks great to me. I will report back if anything pops up, but so far so good. Thank you.

http://i.imgur.com/uAoukwQ.png
http://i.imgur.com/koaxmJa.png
http://i.imgur.com/l2n23hP.png

**Comment by Drullkus** [comment]
That's a nice prismarine ceiling @ate0ate!

**Comment by ate0ate** [comment]
Thanks! Only thing that felt appropriate for an underwater base.

**Comment by tterrag1098** [comment]
Considering the issue is so intermittent, I would like you to keep using it for as long as you can, to see if the issue is gone for real. But that does look promising.

**Comment by ate0ate** [comment]
Will do. I'm doing some considerable expansion ans I always use chisel blocks so that should be a descent test.

**Comment by ate0ate** [comment]
Okay, after some rather extensive playtesting I have some good news and some bad news. The good news is that I have not encountered any instances of weird texture connections or anything else of the sort. The bad news is that since updating my framerate has plummeted and with the addition of more chiseled blocks to my world I actually had to revert to build 0.0.7.7 to continue playing. Its some really terrible lag. I tried throwing more ram at it but up to 7 gig had no effect. Not sure what is happening but the fps gets really bad just scanning over a wall of chiseled blocks. It only marginally improves putting some distance between myself and them too.

**Comment by tterrag1098** [comment]
This issue is known, see #353

**Comment by ate0ate** [comment]
Sorry about that then, I should have checked. I keep swapping back and forth between the version you provided and version 0.0.7.7 just to make sure everything is working well texture-wise. So far so good. The lag is tolerable when building and the like but I have to swap versions when doing anything mob related. I'll report back if anything arises only regarding the textures in the future.

**Comment by tterrag1098** [comment]
Thanks for the report, I found the issue and also discovered a clever optimization I could do. CTM should be just a little faster now. Every bit helps!
