### ISSUE TITLE
Lag in new update

### ISSUE THREAD

**Issue by mrtomwolf** [Chisel-Team/Chisel#353]
I play Sky Factory 3 but I keep the mods up to date rather than following the pack updates.

When updating to 0.0.8.10 the game starts lagging terribly, to the point it's no use playing. If there is anything I can do to help you figure out what could cause this I'd be happy to help.

Regards
TomWolf

**Comment by Chaogomu** [comment]
This one is repeatable.

Pack name is Requiem Experience. version 1.14

Several people have reported fps jumping back and forth from 1 to 30. Downgrading has fixed this.

**Comment by DV666** [comment]
Same here with my private modpack : downgrading to 0.0.7.7 to fix it.

The CPU increase greatly (90-95%) when game try to load chunks.

**Comment by MatthiasMann** [comment]
I made a WarmRoast profile of that - and these calls are also in the "Chunk Batcher *" threads.

![chisel_is_slow](https://cloud.githubusercontent.com/assets/6777029/22949569/f8597fe6-f302-11e6-880b-2454be988d3f.png)

NOTE: This was just placing ~13 sand blocks and breaking them by hand - a very noticeable lag of ~1 second after every block placed or broken. This also varied by chunk - in some chunks this was not noticeable in others extremely like above.

**Comment by tterrag1098** [comment]
The change in question should have improved performance, so I'm trying to figure out why it's not.

Everyone affected, could you try this custom build to see if it improves things? https://drive.google.com/file/d/0BwDDNuT6abxIOGNLUXU1WEVCa3M/view?usp=sharing

**Comment by SeriousCreeper** [comment]
Had the block lag as well, the version you posted seems to have fixed it though, all smooth with that one.

**Comment by ate0ate** [comment]
Huge improvement over the prior build. Still some hiccups compared to 0.0.7.7  around portions of my base containing lots of chisel blocks, but definitely playable.

**Comment by ChloeDawn** [comment]
The lag is not only affecting FPS, but from testing has also been causing a small delay between a block being placed and the block actually rendering in the world - Any block.

**Comment by tterrag1098** [comment]
@InsomniaKitten that is quite impossible....immediate chunk draws are done on the client thread. There can be no delay (except a full pause).

**Comment by SeriousCreeper** [comment]
Actually i've seen the blocks not showing up for a second as well, but i saw it when i removed Chisel to test performance. 
You place a block, you see the bounding box right away but no faces are being drawn, and you can look through the world below the block. But yeah has nothing to do with Chisel.

**Comment by ChloeDawn** [comment]
Oh, I think I know what it *might* be. Do you have `alwaysSetupTerrainOffThread` set to `true` in your Forge config?

**Comment by SeriousCreeper** [comment]
Ah yeah i do have that one set to true as well.

**Comment by Janitor53** [comment]
@Kiyaku "nothing to do with Chisel"
Not sure about it. Today I made some tests with 0.0.7.7 and 0.0.8.10. All fine with first and lag every time I place or break a block with second. Grass/seeds too.

**Comment by SeriousCreeper** [comment]
@Janitor53 i wasnt talking about the lag/freeze when placing blocks, but the blocks taking a second to show up, even with Chisel removed. 

Try the version tterag posted in this thread, that got rid of the block lag for me.

**Comment by Morpheus1101** [comment]
After this fix, i was still getting Lag issues, once i removed Chisel form the pack, all issues i had are now gone.

**Comment by ChloeDawn** [comment]
Well the lag has significantly improved for me. I don't notice any severe lag anymore. Maybe something is conflicting with another mod in your pack @Morpheus1101 ?

**Comment by Morpheus1101** [comment]
Significantly less than b4 yes, but still quite noticable, i tested this removing all other mods and still encounted issues untill i removed Chisel
