### ISSUE TITLE
[1.10.2] OreDict support seems to be broken

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#355]
From what I understand from #188, the oreDict was implemented already. However, at some point it seems to have been lost, and in version 0.0.8.10 no block has oreDict entries.

This seems to affect the mod stones (Marble, Limestone, Basalt), not sure about the resource Blocks (assuming you intended to make them work as functional ingredients)

**Comment by ate0ate** [comment]
Same issue here. I relied pretty heavily on that for swapping between marble and glass mod variants lol.

**Comment by MurphysChaos** [comment]
It appears that none of the ores are being registered with the OreDictionary. Details on how to do this can be found here:
https://mcforge.readthedocs.io/en/latest/utilities/oredictionary/
