### ISSUE TITLE
[1.10.2] [Bug] Compatibility issue with RFTools Elevator Block

### ISSUE THREAD

**Issue by SnowShock35** [Chisel-Team/Chisel#356]
Hi,

I believe I have found a bug with Chisel on Minecraft 1.10.2. Here are the details. . . 

### Important Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2185
- Chisel 0.0.8.11
- RFTools 1.1x-5.83

### Issue Details

In a recent update to Chisel, there appears to be a new compatibility bug with RFTools mod and its elevator blocks. It seems that the block render when the blocks are being moved become un-textured. I imagine this is due to a change in the way the blocks are rendered in Chisel or perhaps a bug in the code. 

I've also confirmed that the issue is only present with the most recent build of Chisel (The one mentioned above).

I've also made @McJty aware of the issue at hand.

### Issue Media

![Issue Media #1](https://ss.blamesnow.co.uk/2017/02/1487242259-cc15f9d6.png)

**Comment by ate0ate** [comment]
That breaks Direwolf's world lol.

**Comment by SnowShock35** [comment]
I know. I found the bug while updating his pack and I use his latest world download to make sure nothing breaks.

**Comment by tterrag1098** [comment]
Considering mods like EnderIO still handle fake block rendering fine, I'd guess this is a bug in RFTools

**Comment by tterrag1098** [comment]
After investigating, RFTools does not set the render layer while drawing blocks. This is only valid while drawing the breaking animation, so it should be set manually by RFTools.

**Comment by McJty** [comment]
@tterrag1098 exactly how should I do this? What renderlayer?

**Comment by tterrag1098** [comment]
This one https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/java/team/chisel/client/render/ModelChiselBlock.java#L108

**Comment by McJty** [comment]
thanks. I'll check it out
