### ISSUE TITLE
missing carpet refile bug report with video

### ISSUE THREAD

**Issue by jprocket45** [Chisel-Team/Chisel#358]
I filed a report that was closed due to it not being a bug?? I made a video to make sure this was the case due 2 I am confused why its not considered a bug I could be wrong but please take a look...I am unsure how you go from having carpet all this time to not having carpet now....Thanks for your time! I am far from a professional youtuber so bare with me and the video.

https://youtu.be/Y2wDpdUm4N0

**Comment by TehNut** [comment]
It was closed because a commit that fixed it was pushed.

**Comment by tterrag1098** [comment]
Please do not open duplicate issues. Your previous issue has been fixed.
