### ISSUE TITLE
Chisel is breaking textures for IE

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#360]
Version: 0.0.8.11

Example: http://i.imgur.com/ql9DVcZ.png

These blocks render without issue when placed in the world. This makes it difficult to figure out what blocks  the multiblock structure requires, as you can imagine.

**Comment by Rahmiel** [comment]
Can confirm, did extensive testing pulling mods out. It might also be breaking Bibliocraft textures as well. This is extremely bad.

**Comment by tterrag1098** [comment]
The problem involves mods using the Chisel rendering system, and improperly handled fake block rendering. I've implemented a workaround which should avoid this issue. Ref e4ada9b2f9769246277c24f4c96b1e93bb064143

**Comment by ghost** [comment]
That was fast, much appreciated tterrag.

**Comment by tterrag1098** [comment]
Well, your issue got me to realize that this bug also affected the preview rendering in the iChisel, so I figured a rather quick fix was necessary :smile:

**Comment by ghost** [comment]
Tested it out and all is right in the world. Off to dump mountains of steel into the excavator now.
