### ISSUE TITLE
Crash upon world load with chisel update 0.0.8.12

### ISSUE THREAD

**Issue by ate0ate** [Chisel-Team/Chisel#361]
After updating chisel my world now crashes shortly after loading. The world briefly renders into existence then the screen turns black and hangs for about ten seconds before crashing with this...

http://pastebin.com/f3CfcGde

**Comment by tterrag1098** [comment]
EnderIO seems to be calling canRenderInLayer with a null layer, which as far as I know is invalid. I would report this to them.

**Comment by ate0ate** [comment]
Okay, thank you.

**Comment by ate0ate** [comment]
When did you stop maintaining EnderIO, @tterrag1098? I stopped playing Minecraft for a while after the 1.7.10 lull but I was a reluctant regular over on the EnderIO issues page when you were working on it lol.
