### ISSUE TITLE
Tesselating block in world with Chisel 1.10.2-0.0.8.12

### ISSUE THREAD

**Issue by mwilkinson81** [Chisel-Team/Chisel#366]
When in an area with chiseled blocks, the 1.10.2 minecraft client crashes with the error "Tesselating block in world". 

I was in a different area where there were no chiseled blocks for several hours before I went into an area the had chiseled blocks when the crashes started.

The crash happened two times a row. I'm using the OuterJaBip modpack that's available on Curseforge. The version of the modpack with Chisel 1.10.2-0.0.8.12 is 1.8.2

Crash report: [crash-2017-02-21_20.16.52-client.txt](https://github.com/Chisel-Team/Chisel/files/792204/crash-2017-02-21_20.16.52-client.txt)

**Comment by tterrag1098** [comment]
Update EnderIO
