### ISSUE TITLE
Request: Chisel Obsidian Portals

### ISSUE THREAD

**Issue by king5327** [Chisel-Team/Chisel#367]
After taking a quick look at the code, it appears that the Chisel obsidian does not even come close to being substitutable for vanilla obsidian in the production of a Nether Portal.

I've never looked too deep into Minecraft's internals, but my knowledge of Java suggests that a separate chisel block extending Obsidian should be able to trigger the same mechanisms that produce a regular Nether Portal.

As such, I'm requesting the change in the hopes that we will someday see Nether Portals that need no special housing to look nice.

**Comment by tterrag1098** [comment]
Nope, not how it works. Vanilla checks specifically for vanilla obsidian. Nothing we can do.
