### ISSUE TITLE
Several broken textures on 1.11.2-0.0.8.6 [Jenkins]

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#369]
Copying from #348, since it seems to be, besides some original bugs, almost the same (along other couple of missing fixes you've already applied on the 1.10 version... Maybe there was some merge missing or something?)

Anyways:

**Mods and versions used:**

* Forge 2252 (MC 1.11.2)
* Chisel 0.0.8.6

**Broken textures/models include:**

* Several Resource Blocks:
  - Aluminum
  - Bronze
  - Cobalt
  - Copper
  - Electrum
  - Gold
  - Invar
  - Iron
  - Lead
  - Nickel
  - Platinum
  - Silver
  - Steel
  - Tin
  - Uranium
* Iron Bars textures (Included this one just in case, although it does say it being a WIP):
  - Frameless Bars (Invisible texture, allows xraying)
  - Thick grid (No transparent sections, has a plain white occupying them)
  - The other variants have missing textures.
* 9 variants of Factory Blocks (all `chisel:technicalnew`)
* All variants of Primal Voidstone
* All variants of Runed Voidstone

**In addition to that, now on 1.11.2:**

~~* Variants of the following blocks with metadata value of 9-15 (Broken texture/model, both in-hand and placed in-world):~~
  - ~~Basalt~~
  - ~~Bricks~~
  - ~~Cobblestone~~
  - ~~Purpur~~
  - ~~Endstone~~
  - ~~Limestone~~
  - ~~Marble~~
  - ~~Prismarine~~
  - ~~Sandstone~~
  - ~~Red Sandstone~~
  - ~~Chiseled Stone~~
* All "Trodden Bricks" block variants, save for Temple Blocks: In all other cases, blocks look odd in-hand, then render correctly when placed in-world.
* Weird texture in-hand for all variants of mossy cobblestone.
* Waterstone blocks have transparent water in-hand, but solid water when in-world. Not sure which one would be the correct one...
* Carpet "Carpet Blocks" have an incorrect texture: they look like full blocks, doing CTM and all, but they keep their appropiate hitbox.

**Comment by starg09** [comment]
The metadata 9-15 seems to happen in my full test pack instance, checking on a clean instance made me notice that particular texture error disappeared. Will test adding mods one by one, see which one causes the issue.

**Comment by Drullkus** [comment]
Please try http://ci.tterrag.com/job/Chisel/branch/1.11%252Fdev/

**Comment by starg09** [comment]
Currently using latest build from there. Still haven't gotten around checking what other mod is causing that particular bug. The rest, however, happen with no other mod included.

**Comment by Drullkus** [comment]
Test it with 10 mods at a time instead of individuals at a time, it'll be quicker. It worked fine on my end too

**Comment by starg09** [comment]
Huh. Ok, not sure why I made that edit (Was 5am over here when I did it, lol), it actually happens even on a clean instance with only latest Chisel from the 1.11 Jenkings... There goes an hour of removing mods and reloading, lol (again).

So, I'd consider all those as bugs in the mod itself, not related to third parties.

**Comment by tterrag1098** [comment]
Could you please re-check on the official 1.11 release?

**Comment by starg09** [comment]
Seems like almost all is fixed! :smile:

Only ~~one~~ two remaining out of the ones in OP is the iron bars, but I guess that's because it's a WIP :) (**EDIT:** Forgot about the waterstone being transparent in hand, then solid in-world)

I'll close this one, and make a new report for the other two things. Thank you! \^^

**Comment by starg09** [comment]
Reopening because I forgot the waterstone one, unless you want me to make a separate issue of that one as well?

**Comment by tterrag1098** [comment]
These should all be fixed

**Comment by tterrag1098** [comment]
BTW the way waterstone works is intentional (and unfixable)
