### ISSUE TITLE
[1.11.2-0.0.9.10 / Forge 2252] Weird interaction with chiseled carpets CTM

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#373]
[The interaction itself recorded.](https://gfycat.com/NervousEcstaticDowitcher)

So, basically the carpet block's CTM seems to be a little bit bugged. When another of the same type of carpet is placed, the block below becomes a non-CTM one, and gets disconnected from the rest.

This is not the case when placing a different block, or even a different type of chiseled carpet block.

**Comment by Drullkus** [comment]
Occurs in 1.10 as well

**Comment by Drullkus** [comment]
@tterrag1098 We could solve this if we had a json flag to enable CTM connections to obscured faces.

**Comment by tterrag1098** [comment]
Fixed in https://github.com/Chisel-Team/ConnectedTexturesMod/commit/c0b7ae152bfb777a88ead7391fdfc2236ea639c4
