### ISSUE TITLE
World Edit Incompatability

### ISSUE THREAD

**Issue by Block3y219** [Chisel-Team/Chisel#374]
When i am using this mod with the World Edit mod i cannot use tool s in conjunction with these blocks. It spits out and error that says "Does not mach a valid block type "[Block ID]". This may have something to do with how your items identify within the code. Please make changes to this so this issue can be no more.

Steps to recreate:
1: Install WorldEdit + Chisel
2: Load a world and run "//wand"
3: Left click in one area, then right on another.
4: Run "//set [Chisel Block ID]"

You will receive the same error as i.

Cheers!
![invalid block](https://cloud.githubusercontent.com/assets/10631600/23581052/1eefc70c-0148-11e7-8765-1f8cbaebfe5c.PNG)

**Comment by TehNut** [comment]
Why is World Edit still using numeric IDs? They should be using the string ID.

**Comment by Drullkus** [comment]
JEI gives the Item IDs that place the blocks. Place the block you want to use and then type /info while holding an item like a stick or a prismarine shard to get the block ID. You can also just use F3.

**Comment by NewRaptor** [comment]
No  me deja poner codigos  numericos me sale que no se a encontrado el  codigo :(
