### ISSUE TITLE
[1.11] Carving.getOreGroup fails when passed ItemStack.EMPTY

### ISSUE THREAD

**Issue by AtomicBlom** [Chisel-Team/Chisel#375]
Hi there team,

I've got an issue with the Shear Madness port, because a slight oversight in Carving. The line of code causing me issues specifically, is 
https://github.com/Chisel-Team/Chisel/blob/eddd8aed5ca2374d535bd55248844dce66510ac0/src/main/java/team/chisel/common/carving/Carving.java#L175
Here is the log: https://gist.github.com/AtomicBlom/2b4f70880bbd6428f97e5d1adcd4c884

ItemStacks should not be null in 1.11, and the == null check should be !itemStack.isEmpty()

There are also a few other potential issues with itemStacks in Carving related to null checks. I tried loading up my fork to give a PR, but some dependancies (mcp mappings & forge aren't downloading for me at the moment)

**Comment by tterrag1098** [comment]
Oredict variants are gone for good, so this is "fixed"
