### ISSUE TITLE
[1.11.2] LittleTiles Connected Textures

### ISSUE THREAD

**Issue by CreativeMD** [Chisel-Team/Chisel#378]
Hey there,

i'm the author of LittleTiles. Some time ago as 1.7.10 was still a thing my mod supported connected textures for chisel, but unfortunately things got a bit more complicated for 1.11.2.

So maybe you can help me out. I might need someone explaining me how those connected textures work and if there is a way to implement support for it?

In Regards
CreativeMD

**Comment by Drullkus** [comment]
~~Really easy! Thanks for your interest in trying out CTM. All you need to do is to mess around with the resources. [We have a repo with examples.](https://github.com/Chisel-Team/CTM-Resources/tree/master/assets/minecraft)~~

~~You'll need to add [this section](https://github.com/Chisel-Team/CTM-Resources/blob/master/assets/forestry/models/block/apiary.json#L13-L23) to your model `.json` file. The `"overrides"` section is optional.~~

~~You'll then need to make the `.cf` file if the face(s) of your block need multiple layers. This goes into the Models folder as well. If the face needs only one layer, then you do not need this file. It is optional.~~

~~Then you'll need the `.ctx` file to define the texture. If it is going to be a non-CTM face, then you do not need the `.ctx` file either. Here is [an example of a `.ctx` file](https://github.com/Chisel-Team/CTM-Resources/blob/master/assets/forestry/textures/blocks/apiary.ctx).~~

~~Mind that we have multiple TextureTypes besides CTM, you can find a [list of what we register in Chisel here](https://github.com/Chisel-Team/Chisel/tree/1.10/dev/src/main/java/team/chisel/client/render/type), but you are totally allowed to register your own in your mod too.~~

EDIT: @tterrag1098 told me what LittleTiles was. RIP

**Comment by tterrag1098** [comment]
I believe he is asking more on the code side, since I don't think LittleTiles uses json models :stuck_out_tongue: 

The answer is still yes, however, you just need to provide the correct extended state when you call getQuads on a chisel model.

**Comment by CreativeMD** [comment]
Thanks, once i will find time for it i will try to implement it.
