### ISSUE TITLE
Texture issues

### ISSUE THREAD

**Issue by VermillionX** [Chisel-Team/Chisel#38]
Noticed this earlier: The Rusted Vent Technical block has the inner textures turned sideways. The non-rusted version is fine though.
![2015-10-12_14 23 09](https://cloud.githubusercontent.com/assets/10645298/10420524/6119b9cc-70f2-11e5-8a9b-13bf41546ca0.png)

And although not actually a bug, Large Bricks are missing mortar between the two lower bricks, resulting in a really ugly tiling effect.
![2015-10-05_13 12 24](https://cloud.githubusercontent.com/assets/10645298/10420541/9f63e9be-70f2-11e5-80dc-20eb2d56751b.png)
Really, the edges of both sides of the bricks don't really match anyway.

**Comment by tterrag1098** [comment]
This was half-fixed in a4b0dfd32cc588378de5053ca0201df3e24d23b6 right @Drullkus ?

**Comment by Drullkus** [comment]
Yes

**Comment by TheCricket** [comment]
that commit message...

**Comment by Drullkus** [comment]
10/10

**Comment by Drullkus** [comment]
Whoops, never closed this issue, and bricks got a total redo.
