### ISSUE TITLE
IChisel GUI Crash

### ISSUE THREAD

**Issue by Starwort** [Chisel-Team/Chisel#381]
I have experienced this in many modpacks I have played, including my own pack containing about 10 mods (based on decor so chisel is main)
Happens in HermitPack 1.6.1 (0.0.7.7), Flat Factory (whatever latest is, can't access it now), and a pack including:
Better Builder's Wands
Chisel 0.0.8.12
Chisels & Bits
CodeChicken Core 1.8+
CodeChicken Lib 1.8+
JourneyMap
JEI
NEI 1.8+
WorldEdit
WorldEditCUI

Chisel is a great mod so I would love to see this fixed.
Keep up the good work.

**Comment by Starwort** [comment]
And there are no issues that I can find involving IChisel or Crash.

**Comment by TehNut** [comment]
#311

**Comment by tterrag1098** [comment]
You didn't look very hard then.
