### ISSUE TITLE
[1.10.2] Crash when right-clicking with the iChisel: java.lang.NullPointerException: Ticking screen

### ISSUE THREAD

**Issue by Xiaminou** [Chisel-Team/Chisel#384]
Crash when right-clicking with the iChisel. I looked at the other issues pointing to NEI, but my crash report looks different? so I'm assuming it's something else.

Crash Report: [crash-2017-03-09_17.47.22-client.txt](https://github.com/Chisel-Team/Chisel/files/831699/crash-2017-03-09_17.47.22-client.txt)

**Comment by tterrag1098** [comment]
Does it look different? Looks the same to me.

**Comment by Xiaminou** [comment]
Well it looked different to me, but I don't know anything about all that. I did remove NEI from the modlist and it fixed it, so nevermind.
