### ISSUE TITLE
Crash when getting item tooltip

### ISSUE THREAD

**Issue by opencma** [Chisel-Team/Chisel#385]
Version: Chisel-MC1.11.2-0.0.9.10.jar

When loading an item list (from BetterQuesting) this crash in Chisel's tooltip handler occurred.

[crash-2017-03-09_22.20.02-client.txt](https://github.com/Chisel-Team/Chisel/files/833042/crash-2017-03-09_22.20.02-client.txt)

**Comment by opencma** [comment]
It seems to be an issue on Better Questing's end.

**Comment by tterrag1098** [comment]
Regardless, try the new 1.11 version.
