### ISSUE TITLE
Crashes when i want to join a world (Crash Report down below)[1.11.2]

### ISSUE THREAD

**Issue by BenSchwing1337** [Chisel-Team/Chisel#387]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.10.jar)
  FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  LoadingPlugin (Quark-r1.2-83.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 3/10/17 7:35 PM
XRay version: 48
Description: Unexpected error

java.lang.NoSuchFieldError: field_78286_d
	at net.minecraftforge.client.model.SimpleModelFontRenderer.func_78266_a(SimpleModelFontRenderer.java:68)
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:293)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:562)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:675)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:420)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:399)
	at net.minecraftforge.client.model.FancyMissingModel$BakedModel.func_188616_a(FancyMissingModel.java:146)
	at com.mamiyaotaru.voxelmap.a.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.a.byte(Unknown Source)
	at com.mamiyaotaru.voxelmap.a.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.k.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.t.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.litemod.LiteModVoxelMap.onPostRenderHUD(Unknown Source)
	at com.mumfrey.liteloader.core.event.HandlerList$HUDRenderListener21.onPostRenderHUD(HandlerList$HUDRenderListener21.java:100)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.postRenderHUD(LiteLoaderEventBrokerClient.java:415)
	at com.mumfrey.liteloader.client.ClientProxy.postRenderHUD(ClientProxy.java:114)
	at net.minecraft.client.renderer.EntityRenderer.handler$onPostRenderHUD$zzk000(EntityRenderer.java:4067)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1382)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.SimpleModelFontRenderer.func_78266_a(SimpleModelFontRenderer.java:68)
	at net.minecraft.client.gui.FontRenderer.func_181559_a(FontRenderer.java:293)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:562)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:675)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:420)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:399)
	at net.minecraftforge.client.model.FancyMissingModel$BakedModel.func_188616_a(FancyMissingModel.java:146)
	at com.mamiyaotaru.voxelmap.a.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.a.byte(Unknown Source)
	at com.mamiyaotaru.voxelmap.a.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.k.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.t.do(Unknown Source)
	at com.mamiyaotaru.voxelmap.litemod.LiteModVoxelMap.onPostRenderHUD(Unknown Source)
	at com.mumfrey.liteloader.core.event.HandlerList$HUDRenderListener21.onPostRenderHUD(HandlerList$HUDRenderListener21.java:100)
	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.postRenderHUD(LiteLoaderEventBrokerClient.java:415)
	at com.mumfrey.liteloader.client.ClientProxy.postRenderHUD(ClientProxy.java:114)
	at net.minecraft.client.renderer.EntityRenderer.handler$onPostRenderHUD$zzk000(EntityRenderer.java:4067)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RaveOP'/305, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['RaveOP'/305, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1992408984 bytes (1900 MB) / 3492806656 bytes (3331 MB) up to 6203899904 bytes (5916 MB)
	LiteLoader Brand: 1.11.2-SNAPSHOT-r49900AE-b6-6
	LiteLoader Mods: 3 loaded mod(s)
          - Autofish version 0.7.1
          - VoxelMap version 1.6.21
          - Mouse Tweaks version 2.8
	LaunchWrapper: 32 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: net.minecraftxray.loader.p
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.atomicstryker.findercompass.client.coremod.FCTransformer
          - Transformer: $wrapper.invtweaks.forge.asm.ContainerTransformer
          - Transformer: $wrapper.vazkii.quark.base.asm.ClassTransformer
          - Transformer: $wrapper.pw.prok.realbench.asm.RBTransformer
          - Transformer: $wrapper.brad16840.common.asm.ClassTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: pw.prok.realbench.asm.RBAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: $wrapper.lumien.randomthings.asm.ClassTransformer
          - Transformer: $wrapper.team.chisel.common.asm.ChiselTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6656m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: Minecraft 1.11.2 MCP 9.38 Powered by Forge 13.20.0.2252 Optifine OptiFine_1.11.2_HD_U_B5 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2252.jar) 
	UCHIJAAAA	forge{13.20.0.2252} [Minecraft Forge] (forge-1.11.2-13.20.0.2252.jar) 
	UCHIJAAAA	aroma1997core{${version}} [Aroma1997Core] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCHIJAAAA	uncraftingtable{1.7.1-pre11} [Uncrafting Table] ([1.11.2]UncraftingTable-1.7.1-pre11.jar) 
	UCHIJAAAA	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHIJAAAA	jei{4.2.7.241} [Just Enough Items] (jei_1.11.2-4.2.7.241.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	aroma1997corehelper{1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.11.2-1.2.0.0.b81.jar) 
	UCHIJAAAA	aroma1997sdimension{1.0} [Aroma1997sDimension] (Aroma1997s-Dimensional-World-1.11.2-1.3.0.0.b31.jar) 
	UCHIJAAAA	quark{r1.2-83} [Quark] (Quark-r1.2-83.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.1} [BetterBedrockGen] (BBG-6.0.1.jar) 
	UCHIJAAAA	bdlib{1.13.1.4} [BD Lib] (bdlib-1.13.1.4-mc1.11.2.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.9.10} [Chisel] (Chisel-MC1.11.2-0.0.9.10.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	coffeespawner{1.0.1} [Coffee Spawner] (CoffeeSpawner-1.11.2-1.0.1.jar) 
	UCHIJAAAA	craftingtweaks{7.1.1} [Crafting Tweaks] (CraftingTweaks_1.11-7.1.1.jar) 
	UCHIJAAAA	cropdusting{0.6} [CropDusting] (CropDusting-0.6-[1.11.2].jar) 
	UCHIJAAAA	cxlibrary{1.3.0} [CXLibrary] (cxlibrary-1.11-1.3.0.jar) 
	UCHIJAAAA	cyclicmagic{1.1.4} [Cyclic] (Cyclic-1.11.2-1.1.4.jar) 
	UCHIJAAAA	durabilitycheck{1.1.0} [Durability Check] (durabilitycheck-1.1.jar) 
	UCHIJAAAA	fecm{1.0.0} [Elytra Crafting Recipe Mod] (Elytra Crafting Mod-1.0.0.jar) 
	UCHIJAAAA	fasterladderclimbing{0.1-118} [Faster Ladder Climbing] (FasterLadderClimbing-1.11-0.1-118.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	fastleavedecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.11-1.2.3.jar) 
	UCHIJAAAA	findercompass{1.11.2} [Finder Compass] (FinderCompass-1.11.2.jar) 
	UCHIJAAAA	exp{1.1.3} [Exp Seedling Mod] (GiacomosExperienceSeedling-1.11.2-1.1.3.jar) 
	UCHIJAAAA	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UCHIJAAAA	harvest{1.11-1.2.0-12} [Harvest] (Harvest-1.11-1.2.0-12.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UCHIJAAAA	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
	UCHIJAAAA	justenoughbuttons{1.11.2-1.4.2} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.2.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	keepinginventory{2.2} [Keeping Inventory] (KeepingInventory-1.11.2-2.2.jar) 
	UCHIJAAAA	kleeslabs{4.3.2} [KleeSlabs] (KleeSlabs_1.11.2-4.3.2.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11-1.1.2.39-universal.jar) 
	UCHIJAAAA	metamorph{1.1.1} [Metamorph] (metamorph-1.1.1-1.11.2.jar) 
	UCHIJAAAA	minions{2.0.0} [Minions] (Minions-1.11.2.jar) 
	UCHIJAAAA	morefurnaces{1.9.4} [More Furnaces] (MoreFurnaces-1.11-1.9.4.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.11).jar) 
	UCHIJAAAA	harvestcraft{1.11.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2f.jar) 
	UCHIJAAAA	prefab{1.2.0.5} [Prefab] (prefab-1.2.0.5.jar) 
	UCHIJAAAA	randomthings{3.8} [Random Things] (RandomThings-MC1.11.2-3.8.jar) 
	UCHIJAAAA	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UCHIJAAAA	roguelike{1.6.3} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.3.jar) 
	UCHIJAAAA	schematica{1.7.8.156} [Schematica] (Schematica-1.11-1.7.8.156-universal.jar) 
	UCHIJAAAA	shulkerbox{1.1.0} [Shulkerbox] (ShulkerBox 1.1.0.jar) 
	UCHIJAAAA	simplegrinder{3.060.R1112} [Simple Grinder] (SimpleGrinder-3.095.R1112.jar) 
	UCHIJAAAA	simpleleather{1.11.2-1.0} [Simple Leather] (simpleleather-1.11.2-1.0.jar) 
	UCHIJAAAA	slimer{1.0} [Slime Chunker] (slimer-1.2.jar) 
	UCHIJAAAA	soulshardstow{1.11-2.6.6-47} [Soul Shards - The Old Ways] (SoulShards-TOW-1.11-2.6.6-47.jar) 
	UCHIJAAAA	sparkshammers{1.11.2-1.6.1} [Spark's Hammers] (sparkshammers-1.11.2-1.6.1.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCHIJAAAA	thutcore{4.3.2} [ThutCore] (thutcore-4.3.2.jar) 
	UCHIJAAAA	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHIJAAAA	toolupgrades{1.2.1} [§9Tool-Upgrades Mod] (Tool Upgrades 1.11.2 (v.1.2.1).jar) 
	UCHIJAAAA	ts2k16{1.1.4} [Twerk-Sim 2K16] (TS2K16-1.1.4.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	villagerinventory{1.0.1} [Villager Inventory Viewer] (VillagerInventory-1.11-1.0.1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	xpbook{0.0.2-beta} [XPBook] (xpbook-1.11.2-0.0.2-beta.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.10.jar)
  team.chisel.common.asm.ChiselTransformer
FCFMLCorePlugin (FinderCompass-1.11.2.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.jar)
  lumien.randomthings.asm.ClassTransformer
RBLoadingPlugin (RealBench-1.11.2-1.3.2.jar)
  pw.prok.realbench.asm.RBTransformer
CoreMod (Aroma1997Core-1.11.2-1.2.0.0.b81.jar)
  
LoadingPlugin (Quark-r1.2-83.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
	List of loaded APIs: 
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.9.10.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.9.10.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* compatlayer (0.2.2) from compatlayer-1.11.2-0.2.2.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.11-7.1.1.jar
		* Guide-API|API (1.11-2.1.0-50) from Guide-API-1.11-2.1.0-50.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.7.241.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.11.2.jar
		* SchematicaAPI (1.1) from Schematica-1.11-1.7.8.156-universal.jar
		* SchematicaAPI|Events (1.1) from Schematica-1.11-1.7.8.156-universal.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* thut|API (1.0.0) from thutcore-4.3.2.jar
		* veinminerApi (0.3) from VeinMiner-1.11-0.35.3.605+dad98e1.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
	Launched Version: forge-13.20.0.2252
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

**Comment by tterrag1098** [comment]
What exactly made you think this was caused by Chisel? The log is full of Voxelmap in the stack.

**Comment by BenSchwing1337** [comment]
befor i put the chisel mod in the pack it worked perfectly

**Comment by tterrag1098** [comment]
That doesn't mean anything, report this to Voxelmap, the crash is theirs.

**Comment by BenSchwing1337** [comment]
I fixed the problem

**Comment by BenSchwing1337** [comment]
I just had to update the optifine version
