### ISSUE TITLE
Laboratory arrow block bug

### ISSUE THREAD

**Issue by Xandoria** [Chisel-Team/Chisel#388]
2 blocks should be switched:
Laboratory Block - Right-faced Arrows  is pointing left
Laboratory Block - Left-faced Arrows is pointing right

**Comment by tterrag1098** [comment]
Just to be clear, this fix is "invisible" since I've swapped the order of the variants while also renaming them. So all existing builds should be unaffected. To the end user, it will just appear as if the tooltips have changed.
