### ISSUE TITLE
Animated fans?

### ISSUE THREAD

**Issue by Xandoria** [Chisel-Team/Chisel#389]
Hello,
Are the "Fans (Fast)" and "Fan (Malfunctioning)" blocks supposed to be animated?
All fans look static except for the "Massive Fan".

**Comment by Drullkus** [comment]
Those should animate. Do you have optifine?

**Comment by Xandoria** [comment]
Yes I do and a shader too (SEUS).

**Comment by Drullkus** [comment]
Try removing optifine. Could be optifine choking on interpolation

**Comment by Xandoria** [comment]
No change when I remove Optifine, the fans are still static.

**Comment by Drullkus** [comment]
Could you please try isolating this issue on your end? Working perfectly on my end.

**Comment by Xandoria** [comment]
I really don't know what to say. I have removed all mods except for Chisel-MC1.11.2-0.0.9.10.jar
I have tried using the lastest forge version 1.11.2-13.20.0.2260 this time.
I have created a new creative flat world and the fans are still not animated except for the enormous one.

**Comment by Xandoria** [comment]
The fans are working in the latest Chisel-MC1.11.2-0.0.9.13 release, thanks!

**Comment by tterrag1098** [comment]
Good enough for me!
