### ISSUE TITLE
Missing entries in en_us.lang file

### ISSUE THREAD

**Issue by Xandoria** [Chisel-Team/Chisel#390]
Hello,
I am translating Chisel into French and I have noticed some small problems with the en_us.lang file.

The following descriptions in en_us.lang do not seem to be effective in the game.
Nothing is displayed.
Could you please check them?

tile.chisel.cobblestoneextra.name=Cobblestone
tile.chisel.cobblestoneextra.bricks-solid.desc.1=Bricks
tile.chisel.cobblestoneextra.bricks-small.desc.1=Small Bricks
tile.chisel.cobblestoneextra.circular.desc.1=Circular
tile.chisel.cobblestoneextra.tiles-medium.desc.1=Tiles
tile.chisel.cobblestoneextra.pillar.desc.1=Pillar
tile.chisel.cobblestoneextra.twisted.desc.1=Twisted
tile.chisel.cobblestoneextra.prism.desc.1=Prism
tile.chisel.cobblestoneextra.raw.desc.1=Raw
tile.chisel.cobblestoneextra.emboss.desc.1=Embossed
tile.chisel.cobblestoneextra.indent.desc.1=Indented
tile.chisel.cobblestoneextra.marker.desc.1=Marker
tile.chisel.cobblestoneextra.sunken.desc.1=Sunken
tile.chisel.cobblestoneextra.poison.desc.1=Poison

tile.chisel.limestoneextra.name=Limestone
tile.chisel.limestoneextra.bricks-solid.desc.1=Bricks
tile.chisel.limestoneextra.bricks-small.desc.1=Small Bricks
tile.chisel.limestoneextra.circular.desc.1=Circular
tile.chisel.limestoneextra.tiles-medium.desc.1=Tiles
tile.chisel.limestoneextra.pillar.desc.1=Pillar
tile.chisel.limestoneextra.twisted.desc.1=Twisted
tile.chisel.limestoneextra.prism.desc.1=Prism
tile.chisel.limestoneextra.raw.desc.1=Raw
tile.chisel.limestoneextra.emboss.desc.1=Embossed
tile.chisel.limestoneextra.indent.desc.1=Indented
tile.chisel.limestoneextra.marker.desc.1=Marker
tile.chisel.limestoneextra.sunken.desc.1=Sunken
tile.chisel.limestoneextra.poison.desc.1=Poison

Missing description for:
- Ender Offset Wand
- all Ice pillars
- 1 Nether Brick
- 1 Chiseled Stone
- Stained glass

No entry for the translation of the Companion cube text "<Sneak to show more>"

Void description:
tile.chisel.valentines.1.desc.1=

**Comment by Drullkus** [comment]
Fixed in b0d70d8 and da1ed60
