### ISSUE TITLE
No designs?

### ISSUE THREAD

**Issue by Blue-Skyfeather** [Chisel-Team/Chisel#394]
I've generally had no problems with this before, but upon loading the 1.8.9 release of the chisel mod with Chisel&bits, Biomes o' plenty, and Thaumcraft for a 1.8.9 server, I can find all the available textures in the creative menu, but cannot apply them with the chisel.

Upon using the chisel with any block no designs show up inside it's GUI nor are any applicable.
Is it possible Thaumcraft and chisel are incompatible?

**Comment by tterrag1098** [comment]
1.8.9 is not supported
