### ISSUE TITLE
Texture issues in every version.

### ISSUE THREAD

**Issue by joel1842** [Chisel-Team/Chisel#395]
I have tried every version of Chisled and I am getting texture issues in all of them... There are a bunch of missing textures, only from default not the mod. Can someone help? http://imgur.com/a/vNK9V

**Comment by joel1842** [comment]
In response to my own comment, I have found that using the default texture pack on top of the mod will fix the issue. Download it here; http://www.mediafire.com/file/j1hsfojrtkabd11/1.11.2+Default+Resource+Pack.rar

**Comment by Drullkus** [comment]
Uh... do you have optifine? Are you on Mac OS? Gimme your launch log. The whole thing.

**Comment by joel1842** [comment]
I do not have options running, but I do have Mac OS for the next week or so
until I get my new PC.

**Comment by Drullkus** [comment]
What model of MacOS? Older models of MacOS explains it though. There's a bit of a driver issue. Press F3 + T in-game to force-reload all textures (texture packs force this too).
