### ISSUE TITLE
[1.11.2] Crash while mining chiseled blocks

### ISSUE THREAD

**Issue by Silvrus** [Chisel-Team/Chisel#396]
Chisel 1.11.2.0.0.9.11

Randomly crashing while mining chiseled blocks, gist [here](https://gist.github.com/Silvrus/b67a74fafecb2f3155681ec594f383d7)

**Comment by SDUBZ** [comment]
also caught here: https://openeye.openmods.info/crashes/5453b88b123414cc956f8e1e9059c383
chisel: Chisel-MC1.11.2-0.0.9.11
forge:1.11.2-2260

**Comment by tterrag1098** [comment]
Does this issue only happen in 1.11? Does it happen with only Chisel installed?

**Comment by SDUBZ** [comment]
i will check later @tterrag1098 i just noticed this on my openeye

**Comment by SDUBZ** [comment]
oh if you need to check for mod incompat heres the mods used as in the description https://minecraft.curseforge.com/projects/sdubzskycraft-2

**Comment by SDUBZ** [comment]
also havent got it to crash yet by itself

**Comment by SDUBZ** [comment]
found it where one of my testers crashed from mining chisel blocks https://clips.twitch.tv/ResourcefulAgreeablePancakeDoubleRainbow

also noticed it takes a whole minute to load world after the crash occurs
https://clips.twitch.tv/DiligentShortGorillaMoreCowbell

**Comment by SDUBZ** [comment]
i actually clipped it when i seen the block change https://clips.twitch.tv/SmellyIncredulousMilkAsianGlow

**Comment by tterrag1098** [comment]
I don't see how that could be caused by Chisel. It looks like some other mod is messing with the item entity, causing it to break.

**Comment by SDUBZ** [comment]
yeah its gonna take alot of debugging i think to figure out whats affecting it

**Comment by Drullkus** [comment]
You can start this by isolating the mods that are causing this interaction.

**Comment by SDUBZ** [comment]
okay isolating the mods that are similar to what crashed with my pack and silvrus was playing

**Comment by SDUBZ** [comment]
okay broke over 4 stacks with no crash O_O, what if it isnt whats affecting item entity but whats reading ?

**Comment by SDUBZ** [comment]
okay no crash after trying different presets and with/out hwyla installed too

**Comment by SDUBZ** [comment]
im wondering if this only happening when 4 gbs is allocated hmmm

**Comment by SDUBZ** [comment]
i can not replicate this issue myself at all and the same person playing my pack doesnt have it happen while not streaming might software interference or poor pc performance

**Comment by Silvrus** [comment]
Just saw all the replies. I'll check mod by mod, but it will be this weekend before I can devote the time for it.

**Comment by Silvrus** [comment]
Didn't get a chance to test mod by mod, but since the last update I've not had a crash. I think this is resolved, thanks for all you do!
