### ISSUE TITLE
[1.10.2][Chisel 0.0.8.13]Iron Block Missing underside Texture

### ISSUE THREAD

**Issue by BuckTheWeasel** [Chisel-Team/Chisel#397]
I found a missing texture on the underside of the Ironblock 

![2017-03-25_21 22 55](https://cloud.githubusercontent.com/assets/10898935/24325848/376c2464-11a2-11e7-808e-a3eaa83b9607.png)

**Comment by tterrag1098** [comment]
Which variant is that? Could you post your startup log?

**Comment by BuckTheWeasel** [comment]
Block of Iron - Vents
I hosted my Startup log on onedrive.
https://1drv.ms/u/s!An7MaZS2F649oGcfZJSh0fT2eTPs

**Comment by Drullkus** [comment]
I vaguely remember this problem and procrastinating on fixing it. Will handle when Laptop finishes fixing a problem.

**Comment by Drullkus** [comment]
Fixed in 73db6a1
