### ISSUE TITLE
Suggestion for woolen clay textures

### ISSUE THREAD

**Issue by Stormalisk** [Chisel-Team/Chisel#4]
So after this whole big cast of drama blowing over, I've been wanting to show some textures I have made for the woollen clay. I like the idea of colored builds and really like to see the block get some love in the form of these variants:

![allwoolclay](https://cloud.githubusercontent.com/assets/14106817/9654705/6b807e12-51fa-11e5-8425-596533606b5b.png)

-Left/Right columns:
--1st is original woolenclay
--2nd is bigbrick
--3rd is littlebrick
--4th is centered
--5th is siding
--6th is shingles
-Up/Down columns:
--1st black
--2nd blue
--3rd brown
--4th cyan
--5th grey
--6th green
--7th light blue
--8th light grey
--9th lime
--10th magenta
--11th orange
--12th pink
--13th purple
--14th red
--15th white
--16th yellow
--17th "sunny"*
- I detest the dijon mustard yellow that minecraft has, so I made a brighter one known as "sunny".

Sunny could be an option for the yellow woolenclay when in the chisel
grid, or it could be crafted using 8 yellow woolenclays and one
bonemeal.

**Comment by tterrag1098** [comment]
This would fit well with the plans I have for a "Paintbrush" tool. I find that using a chisel to color things is a bit silly :D.

**Comment by Stormalisk** [comment]
Guessing your talking about the sunny variant, yea i'd love to see an actual yellow (and yea chiselling the color is kinda silly but just throwing it out there).

Thanks for the label, not sure if I'm able to add it myself. (new to this site)

**Comment by Drullkus** [comment]
I'm the artist and I approve of these images.﻿

**Comment by tterrag1098** [comment]
@Drullkus the only problem is the amount of IDs it would use. We'd need an ID for each variation. And one more if we use the "sunny" variant.

**Comment by TheCricket** [comment]
or add it to existing woolen clay

**Comment by TheCricket** [comment]
then you only need 1 new id

**Comment by tterrag1098** [comment]
@TheCricket huh? There's 16 colors \* 6 variations. So we either need 1 ID per color or one ID per variation.

**Comment by TheCricket** [comment]
we already have woolen clay
edit: nvm I am dumb

**Comment by Stormalisk** [comment]
@Cricket, ha-ha its alright man.

@tterrag, I thought they could be added as damage values to the woollenclay. However, I am assuming it won't be that easy?

**Comment by tterrag1098** [comment]
The woolen clay already uses all 16 for the colors...

**Comment by Stormalisk** [comment]
Right silly me, yea that answers that. I suppose each variant having their own Id and the colors be damage values would be the best option?

**Comment by tterrag1098** [comment]
The only option the way I see it. Question is whether we want to do it or not.

**Comment by Stormalisk** [comment]
Totally up to you guys, I'm really giant fan of this mod ( pun? Heh ) and I'd be ecstatic to see my contribution if you're willing. 

Also, if you're worried about ids casing performance issues I've seen geostrata from Reika add roughly 30 extra ids (ore support for his blocks) and not cause any issue for my toaster of a computer.

**Comment by TehNut** [comment]
It's not about performance issues. It's about how there's a very limited number of ID's.

**Comment by Stormalisk** [comment]
@TehNut was trying to help with moral but yea.

How much could Chisel theoretically put in?

**Comment by TheCricket** [comment]
Assuming its in a modpack or nah?

**Comment by tterrag1098** [comment]
There are 4096 block IDs period. This is for all mods + vanilla to share.

**Comment by TheCricket** [comment]
So technically we could have over 3000*16 blocks if you have a chisel oriented pack

**Comment by tterrag1098** [comment]
Could. But won't.

---

Let's keep this conversation focused on the issue, btw

**Comment by TheCricket** [comment]
Hence technically :P

**Comment by Stormalisk** [comment]
I've also seen mods have damage values on ids much higher than 16, all of the variant could be damage values if its a concern. Though it would be abit messy? I'm not too sure.

**Comment by Stormalisk** [comment]
Now that I think about it, that may only apply to items.
