### ISSUE TITLE
1.10.2 Chisel-Dark Utils Sneaky Blocks Crash on break

### ISSUE THREAD

**Issue by braingkk** [Chisel-Team/Chisel#401]
When breaking Dark Utils sneaky blocks skinned with chisel blocks, it triggers a ctd, and the block does not break
https://pastebin.com/1mtm5j9b 
when breaking via machines [i.e. actually additions auto-breaker] there is no ctd.
checked out dark utils github and it seems he believes it to be chisels fault
https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/55

possibly related mods:
Chisel-MC1.10.2-0.0.8.12
DarkUtilities-1.10.2-1.1.7.111
FTB Beyond 1.2.1 modpack

**Comment by tterrag1098** [comment]
I've posted information on how to solve the problem at the original issue.

**Comment by braingkk** [comment]
tyvm
