### ISSUE TITLE
[Request] [1.9+] Render water behind glass the same as Vanilla glass

### ISSUE THREAD

**Issue by JonoColwell** [Chisel-Team/Chisel#402]
Chisel glass currently renders a flowing water block behind the glass which makes underwater windows difficult to implement, please allow these to render water the same as vanilla glass if at all possible.

http://puu.sh/v0X6H/b7476b5dd7.jpg

**Comment by tterrag1098** [comment]
Impossible to fix, see #324

**Comment by JonoColwell** [comment]
1. That was fast
2. Bugger
