### ISSUE TITLE
Crash report (on start up)

### ISSUE THREAD

**Issue by ml0130** [Chisel-Team/Chisel#407]
[crash-2017-04-13_12.22.40-client.txt](https://github.com/Chisel-Team/Chisel/files/920653/crash-2017-04-13_12.22.40-client.txt)
theirs the full report. Here is what was in the crash window 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisel (chisel)

The current build i'm using is DEV-MC1.10.2-0.0.10.19

**Comment by tterrag1098** [comment]
Duplicate of #406
