### ISSUE TITLE
Crash :/

### ISSUE THREAD

**Issue by Ar97x** [Chisel-Team/Chisel#409]
Crash report: https://www.dropbox.com/s/xu6zn3ulfescvip/crash-2017-04-17_23.43.30-client.txt?dl=0

**Comment by TehNut** [comment]
#406

**Comment by Drullkus** [comment]
Thanks for reporting it. However since this issue is a duplicate of #406, I'll close it here. Thanks for reporting! ^^

**Comment by Ar97x** [comment]
Thank you for the attention, I'll get to it. Glad to contribute.

**Comment by Drullkus** [comment]
It's fixed in latest that's uploaded to CF just not long ago now, too

👉 https://minecraft.curseforge.com/projects/chisel/files/2408716

**Comment by Ar97x** [comment]
Oh, good to know, I'll go directly onto it then.
