### ISSUE TITLE
1.10 Startup Crash

### ISSUE THREAD

**Issue by Amaxter** [Chisel-Team/Chisel#410]
https://hastebin.com/oxolecusug.sql

(removing FoamFix does not solve)

**Comment by TehNut** [comment]
#406

**Comment by Drullkus** [comment]
Thanks for reporting it. However since this issue is a duplicate of #406, I'll close it here. Thanks for reporting! ^^

**Comment by Amaxter** [comment]
For myself: http://i2.kym-cdn.com/photos/images/facebook/000/325/934/060.png
