### ISSUE TITLE
1.11.2(Chisel-MC1.11.2-0.0.9.13) things that have broken textures

### ISSUE THREAD

**Issue by SDUBZ** [Chisel-Team/Chisel#413]
making this post so you and i can track all things that are not working as intended
all glass textures are invisible
![2017-04-21_18 10 32](https://cloud.githubusercontent.com/assets/14084377/25268941/ff6656bc-26bd-11e7-9d21-2c8f2bb6d59e.png)

**Comment by SDUBZ** [comment]
![2017-04-21_18 19 49](https://cloud.githubusercontent.com/assets/14084377/25269242/250c7044-26bf-11e7-9b80-6af993ba1600.png)
a closer look

**Comment by SDUBZ** [comment]
![2017-04-21_18 21 16](https://cloud.githubusercontent.com/assets/14084377/25269294/59ba3358-26bf-11e7-8547-4e0965fb684d.png)
ctm not working ?

**Comment by SDUBZ** [comment]
![2017-04-21_18 29 07](https://cloud.githubusercontent.com/assets/14084377/25269547/7b48eb30-26c0-11e7-8422-d71abf9e96fb.png)
all the ctm blocks

**Comment by SDUBZ** [comment]
voidstone blocks:
![2017-04-21_18 39 02](https://cloud.githubusercontent.com/assets/14084377/25269908/fbd1c2c6-26c1-11e7-83d7-6b26ff4c67c1.png)
![2017-04-21_18 39 04](https://cloud.githubusercontent.com/assets/14084377/25269910/fe2afb14-26c1-11e7-8a60-b47bcf2cf3be.png)
![2017-04-21_18 39 05](https://cloud.githubusercontent.com/assets/14084377/25269915/019e4c38-26c2-11e7-995f-2d250d42f77d.png)
![2017-04-21_18 39 08](https://cloud.githubusercontent.com/assets/14084377/25269926/070c4dbe-26c2-11e7-8033-02c1ba4c7a5a.png)
![2017-04-21_18 39 09](https://cloud.githubusercontent.com/assets/14084377/25269929/0919e396-26c2-11e7-8d21-f4fd12a27a67.png)
![2017-04-21_18 39 12](https://cloud.githubusercontent.com/assets/14084377/25269933/0b7b2de8-26c2-11e7-807f-6d0f4b663a2e.png)
![2017-04-21_18 39 14](https://cloud.githubusercontent.com/assets/14084377/25269940/0fe96034-26c2-11e7-8127-84c471d900c2.png)
![2017-04-21_18 39 26](https://cloud.githubusercontent.com/assets/14084377/25269942/131d3758-26c2-11e7-803d-2f711d959002.png)

**Comment by tterrag1098** [comment]
All of these blocks are working fine for me. Could you please post your startup log.

**Comment by SDUBZ** [comment]
sure can :D here you go 
[fml-client-latest.log (2).txt](https://github.com/Chisel-Team/Chisel/files/946499/fml-client-latest.log.2.txt)
[latest.log.txt](https://github.com/Chisel-Team/Chisel/files/946500/latest.log.txt)

@tterrag1098

**Comment by SDUBZ** [comment]
it would be nice to work out whats affecting chisel in that case

**Comment by SDUBZ** [comment]
@tterrag1098 its custom stuff 3 affecting chisel \o/ currently testing with CustomStuff3-1.11.2-0.10.20

**Comment by SDUBZ** [comment]
![2017-04-21_20 34 52](https://cloud.githubusercontent.com/assets/14084377/25274131/0e384be6-26d2-11e7-82f5-b2ffa3526051.png)
with custom stuff disabled

**Comment by tterrag1098** [comment]
Report it to them. Their coremod is insane, and wiping out all of `Block`'s methods, which completely destroys our hooks.
