### ISSUE TITLE
(crash issue) iChisel causing client crash. (custom pack)

### ISSUE THREAD

**Issue by iDarper** [Chisel-Team/Chisel#416]
(I mentioned this to tterrag earlier on Reddit)

Basically, i have a custom server pack that we built for our community. When holding the ichisel in hand, right clicking the tool crashes the client back to the desktop. Both ichisel and NEI have been updated in the last week and a half, and still causes a crash. Here is the CurseForge project page, so you can see the current mods list/changelogs, maybe it'll help. 

https://mods.curse.com/modpacks/minecraft/244211-wirenut

This issue is not isolated, as it happens everytime anyone tries using it.

Thanks for your time.

**Comment by tterrag1098** [comment]
Please post your crashlog...

**Comment by iDarper** [comment]
requesting a close of the issue. apparently the other pack maintainer updated a couple things since, and it's working now. thanks for your time, and thanks for the awesome mod
