### ISSUE TITLE
Concrete lets beacons through

### ISSUE THREAD

**Issue by yrsegal** [Chisel-Team/Chisel#419]
i don't know why it be but it do

**Comment by yrsegal** [comment]
It's not just concrete, oh no
![2017-04-25_20 41 44](https://cloud.githubusercontent.com/assets/6596492/25413348/bb411eda-29f7-11e7-8921-0cfea0b0444c.png)

**Comment by Drullkus** [comment]
Uh @tterrag1098 did we even test it o_O

@yrsegal incase we can't reproduce, could you try isolating it in the pack? Thanks!

**Comment by yrsegal** [comment]
It was BetterFps, bleh
