### ISSUE TITLE
Crash upon switching worlds

### ISSUE THREAD

**Issue by Alan19** [Chisel-Team/Chisel#420]
When I try switching from one single player world to another while having ModTweaker scripts that modifies chisel groups, the world eventually stops loading. I reported it to Minetweaker but Jared told me to report it here.

Scripts:
https://github.com/belathus/Wanderlust-Renewed/tree/master/scripts

Minetweaker Logs and Console Log:
https://gist.github.com/Alan19/cd6cc910bc39d064a98e1c42200a7ffe

Link to issue on CraftTweaker:
https://github.com/jaredlll08/CraftTweaker/issues/198

Affected Versions (Do not use "latest"):

Minecraft:1.10.2
Forge:12.18.3.2254
Crafttweaker:3.0.24

**Comment by tterrag1098** [comment]
Fixed via #443
