### ISSUE TITLE
Chisel Causing TCon Glitch

### ISSUE THREAD

**Issue by claws61821** [Chisel-Team/Chisel#421]
MC 1.10.2
Forge 12.18.3.2254
Chisel 0.0.10.22
TCon 2.6.3

When using the Tinkers Construct smeltery to pour blocks into the TCon Casting Basin, it outputs as Chisel blocks where available. This causes the Basin to render graphically and report to WAILA as empty erroneously. Right-clicking the Basin still gives the player the block within.

Observed with Copper blocks. Repeatable.

May be duplicate of #380

**Comment by tterrag1098** [comment]
Screenshots?

**Comment by claws61821** [comment]
Sorry about that. Here you are. [https://www.dropbox.com/s/1x0f36j0nzl84m3/ChiselTexturesTConScreenshots.7z?dl=0](url)

**Comment by tterrag1098** [comment]
Bizzare. I can't see how we could cause that. Have you reported it to Tcon?

**Comment by KnightMiner** [comment]
Tinkers Construct uses the first block found in the oredictionary for a lot of our recipes.

As for the rendering, items displayed on top are statically baked into the main model, boni is a little more knowledgeable on the topic if you are to make a report over on our tracker linking back here.

**Comment by TheQuadShot** [comment]
It looks like this is a Chisel issue and it has something to do with rendering the block in the basin. Here's a few vids of what I mean. 
https://www.youtube.com/watch?v=u5zIz3Ob4bI
https://www.youtube.com/watch?v=Toelw_DR47Y

**Comment by austragus** [comment]
Is this issue still being looked at?

**Comment by tterrag1098** [comment]
As said in the referenced Tcon issue, there is not much we can do. Tcon needs to not base its output on ore dict order.

**Comment by KnightMiner** [comment]
I feel like the output is not really the main issue here, Chisel is a fine output as the blocks are compatible. The real issue is the items not rendering in the basins which could probably use more looking into, as assuming Chisel uses  baked models there is no reason they should not display there.

**Comment by tterrag1098** [comment]
I'll leave this open since that is in fact a valid issue, but it's definitely on the Tcon side. Plenty of other mods render chisel blocks as models.

**Comment by KnightMiner** [comment]
Well, most other mods use TESRs, Tinkers does it statically in baked models. I'll try and look into what causes the issue, but my knowledge of both rendering systems is a bit limited.

**Comment by themechman** [comment]
I can confirm this is still happening on 2.6.5 of Tcon.

**Comment by Drullkus** [comment]
@KnightMiner Has this been fixed?

**Comment by KnightMiner** [comment]
Yep, has been fixed for awhile

**Comment by themechman** [comment]
Thanks!
