### ISSUE TITLE
Brick-Topped Dirt loses texture.

### ISSUE THREAD

**Issue by TheQuadShot** [Chisel-Team/Chisel#426]
http://imgur.com/xdskG5p

Minecraft: 1.10.2
Forge: 12.18.3.2281
Chisle: Chisel=MC1.10.2-0.0.10.22

**Comment by Drullkus** [comment]
It's because the one you're using is a pillar type. There's a non-pillar type variation.

**Comment by TheQuadShot** [comment]
Ok, then I don't understand this, also is there a way to put that in the tool tip/waila?

http://imgur.com/eKUyXs9

**Comment by tterrag1098** [comment]
Pillars go horizontally too. If you want the top texture to display on a floor, make it 2 deep.

**Comment by TheQuadShot** [comment]
I'm really sorry if I'm missing something here. If I make a pillar I expect texture to be on all of the blocks in/of the pillar, not just the top one.
