### ISSUE TITLE
Futura Block missing texture

### ISSUE THREAD

**Issue by TheQuadShot** [Chisel-Team/Chisel#427]
The Futura Block (Purple ME Controller) is missing texture.
Minecraft: 1.10.2
Forge: 12.18.3.2281
Chisle: Chisel=MC1.10.2-0.0.10.22

**Comment by tterrag1098** [comment]
Any screenshots? logs?

**Comment by Drullkus** [comment]
Yeah it's a weird heisenbug. I'm not even sure how it's breaking for some people and others not. Works fine on my end.

**Comment by TheQuadShot** [comment]
Here's a screenshot
http://imgur.com/GZf2LEE

**Comment by tterrag1098** [comment]
Please post your latest log file

**Comment by TheQuadShot** [comment]
Sure thing, here ya go
https://pastebin.com/4riJBPpZ

**Comment by Fluoxi** [comment]
Well, anything?

**Comment by Drullkus** [comment]
I think we fixed this in the latest build. Try the latest build. Poke this issue if it still is broken

**Comment by SanAndreaP** [comment]
So... I have to chime in, as I have the exact same issue on 1.10.2 with the latest Chisel release (0.1.0.38).
The problem, for some reason, is the mixed-case of the filename for ```assets/chisel/models/block/futura/controllerPurple.cf```.
If I rename it to ```controllerpurple.cf``` the texture loads just fine.

Here's a screenshot of the block before the change:
https://i.imgur.com/cN1Uq8g.jpg
and here after:
https://i.imgur.com/UATb5kP.jpg

Also I tried it without any texture pack, here's the screenshot with the unmodified Chisel:
https://i.imgur.com/ofbvAX0.jpg

Here's the log w/o texturepacks and the unmodified version:
https://gist.githubusercontent.com/SanAndreasP/fa78af3467aa587f0f6384e9c615036e/raw/f32834f13f17269f6b2f029d624f598f04ada002/latest.log
