### ISSUE TITLE
Ludicrous Speeds on concrete

### ISSUE THREAD

**Issue by Ristellise** [Chisel-Team/Chisel#431]
[Link to a video about it](https://www.youtube.com/watch?v=m5bxdPRdv_Q&feature=youtu.be)
Forward button was not pressed. It was pressed only at the start.
Chisel Version : Chisel-MC1.10.2-0.0.10.22

**Comment by Drullkus** [comment]
Lol whoops. I'll add a water check.

**Comment by brisingraerowing** [comment]
Lol. That's crazy.

**Comment by Ristellise** [comment]
some one please fix this XD

**Comment by brisingraerowing** [comment]
This happens without water as well. It's not as fast, though.
