### ISSUE TITLE
[Question] What resolution are you going for?

### ISSUE THREAD

**Issue by MarcusElg** [Chisel-Team/Chisel#432]
Do you have a long-term plan to have all textures in the same resolution or will you keep adding some 16x textures and some 32x? I would be intresting to know as it seems a little weird to me that different blocks have different resolutions.

Also thanks for making such a great mod!

**Comment by tterrag1098** [comment]
Almost every single texture in Chisel is 16x. A few exceptions were made for certain animations.

**Comment by MarcusElg** [comment]
Thanks for your reply. It seems like many 32x textures have been fixed, or maybe I just remember uncorrectly. Hmm.. Except the fans (I can understand that they are 32x) the antiblocks are the only 32x textures left that I can find. Is there a reason to this? http://imgur.com/a/C4eEc

**Comment by tterrag1098** [comment]
It looks cool? 😛

**Comment by Drullkus** [comment]
I use x16 or x32 wherever it looks best. I usually stick with x16 but if it looks better with x32 then I will go for it. Antiblocks are one of those that look better with x32.
