### ISSUE TITLE
crash when playing server when trying to profile something odd going on in users base(1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [Chisel-Team/Chisel#434]
maybe something or not just thought id let you guys know of the crash
chisel:Chisel-MC1.11.2-0.0.10.14
forge:1.11.2-2296
crash report:
[crash-2017-05-15_16.17.19-client.txt](https://github.com/Chisel-Team/Chisel/files/1000225/crash-2017-05-15_16.17.19-client.txt)

**Comment by tterrag1098** [comment]
Fixed in CTM 0.2.1
