### ISSUE TITLE
chisel blocks in Tinker Smelt

### ISSUE THREAD

**Issue by jprocket45** [Chisel-Team/Chisel#437]
this was brought up but this is highly annoying though im not blaming anyone just seems its pointing to the chisel mod can this be looked into more thanks!  https://github.com/SlimeKnights/TinkersConstruct/issues/2884   they are saying chisel needs to change there loading I am unsure but trying to get to the bottom of it, thank you for your time!

**Comment by tterrag1098** [comment]
There's nothing to be done here, I'm not adding an exception to the load order for every mod out there that tries to pull results from the oredict. The solution is, as described by KnightMiner in your linked issue, to have Tcon list "preferred" results.
