### ISSUE TITLE
Client crash while Chisel is installed

### ISSUE THREAD

**Issue by iamceph** [Chisel-Team/Chisel#438]
Hi there,

I am unable to start Minecraft 1.10.2 with Chisel installed.

Mods are: 
![image](https://cloud.githubusercontent.com/assets/4377405/26312338/8ddd9c5a-3f07-11e7-87b1-ebe1b09d401a.png)

Forge version is: 1.10.2 - 12.18.3.2297
Chisel version: Chisel-MC1.10.2-0.0.10.22
Log: https://hastebin.com/sevahunute.scala

Thanks for any help

**Comment by tterrag1098** [comment]
You have an old version of chisel installed alongside the new CTM, unfortunately that doesn't work. There will be a release of chisel to accomodate the changes soon.
