### ISSUE TITLE
Wot happen

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#44]
http://pastebin.com/DnHZJGip @tterrag1098 fix pls :pray:

**Comment by Drullkus** [comment]
Chatlog http://pastebin.com/RDtaXSGA from #MinecraftForge

**Comment by Drullkus** [comment]
@tterrag1098 Still not fixed, please test before you actually declare as fixed D:

Different crash > http://pastebin.com/aKfCt5j3

**Comment by tterrag1098** [comment]
#blamedrullkus
