### ISSUE TITLE
[1.10.2] Server crash on startup

### ISSUE THREAD

**Issue by GirafiStudios** [Chisel-Team/Chisel#440]
Chisel crashes on server startup, due to running client side version of I18n.
I suspect that my changes to the Chisel config might be what causes the code to be called (Haven't look too much into it), so I have attached that too.

Crash report: https://gist.github.com/GirafiStudios/cf4ac24cea9f847716b5bd2cb9542b13
Chisel config: https://gist.github.com/GirafiStudios/39dfa3ca65d3ec0a517e1abdeb0141bc#file-chisel-cfg-L48-L64
Forge version: 12.18.3.2297
Chisel version: 0.0.10.22

**Comment by tterrag1098** [comment]
Yeah, enabling `B:tooltipsUseBlockDescriptions` on the server should fix this temporarily. I will push a fix soon, currently a lot of code is being changed due to the new mod.

**Comment by tterrag1098** [comment]
Was fixed via 4e590fc53e0e2beef6fbc91552c4c3dad5224907
