### ISSUE TITLE
[1.11.2] Crash on Single Player World when breaking blocks

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#444]
MC: 1.11.2
Forge: 13.20.0.2314
Chisel: 0.0.10.14

Game crashes when breaking blocks (seems to be random).
[Crashlog](https://pastebin.com/fFxRqdbE)

**Comment by tterrag1098** [comment]
> `    at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:273)`

CodeChickenLib is on the stack, could you reproduce without any Chickenbones mods?

**Comment by ghost** [comment]
I'll try. Like I said, it is kinda random. Sometimes I go hours without a crash and other times it happens multiple times. I'll remove Chickenbones mods and will keep you posted.

**Comment by ghost** [comment]
No crahes since removing said mods. I'll assume that was the problen and close this. Thank you.
