### ISSUE TITLE
[1.10.2] Startup crash

### ISSUE THREAD

**Issue by Cakestory** [Chisel-Team/Chisel#447]
This crash happens immediatly after launching the game. Though it seems to be related to the new dependency mod (Connected Textures Mod).
[crash.txt](https://github.com/Chisel-Team/Chisel/files/1077166/crash.txt)

Version of Chisel: 0.0.11.23

**Comment by tterrag1098** [comment]
Fixed via d0c0b9cb89b1ca68cc4e9e00536dc6719578a5c4
