### ISSUE TITLE
[1.10.2] Initialization crash with Ender IO & Funky Locomotion

### ISSUE THREAD

**Issue by Cakestory** [Chisel-Team/Chisel#448]
When launching the game with the latest chisel build from curse and Ender IO and/or Funky Locomotion i get the following crashes for each mod:

[crash-2017-06-15_11.15.37-client.txt](https://github.com/Chisel-Team/Chisel/files/1077177/crash-2017-06-15_11.15.37-client.txt)
[crash-2017-06-15_11.13.05-client.txt](https://github.com/Chisel-Team/Chisel/files/1077176/crash-2017-06-15_11.13.05-client.txt)

Chisel Version: 0.0.11.23

**Comment by tterrag1098** [comment]
Fixed via d0c0b9cb89b1ca68cc4e9e00536dc6719578a5c4
