### ISSUE TITLE
CRASH ON STARTUP

### ISSUE THREAD

**Issue by AnthonyKane5528X** [Chisel-Team/Chisel#449]
Note:  The crash log indicates that both EnderIO and Chisel are somehow involved.  I have already reported it to the folks at EnderIO.

Here is a copy of that Issue ticket

Issue Description:

-This shouldn't have effected anything but I will state these events as they may help to pin down the cause of the crash.
-Downloaded latest version of Chisel-MC1.10.2-0.0.11.23
-Downloaded latest version of CoFHcore1.10.2-4.1.3.5
-Downloaded latest version of Thermal Dynamics-1.10.2-2.0.3.5
-Downloaded latest version of Thermal Expansion-1.10.2-5.1.2.3
-Downloaded latest version of Thermal Foundation-1.10.2-2.1.1.3

I did nothing to EnderIO, but if you read through the crash log you'll see it has something to do with EnderIO and Chisel.

Attempted to load. Game Crashed. Undid all updates. Attempted to load. Game crashed AT LAUNCH.

Here is the paste pin for the crash:
https://pastebin.com/V7Ytfjbm

The game will not attempt to load anymore. Once "Play" is clicked the launcher begins and then immediately crashes.
What happens:

-Click "PLAY" button at launcher. Game attempts to start to load and then crashes.
What you expected to happen:

-Click "Play" and Game Loads
Steps to reproduce:

...
Affected Versions (Do not use "latest"):

    EnderIO: 1.10.2-3.1.1.183
    EnderCore: 1.10.2-0.4.1.66
    Minecraft: 1.10.2
    Forge: 12.18.3.2254

Your most recent log file where the issue was present:

https://pastebin.com/V7Ytfjbm

*EDIT*
FYI for those experiencing the same crash:
Just an FYI to anyone experiencing the same "bug". You can "Fix this" by reverting back to the previous version of Chisel AND you must uninstall the Connected Textures Mod (CTM). When you updated Chisel, it downloaded this mod as a dependency so you may not have noticed it. Doing this will allow your loader to execute and get you back into your game.

Mine you this is not a fix for the bug. It is just a way to undo the change so that you can play again.

**Comment by AnthonyKane5528X** [comment]
Just to be clear:  reverting back to a previous version of Chisel **WILL NOT** fix this once its been done right?

**Comment by tterrag1098** [comment]
Fixed via d0c0b9cb89b1ca68cc4e9e00536dc6719578a5c4
