### ISSUE TITLE
[suggestion] support for tinkers construct + natura

### ISSUE THREAD

**Issue by InkDragon** [Chisel-Team/Chisel#45]
Any chance support for tinkers construct metals or natura woods might be added?

**Comment by Drullkus** [comment]
Aluminium, Bronze, Copper, Tin blocks have been already added long ago and accessible through oredict.

Natura will be put into consideration.

**Comment by InkDragon** [comment]
Was looking for the Others such as Cobalt, ardite, manyullyn
Thank you for considering natura

**Comment by Drullkus** [comment]
Cobalt - Perhaps

I don't see other mods seeing Ardite and Manyullyn though.

**Comment by Drullkus** [comment]
Check out [Unlimited Chisel Works](https://minecraft.curseforge.com/projects/unlimited-chisel-works) :)
