### ISSUE TITLE
Bug With CTM

### ISSUE THREAD

**Issue by MakeLord95** [Chisel-Team/Chisel#451]
Chisel MC1.10.2-0.0.11.24 doesn't recognize CTM MC1.10.2-0.1.0.9 or MC1.10.2-0.1.0.8

https://pastebin.com/PggNB5tj

**Comment by tterrag1098** [comment]
There is no crash in that pastebin

**Comment by Staegrin** [comment]
![not recognizing ctm](https://user-images.githubusercontent.com/8494635/27196145-a4669fb6-5209-11e7-8f0d-3b4d8016796f.png)

Tried both versions 0.1.0.9 and 0.1.0.8

Log says 20:26:11	FML	Client thread	error	The mod chisel (Chisel) requires mod versions [ctm@[MC1.10.2-0.1.0.8,)] to be available
20:26:11	FML	Client thread	error	net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [ctm@[MC1.10.2-0.1.0.8,)]

**Comment by MrSapient** [comment]
Same problem.
Client - http://imgur.com/a/ZekcR
Server - https://pastebin.com/zbRVdXNd

**Comment by Psy-Virus** [comment]
Just downloaded it for forge and also doesn't work. And honestly, I can't find a CTM mod for forge O.o

Any hints?

**Comment by Staegrin** [comment]
CTM stands for ConnectedTexturesMod Been a library for the last 3 versions of versions of the chisel mod since 
Chisel - MC1.10.2-0.0.10.22

**Comment by Psy-Virus** [comment]
I wrote it separated not in one word.... Thanks mate :-)
Weird that even google only gave me something for Spigot...

**Comment by tterrag1098** [comment]
Sorry, CTM was not reporting its version properly, it has been [fixed](https://github.com/Chisel-Team/ConnectedTexturesMod/commit/fec0c798e78a0a86c317987a6dce0cb32d631051) and [released](https://minecraft.curseforge.com/projects/ctm/files/2434709)

**Comment by MrSapient** [comment]
Some reason this fix isnt working server side.

**Comment by Psy-Virus** [comment]
For me neither

**Comment by MrSapient** [comment]
Client side it loads up no problem but the server is still same error.
https://pastebin.com/AE4q20vw
