### ISSUE TITLE
Game crashes with the latest build on 1.11.2

### ISSUE THREAD

**Issue by Sunconure11** [Chisel-Team/Chisel#455]
https://pastebin.com/L3rxT5kP

**Comment by alexbegt** [comment]
To run Chisel 1.11.2 now, It seems you need to install ConnectedTexturesMod (CTM) and I do not see that in the mods list; CurseForge Link: https://minecraft.curseforge.com/projects/ctm

**Comment by Sunconure11** [comment]
Fuck, I didn't notice. I thought it was already installed.

**Comment by Sunconure11** [comment]
And now, yet another error.

https://pastebin.com/qEEuwsBv

**Comment by tterrag1098** [comment]
That build was completely busted, I was in a rush and shouldn't have released as I left home >.>

New release is up now, everything should work.
