### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by fscan** [Chisel-Team/Chisel#456]
When i log in with the newest chisel version (MC1.10.2-0.0.11.25) i get the attached crash. Downgrading to MC1.10.2-0.0.10.22 fixes the problem.

Forge 12.18.3.2316, custom modpack, local single player.

[crash-2017-06-16_23.03.40-client.txt](https://github.com/Chisel-Team/Chisel/files/1081958/crash-2017-06-16_23.03.40-client.txt)

**Comment by tterrag1098** [comment]
You have optifine installed, please reproduce without it.

**Comment by fscan** [comment]
Yes, it seems to be an optifine interaction bug.

**Comment by tterrag1098** [comment]
We do try to maintain OF compatibility, but that can only go so far. Try disabling some settings in OF to see if it's a particular one causing the issue. If you can't isolate it (or even if you can), report it to them.
