### ISSUE TITLE
EnderIO Painted Conduit Facades/Glowstone Visual bug

### ISSUE THREAD

**Issue by cj89898** [Chisel-Team/Chisel#457]
I just updated from Chisel 0.0.10.22 to 0.0.11.25 and I get this weird visual bug with EnderIO painted conduit facades and painted glowstone. Ender IO version hasn't changed (still 3.1.192).

[![https://gyazo.com/445ea9ffc95a895bf65fd40a037e16af](https://gyazo.com/445ea9ffc95a895bf65fd40a037e16af/raw)](https://gyazo.com/445ea9ffc95a895bf65fd40a037e16af)

Both blocks were painted with "Marble | Circular | Has CTM"

Modpack: https://minecraft.curseforge.com/projects/cjs-modpack (v1.7.7 to v1.8.0)

This is multiplayer

**Comment by cj89898** [comment]
It seems that the glowstone thinks it is connecting to the other blocks (as you see it looks like the other center blocks) but the chisel blocks don't recognize it.

**Comment by tterrag1098** [comment]
Fixed in EIO

**Comment by HenryLoenwind** [comment]
Nope. Your bug. https://github.com/SleepyTrousers/EnderIO/issues/4261
