### ISSUE TITLE
[1.11.2] CTM dependency

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#458]
Minecraft crashes shortly after starting and gives the following crash report:

[crash-2017-06-17_11.31.39-client.txt](https://github.com/Chisel-Team/Chisel/files/1082463/crash-2017-06-17_11.31.39-client.txt)

It says
> Caused by: net.minecraftforge.fml.common.MissingModsException:
> Mod chisel (Chisel) requires [ctm@[MC1.11.2-0.1.0.2,)]

so I thought downloading CTMLib on my own could solve the issue, but there's no 1.11.2 version available.

Forge: 1.11.2-13.20.0.2315
Chisel: 0.0.11.16

The previous version (0.0.10.14) does work.

**Comment by ghost** [comment]
I found [ConnectedTexturesMod](https://minecraft.curseforge.com/projects/ctm) to be the one that's needed. Please link that mod under [dependencies](https://minecraft.curseforge.com/projects/chisel/relations/dependencies) to avoid further confusion.

**Comment by tterrag1098** [comment]
It is listed as a dependency:

![](http://i.imgur.com/AeW8Xxs.png)

Not sure why it isn't on that page, seems like a problem with curse, not me.
