### ISSUE TITLE
Rendering issues (Mekanism pipes and EnderIO Travel Anchor)

### ISSUE THREAD

**Issue by erwin1234777** [Chisel-Team/Chisel#459]
Not sure if Chisel might be to blame in this case, but since it deals with rendering and CTM(as far as i know) is helping rendering, im reporting issues where the blocks previously stated are not being rendered (fluids, gases are being rendered without the blocks/pipes). (using latest version of the chisel mod)

**Comment by tterrag1098** [comment]
The issues with EIO are known, but I haven't heard of Mekanism, and they don't even use our API. Can you reproduce any issues without CTM installed?

**Comment by erwin1234777** [comment]
nope, after removal (chisel, bitdrawer and CTM) the Mekanism pipes render normally
Haven't tested the other pipes, only using the Advanced Gas pipe as a testing block since it didn't work on our server (nor my single player world). Not sure about the other pipes, but that one is definetly not rendering correctly.

**Comment by xAlicatt** [comment]
I can confirm that Mekanism pipes are invisible with Chisel/CTM installed. I have tested this with only those mods and then removing Chisel/CTM and they are visible again. I have rolled back Chisel/removed CTM in my pack until a fix is found.

**Comment by erwin1234777** [comment]
@xAlicatt which version did you rollback to make it work? i'm thinking about doing the same

**Comment by xAlicatt** [comment]
@erwin1234777 Just rollback Chisel to the most recent build from April and then remove CTM and it should fix it for you.

**Comment by erwin1234777** [comment]
@xAlicatt will do, thank you :D

**Comment by tterrag1098** [comment]
I cannot reproduce this with CTM and Mekanism alone.

**Comment by xAlicatt** [comment]
@tterrag1098 

[Mekanism + Chisel + CTM](http://i.imgur.com/1T8agsX.png)

[Mekanism + CTM](http://i.imgur.com/908SCrk.png)

**Comment by tterrag1098** [comment]
Uhm...except you also have MCMP and the other two Mek modules? I tested with *only* CTM and Mekanism, period. This leads me to believe the source of the issue is MCMP, somehow. @amadornes ?

**Comment by xAlicatt** [comment]
No need to get snippy....Aren't most people going to run everything? And the fact that removing CTM while still having all of the other mods in fixes the issue leads me to believe that it is a conflict between CTM and MCMP. So it could be you...or it could be them. Or both. Nobody is trying to attack you personally, just passing on what we have experienced.

EDIT: Also, I'm not under the impression that it is even possible to RUN Mekanism without MCMP. I just tried it with CTM + base Mek and it asked for MCMP.

**Comment by tterrag1098** [comment]
Yes most people would run everything. But the point is isolation. We have now determined that the actual root cause is MCMP/CTM, not Mekanism.

**Comment by tterrag1098** [comment]
Also, I still cannot reproduce. This is MCMP+Mek+CTM only.
![](http://i.imgur.com/uq38flZ.png)

**Comment by tterrag1098** [comment]
Just to check, I tried 1.10 too, still works fine.

**Comment by xAlicatt** [comment]
I'm using 1.10.2 with Forge 2281, since that's the latest version that works with Sponge for 1.10.2....cannot speak for the others in this thread though.

**Comment by xAlicatt** [comment]
You have fancy graphics on....I wonder if it's got something to do with that. I always run in Fast.

**Comment by tterrag1098** [comment]
Which *specific* block are you placing in your screenshots?

**Comment by xAlicatt** [comment]
This is base Mek + CTM + MCMP in version 1.10.2/Forge 2281 with Fast Graphics looking at the Basic Universal Cable, but I have placed a random assortment of the other Mek pipes beside it and they are all invisible.
[here](http://i.imgur.com/tyx5iP5.png)

This is the same mod combo with Fancy Graphics
[here](http://i.imgur.com/jssqCp1.png)

Perhaps it's a Forge issue? Which version are you testing with?

**Comment by tterrag1098** [comment]
On 1.10 I was using 12.18.3.2254

**Comment by amadornes** [comment]
@xAlicatt Try placing a bit from C&B in the same blockspace as the pipe and see if it renders or not. If nothing renders, it's probably an MCMP-CTM issue, if it does, Mekanism may be involved.
That said, I haven't seen any issues at all between MCMP and CTM in the past so I'd be surprised if it was some sort of incompatibility between the two.

**Comment by xAlicatt** [comment]
@amadornes This is the same setup Mek + CTM + MCMP (+ C&B for this test) in MC 1.10.2/Forge 2281(using this version of forge because it's the latest version possible to use Sponge on a server)

The same Basic Universal Cable with a single Gold Ore bit placed below it in the same block space.

[clickie!](http://i.imgur.com/p3FQSDj.png)

**Comment by tterrag1098** [comment]
@xAlicatt could you test this build to see if the problem persists? http://ci.tterrag.com/job/ConnectedTexturesMod/branch/1.10%252Fdev/14/

**Comment by xAlicatt** [comment]
@tterrag1098 Pipes are rendering now. There seems to be a weird 2-3 sec lagtime after placing a pipe before it appears and then another 2-3 sec lagtime before the attachment to another block appears, but this could be entirely computer-caused lag.

**Comment by tterrag1098** [comment]
That definitely sounds like tick lag, yes. I didn't see any such performance issues on my end.

**Comment by tterrag1098** [comment]
Then it's fixed. Ref https://github.com/Chisel-Team/ConnectedTexturesMod/commit/3a152b4217b4ab94587d9468978801372c1414a2
