### ISSUE TITLE
[1.10.2] Chisel not being loaded on server

### ISSUE THREAD

**Issue by xXJamieXx** [Chisel-Team/Chisel#461]
So, it seems like Chisel isn't being loaded on the server but the client is fine. I can tell this because when I go to craft a chisel I can't take the output from the crafting bench and its called "Unnamed 0". Nothing from chisel shows up in JEI either. (In singleplayer, it works fine)

Forge: 2281
Chisel: 0.0.11.25
ConnectedTexturesMod: 0.1.0.13

**Comment by tterrag1098** [comment]
Please post the startup log from your server.

**Comment by xXJamieXx** [comment]
Here you go: [Here](https://zerobin.net/?85ac08ff8ef73791#kGUKNlkSe0PiD9wDpo5MAVP+CgTDZueSuZbXiaMN9Zs=) (apologies, pastebin has a character limit...)
From what I can see, these lines: 

> "Unable to read the jar file Chisel-MC1.10.2-0.0.11.25.jar - ignoring"
> "java.util.zip.ZipException: error in opening zip file"

Are what is affecting it. Although this is happening with Decocraft a bit further down as well.

A bit further down also:

> "Zip file Chisel-MC1.10.2-0.0.11.25.jar failed to read properly, it will be ignored"
> "java.util.zip.ZipException: error in opening zip file"

Which seems to be affected by the first bit.

**Comment by tterrag1098** [comment]
Sounds like some of your jar files, including Chisel, got corrupted at some point. I would try downloading them again.
