### ISSUE TITLE
Startup Crash (noob warning)

### ISSUE THREAD

**Issue by Oraiz** [Chisel-Team/Chisel#462]
So I have my own custom pack which I occasionally do a batch update of mods for - recently did one for the new Thermal stuff, and I updates Chisel and a few others, now I have this crash: https://pastebin.com/jWwXyCVq

I've tried rolling back a few versions, but I can't remember which one I was running before!

**Comment by tterrag1098** [comment]
This is a CTM problem, though really it's the fault of your resource pack (F32) shipping broken json files. Vanilla apparently ignores this, so we will have to as well. Ref https://github.com/Chisel-Team/ConnectedTexturesMod/commit/5c57ebcf8cd08e7b0a6fae26d523843bd6769cf8

**Comment by Oraiz** [comment]
Brilliant, thanks a lot for the quick reply.
