### ISSUE TITLE
[Feature Request] Add Marble, Limestone, Basalt to oredict

### ISSUE THREAD

**Issue by Endmateria** [Chisel-Team/Chisel#463]
I don't know if it's Quark or Chisel or both, but both mods add marble, limestone, and basalt worldgen, and their recipes do not play nice together i.e., you can't chisel the Quark (marble/limestone/basalt) blocks, and you can't craft Quark's (marble/limestone/basalt) stairs and slabs with Chisel's blocks.  Can these blocks be added to the oredict so that the two mods work together?

**Comment by Endmateria** [comment]
@Vazkii

**Comment by Drullkus** [comment]
https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/java/team/chisel/Features.java#L218

We've already oredicted our blocks. Bring it up with Vaz
