### ISSUE TITLE
[1.12] EntitySheep.getDyeRgb is not available on the server

### ISSUE THREAD

**Issue by AtomicBlom** [Chisel-Team/Chisel#468]
Hi guys,

Trying to start Shear Madness on the server and I found this fellow:
https://gist.github.com/AtomicBlom/ca54f7369a7e64b83d04806e4314e663

Forge Version: forge-1.12-14.21.0.2373
Minecraft version: 1.12 Server
Chisel version: Chisel-MC1.12-0.0.11.6
CTM version: CTM-MC1.12-0.1.1.1

```
java.lang.NoSuchMethodError: net.minecraft.entity.passive.EntitySheep.func_175513_a(Lnet/minecraft/item/EnumDyeColor;)[F
	at team.chisel.Features$31$1.<init>(Features.java:1347) ~[Features$31$1.class:?]
```

**Comment by tterrag1098** [comment]
Fixed via defd84753401f3041aecad14eaf83506674443ab
