### ISSUE TITLE
[1.12] Concrete Feature overlapping with vanilla's own

### ISSUE THREAD

**Issue by starg09** [Chisel-Team/Chisel#470]
Bringing it up just in case, currently the concrete backport is still present as of build 7 for 1.12, and the chisel variants depend on the mod's own version instead of the vanilla one.

Versions:

* MC 1.12
* Forge 2387
* Chisel (DEV) 0.0.11.7

**Comment by starg09** [comment]
Also, extremely minor detail, but Hardened Clay variants should now be called Terracota :)

(Not sure if you want a separate issue for it)

**Comment by tterrag1098** [comment]
1.12 concrete has been removed
