### ISSUE TITLE
1.11.2 Crash on launch

### ISSUE THREAD

**Issue by jcmgamer** [Chisel-Team/Chisel#471]
https://pastebin.com/XTNdvxPr    This only seems to be happening with the .16 and .18 versions for 1.11.2.  The .14 version is getting the following crash every so often: https://pastebin.com/yr7sZurp

For the first error, I'm not seeing a mod erroring other than Chisel.  If you can link it to another mod causing it to crash, let me know.  As for the second crash, it looks like it was related to codechicken and I just updated it now.  Will post back if I keep getting the second error.

**Comment by tterrag1098** [comment]
> Caused by: net.minecraftforge.fml.common.MissingModsException: Mod chisel (Chisel) requires [ctm@[MC1.11.2-0.1.0.2,)]

**Comment by jcmgamer** [comment]
My bad, I was looking at the Game Version collumn and didn't see that version was for 1.11.2. Edit:  I'm a tard and didn't check the +1/2 after the version number.
