### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#475]
Wow lol.  That is... a lot of OreDict entries. =)

How about a config option to remove them?  No rush.  I already did via MineTweaker using a program I wrote to parse out the info.

**Comment by tterrag1098** [comment]
But why?

**Comment by ghost** [comment]
1>> I think I am not alone in this, but it is annoying to see that many blocks cycle through an unrelated recipe in NEI/ JEI.  I prefer to keep it as clean as possible.
2>> If a mods crafting item, which should be equivalent to something else, cannot be converted then I believe the OreDict is appropriate.  It does not apply in this case as I can re-chisel it back to the original block.
3>> Given that I only chisel the blocks that I need for decoration and convert any extra back to the original block it should be exceedingly rare to actually use one in a recipe.  So see point # 1.

Note: these are just my personal play styles and opinions.

**Comment by tterrag1098** [comment]
My opinion here is that the oredictionary is convenient for crafting with chiseled items, and when it cycles through in recipes it's pretty obvious what the block type is, since JEI will list the oredict name, and the chisel items are named the same as the vanilla verions.
