### ISSUE TITLE
Chisel blocks used in worldgen don't seem to block sunlight

### ISSUE THREAD

**Issue by esotericist** [Chisel-Team/Chisel#476]
Okay, this is kind of a weird problem, but when using the 'Chisel' variant of McJty's Lost Cities worldgen, anywhere that chisel blocks (primarily concrete? exclusively concrete? Not sure which), sunlight propagates down through an arbitrary number of blocks.

What makes it weird is that when placed by hand, those same blocks do properly block sunlight.

Supporting images:
https://drive.google.com/file/d/0B9H6zC2vFoivNkRkSlBYRDVtTmc/view
https://drive.google.com/file/d/0B9H6zC2vFoivNElWeG5wVzRCV2M/view
https://drive.google.com/file/d/0B9H6zC2vFoivSGhTdktsY0JzVms/view

More discussion can be found in the issue I reported originally to McJty over here: https://github.com/McJty/LostCities/issues/34

**Comment by esotericist** [comment]
It's in one of the images, but I'll state explicitly:
Minecraft 1.11.2, Forge 2388, chisel 0.0.11.18, compat layer 0.2.9, CTM 0.1.1.6, lost cities 0.0.16. no other mods.

**Comment by tterrag1098** [comment]
Thank you for the report, I think I've nailed down what might cause this, can you try this test build to verify the fix?

https://drive.google.com/open?id=0BwDDNuT6abxIRjI3YlFBenJlaG8

**Comment by esotericist** [comment]
I am not yet in a position to try it, but I will endeavor to do so soon. Thanks for the swift response.

**Comment by esotericist** [comment]
Re-created the world with that (and the updated CTM I discovered it needed after the first crash), but problem still persists. I am underground, with lots of chisel concrete bricks above me, with F3 showing full sunlight.

**Comment by tterrag1098** [comment]
So turns out I messed up and that build wasn't actually any different...multiple different MC versions can be confusing.

Try this one instead: https://drive.google.com/open?id=0BwDDNuT6abxIRWJMNm5oYXJGWWM

**Comment by esotericist** [comment]
I've been there! Giving it a try. One moment while I launch minecraft and do the worldgen thing again.

**Comment by esotericist** [comment]
Yay!
https://drive.google.com/file/d/0B9H6zC2vFoivZGY2ZU84M3VVVE0/view

This appears to have fixed it. That is now a suitably horrific building interior!

**Comment by esotericist** [comment]
You don't happen to know of a way to force relighting on the problematic old worldgen, do you?

**Comment by tterrag1098** [comment]
I don't, no.

**Comment by esotericist** [comment]
Unfortunate. Well, thanks for your help.

**Comment by Drullkus** [comment]
Try reloading chunks by `F3` `A`
