### ISSUE TITLE
[1.12] TD Covers connected textures

### ISSUE THREAD

**Issue by 016Nojr** [Chisel-Team/Chisel#479]
Not sure if this is implemented in 1.10.2/1.11.2 as I am playing in 1.12.

It would be nice if you could add support for connected textures between Thermal Dynamics covers and normal chisel blocks so you dont have "a line" between the covers and normal blocks.

Example (Using Stone (Big tile)): https://gyazo.com/5db79a8cf14952100f1b78e302d337de

**Comment by tterrag1098** [comment]
This is entirely on their end, our API has had support for this kind of thing for years.
