### ISSUE TITLE
Add ctm to required mods on startup

### ISSUE THREAD

**Issue by UnPure** [Chisel-Team/Chisel#480]
Hey there.
When starting the game with just chisel installed the game is crashing.
This seems to be caused if ctm is missing.
Would it be possible to add that requirement to the startup so the game tells you if something is missing instead of crashing?

**Comment by tterrag1098** [comment]
This is complicated since CTM doesn't work serverside, and FML provides no way to depend on a mod only on the client (or server, for that matter).

However, I've found a better workaround that should pop the GUI about missing mods instead of just crashing.
