### ISSUE TITLE
Crash upon updating screen events [1.12]

### ISSUE THREAD

**Issue by ImAK9** [Chisel-Team/Chisel#481]
Crash happens in multiplayer when changing block type.

https://pastebin.com/yTdPcVU9

**Comment by Gemta** [comment]
I can confirm that this crash also happpens in singleplayer on MC version 1.11.2.

**Comment by kragnoth** [comment]
https://pastebin.com/D8fRseyK

There is a crash dump from single player.  Sorry about not removing foamfix.

Will post new dumpbin if it looks different without foamfix installed.

edit: yup, still crashing.  And dump looks the same.

**Comment by TygreWolf** [comment]
[https://pastebin.com/LDhnYcr8](url)

Also adding my crash dump for this error.  Single Player, converting marble with iron chisel.

Minecraft 1.12, Forge 14.21.1.2406.

**Comment by drakray** [comment]
Chiseling Limestone https://pastebin.com/bY3R9GNQ

HSP
MC 1.11.2
Forge 2393
Chisel 0.0.13.20

**Comment by MrNinja93** [comment]
Still appears to be an issue in the latest chisel for 1.12 (0.0.14.18), almost identical crash log (also multiplayer)

https://gist.github.com/MrNinja93/3a1443a830d4cff276de2412b259b702

Context for the crash using a diamond chisel to chisel cobble to a chisel variant. Accidentally took too much out of the storage drawer so my inventory was full when I went to shift click the block I wanted from the chisel gui.

  
Minecraft: 1.12.2
Forge: 14.23.0.2512 
Chisel: MC1.12-0.0.14.18 
CTM: MC1.12-0.2.3.9
