### ISSUE TITLE
Crash when trying to chisel basalt (1.10)

### ISSUE THREAD

**Issue by warplord** [Chisel-Team/Chisel#484]
I got this crash: 

http://paste.feed-the-beast.com/view/b01ae10b

I was trying to chisel basalt. Both chisel variations and environmental tech variations caused the crash.

**Comment by mcdodge34** [comment]
Same crash while trying to chisel glass, I was able to chisel glass to quite clear glass from enderio but now that I want normal glass back, I got this same crash. I solved the issue by downgrading to build 26, will test if in build 27 tomorrow, but so far, in build 26, works #1, I was using the mod on server and server doesn't crash, only client does it.

**Comment by Captainaviator** [comment]
I got a similar 'Updating screen events' crash in 1.11 when chiseling Astral Sorcery's marble into chisel marble

**Comment by pixzi** [comment]
Same crash for me too. Using any of the other types of marble (quark, Astral Sorcerys) causes it to crash, not tried with the limestone or basalt, although i predict its the same.

**Comment by tterrag1098** [comment]
Duplicate of #481
