### ISSUE TITLE
[1.12] Chisel blocks loosing their textures

### ISSUE THREAD

**Issue by Symbai** [Chisel-Team/Chisel#485]
Hi,

after some minutes in the game chisel blocks lost their textures and turned into gray blocks. If I place new blocks they are gray as well. If I restart the client and log into singleplayer again, all blocks have their correct textures. Then after some minutes, chisel blocks become gray again.

Chisel: Chisel-MC1.12-0.0.13.13.jar
CTM: CTM-MC1.12-0.2.0.3.jar

![javaw_2017-07-14_14-55-51](https://user-images.githubusercontent.com/14368203/28213152-178a71e6-68a5-11e7-8dce-1c180a320b84.png)
![javaw_2017-07-14_14-59-35](https://user-images.githubusercontent.com/14368203/28213153-178b5bec-68a5-11e7-9e3f-c44d995c52f3.png)

**Comment by tterrag1098** [comment]
Can you reproduce this without other mods?

**Comment by Gbergz** [comment]
![chiselbrokentexture](https://user-images.githubusercontent.com/26634554/28332904-93068ca2-6bf6-11e7-8ced-eb24cce4cc37.png)
I've also gotten this in a modpack im playing (1.12)., Chiseled textures are just plain white/gray.
Restarting the game fixes this. I HAVE NO IDEA HOW TO REPRODUCE THIS. But if i do, i will be sure to post it here.
Chisel version: Chisel-MC1.12-0.0.13.13
Forge Version: forge-14.21.1.2410

**Comment by Symbai** [comment]
Update: It happens when using a texture pack. Without texture pack this issue no longer occurs (for ME at least).

@Gbergz: Are you using a texture pack?

**Comment by Drullkus** [comment]
Logs please

**Comment by Notawallplan** [comment]
It is possible that Optifine may be involved. As far as logs are concerned i didn't see anything when the textures changed.

**Comment by Symbai** [comment]
I didn't used optifine, it was the texture pack. Issue can be closed.
