### ISSUE TITLE
Chisel not loading 

### ISSUE THREAD

**Issue by Cyberwolfent** [Chisel-Team/Chisel#486]
I am not seeing Chisel in my mods list.  I see CTM though.  Running CTM 1.12-0.2.0.3 
Forge 14.21.1.2387

**Comment by tterrag1098** [comment]
CTM is a library for chisel. Do you have both installed?

**Comment by Cyberwolfent** [comment]
Yes I do have both loaded.  CTM-MC1.12-0.2.0.3 & Chisel-2.9.5.11  On Forge 1.12.14.21.1.2387

**Comment by tterrag1098** [comment]
Your chisel is from 1.7.10...

**Comment by Drullkus** [comment]
Please download the latest chisel for 1.12 from here :rofl: 

https://minecraft.curseforge.com/projects/chisel/files
