### ISSUE TITLE
Chiseling metal blocks problem (1.10)

### ISSUE THREAD

**Issue by warplord** [Chisel-Team/Chisel#487]
When you try to chisel a block of lead/copper/bronze/etc., that has a block equivalent in IC2, for some reason the game crashes. If you chisel the thermal exmansion block placed in the world - u get only the IC2 varian. U can never get to "Shipping Crate" or "Caution" variants of lead blocks for example. Any idea how this can be fixed?

**Comment by KnightMiner** [comment]
Maybe it would help if you gave the crash report? "It crashes" is not helpful to debug

**Comment by warplord** [comment]
It was the oredict problem. Everything works fine now.
