### ISSUE TITLE
When I try to chisel a birch bookcase game crashes

### ISSUE THREAD

**Issue by senpaisayss** [Chisel-Team/Chisel#489]
So i make a chisel, right click, put the bookcase in the block and try to make a rainbow bookcase and the game crashes

**Comment by tterrag1098** [comment]
Update.

**Comment by senpaisayss** [comment]
I did update I'm using 1.11.2 and the most current version of chisel......

**Comment by tterrag1098** [comment]
Then duplicate of #488
