### ISSUE TITLE
missing block smashingrock causes connection fail to server

### ISSUE THREAD

**Issue by ToserBan** [Chisel-Team/Chisel#491]
On singleplayer i have no problem, but with my modded 1.7.10 forge server i cant connect to the server if chisel is installed. The client log says because of the missing block smashingrock. Without chisel i cant connect.
[chiselproblem.txt](https://github.com/Chisel-Team/Chisel/files/1151186/chiselproblem.txt)
I tried three different Versions of chisel, including 2.9.5.11 for MC 1.7.10, every time the same problem.

**Comment by tterrag1098** [comment]
You must have that item disabled in your client. 1.7.10 is not supported, either way.

**Comment by ToserBan** [comment]
Ok, i found a workaround by myself: I set 
 B:smashingRock=false
in the chisel.cfg file and it worked. Now i can use this great mod with its marble and various stones on my server :)

**Comment by ToserBan** [comment]
Just saw you answered already, thanks ;)
