### ISSUE TITLE
Marble from Astral Sorcery Crash

### ISSUE THREAD

**Issue by TrikSteve** [Chisel-Team/Chisel#492]
Crash to desktop when trying to chisel Marble from Astral Sorcery.

Forge - 12.18.3.2316
Chisel version - 1.10.2 - .0.0.13.28
Astral Sorcery - 1.10.2 - 1.4.5

[crash-2017-07-16_14.11.55-client.txt](https://github.com/Chisel-Team/Chisel/files/1151287/crash-2017-07-16_14.11.55-client.txt)

**Comment by tterrag1098** [comment]
Update.
