### ISSUE TITLE
crash when trying to chisel marble blocks from astral sorcery

### ISSUE THREAD

**Issue by DietmarKrause** [Chisel-Team/Chisel#496]
here is the crash report :https://pastebin.com/wY2j0yx6
tried with iron and diamond chisel. 
reportet to astral sorcery, too

**Comment by loadstarnes** [comment]
I have a very similar problem [here](https://pastebin.com/37J8aXJE) except with Basalt blocks. 

Note that I am using 1.11.2 while @DietmarKrause is using 1.12... however the errors still seem quite similar.

I was chiseling Basalt blocks into the trodden bricks chiseled form.

Edit: However, I am using a slightly outdated Chisel version. I will update this once I test again...

**Comment by tterrag1098** [comment]
This has been fixed in the latest release...for a while.
