### ISSUE TITLE
[1.12] Crash With Tinker's Construct

### ISSUE THREAD

**Issue by CluelessPhil** [Chisel-Team/Chisel#498]
Hello, so I've needed to update my modpack Pristine, and TiCon was just out for 1.12 . I added it with Moar Tinkersw loaded the game and it crashed. I then went mod by mod and i went to Chisel and it had that crash.
# Crash: [crash-2017-07-18_21.38.54-client.txt](https://github.com/Chisel-Team/Chisel/files/1157772/crash-2017-07-18_21.38.54-client.txt)

**Comment by alexbegt** [comment]
This is a known bug with Tinkers Construct: [#3006](https://github.com/SlimeKnights/TinkersConstruct/issues/3006). It has been resolved but a new alpha has not been pushed to curse yet.

**Comment by CluelessPhil** [comment]
Ok, thank you

**Comment by KnightMiner** [comment]
For the record, this crash is caused by a recipe with an output that has a stack size of 0. Its patched on our side so it just ignores those, but if removing Chisel fixed it you might want to verify none of your recipes have a broken output (not sure if there are legitimate cases for empty outputs)

**Comment by tterrag1098** [comment]
The culprit seems to be this mod: https://minecraft.curseforge.com/projects/block-armor

Report it to them.

**Comment by Akzyra** [comment]
Thanks for finding the mod that caused it.    
For me it was the one of the "Extreme Reactors" Block-Armours. I disabled them all.
