### ISSUE TITLE
Waterstone Odd Texture bug 1.10.2

### ISSUE THREAD

**Issue by deadspidervenom** [Chisel-Team/Chisel#499]
The issue i would like to report, is the water for the connected texture blocks for waterstone(or lavastone) seems to bug out. like its trying to cover the whole block with the water texture and it changes and shifts when i move.

It only happens with the blocks that use liquids, such as waterstone, and lavastone and its only their connected texture blocks, all other blocks are fine.

I do have optifine installed, and no i will not uninstall it, because i seriously need it for some reason, else i can't run anything modded unless its like idk just forge, maybe a small mod or two, no its not any of my settings, yes ive tried using both better FPS and foamfix they literally do nothing for me without optfine, and no its not my PC, here are the important parts that effect this sort of performance.

AMDFX 8350 8core 4ghz
GTX 970 4gb gddr5
12gb of ddr3 ram (8 of which is allocated to minecraft, and im playing on a dedicated server so the stress is reduced even further)

Which should be well over kill for even the heaviest mod packs.

Also i am taking this problem to you and not Optifine, cause its only like 8 blocks doing it, and they are very specific blocks with very special textures.

Now i am more then happy to use another block, but i would strongly prefer to use waterstone, if i seem defensive at all, its because ive seen your replies to people using optfine, and i find them distasteful to say the least.

**Comment by tterrag1098** [comment]
We do not support Optifine. I'm sorry you "need" it (though your specs say otherwise...they are comparable to my computer and I have never needed optifine), but it does too many strange things to rendering that we cannot possibly debug every odd issue caused by it. If this does not happen without OF, then it's not our bug.

**Comment by deadspidervenom** [comment]
Its not "need" it its need, it not a question its not me just being "oh im a poor idiot who knows nothing about anything and think just because it says it works it works" its literal, ive tried everything it is what works, i know my specs say other wise, i know its stupid i even need to use it, but like i said its not something i can get around.

Just because removing a mod solves a problem does not make it that mod causing the issues, how does one test if the problem is chisel is removing chisel does not enable you to see the problem ?

Don't think you mod is flawless, and treat everyone who uses optifine as a idiot, i came to YOU because its only YOUR mod having issues with connected textures, and its not any other block BESIDES a 2 blocks, and their related textures, every block works. without issue, without conflict.

I also think out of all the mods ive tried, chisel has always been the only one with conflict with optfine, its like you purposely make it conflict out of spite, but hey ill just use a different block, sense you want to think that your mod is flawless, and don't even try to work with it even though SO many people use it for either shaders, or performance.

Please get a reality check. Sincerely someone that likes waterstone, and literally needs optfine to play modded minecraft above 6fps

**Comment by Tamaized** [comment]
lol

**Comment by dennisheperol** [comment]
I think the problem is that you are not using your graphic card to play Minecraft.

Look up at Google something like: Minecraft isn't using the right graphics card

PS: lol

**Comment by deadspidervenom** [comment]
Bro i have one graphics card, i built my PC, i did not make the mistake of stupidly buying a motherboard with a built in graphics card, causes to many conflicts

**Comment by dennisheperol** [comment]
Sister, are you 100% certain you are using it?

**Comment by ChloeDawn** [comment]
If you are having FPS issues that severe in modded with a 970 I highly recommend removing mods one at a time to see if one in particular is causing the performance issue. I've played large packs on my 970 with no issues, without Optifine, and with it + shaders enabled.

**Comment by deadspidervenom** [comment]
Im really curious how one plays modded minecraft with shaders without optifine, last i checked the only other shader thing is "shadermod" and its a client mod like forge.

It happens regardless of the modpack, yes i can get 60-90 fps, but its not stable, and the further i progress in any modpack besides skyfactory, my fps starts freaking out.

Optfine stabilizes my FPS so i am not feeling something akin to motion sickness every 5 seconds due to my fps going from 60fps to 6fps, for no other reaso then to piss me off, im not a imbecile, ive tried every solution possible via software, what makes it funny is it only happens with minecraft, every other game is just fine

**Comment by ChloeDawn** [comment]
> without Optifine, and with it + shaders enabled.

> with it + shaders enabled.

> **with it**

**Comment by deadspidervenom** [comment]
apologies i have a bad habit of skipping words when i am reading, ive been working on it but it still happens from time to time

**Comment by Tamaized** [comment]
I'm still curious as to why you think people need to support the hacky, incompatible mess that is Optifine.
Chisel, and other mods, do not intentionally make it so they're not compatible with Optifine, Optifine just does a lot of shit to the main MC class files that breaks so much stuff.

If anything, it's Optifine's end you should be angry at, they're the ones who refuse to work with mod authors. Back in the day (idk if they still do or not) they had a policy where you couldn't include it in modpacks for this reason.

**Comment by deadspidervenom** [comment]
they still have a policy, also if they are unwilling to work with mod authors do you think me reporting to them that they have a conflict with a mod would change anything? I think it would have 0 affect. So what the point of being like optfine and being dicks that don't want to work with people using other mods, all you are doing is being like them, which you despise ?

The reason i am saying its their end is the issue, is because the other end won't do anything at all, so instead of understanding this and trying to work with those who need to use the stupid thing, they shit on everyone and say we can't do anything about it, either remove the mod or remove our mod. Instead of take the time to making a small compatibility patch for like 8 blocks that are incompatible, or fixing the issue.

**Comment by ChloeDawn** [comment]
If this bug is a big problem for you, please consider reporting it to OptiFine's issue tracker too. Although it is possible that Chisel is to blame; it is likely a 50/50 conflict where both mods are attempting to do similar things and it is causing problems.

**Comment by Tamaized** [comment]
Has it ever occurred to you that it may be impossible to fix on Chisels end?

**Comment by deadspidervenom** [comment]
As impossible as me breathing air while alive, again would like to state, ive used tons of other mods, and chisel is so far the only mod with connected texture issues, when optifine is installed

**Comment by Tamaized** [comment]
That doesn't justify that it's possible for Chisel to fix.

**Comment by deadspidervenom** [comment]
its a texture that uses liquid textures from water and lava, tons of mod has done it, with no conflict, they must be magical people able to fix this texture issue, when chisel devs can't do it

**Comment by Tamaized** [comment]
Incompetence at its finest right there. ^

**Comment by deadspidervenom** [comment]
how so? i don't see why one mod is different from another, they are both java coding

**Comment by dennisheperol** [comment]
Or Scala or Kotlin (not that that really matters)

**Comment by ChloeDawn** [comment]
Chisel has special handling for its blocks due to how the CTM is rendered; you cannot simply compare it to other mods that add a basic block with a fluid texture on it.

**Comment by Tamaized** [comment]
Well, you're obviously not a programmer, you don't understand what's going on under the hood. You can't make these claims that the Chisel devs simply don't know how to fix it. It's much more complicated than that.

**Comment by tterrag1098** [comment]
Enough. I've said my bit.
