### ISSUE TITLE
Transparent malfunctioning fan not animated

### ISSUE THREAD

**Issue by tehFoxx0rz** [Chisel-Team/Chisel#5]
As the title says, the transparent malfunctioning fan (in the technical blocks) currently appears exactly the same as the still one.  I tried to see if I could fix this with a resource pack texture, but it doesn't look like the malfunctioning transparent one actually has its own texture (the variant of the opaque one looks pretty neat though).

And while I'm here, I'll just say it'd be great to see some of the unused textures implemented sometime, like the "mechanical2" stuff, "symbolgold" in the unused folder, and the shingles!

**Comment by Drullkus** [comment]
Texture removed
