### ISSUE TITLE
Odd compatability with ganymedes woodstuff mod

### ISSUE THREAD

**Issue by Stormalisk** [Chisel-Team/Chisel#50]
As the title says, chests from woodstuff are interchangeable with the chisel. I am wondering if this can be changed.

**Comment by Choonster** [comment]
This is because both WoodStuff Chests and Chisel Presents are registered as "chest" in the Ore Dictionary. I don't think there's any way to disable this without using something like MineTweaker to remove WoodStuff Chests from the Ore Dictionary or register them under a different name.

**Comment by Stormalisk** [comment]
Yes, I know. 

I am wondering if a solution could be done between Ganymedes and the chisel team. 

Right now being able to chisel the chests is kinda hacky, and I want to disable it. I don't really want to download minetweaker just for it.

**Comment by Drullkus** [comment]
Minetweaker, if it bothers badly
