### ISSUE TITLE
User uncovered cascading worldgen with chisel [1.11.2]

### ISSUE THREAD

**Issue by Sunconure11** [Chisel-Team/Chisel#500]
https://gist.github.com/SjetCraft/8a0525aa46aba6e0e2d88cd5768aae35

I do realize the user is using optifine, but I'm trying to knock out some things that could be causing some major lag issues in my pack, so far. I am getting the user to generate a log without optifine, just in case, as I did see the little debate going on.

**Comment by tterrag1098** [comment]
Uhm...what dimension has id -2147483648? It only seems to occur there, and at ludicrous coordinates (in the millions of blocks away from the origin). I'd be hesitant to blame this on chisel considering I've never seen that issue for vanilla dimensions.

**Comment by TehNut** [comment]
Fairly sure that's the Mystcraft profiling dimension.

**Comment by Sunconure11** [comment]
Yeah, that would be Mystcraft. A bunch of issues related to Mystcraft were discovered, relating to that mod, with its 1.11.2 port.

https://github.com/XCompWiz/Mystcraft-Issues/issues/182

https://github.com/XCompWiz/Mystcraft-Issues/issues/187

https://github.com/Ivorforce/RecurrentComplex/issues/255

**Comment by HellFirePvP** [comment]
*snip* nevermind

*sigh*

**Comment by tterrag1098** [comment]
Then why doesn't this happen in any other dimension?
