### ISSUE TITLE
Dupe when chisel breaks

### ISSUE THREAD

**Issue by KidsDontPlay** [Chisel-Team/Chisel#501]
Chisel - MC1.12-0.0.13.14 
https://drive.google.com/file/d/0Bxk8bebSTRk-TTRFNFI5d0xKR2s/view?usp=sharing

**Comment by acun1994** [comment]
Chisel-MC1.12-0.0.14.18

Bumping issue.

Any blocks in Chisel Interface gets thrown out when chisel loses all durability. However, the targetted chisel blocks equal to the durability remaining appears in inventory. Possibly just forgot to add a check to change the ItemStack when breaking chisel.

**Comment by tterrag1098** [comment]
Tracking under #516
