### ISSUE TITLE
1.11.2 crash

### ISSUE THREAD

**Issue by jcmgamer** [Chisel-Team/Chisel#502]
I've been getting this crash every couple hours while playing.  https://pastebin.com/JNBKQHst  Not 100% sure whether it's chisel or codechicken that is causing the error, I just know that they are both involved in the crash.  I'm thinking it may be caused by the fact that i'm using an efficiency 15 pickaxe to instant break blocks.

**Comment by tterrag1098** [comment]
If you cannot reproduce it without CodeChickenLib then it is assumed to be their bug, as they are the ones calling this method with an invalid stack.
