### ISSUE TITLE
Client Crash when JEI attempts to render Chisel Paper Microblocks

### ISSUE THREAD

**Issue by sab0tic** [Chisel-Team/Chisel#504]
I realize this could be a problem with Microblocks / Forge Multipart, so I apologize if this isn't the right place to post it. I just figured since pretty much every single other Chisel blocks works with microblocks, that perhaps something was different about the Paper set of blocks.

Adding paper to the "microblocks.cfg", and then searching for it in JEI, causes the client to crash. I've attached the crash report! Happy to answer any other questions.

Again, apologies if this isn't the right place but it's my best guess.
[crash-2017-07-26_22.25.55-client.txt](https://github.com/Chisel-Team/Chisel/files/1178613/crash-2017-07-26_22.25.55-client.txt)

**Comment by tterrag1098** [comment]
Please report this to CCL/FMP
