### ISSUE TITLE
Blocks aren't rendered Properly - Pink and Black Blocks with Text on them

### ISSUE THREAD

**Issue by scaredtodeaf** [Chisel-Team/Chisel#506]
Versions:
chisel-MC1.12-0.0.13.14
CTM-MC1.12-0.2.1.4

https://gyazo.com/933be681ea98eb6ca9b848ec8e7c95a1
https://gyazo.com/21b21bca5ca23f5784ce7b16d7d739a0

Haven't changed any configs. If you need more information, just ask and ill provide.

**Comment by Williamhb** [comment]
All my chisel blocks are the same with:
Chisel - MC1.10.2 - 0.0.13.29
CTM - MC10.10.2 - 0.2.1.20
tried to reinstall chisel & CTM.
still just missing texture to all chisel blocks

**Comment by Hjaldar** [comment]
Seems to be an issue with the most recent versions of CTM. Rolling back a version (to 0.2.0.3) worked in 1.12.

See  https://github.com/Chisel-Team/ConnectedTexturesMod/issues/18

**Comment by tterrag1098** [comment]
Tracking on the CTM issue.
