### ISSUE TITLE
Did you remove pumpkins?

### ISSUE THREAD

**Issue by Jiinxycat** [Chisel-Team/Chisel#509]
I am in a 1.11.2 world, and went to carve a pumpkin with a chisel to find out that they are no longer there. I even looked in JEI to see the different ones, and they are no where to be found. Did you remove them, was there a reason for removing them, and will they be back? Just wondering. It just made e sad I can't carve pumpkins and make them cute anymore.

**Comment by rockobonaparte** [comment]
Jack-o-Lanterns might have been a Chisel 2/Chisel 3 thing. I requested them to be included along with a bunch of other ones from that pack in my request as well:

https://github.com/Chisel-Team/Chisel/issues/508

It sounds like it'll get addressed after everybody finishes relaxing for the summer hehehe.

**Comment by Drullkus** [comment]
> relaxing for summer

You mean working on a resourcepack due in 2 days, and retexturing the entirety of Chisel and Twilight Forest for the 1.13 update. I got a loooot of stuff to do. It'll come.

**Comment by rockobonaparte** [comment]
Don't worry about it. I was honestly hoping you all actually were relaxing instead of getting bumrushed by the community for not being an instant service. I have plenty of other repairs on the stuff I'm doing before I'm even slowed down by anything I had asked for.

**Comment by Jiinxycat** [comment]
Good luck Drullkus. Also if you have the time you should definitely take some time to relax. You sound like you have a lot on your plate. I understand your stress. It isn't a big deal I was just wondering if the pumpkins had been forgotten under the piles of textures >.<

**Comment by Jiinxycat** [comment]
Closing my issue/question about happy pumpkins. Do try to find at least a day to relax your eyes from tons of pixels. Thanks again for the reply.
