### ISSUE TITLE
[1.11.2] Strange light behaviour with chiseled covers/drawers

### ISSUE THREAD

**Issue by PearlCanopus** [Chisel-Team/Chisel#510]
Chisel: 0.0.13.22 f. MC 1.11.2
Forge: 13.20.1.2386 f. MC 1.11.2
Thermal Dynamics: 2.2.6.13 f. MC 1.11.2
Storage Drawers: 2.4.2.10 f. MC 1.11.2
Optifine: 1.11.2 HD U C3
No shaders in use and medium to low graphics settings.

When using framed drawers/trims from Storage Drawers Mod or pipe covers from Thermal Dynamics with chiseled block textures I get strange light behaviours or shadows on them. This seems to be unrelated to surface lighting. Usually the blocks appear darker.

**Comment by tterrag1098** [comment]
Report this to those mods...and remove Optifine first of all.
