### ISSUE TITLE
(Chisel2 mod) Trapped Chest

### ISSUE THREAD

**Issue by KCFly1OH** [Chisel-Team/Chisel#513]
So, I used to be able to get trapped chests when putting regular chests onto the chisel, I don't know what happened but now I can't chisel the chest into anything. Is there a way to get this option back? I checked the config file but i"m not sure what to do about it. Any help would be appreciated. Thanks

**Comment by tterrag1098** [comment]
The trapped chest requires an extra ingredient to craft, being able to chisel it would be considered a dupe bug.
