### ISSUE TITLE
Missing Texture Netherrack is a chiseling option

### ISSUE THREAD

**Issue by The-Fireplace** [Chisel-Team/Chisel#515]
![2017-08-10_15 11 18](https://user-images.githubusercontent.com/5914284/29190060-5d8fa956-7dde-11e7-81a6-9a3078acc936.png)
Chisel MC1.12-0.0.13.15
Forge 14.21.1.2443

[fml-client-latest.log](http://paste.ubuntu.com/25285607/)

**Comment by tterrag1098** [comment]
What ID/meta is that? It's not added by Chisel...

**Comment by The-Fireplace** [comment]
Vanilla netherrack, meta 32767, which if I recall correctly, is OreDictionary.WILDCARD_VALUE.

**Comment by tterrag1098** [comment]
Some other mod must be adding that, it is not present in my dev environment.

![](https://i.imgur.com/RVTwXsl.png)
