### ISSUE TITLE
During Chisling Block Dupe bug

### ISSUE THREAD

**Issue by LunarW15** [Chisel-Team/Chisel#516]
https://www.youtube.com/watch?v=eBS04a0TLmA
1. Use the chisel until durability almost reaches zero
2. Then put blocks in chisel's GUI and use the chisel.
3. when the chisel item get destroyed, the block that contained by chisel will be dropped without being consumed.

**Comment by tterrag1098** [comment]
Please test on latest build: http://ci.tterrag.com/job/Chisel/job/1.10-dev/31/

**Comment by dhudd3** [comment]
just a note the durability only needs to be 1 lower then the amount of blocks being used so its broken during chiseling you can dupe 63 blocks this way (tested using 0.13.16)

**Comment by raphydaphy** [comment]
This still happens on 0.0.14.18 for 1.12.2.
