### ISSUE TITLE
[1.12] iChisel crash

### ISSUE THREAD

**Issue by StenSipma** [Chisel-Team/Chisel#517]
There seems to be a problem with the iChisel. The last few blocks I tried to chisel resulted in a crash.

[Crash Report](https://gist.github.com/StenSipma/23c08fcae04ca3bdb3d86fb75f959fad) 
There seems to be a problem in the GUI.

If more information is needed, I would be happy to provide (if possible).

**Comment by tterrag1098** [comment]
Duplicates #514
