### ISSUE TITLE
[1.12] crash when looking at chiseled block

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#518]
Version 0.0.13.16 causes a crash ([log](https://pastebin.com/APWRL0mH)) when looking at a chiseled block (perhaps related to The One Probe?). Reverting to 0.0.13.15 fixes this. It might be in ctm though?

**Comment by MokahTGS** [comment]
https://pastebin.com/JKhTZ5mB

This is our log.  The blocks in question are in a storage crate and we don't crash when looking at the chiseled blocks placed in the world.

**Comment by MokahTGS** [comment]
Well reverting to .15 with the newest version of CTM gives us this:

https://pastebin.com/QGuqUnpj

**Comment by tterrag1098** [comment]
Fixed via Chisel-Team/ConnectedTexturesMod@ac486f77639592bad953bc49ce1d19dbccee4657
