### ISSUE TITLE
1.12.1 - Crash on Start

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#519]
https://gist.github.com/P3rf3ctXZer0/05a640202551cd235932f79db13207aa

**Comment by tterrag1098** [comment]
This looks to be caused by FlatColoredBlocks, there's nothing about chisel in the crash.

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 well removing chisel made it work so that is why I posted this here. Well looks you and the Flatblocks Dev will need to have some cross mod chat.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/AlgorithmX2/FlatColoredBlocks/issues/49

**Comment by AlgorithmX2** [comment]
The issue reported in this crash appears to be the failure of FCB to load its own textures, I cannot explain why the presense of chisel breaks this however.

Also, following me preventing the missing texture crash ( by returning missno texture ), my instance crashed later when TiC was loading, upon removing chisel, that crash resolved itself.

> java.lang.NullPointerException: The validated object is null
> 	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
> 	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
> 	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
> 	at slimeknights.tconstruct.tools.ToolClientEvents.onModelBake(ToolClientEvents.java:88)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_326_ToolClientEvents_onModelBake_ModelBakeEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
> 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 

I'm not sure whats going on here @tterrag1098 but it seems centered around chisel.
