### ISSUE TITLE
no craft-chisel for End stone?

### ISSUE THREAD

**Issue by Bogdan-G** [Chisel-Team/Chisel#52]
Hello. Version: 2.9.3.9 (release folder)
MC 1.7.10; Forge 1517; Opti, FC, etc
Vanilla End stone not add GUI-chisel:
![image](http://imgur.com/cbSixS3.png)
but chiseled end stone can edit:
![image](http://imgur.com/1QKyFJh.png)

although the texture of the end stone have been added 3 months ago:
https://github.com/Chisel-Team/Chisel/commit/c1389d9de02be36e362cb733e79a40c189fcec2a https://github.com/Chisel-Team/Chisel/commit/04aae7f5f56790eac5a28df1865c3a7d74d9dd26

It is planned for the future or a bug?

<hr>

I also noticed that the game can not find the file:
 [Client thread/ERROR]: Using missing texture, unable to load chisel:textures/blocks/endstone/EnderFrame.png, java.io.FileNotFoundException

Files EnderFrame-N-DDD.png/EnderFrame-N.png present, and without numbering no))

<hr>

debug-info:
 [Client thread/DEBUG] [FML/]: Unable to lookup chisel:cobblestoneWall for public static team.chisel.block.BlockCarvableWall team.chisel.init.ChiselBlocks.cobblestoneWall. This means the object wasn't registered. It's likely just mod options.
-//-  chisel:obsidian2 -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.obsidian2.
-//- chisel:voidstonerunic for public static team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.voidstonerunic. 
-//- chisel:circuits -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.circuits. 
-//- chisel:arcane -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.arcane.
-//- chisel:thaumium -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.thaumium.
-//- chisel:tallow -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.tallow.
-//- chisel:bloodRune -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.bloodRune.
-//- chisel:bloodBrick -//- team.chisel.block.BlockCarvable team.chisel.init.ChiselBlocks.bloodBrick.

bug reg?

**Comment by Drullkus** [comment]
Issue already fixed a few weeks ago, is available in the 3.0 dev branch.

**Comment by tterrag1098** [comment]
That's not fixed

**Comment by Drullkus** [comment]
![screen shot 2015-10-30 at 2 00 38 pm](https://cloud.githubusercontent.com/assets/5010174/10857975/b1f0b394-7f0e-11e5-95bb-0309295345a8.png)

**Comment by tterrag1098** [comment]
NOT. RELEASED.
