### ISSUE TITLE
1.12.1 (crash in world looking around)

### ISSUE THREAD

**Issue by SDUBZ** [Chisel-Team/Chisel#520]
Forge:1.12.1-2456
Chisel:1.12.1-0.0.13.16

Crash report:
[crash-2017-08-16_23.37.35-client.txt](https://github.com/Chisel-Team/Chisel/files/1228369/crash-2017-08-16_23.37.35-client.txt)

**Comment by tterrag1098** [comment]
Update CTM

**Comment by brisingraerowing** [comment]
EDIT: Nevermind. I somehow forgot to load the new Chisel version into my instance when I downloaded it earlier today.

**Comment by tterrag1098** [comment]
Your crash is different, your chisel version is outdated.

**Comment by brisingraerowing** [comment]
I literally just noticed that. And I had downloaded it earlier too...

**Comment by tterrag1098** [comment]
The update *was* released today.

**Comment by brisingraerowing** [comment]
I know that. I had downloaded it about an hour after it was released, but forgot to install it into my instance.
