### ISSUE TITLE
crash after a while playing but not so sure if this is connected to chisel

### ISSUE THREAD

**Issue by JasonKillsUs** [Chisel-Team/Chisel#521]
oh god why i have to live with "codechicken.lib"
MC 1.12.1_Forge_2456, Chisel-MC1.12-0.0.13.16, CTM-MC1.12-0.2.2.6

"https://pastebin.com/mQV2pzUC"

**Comment by drakray** [comment]
got [something very simillar](https://pastebin.com/H0EtKZba) while looking at Oak Wood usage in JEI

EDIT:
MC 1.11.2
Forge 1.11.2-2454
Chisel 0.0.13.23
CTM 0.2.2.11

**Comment by fusionmc-evilscoop** [comment]
same in mc 1.10
forge 2316
chisel 13.30
ctm 2.2.23

**Comment by Seth0067** [comment]
same here for 1.12
[paste crash](https://pastebin.com/y0dk1HrD)

**Comment by tterrag1098** [comment]
Duplicate of #518
