### ISSUE TITLE
Render crash on world join

### ISSUE THREAD

**Issue by OrdinatorStouff** [Chisel-Team/Chisel#524]
When updating to Chisel-MC1.12-0.0.13.16.jar for ATC server/pack on Forge 2456 1.12.1 -- I created a brand-new fresh SSP world, world rendered for a split second then client crashed with NoSuchMethodError with getRenderContext. Using Chisel-MC1.12-0.0.13.15.jar instead world loads fine and has no issues.

https://pastebin.com/FyQgPmVC

**Comment by miiichael** [comment]
Yeah, I'm seeing this too after I updated my modpack. forge-1.11.2-13.20.1.2454, Chisel - MC1.11.2-0.0.13.23. Crashes went away when I downgraded back to .22. The game also crashes sufficiently awkwardly (music still plays, but rendering is toast) to require killing manually.

https://pastebin.com/vr7jzEaP

**Comment by tterrag1098** [comment]
Update CTM
