### ISSUE TITLE
[1.12.1][0.0.13.16] MC crashes on world load

### ISSUE THREAD

**Issue by tony8128** [Chisel-Team/Chisel#526]
No matter if it is an old world or a newly created one, Minecraft screen turns grayish-cyan after world load and then crashes.

I'm playing FTB Unstable v2.0.0 modpack, with CTM 0.2.1.5 installed. Not sure if it is outdated or not.

Crash log: http://paste.feed-the-beast.com/view/ec90454c

**Comment by Drullkus** [comment]
CTM is outdated, update

https://minecraft.curseforge.com/projects/ctm/files
