### ISSUE TITLE
Minecraft 1.12.1 random crash

### ISSUE THREAD

**Issue by Realever** [Chisel-Team/Chisel#527]
Hi,
my game client crash random on the server.here are the crash reports: https://pastebin.com/bUD0w5mk and https://pastebin.com/2U397ekA

**Comment by jhollowe** [comment]
I believe this is the same problem I have. I have a problem when I search with JEI (it happened when I searched "s" while typing "seed", but I think the search term is not the issue). mezz told me to report the issue for Chisel (https://github.com/mezz/JustEnoughItems/issues/952). 
https://puu.sh/x7xhH.txt

**Comment by Realever** [comment]
yes my game crash too when i search in jei

**Comment by tterrag1098** [comment]
Duplicate / caused by #523
