### ISSUE TITLE
MC 1.12.1 Extreme Request - Chisel Should fail on load if CTM is not present to warn users like a normal mod!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#528]
I just wasted 3 fucking hours because your mod still tried launching without CTM! I didn't realize I had forgot CTM and was trying to fix a crash as seen here.

https://gist.github.com/P3rf3ctXZer0/547b66facce908b72d024c49fb0eb12b

please make sure to deny mod initialization in the future if users forget to add CTM.

https://github.com/Glitchfiend/BiomesOPlenty/issues/1097

I am so pissed right now.

**Comment by Drullkus** [comment]
I'm not even sure how your game launched without CTM. If you attempt to launch Chisel without CTM, the launch already catches itself with this screen.

<img width="880" alt="screen shot 2017-08-20 at 1 48 13 am" src="https://user-images.githubusercontent.com/5010174/29493398-a8598e4e-8549-11e7-8c06-6b115b51a4e2.png">

**Comment by P3rf3ctXZer0** [comment]
Could be a windows 10 bug I don't have Linux or Mac! At any rate it is strange.

**Comment by miiichael** [comment]
Nope, I can confirm that chisel + biomesoplenty - ctm = weird uninformative crash.

See [crash-2017-08-20_23.00.43-client.txt](https://github.com/Chisel-Team/Chisel/files/1237163/crash-2017-08-20_23.00.43-client.txt).

Having just noticed #480, I'm guessing this is a case of Chisel not throwing MissingModsException soon enough to prevent BoP falling on its face.

**Comment by AlgorithmX2** [comment]
Additional Crash without CTM involving C&B
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/302

**Comment by tterrag1098** [comment]
This is a long standing forge bug that I have mentioned to lex, but fell on deaf ears. A mod erroring can cause an exception to be swallowed, and other mods will have their registry events called without preInit having been called, causing strange errors like this. The only way to know the original crash is to remove other mods, which is obviously not practical.

[This bit of code](https://gist.github.com/pau101/9f2284bf99b8c19352472b8156afc35e) can cause these swallowed exceptions to be printed.

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 Lex and his team don't want to deviate from core vanilla code. Trust me I have asked them repeatedly for things that help with modders and moddies. This includes increasing forges ID pools Manage Java a bit more differently Etc. So if he hasn't budged yet he never will.

**Comment by ogurets** [comment]
But what should Optifine users do? CTM is said to be implemented inside Optifine and will conflict with CTM mod.
