### ISSUE TITLE
Prospective Mod Blocks to be chiseled

### ISSUE THREAD

**Issue by Drullkus** [Chisel-Team/Chisel#53]
- Generic
  - Basalt
  - Cobalt
- Botania - Tristaric
  - Elementium - 
  - Manasteel
  - Terrasteel
  - Livingrock
  - Livingstone
  - Shimmerwood - Botania:shimmerwoodPlanks
  - Shimmerrock - Botania:shimmerrock
  - Bifrost - Botania:bifrostPerm
  - Alfglass - Botania:elfGlass
  - Managlass - Botania:manaGlass
- TwilightForest
  - TFTowerwood
  - TFUnderbrick
  - Castlebrick things

**Comment by VermillionX** [comment]
Might want to consider adding Railcraft's building blocks to the list (Sandy/Bloodstained/Frostbound/Quarried/Abyssal Stone). They could really do with some extra options.

**Comment by Drullkus** [comment]
Outdated
