### ISSUE TITLE
Client Crash - Tesselating Block Model (1.10.2, Chisel 0.0.13.30)

### ISSUE THREAD

**Issue by sab0tic** [Chisel-Team/Chisel#531]
This error was happening last night to a friend, on a different block. I updated Chisel from .29 to .30 on the server, and he longer had this error happen. However, I am now receiving the error consistently when joining the server.

I avoid using clientside mods that can cause these sorts of issues (such as Optifine), but it's possible I do have a few client mods that could be mucking things up and causing this error to happen. I'm happy to try disabling any recommended mods or otherwise to see if I can get around this.

[crash-2017-08-27_18.15.25-client.txt](https://github.com/Chisel-Team/Chisel/files/1254754/crash-2017-08-27_18.15.25-client.txt)

**Comment by tterrag1098** [comment]
Update CTM
