### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zuruckt** [Chisel-Team/Chisel#533]
Crash whenever i log in the server, alredy deleted block but crashed again.

Minecraft Version: 1.10.2
Chisel Version : Chisel-MC1.10.2-0.0.13.30
While on Server with other mods:
https://hastebin.com/qizinorumi.txt

Singleplayer with no other mods:
https://hastebin.com/avuvipibex.txt

**Comment by tterrag1098** [comment]
Update CTM
