### ISSUE TITLE
Updating from 1.10.2 to 1.12 causes some blocks to break

### ISSUE THREAD

**Issue by kirokadura** [Chisel-Team/Chisel#535]
Hello! I've recently update all my mods from 1.10.2 to 1.12, but I have encountered a issue. When I opened the map I was working on in 1.10, some especific blocks disappeared, as can be seen on the pictures I linked in this C&B thread:

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/303

Some of the blocks I noticed were gone were: a Sandstone variation(raw?), Raw Basalt, Raw Marble, Cobblestone Brick and some planks variations. Other stuff like Brownstone was left intact. It affected both C&B blocks and full Chisel blocks, so I am not sure if C&B is responsible.

Does it have something to do with ID changes between the 1.10.2 version and the latest 1.12 one? As I said in the other thread, all blocks are invisible and if I try walking on them I get stuck, boucing up and down kinda twitchy. Exiting and entering the save causes the blocks to disappear, but leave behind the a dark spot.

Versions I was using before updating:
CTM - CTM-MC1.10.2-0.1.1.16
Chisel - Chisel-MC1.10.2-0.0.11.26

Versions I am using now:
CTM - CTM-MC1.12-0.2.2.7
Chisel - Chisel-MC1.12-0.0.13.16

It's a very big project, so rebuilding so many areas will delay progress a lot. I really hope I'm doing something wrong and there's a way to fix this.

If it has nothing to do with Chisel, sorry for wasting your time, but any help is appreciated. Thanks in advance!

**Comment by tterrag1098** [comment]
In 1.12 all IDs had to be lowercased, this caused some to break. We didn't deem it worthwhile to go through every single change and write porting code. The best you can do is use something like mIDas gold to remap the IDs for you.
