### ISSUE TITLE
Crash in my modpack when installing the new Chisel-MC1.10.2-0.0.13.30

### ISSUE THREAD

**Issue by Williamhb** [Chisel-Team/Chisel#536]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.10.2-1.9.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.2.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  HFTransformer (Harvest-Festival-1.10.2-0.6.0-218.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.55-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 8/30/17 10:53 AM
Description: Tesselating block model

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ICTMTexture;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:164)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: team.chisel.ctm.api.util.RenderContextList.getRenderContext(Lteam/chisel/ctm/api/texture/ICTMTexture;)Lteam/chisel/ctm/api/texture/ITextureContext;
	at team.chisel.client.render.ModelChiselBlock.addAllQuads(ModelChiselBlock.java:98)
	at team.chisel.client.render.ModelChiselBlock.createModel(ModelChiselBlock.java:83)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.lambda$getQuads$1(AbstractCTMBakedModel.java:164)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$$Lambda$1328/1101199681.call(Unknown Source)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4739)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:164)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)

-- Block model being tesselated --
Details:
	Block: chisel:marbleextra[variation=7]
	Block location: World: (-520,31,-606), Chunk: (at 8,1,2 in -33,-38; contains blocks -528,0,-608 to -513,255,-593), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)

-- Block being tesselated --
Details:
	Block type: ID #1135 (tile.chisel.marbleextra // team.chisel.common.block.BlockCarvable)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (-520,31,-606), Chunk: (at 8,1,2 in -33,-38; contains blocks -528,0,-608 to -513,255,-593), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)

-- Block being tesselated --
Details:
	Block type: ID #1135 (tile.chisel.marbleextra // team.chisel.common.block.BlockCarvable)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (-520,31,-606), Chunk: (at 8,1,2 in -33,-38; contains blocks -528,0,-608 to -513,255,-593), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
Stacktrace:
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:61)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:199)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_178505_b(ChunkRenderDispatcher.java:171)
	at net.minecraft.client.renderer.RenderGlobal.func_174970_a(RenderGlobal.java:952)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1286)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['w1liam'/171, l='MpServer', x=-524.48, y=17.00, z=-604.87]]
	Chunk stats: MultiplayerChunkCache: 266, 266
	Level seed: 0
	Level generator: ID 09 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-35,64,-40), Chunk: (at 13,4,8 in -3,-3; contains blocks -48,0,-48 to -33,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1415092 game time, 892981 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 17 total; [EntityGaiaPropFlowerCyan['Cyan Flower'/418, l='MpServer', x=-554.50, y=66.00, z=-612.50], EntityGaiaPropFlowerCyan['Cyan Flower'/419, l='MpServer', x=-537.50, y=66.00, z=-631.50], EntityGaiaPropFlowerCyan['Cyan Flower'/420, l='MpServer', x=-536.50, y=67.00, z=-631.50], EntityPainting['Painting'/484, l='MpServer', x=-482.97, y=70.50, z=-623.50], EntityGaiaPropFlowerCyan['Cyan Flower'/485, l='MpServer', x=-495.50, y=65.00, z=-623.50], EntityItemBuoy['item.item.yurt_large'/486, l='MpServer', x=-543.49, y=63.00, z=-570.88], EntityPlayerSP['w1liam'/171, l='MpServer', x=-524.48, y=17.00, z=-604.87], EntityGaiaPropFlowerCyan['Cyan Flower'/464, l='MpServer', x=-524.50, y=66.00, z=-608.50], EntityGaiaPropFlowerCyan['Cyan Flower'/432, l='MpServer', x=-525.50, y=67.00, z=-628.50], EntityGaiaPropFlowerCyan['Cyan Flower'/433, l='MpServer', x=-526.50, y=67.00, z=-629.50], EntityGaiaPropFlowerCyan['Cyan Flower'/434, l='MpServer', x=-514.50, y=67.00, z=-638.50], EntityNPCVillager['Johan'/435, l='MpServer', x=-524.54, y=67.00, z=-632.57], EntityGaiaPropFlowerCyan['Cyan Flower'/437, l='MpServer', x=-541.50, y=66.00, z=-615.50], EntityPainting['Painting'/484, l='MpServer', x=-482.97, y=70.50, z=-623.50], EntityGaiaPropFlowerCyan['Cyan Flower'/438, l='MpServer', x=-537.50, y=66.00, z=-609.50], EntityGaiaPropFlowerCyan['Cyan Flower'/476, l='MpServer', x=-503.50, y=67.00, z=-618.50], EntityGaiaPropFlowerCyan['Cyan Flower'/477, l='MpServer', x=-508.50, y=67.00, z=-619.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 323017728 bytes (308 MB) / 3082747904 bytes (2939 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 18 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 89 mods loaded, 89 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{2.2.2} [AppleCore] (AppleCore-mc1.10.2-2.2.2.jar) 
	UCHIJAAAA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.10.2-1.0.7.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJAAAA	thedragonlib{1.10.2-1.3.1} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.1.jar) 
	UCHIJAAAA	armorplus{1.10.2-8.7.1.2} [ArmorPlus] (armorplus-1.10.2-8.7.1.2.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	AromaBackup{2.0.0.0.b62} [AromaBackup] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.73} [Natura] (natura-1.10.2-4.1.0.73.jar) 
	UCHIJAAAA	betterwithmods{0.14.23 Beta} [Better With Mods] (Better With Mods-0.14.25-1.10.2.jar) 
	UCHIJAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2290} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar) 
	UCHIJAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJAAAA	ChestTransporter{2.5.18} [Chest Transporter] (ChestTransporter-1.10.2-2.5.18.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.13.30} [Chisel] (Chisel-MC1.10.2-0.0.13.30.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJAAAA	ctm{MC1.10.2-0.2.1.21} [CTM] (CTM-MC1.10.2-0.2.1.21.jar) 
	UCHIJAAAA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJAAAA	defaultworldgenerator-port{1.9.4-0.4} [Default World Generator] (DefaultWorldGenerator-port-1.9.4-0.4.jar) 
	UCHIJAAAA	dsurround{3.4.6.2} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.6.2.jar) 
	UCHIJAAAA	presets{3.4.6.2} [§3Presets!] (DynamicSurroundings-1.10.2-3.4.6.2.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.5.1.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forestry{5.2.17.383} [Forestry] (forestry_1.10.2-5.2.17.383.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UCHIJAAAA	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHIJAAAA	grimoireofgaia{1.5.6} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.6.jar) 
	UCHIJAAAA	gbook{1.7.3} [Guidebook] (Guidebook-1.10.2-1.7.3.jar) 
	UCHIJAAAA	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.10.2-1.9.jar) 
	UCHIJAAAA	harvestfestival{0.6.0} [Harvest Festival] (Harvest-Festival-1.10.2-0.6.0-218.jar) 
	UCHIJAAAA	Waila{1.8.17-B31_1.10.2} [Waila] (Hwyla-1.8.17-B31_1.10.2.jar) 
	UCHIJAAAA	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.1.3.jar) 
	UCHIJAAAA	InfernalMobs{1.7.1} [Infernal Mobs] (InfernalMobs-1.10.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.3.jar) 
	UCHIJAAAA	initialinventory{1.0.1} [InitialInventory] (InitialInventory-1.0.1.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.31} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.31.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UCHIJAAAA	jepb{1.1} [Just Enough Pattern Banners] (jepb-1.10.2-1.1.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.0b1} [JourneyMap] (journeymap-1.10.2-5.5.0b1.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	nsa{1.0.0} [No Sleeping Allowed] (MC1.10.2 NoSleepingAllowed1.0.1.jar) 
	UCHIJAAAA	minecolonies{@VERSION@} [MineColonies] (minecolonies-universal-1.10.2-0.8.3384.jar) 
	UCHIJAAAA	mtrm{1.2.1.26} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar) 
	UCHIJAAAA	modtweaker{2.0.13} [Mod Tweaker] (ModTweaker2-2.0.13.jar) 
	UCHIJAAAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	UCHIJAAAA	morebees{1.10.2-1.4.1.1} [More Bees] (morebees-1.10.2-1.4.1.1.jar) 
	UCHIJAAAA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJAAAA	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UCHIJAAAA	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHIJAAAA	RTG{4.2.0.0-snapshot-5} [Realistic Terrain Generation] (RTG-1.10.2-4.2.0.0-snapshot-5.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.10.2-1.3.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJAAAA	survivalistlighting{1.10.2-1.1} [Survivalist Lighting] (Survivalist Lighting-1.10.2-1.1.jar) 
	UCHIJAAAA	survivalist{1.10.1} [Survivalist] (Survivalist-1.10.2-1.10.1.jar) 
	UCHIJAAAA	ToughAsNails{1.1.1.55} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.55-universal.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.10} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.10.jar) 
	UCHIJAAAA	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	UCHIJAAAA	waterstrainer{1.4.2} [Water Strainer] (WaterStrainer-1.9.4-1.4.2.jar) 
	UCHIJAAAA	xnet{1.3.2} [XNet] (xnet-1.3.2.jar) 
	UCHIJAAAA	harvesttweaks{1.10.2-0.1.2.DEV.9651204} [Harvest Tweaks] (HarvestTweaks-1.10.2-0.1.2.jar) 
	UCHIJAAAA	hungeroverhaul{1.10.2-1.1.0.jenkins118} [Hunger Overhaul] (HungerOverhaul-1.10.2-1.1.0.jenkins118.jar) 
	Loaded coremods (and transformers): 
CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.10.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
HFTransformer (Harvest-Festival-1.10.2-0.6.0-218.jar)
  joshie.harvest.asm.HFTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.55-universal.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)
		- tconstruct (Enabled/Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	Launched Version: forge-12.18.3.2316
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by tterrag1098** [comment]
Update CTM.

Please check other issues before reporting.
