### ISSUE TITLE
Missing bookshelf textures in 1.11.2

### ISSUE THREAD

**Issue by TynotWolfDragon** [Chisel-Team/Chisel#539]
OK, so I can rule out interference, because chisel is the only mod installed. its just straight up missing the textures on a fresh install.
![2017-09-06_08 17 52](https://user-images.githubusercontent.com/16494408/30111610-5b2dea5c-92dc-11e7-9cd8-55095089f661.png)

**Comment by ghost** [comment]
duplicate of #523

**Comment by tterrag1098** [comment]
Duplicate of #523
