### ISSUE TITLE
[1.10.2] Server crash on load

### ISSUE THREAD

**Issue by Techokami** [Chisel-Team/Chisel#541]
Minecraft: 1.10.2
Forge: 12.18.3.2422
Chisel: 0.0.14.32

Chisel is looking for a function that only exists on client-side Minecraft. As such, the server explodes.
[Crashlog is here.](https://pastebin.com/PcdMZ5Q1)

**Comment by tterrag1098** [comment]
There was an update already to address this

**Comment by Techokami** [comment]
Is the file up on Curse yet? So I can update the modpack that goes with the server.

**Comment by tterrag1098** [comment]
[Yes](https://minecraft.curseforge.com/projects/chisel/files/2479325)

**Comment by Techokami** [comment]
Wow what the hell is with Curse then? The client says that the latest is still 0.0.14.32 and won't let me get the updated file.

**Comment by lol768** [comment]
Maybe that should be marked release instead of alpha to be visible in the client?

**Comment by tterrag1098** [comment]
All previous alphas have been available, not sure why this one would be any different. It's marked as it is for a reason.

**Comment by Techokami** [comment]
No, Alphas can still be visible to the client. I think Curse is just drunk or something.

**Comment by lol768** [comment]
Ah, fair enough. 🤞 they can resync it for you
