### ISSUE TITLE
1.12 - 0.14.18 Marble and Limestone missing

### ISSUE THREAD

**Issue by feckyeslife** [Chisel-Team/Chisel#542]
Testing out the new alpha release (0.0.14.18 in MC 1.12) and I noticed that while the variations of Marble and Limestone are still present, the raw/plain versions that generate in the world are no longer present. Is this intentional? I'm happy to grab a different mod to put them into the game if it was a decision due to duplication in a common mod, but it seemed odd that the chiseled versions still exist but no plain ones. 
Thanks!

**Comment by tterrag1098** [comment]
They definitely should still exist...listed as the "Raw" variant. Can you double check?

**Comment by feckyeslife** [comment]
Okay, I am seeing that now. I lost my storage drawer full of the original versions and didn't scan the whole list of variants properly. 
Am I correct to assume that previously generated chunks will now have air or will those auto-correct to the new "raw" variant? (Apologies for all the q's)

**Comment by tterrag1098** [comment]
Previously generated? Generated when? The worldgen has used the raw variant for a good while now.

**Comment by feckyeslife** [comment]
Worldgen is what I meant. I went from 0.13.15 to the new 0.14.18 so maybe I missed something inbetween. Thank you for your help.
