### ISSUE TITLE
1.12 Recipes missing for several blocks / Bookshelves don't have an inventory image

### ISSUE THREAD

**Issue by dragon3025** [Chisel-Team/Chisel#548]
Several blocks don't have a recipe for an original block to make chisel blocks. I think some or all of these are originating from other mods, but I tried using a block from the other mods, and it doesn't work: for example, using Thermal Foundations Block of Aluminum in the Chisel GUI won't give any options for it.

These are the blocks without an original block recipe:

Block of Aluminum
Block of Bronze
Block of Basalt
Block of Coal Coke
Block of Copper
Block of Electrum
Block of Invar
Block of Lead
Block of Nickel
Block of Platinum
Block of Silver
Block of Steel
Block of Tin
Block of Uranium

EDIT: I also noticed that bookshelves don't have an inventory image.

**Comment by Drullkus** [comment]
@tterrag1098 oh right, you removed the oredict. Q.Q

**Comment by tterrag1098** [comment]
The bookshelf issue will be fixed in an upcoming CTM release. As for the metal blocks, yes we need to add our own recipes now, or add some special code that reads the oredict for those specific variants since I can't imagine converting between those will be a problem.
