### ISSUE TITLE
hi Chisel Team i see dark spots in the block i chisel

### ISSUE THREAD

**Issue by trilexcom** [Chisel-Team/Chisel#550]
hi Chisel Team i see dark spots in the block i chisel

when i chisel a block if their is anything block behind it on the left of the screen shadow goes away, if i chisel a block on the right i dont get a any shadow

i have attached few pictures of the screenshot plus the crashlog

please let me know if its chisel or other mod is causing the problem

i am using modpack called Trilex Pack! 

Forge Version : 2484
Chisel : Chisel-MC1.12-0.0.14.18
ConnectedTexturesMod Version : CTM-MC1.12-0.2.2.7 

Crashlog link : https://pastebin.com/4VvArhHk
Screenshot link : https://imgur.com/a/ltfie

Thanks again

**Comment by tterrag1098** [comment]
Forge bug, has been fixed via https://github.com/MinecraftForge/MinecraftForge/pull/4387

Update forge (you missed it by one build!)

**Comment by trilexcom** [comment]
ah thanks you are awesome tterrage

**Comment by Drullkus** [comment]
Whoa dang that's weird-looking.
