### ISSUE TITLE
Client Crash on Chisel-MC1.10.2-0.0.14.33

### ISSUE THREAD

**Issue by chezpaul** [Chisel-Team/Chisel#551]
Game works fine with Chisel-MC1.10.2-0.0.13.29 but crashes on the client side with Chisel-MC1.10.2-0.0.14.33 and only on login. Client boots fine, server boots fine.

Client crash log is [here](https://pastebin.com/0cD3BgHT)

**Comment by tterrag1098** [comment]
Update CTM
