### ISSUE TITLE
[1.7.10] Chisel causing IC² blocks to be invisible; Mipmap/Optifine irrelevant 

### ISSUE THREAD

**Issue by mount2010** [Chisel-Team/Chisel#552]
Chisel is causing IC² blocks to become see-though. Although I have found solutions that say that reducing Mipmap to 0 works, after attempting the solution the problem still persists. I do not use Optifine, therefore the Multicore Optifine issue is irrelevant to my case.

My friend with the same mods also experiences this issue, therefore it is likely not a problem with my computer.

Nothing in FML-client-latest.log indicates that Chisel isn't doing it's job.

I am on Chisel version 2.9.5.11, downloaded from CurseForge, and IC2 version 2-2.2.823

**Comment by tterrag1098** [comment]
What leads you to believe this is Chisel? Either way, 1.7.10 is no longer receiving updates except for critical bugfixes.
