### ISSUE TITLE
[1.12.2] Crash with Tinkers' Construct

### ISSUE THREAD

**Issue by mmelvin0** [Chisel-Team/Chisel#559]
Using Chisel 0.0.14.18 + Tinkers 2.7.3.30.

[crash report](https://gist.github.com/mmelvin0/10b5428d6e7180b91aa4d6b4a4c6b292)

This occurs immediately + consistently upon starting Minecraft after adding Chisel to the mods directory. I tried removing everything except Chisel, Mantle, and TConstruct and the same crash still occurs.

**Comment by tterrag1098** [comment]
You don't have CTM

**Comment by mmelvin0** [comment]
Sorry about that man, I knew that...

Just more evidence I should not try to do two things at once.
