### ISSUE TITLE
Dark Oak Planks are utter f***ing garbage.

### ISSUE THREAD

**Issue by Cypher121** [Chisel-Team/Chisel#56]
They don't even match the color of real planks!
![2015-11-03_18 30 26](https://cloud.githubusercontent.com/assets/8020624/10928118/9005a182-825a-11e5-8acb-4ddca6c3cebc.png)

**Comment by Drullkus** [comment]
Can agree. Will retexture for 3.0 release along with all other wooden variants.

**Comment by alexbegt** [comment]
Needs more Info, crash log, and a 3 page essay on why this should be changed. LOL I don't even work here why am I saying this. <3

**Comment by Drullkus** [comment]
@alexbegt lol what 3 page essay? I've chiseled an essay on three stone tablets.

**Comment by tehFoxx0rz** [comment]
Acacia planks too...

**Comment by Drullkus** [comment]
@tehFoxx0rz How about all of them :P

**Comment by BBoldt** [comment]
I really like the way @ScottKillen did them for Unity:

https://github.com/CyanideX/Unity/pull/35#issuecomment-103356680

Not a pic of the dark oak there but you get the idea. :P

**Comment by ScottKillen** [comment]
Thanks, @BBoldt ! :grinning:

**Comment by Drullkus** [comment]
Hey @ScottKillen, yes, if you'd permit, we'd love to use your wood textures in chisel :3

**Comment by BBoldt** [comment]
Also while you're at it, check out the chisel item textures for Unity, made by @Yulife.

:smile:

**Comment by ScottKillen** [comment]
I am absolutely fine with that. Thanks for the honor!

**Comment by TheCricket** [comment]
@Cypher121 Well fuck you too then, at least I tried making textures back when it was just me. You could be nice and say hey the dark oak textures need an update I think they could be improved instead of being rude.

**Comment by Cypher121** [comment]
@TheCricket lol, it was a joke between me and @Drullkus in IRC. And they really don't match original colors, do they?

**Comment by TheCricket** [comment]
No they don't but I made them a year ago when I had really bad eyes

**Comment by Drullkus** [comment]
Can confirm with @Cypher121

**Comment by tehFoxx0rz** [comment]
@Drullkus I find the others fine; they're smooth-shaded and matched the vanilla plank colours. I mean, if you guys want to retexture them all that's up to you, but only the acacia and dark oak ones are in need of some reworking imo (and different from the others).

**Comment by Drullkus** [comment]
They're not the quality that I can make them to be.

**Comment by TheCricket** [comment]
because I made them

**Comment by Drullkus** [comment]
I'm talking about all of them, not just the ones you made

**Comment by alexbegt** [comment]
LADY'S LETS NOT FIGHT PLEASE? <3

**Comment by Drullkus** [comment]
I don't want to fight.

**Comment by tterrag1098** [comment]
Dark oak has since been retextured
