### ISSUE TITLE
Crash when using Chisel + Reikas mods  (1.7.10)

### ISSUE THREAD

**Issue by brandyyn** [Chisel-Team/Chisel#561]
crash: https://pastebin.com/ThKnhfpC
modslist: http://prntscr.com/gqt7jj

this was after i updated from v16 to v18 for reikas mods

**Comment by tterrag1098** [comment]
Why report it to us? This crash is clearly caused by Reika's mods. Take it to him.

**Comment by brandyyn** [comment]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1600#event-1270255608

**Comment by tterrag1098** [comment]
I have no reason to believe chisel is doing anything of the sort, as I have no reports of "corrupt worlds" due to chisel worldgen.

**Comment by ReikaKalseki** [comment]
I am throwing the exception, but something is calling world.setBlock() with a null argument during worldgen. What that is I do not know.

**Comment by brandyyn** [comment]
So whats happening? :/

**Comment by tterrag1098** [comment]
1.7.10 is no longer receiving updates except for critical bugfixes. Unless you can prove this is caused by chisel, I am left to believe that it is not.

**Comment by brandyyn** [comment]
Maybe it has some built in compatibility with chisel which is messing something up (IE placing NULL as reika suggested)
