### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#562]
Basalt and Marble of my mod does not recognized by the Chisel mod. How can i make it compatible?

**Comment by ghost** [comment]
oh, i found the wiki, sorrryyy :D

**Comment by tterrag1098** [comment]
The wiki is outdated, please see [IMC.java](https://github.com/Chisel-Team/Chisel/blob/1.10/dev/src/main/java/team/chisel/api/IMC.java#L49-L90)
