### ISSUE TITLE
[1.12] iChisel crash

### ISSUE THREAD

**Issue by LeChuckXIV** [Chisel-Team/Chisel#564]
shift clicking chisel all when on low durability causes game to crash, when returning chisel is destroyed and most items are chiseled.

crash log: https://pastebin.com/tY12GTKu

chisel version: MC1.12-0.0.14.18

**Comment by The-Fireplace** [comment]
I can confirm this.
http://paste.ubuntu.com/25710650/
Minecraft 1.12.2
Chisel MC1.12-0.0.14.18
Forge 14.23.0.2497
Tested in SMP.
