### ISSUE TITLE
Crash On Start.

### ISSUE THREAD

**Issue by ImLunaUwU** [Chisel-Team/Chisel#565]
#### What happens:

When i launched my my OWN modpack it loaded the mods and was nearly done and then the launcher closed. no ¨Sorry, Your minecraft has crashed.¨ message at all

#### What i expected to happen:

A peacefull launch and no crashes.

#### Crash Report:

[Pastebin](https://pastebin.com/tyzBW2Yx)
____
#### Versions:

- CTM: MC1.10.2-0.2.3.26
- Chisel: MC1.10.2-0.0.14.33
- Minecraft: 1.10.2
- Forge: 12.18.3.2488

Need More Info?

**Comment by ImLunaUwU** [comment]
Nothing Yet?

**Comment by tterrag1098** [comment]
This crash is nonsense, the class it's looking for doesn't exist and hasn't since 1.7. Are you sure you didn't leave a 1.7 version of chisel in your mods folder by mistake?

**Comment by ImLunaUwU** [comment]
@tterrag1098 Well, its fun you say it... i found out i forgot to update chisel from 1.7 to 1.10.2 sorry for the inconvenience and me being stupid. xD
