### ISSUE TITLE
1.10.2 Marble and Basalt texture disapears 

### ISSUE THREAD

**Issue by Arsomang** [Chisel-Team/Chisel#569]
Marble and Basalt textures disappears after opening config window in Advanced Generators witch also causes client crash when JEI tries to pull a texture for these materials. Placing one of these materials and breaking them restores texture and prevents crash in JEI. But frustrating trying to remember to do that every time you open the Generators Config window.

**Comment by bdew** [comment]
I've tracked this issue down to me leaving the render layer set to TRANSLUCENT after some GUI stuff in my code. If i change it back to SOLID it fixes the rendering issue in chisel.

It only affects the rendering of the items, the blocks placed in the world are always rendered correctly.

I've released a fix for that for 1.12 and going to release updates for 1.10 and 1.11 too.

That being said you should probably not rely on the render layer being set to anything specific when rendering items, and fix it on your side as well.

Also i didn't see any crashes on any version i tested on (1.10.2/1.11.2/1.12.2) with recent versions of involved mods.

**Comment by Arsomang** [comment]
How do i fix that on my end?

**Comment by bdew** [comment]
@Arsomang i meant "your" as in, chisel code. For end users the updates i posted to bdlib should fix the issue.

**Comment by tterrag1098** [comment]
@bdew the layer should always be *null* outside of block rendering, not SOLID. You've just fixed the problem for our blocks which happen to use the SOLID layer.

**Comment by Arsomang** [comment]
When are you going to release and update to fix this issue?
