### ISSUE TITLE
Null Object Crash [1.12] - [Chisel-MC1.12-0.0.14.18]

### ISSUE THREAD

**Issue by ggtechyguy** [Chisel-Team/Chisel#572]
I've tested this, and it is Chisel causing this error, without it, the modpack I'm working on loads no problem.    Adding it into the modpack produces the following error:

The game crashed whilst initializing game
Error: java.lang.NullPointerException: The validated object is null

Now I realize this is an Alpha Release for 1.12, and I'm not expecting it to be 100%, which is why I am reporting the issue, so it can be looked into.

**Comment by tterrag1098** [comment]
Do you have a full crash log?

**Comment by ggtechyguy** [comment]
[crash-2017-10-08_18.51.37-client.txt](https://github.com/Chisel-Team/Chisel/files/1369147/crash-2017-10-08_18.51.37-client.txt)

There ya go.

**Comment by tterrag1098** [comment]
Update/install CTM, it is required.
