### ISSUE TITLE
Chisel makes issues with bloodmagic

### ISSUE THREAD

**Issue by MIGA2001** [Chisel-Team/Chisel#574]
Chisel makes issues with bloodmagic. Pleasse help me(
[crash-2017-10-10_17.54.42-client.txt](https://github.com/Chisel-Team/Chisel/files/1372147/crash-2017-10-10_17.54.42-client.txt)

**Comment by Drullkus** [comment]
There's no involvement from Chisel here, please report to [WayofTime/BloodMagic](https://github.com/WayofTime/BloodMagic)
