### ISSUE TITLE
Disabling Mossy Bricks chiseling config option does't work

### ISSUE THREAD

**Issue by davqvist** [Chisel-Team/Chisel#575]
MC 1.12.1 (will update to 1.12.2 in the next days)
Forge 2485
Chosel 0.0.14.18

B:allowBrickToMossyInChisel=false
doesn't seem to have an effect, I can still chisel into Mossy Bricks

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-Team/Chisel/commit/f15de1c741c6b51cb1c46e1d0f606d7183b714d8
