### ISSUE TITLE
[1.12.2] can't chisel some blocks like copper

### ISSUE THREAD

**Issue by TheSnowyChickens** [Chisel-Team/Chisel#576]
Hello,

in the picture you can see, the copper blocks from your mod, but I can't chisel the normal copper block, from Mekanism, into your blocks.
I installed both mods without config changes.

![2017-10-15_14 24 53](https://user-images.githubusercontent.com/29357962/31584760-a5225476-b1b4-11e7-8c83-6cea440bc72b.png)

Now the question, am I just stupid or it doesn't work?

MC : 1.12.2
Forge : 2512
Chisel :  0.0.14.18
CTM : 0.2.3.9

EDIT : Same happend with all Thermal blocks into chisel block, JEI show me now recipes.
![2017-10-15_14 48 01](https://user-images.githubusercontent.com/29357962/31584899-e28d8c56-b1b7-11e7-835b-619cb82e23cf.png)

**Comment by drakray** [comment]
see changelog from https://minecraft.curseforge.com/projects/chisel/files/2479232

**Comment by tterrag1098** [comment]
This is already resolved by https://github.com/Chisel-Team/Chisel/commit/9d403d8cf01b7410dc7ad0f1ab09857621b24046

**Comment by drakray** [comment]
:O , cant wait for the next release then :D (no more need for CT workaround lol)
