### ISSUE TITLE
[1.10.2]Re-Add Chisel Mode in GUI

### ISSUE THREAD

**Issue by Cmoor** [Chisel-Team/Chisel#578]
Hey there,
So my suggestion is to re-add the chisel modes within the GUI. It seemed to be a lot easier. Or maybe even an enhancement to shift and scroll while holding the Diamond Chisel in your hotbar to change modes.

I'm being a bit picky with this but would it be possible to add a higher radius to chisel as well?
Example: 5x5

Thanks for taking the time to read this, hope to hear back soon!

**Comment by tterrag1098** [comment]
I have an almost finished port of this feature, I just need to clean up the GUI stuff.

https://github.com/Chisel-Team/Chisel/tree/1.10/chisel_modes

**Comment by Cmoor** [comment]
Ooo I can't wait to try it out! Thank you for the speedy reply
