### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Leigionairciam** [Chisel-Team/Chisel#58]
Everytime I try and start the game with forge on 1.8 it just crashes

**Comment by Choonster** [comment]
The 1.8 version is still in early development, but if you want the problem fixed you should post the crash report.

**Comment by Drullkus** [comment]
Crashlog pls

**Comment by tterrag1098** [comment]
This is undoubtedly fixed (I have tested the new code on both client and server and it launches fine)
