### ISSUE TITLE
1.12.2 iron bars item (WIP!)

### ISSUE THREAD

**Issue by CollapsedMondas** [Chisel-Team/Chisel#583]
ok, i changed ctm mod with most new version and bookshelf problem has solved.
but some iron bars items has no texture like this.
![2017-11-08_15 07 34](https://user-images.githubusercontent.com/26104230/32534012-0ceff0be-c497-11e7-8b84-d918e4c24c35.png)

those item's name is modern fence / thick cage / pointy spikes / thin grid / ornate / straight / bounded.

what shall i do?

**Comment by tterrag1098** [comment]
They very clearly say WIP in the tooltip, no? So they are not finished, not a bug.
