### ISSUE TITLE
CraftTweaker Support for 1.12.2

### ISSUE THREAD

**Issue by KAfable** [Chisel-Team/Chisel#586]
Hi, just wondering are there plans for CraftTweaker support for 1.12.2? There are some chisel blocks I want to use with Modular Machinery as part of multiblocks, but wanted to make it so that they aren't chiselable and need to be crafted an alternate way.

**Chisel**: 0.0.14.18
**Minecraft**: 1.12.2

Thanks.

**Comment by tterrag1098** [comment]
I've never done much with CraftTweaker, @jaredlll08 are you planning to put Chisel support in ModTweaker, or should I tackle this?

**Comment by KorDum** [comment]
+1

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/ModTweaker/commit/b9104b43b4b95d25c90532305dd3ba95442b9b1d
