### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [Chisel-Team/Chisel#591]
Chisel - MC1.12-0.1.0.20
MC/F 1.12/2443

Couldn't get to full load, got dumped back to main titles with the 'unexpected error occurred' message

https://pastebin.com/A2kegBbj

**Comment by tterrag1098** [comment]
Seems like an issue with AbyssalCraft to me?

**Comment by Nexusdog** [comment]
Hmm, conflict I guess - rolling back chisel to previous version resolved issue.

**Comment by TimGoll** [comment]
same issue. Chisel alpha is still working

**Comment by warplord** [comment]
https://pastebin.com/adpNqWCe

Same issue here, after updating Chisel to the new version

**Comment by trogarus** [comment]
Same thing, so not posting logs as it's with abyssalcraft as well. Started only after new update and a rollback didn't fix it for me. I had to actually remove chisel, for now, until this is fixed as my minecraft wouldn't even start to load a world with the present chisel version. Only rolled back to the previous version and it still crashed the world. Deleted configs for chisel on that version, still crashed, hence why I removed the mod for now. Will check abyssalcraft issue tracker and make sure this is cross posted there if not already.

**Comment by TimGoll** [comment]
@trogarus you have to roll back 3 versions to the alpha version. All 3 betas from yesterday have the same bug

**Comment by trogarus** [comment]
Thanks @TimGoll . It's already tracking over there so mentioned this thread with additional logs if they need them to sort the issue.

**Comment by Drullkus** [comment]
I moved your pastes to pastebin.com, can you guys PLEASE not paste the whole thing here? Just paste on Pastebin, submit, copy URL of pastebin, and link it here

**Comment by tterrag1098** [comment]
Workaround added in 1eff222d4137373a1ca763cfc1451772c3d65a5f

**Comment by trogarus** [comment]
@Drullkus problem with that then stuff sits on pastebin with no link to the discussion here when an issue arises. As such, google searches give no solutions to the issue, just a bunch of pastebin links to nothing useful in order for someone to fix their issue or understand how to fix it. Yeah, I know, common "etiquette" is to pastebin, and this is why it's a bad idea.

**Comment by trogarus** [comment]
@tterrag1098 , thanks again for the hard work and the work around while we await AbyssalCraft to fix the issue =)
