### ISSUE TITLE
Server Crash with Version 1.12-0.1.0.20

### ISSUE THREAD

**Issue by Luckyday84** [Chisel-Team/Chisel#592]
Just my server crashes on startup with Version 1.12-0.1.0.20 forge version 1.12.2-14.23.1.2562
Clients boot up fine.

https://pastebin.com/DcqjupW2

**Comment by joshricker** [comment]
Same for the 1.10.2 version. (0.1.0.36)

**Comment by tterrag1098** [comment]
Fixed via bd25788f9987de09b9ea878dbfbd86bb3314d461
