### ISSUE TITLE
Crash on loading minecraft

### ISSUE THREAD

**Issue by DarkJarris** [Chisel-Team/Chisel#595]
Using Chisel MC1.12-0.1.0.23 results in a crash on minecraft startup, disabling the mod solves the problem but obviously cannot use the mod.

Uploaded crash report:

[crash-2017-12-11_00.14.42-client.txt](https://github.com/Chisel-Team/Chisel/files/1546185/crash-2017-12-11_00.14.42-client.txt)

**Comment by P3rf3ctXZer0** [comment]
You are missing CTM
