### ISSUE TITLE
[1.10.2] Unable to chisel to chisel varients of raw metal blocks

### ISSUE THREAD

**Issue by scalda** [Chisel-Team/Chisel#598]
Hi, 

I have just started to update foolcraft to 2.6 and I have updated chisel but I have a problem, I am unable to chisel let's say a copper block from TE to any of the chisel varients this goes for any and all metal blocks, along with the fact that none of the chisel metal blocks show up in JEI either. If I do /give a chisel variant of a metal block and I can put that block in the chisel I can turn that back into a raw metal block. (please see attached images)

I have tried adding the raw blocks to the groups via modtweaker to no avail as it stats that `ERROR: Error executing 08-chisel.zs: Cannot add to Ore Dictionary Group.`

Chisel : Chisel-MC1.10.2-0.1.0.38
CTM : CTM-MC1.10.2-0.2.3.26

<img src="https://i.gyazo.com/2f5f4657db2ac53587fefb8d0f423629.png" alt="with a chisel varient">
<img src="https://i.gyazo.com/66183de8847aa75264bb78814653a765.png" alt="with raw metal block">

**Comment by tterrag1098** [comment]
It will pick up any blocks with the same OreDictionary tag automatically, so just add that to the items you want in the group.

**Comment by scalda** [comment]
But this is what I was saying that it is not doing what you are suggesting it should be, as you can see from the images above., as for the crafttweaker/modtweaker integration it throws an error that it can't add the metal blocks to the groups as they no longer exist. it was working fine via the intergration of the last alpha version of chisel for 1.10.2 but not in the beta version that I posted above

**Comment by tterrag1098** [comment]
Yeah, I thought about it more and you were right, the issue is that it can't find a reverse mapping from the other mods' items to the group. I've added a solution for this.

**Comment by scalda** [comment]
Thank you for this. I look forward to the release of this fix, 

Would this also explain why the chisel varients don't show in JEI?

**Comment by tterrag1098** [comment]
No, that sounds like a separate issue

**Comment by scalda** [comment]
Ok, i will open another issue with it.

Thanks again @tterrag1098
