### ISSUE TITLE
[1.12.2] Recent update broke Factory blocks

### ISSUE THREAD

**Issue by Darkmega18** [Chisel-Team/Chisel#599]
[version: MC1.12-0.1.0.23] Yes I know theres another version of this issue, but that was for a 1.10.2 version. the factory blocks worked with the last version I had until the update from earlier today. I noticed only because their auto generated EMC value disappeared and I was trying to craft them for something I was building. :V

**Comment by tterrag1098** [comment]
It's the same bug, so tracking under #594

**Comment by Darkmega18** [comment]
well, since I just installed crafttweaker for other tweaks I'll go ahead and just add the recipe back in manually so it never breaks again. since I can easily do that with crafttweaker recipemaker going. ;)
