### ISSUE TITLE
[1.10.2] Chisel metal block varients don't show in JEI.

### ISSUE THREAD

**Issue by scalda** [Chisel-Team/Chisel#602]
Chisel : Chisel-MC1.10.2-0.1.0.38
CTM : CTM-MC1.10.2-0.2.3.26
Modpack : Foolcraft 2.6

Hi, in the latest version of chisel (see above) there is a lack of chisel metal block variations showing in JEI 
In fact, it looks like it is all metal chisel block varients including vanilla blocks

**Comment by oitsjustjose** [comment]
Probably because you have UniDict; all the chisel metal blocks are OreDict'd now, so UniDict hides all but the default selected variant.

**Comment by scalda** [comment]
I hadn't even thought of that i would if there is a way to turn the chisel
side of things off to allow them to show

**Comment by drakray** [comment]
I had the same trouble, removed Unidict, but still no recipe for Chisel's metal blocks
EDIT: I'm on 1.12.2

**Comment by drakray** [comment]
After futher investigation, chisel:blockgold don't work, but chisel:gold do, between meta only
No (Char)Coal work, neither iron/diamond/emerald/lapis
Quartz/Redstone/Obsidian work normally, as the rest do
[Modlist](https://pastebin.com/D6jhMXe1) using `/ct mods`

**Comment by drakray** [comment]
ok, I don't know what happened, but `chisel:gold` don't exist anymore in my game, and I used ActuallyAddition Advanced Info to realize that Chisel's block from my previous post are not oreDicted

**Comment by drakray** [comment]
Also, Immersive Engineering' Block of Coal Coke can't be chiseled to Chisel variant, yet they share `blockFuelCoke` as oreDict(this might be Unidict's fault, as I put it back after the test 3 posts ago)

**Comment by drakray** [comment]
More info: `chisel:gold` are OreDicted as `blockGold`, and UniDict was responsible for their disappearance.

**Comment by tterrag1098** [comment]
What I'm gathering is that this seems to be an issue with UniDict, not Chisel?

**Comment by drakray** [comment]
Problem exist even without Unidict

**Comment by tterrag1098** [comment]
I think you are getting confused, this issue is specifically about chisel blocks not showing in JEI, nothing to do with recipes. There is no recipe for chisel metal blocks because you are meant to chisel them from the mod versions that do have crafting recipes.

**Comment by drakray** [comment]
ah ok yes sorry, in that matter, there is a conflict with UniDict that hide `chisel:gold`, in my case, but I see the rest with or without UD, in 1.12.2 .
