### ISSUE TITLE
[1.12.2] Crash upon shift-clicking stack when Iron Chisel is about to break

### ISSUE THREAD

**Issue by Endgineer** [Chisel-Team/Chisel#603]
Tested this twice:
1st: Tried to chisel 64 cobble when the chisel was about to break; crash happened.
2nd: Chiseled 32 blocks separately, then tried to chisel the rest; crash happened.

Crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.72-universal.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  FarseekCoreMod (Farseek-1.12-2.2.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/13/17 1:35 AM
Description: Updating screen events

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to team.chisel.api.IChiselItem
	at team.chisel.common.inventory.SlotChiselSelection.craft(SlotChiselSelection.java:59)
	at team.chisel.common.inventory.ContainerChisel.func_82846_b(ContainerChisel.java:125)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at team.chisel.common.inventory.ContainerChisel.func_184996_a(ContainerChisel.java:95)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at team.chisel.client.gui.GuiChisel.func_73864_a(GuiChisel.java:58)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.common.inventory.SlotChiselSelection.craft(SlotChiselSelection.java:59)
	at team.chisel.common.inventory.ContainerChisel.func_82846_b(ContainerChisel.java:125)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at team.chisel.common.inventory.ContainerChisel.func_184996_a(ContainerChisel.java:95)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at team.chisel.client.gui.GuiChisel.func_73864_a(GuiChisel.java:58)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: team.chisel.client.gui.GuiChisel

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Endgineer'/228, l='MpServer', x=-904.85, y=74.00, z=-771.30]]
	Chunk stats: MultiplayerChunkCache: 416, 416
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-345,64,250), Chunk: (at 7,4,10 in -22,15; contains blocks -352,0,240 to -337,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 173743 game time, 230927 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 74 total; [EntityZombie['Zombie'/5888, l='MpServer', x=-923.50, y=158.00, z=-741.50], EntitySpider['Spider'/5889, l='MpServer', x=-927.50, y=75.00, z=-798.50], EntitySkeleton['Skeleton'/386, l='MpServer', x=-880.84, y=64.64, z=-777.87], EntityBabySkeleton['Baby Skeleton'/5890, l='MpServer', x=-933.50, y=75.00, z=-804.50], EntityPlayerSP['Endgineer'/228, l='MpServer', x=-904.85, y=74.00, z=-771.30], EntitySkeleton['Skeleton'/5382, l='MpServer', x=-843.50, y=100.00, z=-768.50], EntityZombie['Zombie'/6022, l='MpServer', x=-952.50, y=46.00, z=-837.50], EntitySkeleton['Skeleton'/6150, l='MpServer', x=-918.50, y=159.00, z=-736.50], EntityChickLeghorn['Leghorn Chick'/264, l='MpServer', x=-967.56, y=63.00, z=-789.01], EntityCreeper['Creeper'/393, l='MpServer', x=-857.50, y=94.00, z=-746.50], EntityWitch['Witch'/5387, l='MpServer', x=-866.50, y=133.00, z=-753.50], EntityZombie['Zombie'/6155, l='MpServer', x=-907.50, y=159.00, z=-729.50], EntitySpider['Spider'/4492, l='MpServer', x=-973.50, y=17.00, z=-727.50], EntityZombie['Zombie'/5900, l='MpServer', x=-872.50, y=79.00, z=-848.50], EntityZombie['Zombie'/3346, l='MpServer', x=-925.27, y=38.00, z=-810.52], EntityCreeper['Creeper'/5394, l='MpServer', x=-897.50, y=72.00, z=-818.50], EntityBat['Bat'/5907, l='MpServer', x=-858.34, y=24.34, z=-765.47], EntityBat['Bat'/6038, l='MpServer', x=-980.17, y=15.40, z=-714.41], EntityBat['Bat'/6039, l='MpServer', x=-978.75, y=15.87, z=-716.75], EntityBat['Bat'/6040, l='MpServer', x=-980.69, y=15.18, z=-713.25], EntityItem['item.item.rabbitFoot'/2586, l='MpServer', x=-918.40, y=158.00, z=-755.77], EntityBat['Bat'/5147, l='MpServer', x=-957.16, y=47.01, z=-739.86], EntitySkeleton['Skeleton'/5403, l='MpServer', x=-872.50, y=144.00, z=-692.50], EntityZombie['Zombie'/6043, l='MpServer', x=-960.50, y=18.00, z=-724.50], EntitySpider['Spider'/5925, l='MpServer', x=-971.50, y=64.00, z=-846.50], EntityZombie['Zombie'/6186, l='MpServer', x=-885.50, y=41.00, z=-764.50], EntityZombie['Zombie'/6187, l='MpServer', x=-887.50, y=41.00, z=-767.50], EntityHogHampshire['Hampshire Hog'/300, l='MpServer', x=-950.09, y=119.00, z=-728.10], EntityCreeper['Creeper'/5420, l='MpServer', x=-830.17, y=129.00, z=-819.86], EntityCreeper['Creeper'/6188, l='MpServer', x=-884.50, y=41.00, z=-763.50], EntityCreeper['Creeper'/5935, l='MpServer', x=-827.50, y=129.00, z=-789.50], EntityBat['Bat'/5040, l='MpServer', x=-971.29, y=54.98, z=-753.24], EntityFrogs['Frog'/306, l='MpServer', x=-956.50, y=63.00, z=-780.50], EntityWolf['Wolf'/307, l='MpServer', x=-956.66, y=62.42, z=-781.30], EntityBat['Bat'/5043, l='MpServer', x=-872.85, y=40.68, z=-752.42], EntityBat['Bat'/5301, l='MpServer', x=-894.38, y=23.10, z=-701.70], EntityBat['Bat'/5302, l='MpServer', x=-889.55, y=22.12, z=-703.42], EntityWolf['Wolf'/311, l='MpServer', x=-971.34, y=63.00, z=-777.61], EntityBat['Bat'/5307, l='MpServer', x=-851.25, y=32.04, z=-748.16], EntityCreeper['Creeper'/6075, l='MpServer', x=-946.50, y=125.00, z=-723.50], EntityCreeper['Creeper'/5183, l='MpServer', x=-929.06, y=69.00, z=-790.55], EntityBlizz['Blizz'/6079, l='MpServer', x=-871.50, y=135.00, z=-770.50], EntityHogHampshire['Hampshire Hog'/321, l='MpServer', x=-957.00, y=76.00, z=-761.50], EntitySquid['Squid'/325, l='MpServer', x=-942.56, y=61.81, z=-819.93], EntityZombie['Zombie'/4174, l='MpServer', x=-850.30, y=100.00, z=-761.70], EntityRabbitBuckChinchilla['Chinchilla Buck'/337, l='MpServer', x=-912.35, y=166.00, z=-752.60], EntitySkeleton['Skeleton'/5969, l='MpServer', x=-984.50, y=68.00, z=-756.50], EntityCreeper['Creeper'/6097, l='MpServer', x=-933.79, y=123.00, z=-768.50], EntityBat['Bat'/338, l='MpServer', x=-925.91, y=53.10, z=-759.47], EntityRabbitDoeChinchilla['Chinchilla Doe'/340, l='MpServer', x=-913.63, y=170.00, z=-746.25], EntitySkeleton['Skeleton'/3028, l='MpServer', x=-947.50, y=43.00, z=-821.50], EntityBlizz['Blizz'/4692, l='MpServer', x=-899.50, y=17.00, z=-732.50], EntityRabbitDoeChinchilla['Chinchilla Doe'/343, l='MpServer', x=-918.17, y=155.00, z=-760.40], EntityCreeper['Creeper'/5847, l='MpServer', x=-950.51, y=51.00, z=-764.18], EntitySpider['Spider'/6104, l='MpServer', x=-920.50, y=69.00, z=-789.50], EntityCreeper['Creeper'/5980, l='MpServer', x=-967.65, y=71.00, z=-719.18], EntityHenLeghorn['Leghorn Hen'/349, l='MpServer', x=-927.27, y=65.00, z=-776.50], EntityHenLeghorn['Leghorn Hen'/350, l='MpServer', x=-921.35, y=68.00, z=-785.43], EntityCreeper['Creeper'/6112, l='MpServer', x=-857.50, y=137.00, z=-771.50], EntitySquid['Squid'/5859, l='MpServer', x=-942.40, y=60.36, z=-817.88], EntitySquid['Squid'/5860, l='MpServer', x=-943.33, y=61.00, z=-819.36], EntityCreeper['Creeper'/5989, l='MpServer', x=-898.50, y=148.00, z=-709.50], EntityBat['Bat'/4714, l='MpServer', x=-969.25, y=42.10, z=-821.49], EntityRabbitDoeChinchilla['Chinchilla Doe'/366, l='MpServer', x=-912.48, y=156.17, z=-729.61], EntityRabbitBuckChinchilla['Chinchilla Buck'/367, l='MpServer', x=-901.35, y=168.00, z=-734.65], EntitySkeleton['Skeleton'/4339, l='MpServer', x=-857.50, y=98.00, z=-737.50], EntityZombieVillager['Zombie Villager'/5107, l='MpServer', x=-909.50, y=64.00, z=-843.50], EntityItem['item.item.rabbitFoot'/502, l='MpServer', x=-893.04, y=137.00, z=-775.77], EntityItem['item.item.rabbitFoot'/503, l='MpServer', x=-848.05, y=174.00, z=-769.13], EntityZombie['Zombie'/5111, l='MpServer', x=-878.50, y=69.00, z=-809.50], EntityBat['Bat'/5496, l='MpServer', x=-984.60, y=15.76, z=-772.48], EntityItem['item.item.minecraft:beef'/505, l='MpServer', x=-959.13, y=77.00, z=-732.70], EntityItem['item.item.leather'/506, l='MpServer', x=-959.60, y=77.00, z=-731.62], EntityRoosterLeghorn['Leghorn Rooster'/250, l='MpServer', x=-966.25, y=64.00, z=-832.40]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1165033536 bytes (1111 MB) / 2777677824 bytes (2649 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                | Source                                          | Signature                                |
	|:------ |:-------------------- |:---------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft            | 1.12.2                 | minecraft.jar                                   | None                                     |
	| UCHIJA | mcp                  | 9.42                   | minecraft.jar                                   | None                                     |
	| UCHIJA | FML                  | 8.0.99.99              | forge-1.12.2-14.23.1.2555-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                | 14.23.1.2555           | forge-1.12.2-14.23.1.2555-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | uncraftingtable      | 1.8-beta6              | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
	| UCHIJA | biomesoplenty        | 7.0.1.2310             | BiomesOPlenty-1.12.2-7.0.1.2310-universal.jar   | None                                     |
	| UCHIJA | craftstudioapi       | 1.0.0                  | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCHIJA | quark                | r1.4-120               | Quark-r1.4-120.jar                              | None                                     |
	| UCHIJA | animania             | 1.4.3                  | animania-1.12.2-1.4.3.jar                       | None                                     |
	| UCHIJA | autoreglib           | 1.3-15                 | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCHIJA | betterbuilderswands  | 0.11.1                 | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJA | betterfoliage        | 2.1.10                 | BetterFoliage-MC1.12-2.1.10.jar                 | None                                     |
	| UCHIJA | bibliocraft          | 2.4.3                  | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJA | codechickenlib       | 3.1.3.313              | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | chickenchunks        | 2.4.0.70               | ChickenChunks-1.12-2.4.0.70-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | ctm                  | MC1.12-0.2.3.9         | CTM-MC1.12-0.2.3.9.jar                          | None                                     |
	| UCHIJA | chisel               | MC1.12-0.1.0.23        | Chisel-MC1.12-0.1.0.23.jar                      | None                                     |
	| UCHIJA | redstoneflux         | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | cofhcore             | 4.3.7                  | CoFHCore-1.12.2-4.3.7.25-universal.jar          | None                                     |
	| UCHIJA | cofhworld            | 1.0.2                  | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
	| UCHIJA | crafttweaker         | 4.0.10                 | CraftTweaker2-1.12-4.0.10.jar                   | None                                     |
	| UCHIJA | ctgui                | 1.0.0                  | CraftTweaker2-1.12-4.0.10.jar                   | None                                     |
	| UCHIJA | jei                  | 4.8.5.136              | jei_1.12.2-4.8.5.136.jar                        | None                                     |
	| UCHIJA | crafttweakerjei      | 2.0.0                  | CraftTweaker2-1.12-4.0.10.jar                   | None                                     |
	| UCHIJA | dirt2path            | 1.7.0                  | dirt2path-1.7.0.jar                             | None                                     |
	| UCHIJA | thermalfoundation    | 2.3.7                  | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
	| UCHIJA | thermalexpansion     | 5.3.7                  | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
	| UCHIJA | dyndyn               | 1.12.2-1.8             | DynamicDynamos-1.12.2-1.8.jar                   | None                                     |
	| UCHIJA | dsurround            | 3.4.7.2                | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | presets              | 3.4.7.2                | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCHIJA | elevatorid           | 1.3.5                  | ElevatorMod-1.12.2-1.3.5.jar                    | None                                     |
	| UCHIJA | endercrop            | 1.12-1.3.4             | endercrop-1.12-1.3.4.jar                        | None                                     |
	| UCHIJA | exnihilocreatio      | 1.12-0.1.5             | exnihilocreatio-1.12-0.1.5.jar                  | None                                     |
	| UCHIJA | farseek              | 2.2.2                  | Farseek-1.12-2.2.2.jar                          | None                                     |
	| UCHIJA | fastleafdecay        | v14                    | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJA | gravestone           | 1.10.0                 | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJA | hardcoredarkness     | 2.0                    | HardcoreDarkness-MC1.12.2-2.0.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJA | hungerstrike         | 1.12-1.0.8             | HungerStrike-1.12-1.0.8.jar                     | None                                     |
	| UCHIJA | waila                | 1.8.23                 | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
	| UCHIJA | mantle               | 1.12-1.3.1.21          | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJA | tconstruct           | 1.12-2.8.0.45          | TConstruct-1.12-2.8.0.45.jar                    | None                                     |
	| UCHIJA | immersiveengineering | 0.12-75                | ImmersiveEngineering-0.12-75.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA | immersivepetroleum   | @VERSION@              | immersivepetroleum-1.12.2-1.1.5.jar             | None                                     |
	| UCHIJA | instantunify         | 1.0.7                  | instantunify-1.12.2-1.0.7.jar                   | None                                     |
	| UCHIJA | itemscroller         | 0.11.0                 | itemscroller-1.12.0-0.11.0.jar                  | None                                     |
	| UCHIJA | jaopca               | 1.12.2-2.2.5.64        | JAOPCA-1.12.2-2.2.5.64.jar                      | None                                     |
	| UCHIJA | oredictinit          | 1.12.2-2.2.1.67        | JAOPCA-1.12.2-2.2.5.64.jar                      | None                                     |
	| UCHIJA | journeymap           | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJA | mekanism             | 9.4.2                  | Mekanism-1.12.2-9.4.2.327.jar                   | None                                     |
	| UCHIJA | mekanismgenerators   | 9.4.2                  | MekanismGenerators-1.12.2-9.4.2.327.jar         | None                                     |
	| UCHIJA | naturescompass       | 1.5.0                  | NaturesCompass-1.12.2-1.5.0.jar                 | None                                     |
	| UCHIJA | neat                 | 1.4-15                 | Neat 1.4-15.jar                                 | None                                     |
	| UCHIJA | netherportalfix      | 5.3.13                 | NetherPortalFix_1.12.1-5.3.13.jar               | None                                     |
	| UCHIJA | harvestcraft         | 1.12.2a                | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCHIJA | plustic              | 6.3.2.1                | plustic-6.3.2.1.jar                             | None                                     |
	| UCHIJA | reborncore           | 3.5.2.171              | RebornCore-1.12.2-3.5.2.171-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJA | refinedstorage       | 1.5.25                 | refinedstorage-1.5.25.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJA | rebornstorage        | 1.0.0                  | RebornStorage-1.12.2-3.0.2.32.jar               | None                                     |
	| UCHIJA | refinedstorageaddons | 0.2                    | refinedstorageaddons-0.2.jar                    | None                                     |
	| UCHIJA | simplyjetpacks       | 2.1.3.17               | SimplyJetpacks2-1.12.2-2.1.3.17.jar             | None                                     |
	| UCHIJA | stg                  | 1.12.2-1.2.3           | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHIJA | streams              | 0.4.1                  | Streams-1.12-0.4.1.jar                          | None                                     |
	| UCHIJA | thermalcultivation   | 0.1.2                  | ThermalCultivation-1.12.2-0.1.2.8-universal.jar | None                                     |
	| UCHIJA | thermaldynamics      | 2.3.7                  | ThermalDynamics-1.12.2-2.3.7.14-universal.jar   | None                                     |
	| UCHIJA | tinkertoolleveling   | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCHIJA | toughasnails         | 3.0.0.72               | ToughAsNails-1.12-3.0.0.72-universal.jar        | None                                     |
	| UCHIJA | waterstrainer        | 3.2.0                  | WaterStrainer-1.12-3.2.0.jar                    | None                                     |
	| UCHIJA | wawla                | 2.5.246                | Wawla-1.12.2-2.5.246.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJA | wrapup               | 1.12-1.1.3             | WrapUp-1.12-1.1.3.jar                           | None                                     |

	Loaded coremods (and transformers): 
TANLoadingPlugin (ToughAsNails-1.12-3.0.0.72-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
FarseekCoreMod (Farseek-1.12-2.2.2.jar)
  farseek.core.FarseekClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.5.2.171
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 970M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by jusvit** [comment]
`The game crashed whilst updating screen events
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to team.chisel.api.IChiselItem`

Same

**Comment by VladimirMangos** [comment]
Confirm also.  Chisel-MC1.12-0.1.0.21 is last version without this crash

**Comment by Not-February** [comment]
I believe I have narrowed down this issue more precisely; my friend was having this, and it only happened to him when he was shift-left-clicking the output to automatically place it into his inventory afterwards.

He was using an iron chisel that had very little durability left at the time if it matters; simply left-clicking the output without any modifier keys resulted in the chisel breaking itself properly after having chiseled everything it could in the stack and then ejecting everything into the world.

**Comment by mickedplay** [comment]
+1

**Comment by Endgineer** [comment]
+1; what Febilian said.
Also confirmed that this only happens with an Iron Chisel; the Diamond Chisel works fine.

**Comment by tterrag1098** [comment]
I'm thinking this will be fixed by 2de772f47ac04cb4460088e2eadaf3a12b753b47 but I need to port it forward to check

**Comment by tterrag1098** [comment]
Yes, confirmed fixed

**Comment by ThomasAunvik** [comment]
@Endgineer Just to confirm, at 0.1.0.23 it does the same, but this time i crashed with the Diamond Chisel. Not sure if it is fixed. I will try it at 0.1.1.24

Edit, yup. fixed at 0.1.1.24

**Comment by tterrag1098** [comment]
I specifically fixed this in 0.1.1
