### ISSUE TITLE
Minor Chunk Corruption from In-World Chiseling

### ISSUE THREAD

**Issue by oitsjustjose** [Chisel-Team/Chisel#604]
## Environment:
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2558
Chisel Version: 0.1.0.23
CTM Version: 0.2.3.9
<details>

- ActuallyAdditions-1.12.2-r125.jar
- AkashicTome-1.2-9.jar
- antiqueatlas-1.12-4.4.4.jar
- applied-llamagistics-1.12.1-rv5-beta-10.jar
- AppliedFluidics-1.12.1-1.0.3.jar
- astralsorcery-1.12.2-1.8.3.jar
- AutoRegLib-1.3-13.jar
- Baubles-1.12-1.5.1.jar
- BetterFps-1.4.8.jar
- blockcraftery-0.1.3.jar
- Botania r1.10-352.jar
- Ceramics-1.12-1.3.3b.jar
- Chameleon-1.12-4.1.3.jar
- ChickenChunks-1.12-2.4.0.70-universal.jar
- Chisel-MC1.12-0.1.0.23.jar
- chiselsandbits-14.11.jar
- CodeChickenLib-1.12-3.1.3.313-universal.jar
- CoFHCore-1.12.2-4.3.7.25-universal.jar
- CoFHWorld-1.12.2-1.0.2.10-universal.jar
- comforts-1.12.2-1.1.0.jar
- CraftTweaker2-1.12-4.0.10.jar
- CTM-MC1.12-0.2.3.9.jar
- cucumber[1.12]-1.0.2.jar
- diethopper-1.1.jar
- DoggyTalents-1.12-1.14.2.308-universal.jar
- elulib-0.1.11.jar
- EnderStorage-1.12-2.4.1.124-universal.jar
- extrautils2-1.12-1.6.8.jar
- foamfix-0.7.2-1.12-anarchy.jar
- forestry_1.12.2-5.7.0.215.jar
- Geolosys-1.12.1-1.8.4-beta.jar
- gigaherz.commons-1.12.1-0.6.4.jar
- gottagofast-1.0.jar
- gravestone-1.8.4.jar
- Guide-API-1.12-2.1.4-56.jar
- Hwyla-1.8.23-B38_1.12.jar
- ImmersiveEngineering-0.12-75-core.jar
- ImmersiveEngineering-0.12-75.jar
- inventorysorter-1.12.2-1.12.4+52.jar
- ironchest-1.12.2-7.0.34.820.jar
- jeibees-0.9.0.5-mc1.12.2.jar
- jei_1.12.2-4.8.4.131.jar
- MagicalPsi-1.3.jar
- Mantle-1.12-1.3.1.21.jar
- mcjtylib-1.12-2.5.0.jar
- MCMultiPart-exp-2.3.4_49.jar
- modtweaker-4.0.5.jar
- Morpheus-1.12-3.3.2.jar
- MTLib-3.0.0.jar
- mysticalagriculture-1.12-1.6.6.jar
- mysticalworld-0.1.jar
- OpenComputers-MC1.12.1-1.7.1.43.jar
- Psi-r1.1-59.jar
- Quark-r1.4-120.jar
- QuickLeafDecay-MC1.12.1-1.2.4.jar
- RebornCore-1.12.2-3.5.2.171-universal.jar
- RebornStorage-1.12.2-3.0.2.32.jar
- RedstoneArsenal-1.12.2-2.3.7.18-universal.jar
- RedstoneFlux-1.12-2.0.1.2-universal.jar
- refinedstorage-1.5.28.jar
- rftools-1.12-7.15.jar
- rustic-0.4.3.jar
- StorageDrawers-1.12.1-5.3.1.jar
- TConstruct-1.12-2.8.0.45.jar
- ThermalDynamics-1.12.2-2.3.7.14-universal.jar
- ThermalExpansion-1.12.2-5.3.7.31-universal.jar
- ThermalFoundation-1.12.2-2.3.7.18-universal.jar
- Tinkers' Addons-1.12.1-1.0.7.jar
- ToolBelt-1.12.0-1.7.1.jar
- twilightforest-1.12.2-3.5.263-universal.jar
- UniDict-1.12.2-1.6.jar
- VTweaks-1.12.2-1.4.12b.jar
- WanionLib-1.12.2-1.3.jar
- WearableBackpacks-1.12.2-3.1.0.jar
- Xtones-1.12-1.0.7-10.jar
</details>

### What happens:

Performing an in-world chisel on a block added to the chisel compat list via OreDictionary (in my case, Limestone from Quark) causes a client-side crash when playing on a dedicated server. Upon restart, the chunk had at least a dozen odd rendering bugs. These bugs include:

- Chisel and bits blocks not rendering
- Storage drawers not showing contents
- Framed storage drawers showing nothing but the blank frame texture
- MCMP blocks completely (visually) missing
- Blockcraftery blocks not rendering their applied block texture

A full demonstration can be found [here](https://mixer.com/oitsjustjose?vod=13199009) at timestamp 1:10:03 (1 hour, 10 minutes, 3 seconds).

Here is the [client crash log](https://pastebin.com/WpGpev4G). Also, these chunk rendering issues *persist* upon client *and* server reboot; hence my belief that it's some type of corruption..

### Steps to reproduce:

1. Install Chisel, CTM, Forge and Quark (possibly other mods)
2. Place a Quark Limestone / Marble / Basalt block in-world
3. Chisel said block with a Chisel

_____

Let me know if I can help any... our world is relatively unplayable until this issue gets resolved (hoping that it can retroactively fix what's been broken..).

**Comment by tterrag1098** [comment]
Unfortunately I don't think anything I do can fix your world...backups are important. However I also don't think this occurred in a vacuum. You are not the first to report this crash but you are the first to have it also cause "corruption" so I imagine it was some kind of interaction with another mod that caused it. Tracking under #606 to avoid confusion.

**Comment by oitsjustjose** [comment]
It actually fixed itself when I updated MCMP (a logical culprit, as most of my blocks erroring out were multiparts).

But I do still have the weirdness described in #606, so thanks!
