### ISSUE TITLE
[1.12.2] Factory Block/Tyrian recipe conflict

### ISSUE THREAD

**Issue by Riyshn** [Chisel-Team/Chisel#605]
Chisel-MC1.12-0.1.0.23

I'm not sure if this is the same issue as #594, but I am unable to craft Factory Blocks; JEI shows no recipe for them, and the trying the normal recipe (4 Stone, 4 Iron Ingots) creates 32 Tyrian instead, while the normal Tyrian recipe (8 Stone, 1 Iron Ingot) does not craft anything.

**Comment by Dragnier** [comment]
Just noticed this myself. Definitely odd. Temporarily using Craft Tweaker to fix this for myself.

**Comment by mctom987** [comment]
This was working in Direwolf20 1.3.0, and broke in 1.4.0

I tried using MineTweaks to add the recipe back, but I couldn't figure out a way to craft Factory Blocks at all. Tyrian set to it's original just fine, so it appears this issue goes beyond just the recipe.

**Comment by mctom987** [comment]
Tyrian recipe looks oddly similar to Factory

Factory
https://github.com/Chisel-Team/Chisel/blob/e4efed03409967079db25e9c96390d2105e2b7a7/src/main/java/team/chisel/Features.java#L1232

Tyrian
https://github.com/Chisel-Team/Chisel/blob/e4efed03409967079db25e9c96390d2105e2b7a7/src/main/java/team/chisel/Features.java#L2861

**Comment by PaternoX** [comment]
this problem is also presenting in project ozone lite v1.3.4, recipe for factory block shows the crafted block with a red ), and does not produce any blocks when in a crafting grid.
