### ISSUE TITLE
Duplication glitch when a chisel breaks

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Chisel-Team/Chisel#608]
Forge version: 14.23.1.2555
Chisel version: 0.0.14.18
Modpack: Direwolf 20 1.12 version 1.2.0
Log file: https://paste.ee/p/ZitQ4

Replication steps:

1. Grab an iron chisel and a stack of any chisel-compatible blocks.
2. Chisel the entire stack at once using shift click
3. Repeat until the chisel breaks

It will break before it can chisel the entire stack of blocks. When it does, the items you successfully chiseled will appear in your inventory. The entire stack of the block you were trying to chisel will also be dropped on the ground, giving you extra blocks. I got 53 extra from my testing.

**Comment by tterrag1098** [comment]
Please update Chisel
