### ISSUE TITLE
Material with ID already exists type error

### ISSUE THREAD

**Issue by chezpaul** [Chisel-Team/Chisel#61]
I'm getting a bunch of material with ID already exists type error on my server log:

http://pastebin.com/XHdkQ0af

Running Latest version with Cauldron 1.7.10 1492.155

**Comment by chezpaul** [comment]
Same issue with KCauldron 1.7.10 1517.168 in case it helps

**Comment by Drullkus** [comment]
Try not using Cauldron

**Comment by chezpaul** [comment]
That's a super smart remark. And just to be as smart as you are, I'll answer that I'm not using Cauldron.
Try to figure that one out.

**Comment by Drullkus** [comment]
Well, we could use the log without Cauldron in the set up.

**Comment by chezpaul** [comment]
I have over 150 mods and never had that type of error before I installed Chisel, going on a year and a half. Is there a way I can check those ID's?

**Comment by Drullkus** [comment]
Can we have the _full_ log?

**Comment by Drullkus** [comment]
If we get the full log, we can determine what the problem is.

**Comment by TehNut** [comment]
> That's a super smart remark. And just to be as smart as you are, I'll answer that I'm not using Cauldron.
> Try to figure that one out.

You never once said that you tried without Cauldron. You also never provided a log from without Cauldron.

And it wasn't a "super smart remark". It was him asking you to try without the unsupported hack you had installed. So get off your high horse.

**Comment by chezpaul** [comment]
I said I was using KCauldron, not cauldron. 
My whole server is based on KCauldron, why would I try the mod with it? I couldn't even open my world.
It makes no sense.

Anyway, thanks for trying to help.
Here's my full log

http://pastebin.com/1ANF4zTu

**Comment by TehNut** [comment]
KCauldron _is_ Cauldron.

**Comment by chezpaul** [comment]
Yes and no...is Chisel 2 the same as Chisel 1?
Some people might say yes and other would say no. I bet you would say no.

**Comment by tterrag1098** [comment]
Stop playing semantics. Any variant of bukkit+forge is UNSUPPORTED. Test without it and see if it still happens.

**Comment by chezpaul** [comment]
Same error running same mods in Forge 1.7.10 1517
http://pastebin.com/eM71QEzz

**Comment by chezpaul** [comment]
Is there a trick to get in your error log the [NAME OF MOD] in front of every line?
That's kinda cool.

**Comment by tterrag1098** [comment]
Do you have any chisel blocks manually added to FMP? That is automatic now.

**Comment by chezpaul** [comment]
I doubt it but possible. Which config would that be? I don't see a config for it.

**Comment by tterrag1098** [comment]
microblocks.cfg

**Comment by chezpaul** [comment]
I remember editing this cfg on the recommendation of someone but going back to it being blank because it added a bunch of unrelated errors.

This is what it is right now:

#Configuration file for adding microblock materials for aesthetic blocks added by mods
#Each line needs to be of the form <name>:<meta>
#<name> is the unlocalised name or registry key of the block/item enclosed in quotes. NEI can help you find these
#<meta> may be ommitted, in which case it defaults to 0, otherwise it can be a number, a comma separated list of numbers, or a dash separated range
#Ex. "dirt" "minecraft:planks":3 "iron_ore":1,2,3,5 "ThermalFoundation:Storage":0-15

**Comment by tterrag1098** [comment]
Ok well someone/something is adding chisel blocks to FMP manually. It's not really a problem though, it's a harmless error.

**Comment by chezpaul** [comment]
k cool thanks
