### ISSUE TITLE
[1.12.2] Factory blocks are not craftable

### ISSUE THREAD

**Issue by Draskh** [Chisel-Team/Chisel#611]
The recipe for factory blocks is missing. 

Chisel - MC1.12-0.1.1.24

**Comment by Draskh** [comment]
Recipe does not appear in JEI and trying the normal one ( 4 stone and 4 ingots) results nothing.

**Comment by mctom987** [comment]
Possibly a dupe of #605

**Comment by Draskh** [comment]
Possibly, but it creates nothing, not even Tyrian.

**Comment by JonasCiss** [comment]
works now. 
![Uploading 2017-12-28_11.11.36.png…]()

**Comment by Draskh** [comment]
It works now. 
![2017-12-28_11 11 36](https://user-images.githubusercontent.com/26455012/34412397-4a946004-ebdd-11e7-8175-dc0dbd03cd73.png)
