### ISSUE TITLE
[1.12.2] Charcoal Block has no burn time and cannot be chiseled

### ISSUE THREAD

**Issue by Shahelion** [Chisel-Team/Chisel#614]
Applies to all variants.

![2017-12-21_00 39 28](https://user-images.githubusercontent.com/6917535/34247458-6d503470-e5e7-11e7-9545-17580263c853.png)

**Comment by Snownee** [comment]
Yes, and this issue is the same with Coal Blocks

**Comment by fallenhunter1** [comment]
Will note that charcoal blocks at least, cannot be turned back into Charcoal as well. Hope real life allows the devs to fix this sometime in the near future. 

Thanks, btw, to all the devs/admins for your time.

**Comment by dragonpaw** [comment]
(And sadly, setting a burn time on them via craftweaker doesn't seem to fix the issue.)

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/34460066-829d1ec4-ee3e-11e7-8be1-f0748bb1f419.png)
@dragonpaw Actually it does ;)

**Comment by dragonpaw** [comment]
@Snownee Hmm... I used `furnace.setFuel(<chisel:block_charcoal2:1>, 16000);` and the only effect it had was allowing me to insert the item into some modded furnaces, but it never burned and didn't show a burn time in my tool tips. What script did you use?

**Comment by Snownee** [comment]
@dragonpaw 
```
furnace.setFuel(<chisel:block_charcoal:*>, 16000);
furnace.setFuel(<chisel:block_charcoal1:*>, 16000);
furnace.setFuel(<chisel:block_charcoal2:*>, 16000);
```

**Comment by dragonpaw** [comment]
@Snownee 
Maybe it doesn't work with a server, as the one you listed doesn't seem to work for me. Despite it clearly loading:
```
[INITIALIZATION][SERVER][INFO] [crafttweaker | SIDE_SERVER]: Loading Script: {[0:crafttweaker]: ash.zs}
[INITIALIZATION][SERVER][INFO] Setting fuel for <chisel:block_charcoal:*>
[INITIALIZATION][SERVER][INFO] Setting fuel for <chisel:block_charcoal1:*>
[INITIALIZATION][SERVER][INFO] Setting fuel for <chisel:block_charcoal2:*>
```

**Comment by tterrag1098** [comment]
Seems to be fine now 
![image](https://user-images.githubusercontent.com/3751664/43476339-5b471562-94c6-11e8-97f6-a26870ef3618.png)
