### ISSUE TITLE
Chisel-MC 1.10.2-0.0.13.30 :Crash when trying to left-click chisel two stacked cobblestone slabs

### ISSUE THREAD

**Issue by brad3055** [Chisel-Team/Chisel#615]
When I was trying to chisel cobblestone that I've already placed, I sometimes came across patches where, instead of a normal cobblestone, I had placed two cobblestone slabs; when trying to chisel a block made up of these two slabs the game would crash.

Here is the crash report. I'm playing Sink into Madness mod pack with the Chisel version specified.

[crash-2017-12-23_03.13.32-client.txt](https://github.com/Chisel-Team/Chisel/files/1583973/crash-2017-12-23_03.13.32-client.txt)

**Comment by tterrag1098** [comment]
You are quite outdated, please try newer versions.
