### ISSUE TITLE
[1.7.10] Chisel mod broke the texture of steam in Railcraft

### ISSUE THREAD

**Issue by demycat** [Chisel-Team/Chisel#616]
After installing the version of chisel mod 2.9.5.11 for minecraft 1.7.10, the texture steam became such (screenshot)! How to fix?
![2017-12-25_12 46 23](https://user-images.githubusercontent.com/34833284/34338464-b4edaa1e-e971-11e7-9e5d-0a98afaf189f.png)
![2017-12-25_12 46 27](https://user-images.githubusercontent.com/34833284/34338465-b50b1f90-e971-11e7-9ffd-67b9270d320e.png)

**Comment by tterrag1098** [comment]
1.7.10 is no longer being updated, and this seems like a bug in Railcraft.
