### ISSUE TITLE
[1.12.2] Unable to chisel metal and gemstone blocks

### ISSUE THREAD

**Issue by EdC94** [Chisel-Team/Chisel#620]
Hi,

I can't seem to chisel metal and gemstone blocks, be it vanilla (iron, gold, diamond, emerald, lapis) or modded (aluminum, bronze, cobalt, copper, electrum...) 
The chisel blocks variants appear in jei but don't have chisel recipes and indeed the blocks are not chiselable.
All are enabled in the config, clientside and serverside.

**Comment by ghost** [comment]
Having the same problem using current  Modern Skyblock 2 modpack.
Chisel MC1.12-0.1.1.24

**Comment by gryttr** [comment]
Can confirm. Chisel MC1.12-0.1.1.24, default configs. Minecraft 1.12.2 with Forge 14.23.1.2565. Whatever it is, it's also breaking Thermal Foundation's Forge Lexicon.

**Comment by brisingraerowing** [comment]
I've been watching Xisuma's FoolCraft series, and he mentioned this issue as well, and FC is in 1.10.2, so this likely affects all versions. I have a 1.10.2 instance set up, so I can test if needed.

**Comment by tterrag1098** [comment]
Fixed via 2a448df9308ed94ee3a777b5d5cb4085869d095d
