### ISSUE TITLE
iChisel game crash when stone is turned into spiral stone brick from Twilight forest

### ISSUE THREAD

**Issue by BioGeekJoey** [Chisel-Team/Chisel#621]
When cycling through all stone chisel options with the iChisel it will crash the game when you chisel stone into spiral stone brick.

Removing the block will fix the crashing.

[crash-2018-01-01_15.53.34-client.txt](https://github.com/Chisel-Team/Chisel/files/1596141/crash-2018-01-01_15.53.34-client.txt)

**Comment by tterrag1098** [comment]
Update
