### ISSUE TITLE
[1.12.2] The game crashed whilst initializing game.

### ISSUE THREAD

**Issue by AwesomeAla** [Chisel-Team/Chisel#622]
Error: java.lang.NullPointerException: Initializing game

**Comment by tterrag1098** [comment]
Helpful. Maybe post some actual information?

**Comment by AwesomeAla** [comment]
What do you mean?

**Comment by KnightMiner** [comment]
He means if the game crashed, the only way anyone will be able to fix the crash is a full crash report. The first line is completely useless on its own as that issue could be anywhere. Go to Pastebin.com, paste your crash report, then link it here.
