### ISSUE TITLE
Connected textures bug with optifine

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#624]
Chisel - MC1.12-0.1.1.26
Optifine 1.12.2 HD U C7
CTM - MC1.12-0.2.3.9

I know modders don't like to support optifine but this bug wasn't happening before. So I just wanted to let you know

![2018-01-06_19 02 47](https://user-images.githubusercontent.com/30737871/34645597-88841c9c-f317-11e7-99d4-ddda42a3359f.png)
![2018-01-06_19 03 26](https://user-images.githubusercontent.com/30737871/34645598-8dfb1f0e-f317-11e7-927f-8b01912d5f64.png)
![2018-01-06_19 03 09](https://user-images.githubusercontent.com/30737871/34645600-920f59a2-f317-11e7-8b1c-1381a42d913e.png)

Removing optifine fixes most of the textures except this one:

![2018-01-06_19 58 56](https://user-images.githubusercontent.com/30737871/34645794-5d0c4882-f31c-11e7-9b90-c86a2309881a.png)

**Comment by tterrag1098** [comment]
Please report this to Optifine, as this is very likely on their end.
