### ISSUE TITLE
Crash on startup with custom texture pack

### ISSUE THREAD

**Issue by Trixz2018** [Chisel-Team/Chisel#625]
minecraft 1.12
forge 14.23.1.2583
chisel 12-0.1.1.26

got this weird crash after adding a texture pack
https://paste.ee/p/QAkRg
  
tested without any texture packs and minecraft launched, gonna try and add one at a time to see which one crashes it. 
  
Edit: think i found the issue, but need to be sure. any help would be great
So using my own custom texture pack i get this crash which is annoying and i don't understand why . . .

**Comment by Trixz2018** [comment]
alright i took out some files and repacked the texture pack and now it won't even load my texture pack

**Comment by Trixz2018** [comment]
forget it

**Comment by tterrag1098** [comment]
For the record, you have some invalid .mcmeta file in that RP
