### ISSUE TITLE
[1.12.2] Duplicateion bug

### ISSUE THREAD

**Issue by SirDancealot** [Chisel-Team/Chisel#629]
if you have something you want to convert to another texture in the slot and then use the numberkey (1 through 9) to choose which inventory-slot  you want the new textured block in, 1 copy of the new textured block gets placed in the corresponding inventory-slot, and the entire stack that should have been converted gets placed on your cursor (and the one is not substracted from that). (Not entirely sure if its a glitch that is coused by thye mod alone or if it's inventory tweaks that does something as i also have that mod installed, found bug in the modpack "Modern Skyblock 2")

**Comment by tterrag1098** [comment]
Tracked under #644
