### ISSUE TITLE
[1.12.2] iChisel can't chisel Gold Blocks.

### ISSUE THREAD

**Issue by VermillionX** [Chisel-Team/Chisel#630]
Works with the normal chisels, but the iChisel won't chisel gold blocks into any of the gold blocks below the first line of options.

**Comment by tterrag1098** [comment]
Are you on the latest version?

**Comment by VermillionX** [comment]
Version 1.12.0.1.1.26
So, yes.

**Comment by tterrag1098** [comment]
What do you mean "below the first line of options"?

**Comment by VermillionX** [comment]
On the ichisel's GUI when gold block is selected. Only the top line of options work. All the other types of gold block below the first line won't chisel. Clicking them does nothing.

**Comment by tterrag1098** [comment]
I've never heard of anything like that. If there's items in the slots they
should be valid. What other mods do you have?

On Feb 26, 2018 1:56 AM, "Vermillion" <notifications@github.com> wrote:

On the ichisel's GUI when gold block is selected. Only the top line of
options work. All the other types of gold block below the first line won't
chisel. Clicking them does nothing.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Chisel-Team/Chisel/issues/630#issuecomment-368407249>,
or mute the thread

**Comment by VermillionX** [comment]
It's quite a list...
Mostly tech mods: TechReborn, ImmersiveEngineering, IC2, ExU2, Quark, Reliquary, Pam's, TiC, OpenComputers, Botania, ActuallyAdditions, etc...
Nothing that adds alternative gold blocks, but this also affects other metal block types.

**Comment by tterrag1098** [comment]
I need to be able to reproduce this to test it. Until I can, there's not much I can do.

**Comment by VermillionX** [comment]
It's a public modpack: https://www.technicpack.net/modpack/hac-testbed.1066281

**Comment by NotAVerb** [comment]
I am unable to chisel gold blocks with an iron chisel using left-click and shift left-click, the gui works.
Also, the gold block patterns "caution" through "scaffold" and the vanilla gold block do not have chisel recipes in JEI. When one of the patterns that is not part of the sequence I described is selected, it becomes impossible to chisel back to any of the blocks from said sequence.

Left-clicking on Iron, Diamond, Emerald, and Lapis, blocks does nothing. Shift left-clicking on said blocks can only reach a single variation.

Minecraft 1.12.2
Chisel 0.2.0.31

**Comment by suneyedset** [comment]
I am having the same issue with the ichisel on gold blocks. I am playing the ftb revelation mod pack. Normal chisel works, ichisel does not, with some of the gold block textures. About half.

**Comment by flanigomik** [comment]
can confirm, is occurring in the public FTB Revelation pack, ichisle does not work but normal (iron one) seems to, can't chisle in world at all for gold blocks

**Comment by WeaselOnaStick** [comment]
Got the same problem in Enigmatica2Expert:Skyblock

**Comment by Autoquark** [comment]
Also occurs in Project Ozone 3
