### ISSUE TITLE
Sound issue or something

### ISSUE THREAD

**Issue by twestin74** [Chisel-Team/Chisel#631]
trying to load the game and get this . . . . . .The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.block.Block.func_149672_a(Lnet/minecraft/block/SoundType;)Lnet/minecraft/block/Block; from class team.chisel.Features$1

And that is with just the chisel mod installed and nothing else

**Comment by tterrag1098** [comment]
Please post your whole log - I suspect you are using the wrong mod version for your MC version.

**Comment by twestin74** [comment]
Hey, sorry for the long delay. My question is a valid one, I did get it figured out it was the fact that I had run Chisel before and changed some things in the config file and the server wouldn't let me on cause of that.  The error message was trying to tell me that I had changed a block in the config.  I reloaded my config for the chisel mod and it works great.  By the way I love your mod it is awesome!  Also thanks for the response it is appreciated!
