### ISSUE TITLE
[1.12.2] Chisel Doesn't support Quark Glass shards

### ISSUE THREAD

**Issue by Ristellise** [Chisel-Team/Chisel#632]
A Picture Paints A Thousand Words, But A Video Shows A Thousand Pictures... right? Soo here: [Why Chisel...](https://streamable.com/vf7rv)

Chisel Version: MC1.12-0.1.1.26
Quark Version: R1.4-122

**Comment by tterrag1098** [comment]
I see no way to add this support, please ask Vazkii about it.
