### ISSUE TITLE
iChisel (crashing/halting) server

### ISSUE THREAD

**Issue by Whazaaaaa** [Chisel-Team/Chisel#633]
Hello I've been having an issue with chisel sorta halting my server. I've been to 2 different places but they told me to come here.

If you could look at my issue in the other place that would be amazing.
https://github.com/SpongePowered/SpongeForge/issues/1972

Basically because of chisel the server sorta crashes but Sponge (pluginmanager) makes it so the server doesnt crash but it still halts the server somehow making the server unstable. Could you take a look at whats happening and tell me whats going wrong and if I can fix it myself or if I should wait for a modpack update. Thank you.

**Comment by Drullkus** [comment]
Looks like a Sponge Plugin issue
