### ISSUE TITLE
[1.12.2] Crash with Latest Blood Magic

### ISSUE THREAD

**Issue by nmarshall23** [Chisel-Team/Chisel#634]
Blood Magic: 1.12.2-2.2.1-83
Chisel: MC1.12-0.1.1.26

I've turned off the blood Magic feature and I still get a crash.

```
java.lang.NoClassDefFoundError: team/chisel/common/block/BlockCarvableTranquility
	at team.chisel.Features.<clinit>(Features.java:2085)
```

[Link](https://pastebin.com/kFxWSncM) to full log.

I know that Blood Magic is in alpha, so I wouldn't expect that Chisel have support for it. But Chisel shouldn't be crashing even when I disable support.

**Comment by TehNut** [comment]
Chisel is crashing because I repackaged things. For now, use the old build.

**Comment by TehNut** [comment]
@Drullkus the new way to do this (once I implement and build it) would be something along the lines of

```java
@BloodMagicPlugin
public class ChiselBMPlugin implements IBloodMagicPlugin {

    @Override
    public void register(IBloodMagicAPI api) {
        api.getValueManager().setTranquility(Blocks.STONE.getDefaultState(), "PLANT", 1.0D);
    }
}
```

No more need the custom class.

**Comment by Drullkus** [comment]
Awesome awesome.

**Comment by Darkmega18** [comment]
whoops. yeah, got this crash also. so use a previous version or something?

**Comment by LocalBoomer** [comment]
If anyone (namely me) doesn't pay attention to mod updates and isn't sure which to roll back, roll back Blood Magic to version 1.12.2-2.2.0-82 and you can leave support for it on in Chisel.

**Comment by MokahTGS** [comment]
https://github.com/WayofTime/BloodMagic/issues/1210

**Comment by Majora320** [comment]
Just to let you know, it would be nice to get a fix for this as soon as you have time: Blood Magic 1.12 had an issue where it couldn't run on dedicated servers until a commit from ~2 days ago, so downgrading BM to fix this isn't possible if you're running a server (like me).

**Comment by TehNut** [comment]
Remove BM. I have not pit out a build containing the new API.

**Comment by TehNut** [comment]
@Drullkus This has been released in `1.12.2-2.2.2-85`.

**Comment by InjuredWolf** [comment]
I take it we're now just waiting on a Chisel update with the fixes?

**Comment by Sunconure11** [comment]
What's the word regarding this? I've noticed the pull for the fix has been there for a bit.

**Comment by shdwdrake8** [comment]
Would love to be able to add Blood Magic to my server but Chisel is holding my server hostage. Please make this fix!

**Comment by drakray** [comment]
Crash in Loading 5/7, https://pastebin.com/ZUvxP3Jt
MC 1.12.2
Forge 14.23.2.2617
Chisel MC1.12-0.1.1.27 
BloodMagic 1.12.2-2.2.3-86
BunchaOther

**Comment by TehNut** [comment]
Okay `getTotalVariations()` does *not* do what I thought it did, but I guess that makes sense now that I understand it.
