### ISSUE TITLE
Crashing in 1.12.2

### ISSUE THREAD

**Issue by SupremHatchet** [Chisel-Team/Chisel#635]
This may be an issue on my part so i am sorry if i wasted your time. Anyway, while loading this mod in forge (release1.12.2-forge1.12.2-14.23.1.2561) i experience a crash, i have not yet been able to open the minecraft title screen to use this mod. I know that having this mod installed causes these crashes because when i remove it everything works fine without crashes. I have tried newer and older versions of chisel but it still crashes. I have dedicated 3gb of ram to forge. 
The mods i have installed alongside chisel:
AutoRegLib-1.3-15
better foliage-MC1.12-2.1.10
BiomesOPlenty-1.12.2-7.0.1.2313-universal
BlockArmor-1.12.2-2.4.10
DynamicSurroundings-1.12.2-3.4.7.2
gravestone-1.10.1
jei_1.12.1-4.7.8.95
Mantle-1.12-1.3.1.18
OptiFine_1.12.2_HD_U_C7
p455w0rdslib-1.12-2.0.22
PattysMoreStuff-stable-1.1.1
Quark-r1.4-122
RedstoneFlux-1.12-2.0.1.2-universal
SoundFilters-0.10_for_1.12
tinyprogressions-1.12-3.2.10+-+Beta
ToughAsNails-1.12.2-3.1.0.73-universal
ToughExpansion-1.12-3.2.10

If any of these mods causes issues with chisel, please let me know. Unfortunately, the only versions of this mod i can get the direct name of are:
Chisel-MC1.12-0.1.1.26
Chisel - MC1.12-0.1.0.22
Chisel - MC1.12-0.1.0.20
Chisel - MC1.12-0.1.0.23

Crash message:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game

I hope that this issue can be fixed because I really like this mod and don't want to have to uninstall it. Sorry if this is on my part

**Comment by Drullkus** [comment]
We can't tell much from this information, could you please give us the full crashlog? [Copy and paste the contents of the crashlog file to Gist](https://gist.github.com) and link the Gist on this issue ticket.

**Comment by SupremHatchet** [comment]
https://gist.github.com/SupremHatchet/21ebea5502a792d8b0d7a02d5ab86293
Sorry this took a while, i am new to github and am still learning everything. Tell me if you need any more information

**Comment by tterrag1098** [comment]
You forgot to install CTM
