### ISSUE TITLE
Chisel FML Log Spam and World Gen Cascading Lag

### ISSUE THREAD

**Issue by DatrixTHLK** [Chisel-Team/Chisel#637]
HI,

First off I like this mod because of how many blocks this adds and how I can decorate stuff. This mod has been having issues for a few days causing cascading lag and FML Spam.

> [20:46:36] [Server thread/WARN] [FML/]: Chisel loaded a new chunk (65536, 0  Dimension: -2147483648) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Minecraft: 1.11.2
Forge: 13.20.1.2588
Chisel: 0.1.1.31

Thanks for at least taking a look at the issue.

**Comment by pau101** [comment]
What other mods do you have installed?

**Comment by tterrag1098** [comment]
Specifically, are you using Sponge(forge) ?

**Comment by DatrixTHLK** [comment]
@tterrag1098  No, I'm not. Am I supposed to?
@pau101 Mod list: https://gist.github.com/DatrixTHLK/90abf13495b4ce9a929847cab84f259d

**Comment by tterrag1098** [comment]
Can you reproduce this on 1.12 with new versions of forge? That's my only lead atm.

**Comment by DatrixTHLK** [comment]
Sorry it took so long to get back to you. The Chisel mod works just fine on 1.12.2. I haven't had any critical errors or crashes yet.
