### ISSUE TITLE
Compress images?

### ISSUE THREAD

**Issue by Ghostlyr** [Chisel-Team/Chisel#645]
Do not you think that the images should be optimized? Resources size in `assets\chisel\textures` is scary - more than 50 megabytes.
OptiPNG `-o7` decreasing size to 2,03 MB. No textures glithces in the game was observed. But are possible with transparent blocks\items.

**Comment by tterrag1098** [comment]
Is there any change to the jar?

**Comment by Ghostlyr** [comment]
Chisel-MC1.12-0.1.1.28.jar - 17 345 667
Chisel-MC1.12-0.1.1.28 (optiPNG).jar - 4 278 811

**Comment by tterrag1098** [comment]
Thanks for the tip, I had done this a while ago, but not since we retextured quite a bit of the mod. Photoshop's default export is garbage and results in bloated files apparently :)

**Comment by Drullkus** [comment]
I didn't even export as png, I did save as png. There's actually a difference 😅
