### ISSUE TITLE
[Chisel - MC1.12.2-0.2.0.31] Could not resolve <chisel : block_charcoal2 : 1> 

### ISSUE THREAD

**Issue by NucloidTTV** [Chisel-Team/Chisel#650]
Updated from Chisel-MC1.12-0.1.1.26 to Chisel - MC1.12.2-0.2.0.31.  Getting error while loading into save

> [CHAT] ERROR: 00_recipe_changes.zs:108: Could not resolve <chisel : block_charcoal2 : 1>
> [CHAT] ERROR: Error while applying actions

![image](https://user-images.githubusercontent.com/3248262/36797957-55ff305c-1c77-11e8-9e9e-6e75d37d5a20.png)

**Comment by wamc2017** [comment]
That's an error in one of your crafttweaker scripts, report it to your modpack author, that's not a problem with the chisel mod itself... ;)
