### ISSUE TITLE
Auto-Chisel Crash on sound?

### ISSUE THREAD

**Issue by MercerK** [Chisel-Team/Chisel#651]
I think Auto-Chisel is crashing on sound. It isn't the normal ticking sound, I think. Two times a diamond chisel broke and the game has crashed. However, this is the third time it has crashed and only once did it produce a crash log. The first time - the world kicked me to main menu. Second time - world kicked me to main menu & crashed. Third time - world stop responding as a diamond chisel broke. Was able to get the game log on the third instance. Crash log from second instance.

Here is the game log - https://pastebin.com/X2f01ZUP.
Here is the one crash log - https://pastebin.com/9PVdktHG

**Comment by vinixd1997** [comment]
I get exactly the same log, everytime a chisel runs out and it trys to chisel blocks without a chisel i think

**Comment by artdude543** [comment]
Users having this on SevTech Ages now https://github.com/DarkPacks/SevTech-Ages/issues/2471 Had a few streamers with the same issue when they progressed. Is their an ETA on this @tterrag1098 ?

**Comment by Moobien** [comment]
I get the audio crash also when the autochisel is running, and ONLY when the autochisel is running. https://pastebin.com/pLfXX9VR

**Comment by tterrag1098** [comment]
Fixed via 3d38b96bcbe9244b2858bb20076255b463aa9485
