### ISSUE TITLE
Awkward tesselation of temple cobble

### ISSUE THREAD

**Issue by NotAVerb** [Chisel-Team/Chisel#652]
This texture feels harsh on the eyes to me. I think it's corners that bother me the most. Are the textures supposed to stitch together like this?
![2018-03-01_14 04 11](https://user-images.githubusercontent.com/30223331/36864668-30a838f8-1d85-11e8-83b1-727e68ac9155.png)
Is there any chance of these blocks being cleaned up a little?
Or maybe even changing the texture to be another "cracked" chisel block? Like the cracked marble peaking into the screenshot on the right side.

Also, is the golden eye block supposed to connect to other blocks of its kind? It seems incomplete as it is now.

**Comment by Drullkus** [comment]
These blocks are from the Eldritch Game, I honestly am not really going to be modifying these at all.
