### ISSUE TITLE
[1.12] java.lang.NullPointerException - when disabling blocks in config

### ISSUE THREAD

**Issue by MasterEnderman** [Chisel-Team/Chisel#653]
Forge: 14.23.2.2623
Chisel: 0.2.0.31
Crash Report: https://pastebin.com/XJwyqE6C

**Comment by ChloeDawn** [comment]
@MasterEnderman This issue only appears to affect the chisel items and the auto-chisel. A workaround for now would be to leave them enabled, then disable their recipes via [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker).

**Comment by tterrag1098** [comment]
Fixed via e7baef36bdee955f697a07f4ea30d9d6a4049a94 and 6c048728fa30fd18514026381b094cd6742364eb
