### ISSUE TITLE
[1.12.2] What's with the carpets?

### ISSUE THREAD

**Issue by NotAVerb** [Chisel-Team/Chisel#654]
The fancy chisel carpets are not accessible without cheats, is this intentional? 
When a chisel carpet is chiseled it is possible to access a third "null" variation of the carpet color. Breaking this block gives the player nothing.
I also found this error in my log file. https://gist.github.com/NotAVerb/7f947f810b8006fef1c1490ff71c59fe

V0.2.0.31

**Comment by NotAVerb** [comment]
Chisel's carpets are also transparent on their undersides.
![2018-03-13_01 07 10](https://user-images.githubusercontent.com/30223331/37323549-720ad92c-267c-11e8-9d13-188c572e411a.png)

**Comment by tterrag1098** [comment]
This seems no longer relevant 
![image](https://user-images.githubusercontent.com/3751664/43475569-35e800ee-94c4-11e8-8c3b-b95ded524ae9.png)
