### ISSUE TITLE
[1.12.2] Target a Block 

### ISSUE THREAD

**Issue by f0kx** [Chisel-Team/Chisel#655]
If i want to Chisel a Block in the World and i want a specific type of block i put it in my chisel inventory and than it doesnt work!
For example i want DENT cobble and dont want to click all the way through!
Is this feature implemented??
grats

**Comment by tterrag1098** [comment]
Yes that is implemented, it should work exactly as you described

**Comment by f0kx** [comment]
Okay strange because nothing happens...
I have 1 dent cobble in my chisel and want to switch a3x3 area cobble to dent cobble by left clicking... That's how it works right?

**Comment by tterrag1098** [comment]
![image](https://user-images.githubusercontent.com/3751664/43475451-d6e478b6-94c3-11e8-9c82-a2924855be64.png)
![image](https://user-images.githubusercontent.com/3751664/43475460-dcdd2a38-94c3-11e8-8856-2fea10c349c8.png)

Working fine here
