### ISSUE TITLE
Not really an issue but maybe something to look into

### ISSUE THREAD

**Issue by ThaDaVos** [Chisel-Team/Chisel#656]
The developer of DynMap is doing great work on adding support for modded blocks and maybe need your help for supporting chisel blocks :D

https://github.com/webbukkit/DynmapBlockScan/issues/1

**Comment by tterrag1098** [comment]
Chisel will eventually be using entirely vanilla JSON models (with extensions provided by CTM) so DynmapBlockScan should work fine in the future.

**Comment by generrosity** [comment]
Appologies @tterrag1098 for commenting on a closed issue, but I can't find it elsewhere.

I'm keen to hear when the vanilla JSON models do get implimented (and our server looooves using Chisel) - is there an appropriate open feature 'issue' or place to get notifications?

**Comment by Routhinator** [comment]
@tterrag1098 I keep finding myself here, as @generrosity did, because I am trying to get an idea when Chisel will switch to the JSON models so I can add a status to our server. At this point Chisel blocks are the only major issue with Dynmap rendering and BlockScan.

**Comment by tterrag1098** [comment]
It's already done, you can try a dev build. But I have a few things left to do before this version can be released.

**Comment by generrosity** [comment]
I think I've heard this - it's quite an update that you are making in your time. 

Thanks for confirming it's ticking along! As always, appreciate your work 👌💚

**Comment by Routhinator** [comment]
Sweet, thanks for the update @tterrag1098 !
