### ISSUE TITLE
Crash in starting (1.7.10)

### ISSUE THREAD

**Issue by michalskip98** [Chisel-Team/Chisel#660]
when i try to start minecraft, after 30-40 seconds its crashing 
on crash log i found "Could not find texture metals/aluminum/caution, and no custom texture manager was provided." What i should to do?

**Comment by NotAVerb** [comment]
If you're playing in an instance without aluminum you should disable the aluminum blocks in chisel's config.

**Comment by michalskip98** [comment]
um... how to find chisel config? xD

**Comment by NotAVerb** [comment]
This will depend on where your minecraft instance is installed.
Find your `/.minecraft/` folder. Then navigate to `/.minecraft/config/`.
Chisel's config should be inside of this folder. It should be called `chisel.cfg`.

**Comment by michalskip98** [comment]
thanks you very much

**Comment by tterrag1098** [comment]
It should be noted that that error is not a crash and would not be the cause of your game crashing.
