### ISSUE TITLE
[1.12.2] Make CTM a proper client-side dependency

### ISSUE THREAD

**Issue by Choonster** [Chisel-Team/Chisel#661]
MinecraftForge/MinecraftForge#4403 added support for sided dependencies specifically for situations like Chisel and CTM, but Chisel still uses its old, slightly hacky code to detect whether CTM is installed on the client instead of declaring it as a client-side dependency.

It appears that @tterrag1098 intended to do that back in November 2017 (as mentioned [here](https://github.com/SlimeKnights/TinkersConstruct/issues/3226#issuecomment-343405078)), but it never happened.

**Comment by Drullkus** [comment]
@tterrag1098 The problem is older forge versions is that they will crash on that. It happened with Twilight Forest...

**Comment by tterrag1098** [comment]
I think it's been long enough. Plus our current way crashes a lot too.
