### ISSUE TITLE
[1.12.2] Rusty Transparent Scaffold Connected Texture Broken

### ISSUE THREAD

**Issue by TherminatorX** [Chisel-Team/Chisel#663]
![image](https://user-images.githubusercontent.com/7256249/37571231-de6cf510-2ac7-11e8-88e5-dbd8589dfdda.png)
Unsure if and/or to what extent other transparent/ct blocks are affected
Version 1.12.2-0.2.0.31

**Comment by errorsallthethings** [comment]
Same issue as Therminator X.

Running the FTB Revelations mod pack 1.8.0 release.
Chisel version 1.12.2-0.2.0.31

![2018-04-08_09 07 13](https://user-images.githubusercontent.com/26232023/38468498-868de75a-3b0c-11e8-8370-b0934fde5535.png)

**Comment by Lewdicolo** [comment]
Still broken!

SevTech Ages v3.0.5
Chisel v1.12.2-0.2.0.31
CTM vMC1.12-0.2.3.12

![image](https://user-images.githubusercontent.com/19986227/38925002-030c5f82-42c4-11e8-9d0a-59791aa7f255.png)

**Comment by TherminatorX** [comment]
@Drullkus Got an update?
