### ISSUE TITLE
Starting up 1.12.x server with Chisel, and without CTM, gives misleading crash reports

### ISSUE THREAD

**Issue by LiaungYip** [Chisel-Team/Chisel#669]
Chisel for MC 1.12 depends on CTM.

People who don't read the CurseForge page, for whatever reason, frequently manage to install Chisel without installing CTM. (see, for example, #635, #601, #585, #572, #559.)

Sometimes, this gives an informative error message. For example, if you install only Chisel (and no other mods at all), Forge will tell you that you need CTM:

![image](https://user-images.githubusercontent.com/2173684/38148922-c433510c-349b-11e8-833d-e27283fcc4e9.png)

However, starting up with just **one** additional mod (Chisel + Tinker's Construct, for example) can cause Minecraft to crash before there's a chance to display the "CTM is missing" error. Instead, the user sees an error indicating a crash in some other mod:

    java.lang.NullPointerException: The validated object is null
    	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
    	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
    	at net.minecraft.util.registry.RegistrySimple.func_82595_a(SourceFile:35)
    	at slimeknights.tconstruct.tools.ToolClientEvents.onModelBake(ToolClientEvents.java:89)

The lack of CTM isn't pointed out in the logs, either. For example, [fml-client-latest.log](https://github.com/Chisel-Team/Chisel/files/1864486/fml-client-latest.log) doesn't mention the lack of `ctm` or `connectedtexturesmod`.

This is creating an (avoidable?) support burden on the Chisel team, and the Tinker's Construct team (see https://github.com/SlimeKnights/TinkersConstruct/issues/3434, [#3299](https://github.com/SlimeKnights/TinkersConstruct/issues/3299), [#3284](https://github.com/SlimeKnights/TinkersConstruct/issues/3284), [#3319](https://github.com/SlimeKnights/TinkersConstruct/issues/3319), [#3226](https://github.com/SlimeKnights/TinkersConstruct/issues/3226), for example.)

The support burden may be lightened if Chisel is more aggressive about detecting the lack of CTM and failing very early. Adding CTM as a "Required Library" on CurseForge may also help. ([Currently, CTMLib is listed as an Embedded Library](https://minecraft.curseforge.com/projects/chisel/relations/dependencies)), but there are no ["Required Libraries" listed](https://minecraft.curseforge.com/projects/chisel/relations/dependencies?filter-related-dependencies=3).)

Possibly related: #661 ?

**Comment by TehNut** [comment]
>Adding CTM as a "Required Library" on CurseForge may also help. (Currently, CTMLib is listed as an Embedded Library), but there are no "Required Libraries" listed.)

Pretend that tab doesn't exist. It's almost always wrong. Look at the individual files. It is listed.

**Comment by LiaungYip** [comment]
> Pretend that tab doesn't exist. It's almost always wrong. Look at the individual files. It is listed.

![image](https://user-images.githubusercontent.com/2173684/38150235-462b68b6-34a1-11e8-996e-17bad3f593c4.png)

This is very good to know - thanks for pointing it out.

**Comment by TehNut** [comment]
Also I'm pretty sure this is fixed in https://github.com/Chisel-Team/Chisel/commit/5cb19a69e736fa8a21ad5e0c6931daba7679ece5

**Comment by tterrag1098** [comment]
It is, yes. The problem with the old way is a forge bug that will probably never be fixed.
