### ISSUE TITLE
[1.12.2] Crashed on hitting a chiseled block with EvilCraft's blood on it.

### ISSUE THREAD

**Issue by XBagon** [Chisel-Team/Chisel#671]
[crash-2018-04-11_19.02.46-client.txt](https://github.com/Chisel-Team/Chisel/files/1899795/crash-2018-04-11_19.02.46-client.txt)

**Comment by XBagon** [comment]
Not sure if Chisel's or EvilCraft's fault.

**Comment by tterrag1098** [comment]
This is on EvilCraft, they are passing a null render layer to Block.canRenderInLayer, which is invalid.
