### ISSUE TITLE
On Worldjoin crash

### ISSUE THREAD

**Issue by DrKilledalot** [Chisel-Team/Chisel#672]
Playing on a server , i crash evrytime i join the world (the server doesnt crash) after I
tried connecting a TD fluiduct to mekanism turbine, which worked without a problem in our previus modpack that didnt have chisel

heres the report: https://pastebin.com/qVhVSKZp 

EDIT: Found that this only happens with TD ducts (all types) on a mekanism valve

**Comment by tterrag1098** [comment]
Update TD
