### ISSUE TITLE
Crash when CTM blocks with EvilCraft blood on top are broken

### ISSUE THREAD

**Issue by genandnic** [Chisel-Team/Chisel#673]
#### Short description:
The game crashes when I try to break a chiseled block with blood on top of it. Not sure if this is a bug with EvilCraft, CTM, or Chisel.
#### Steps to reproduce the problem:

1. Place a block with CTM from the mod Chisel (In my case it was the circular cobblestone block)
2. Kill a mob on top of the block with connected textures so that there's blood on the block
3. Break the block

#### Versions:
- EvilCraft:  1.12.2-0.10.53
- CyclopsCore: 1.12.2-0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2611
- Chisel: 1.12.2-0.2.0.31
- CTM: 1.12.2-0.2.3.12

**Comment by Chris-The-Lion** [comment]
Just had this issue crash the game for me, hoping there is a fix soon
