### ISSUE TITLE
Crashing in Sevtech when breaking Marble with Black Quartz AIOT

### ISSUE THREAD

**Issue by RandomLibrarian** [Chisel-Team/Chisel#676]
https://pastebin.com/jfyWtm3e

Game crashes when I swing the AIOT at Marble. (nevermind, happens with anything even hands)

**Comment by RandomLibrarian** [comment]
Backed up my world folder and created a new server in SevTech 3.0.6. When I logged in after restoring the backup it is still happening.

**Comment by tterrag1098** [comment]
I can't see how this would happen, unless some other mod has broken particles...It only happens in Sevtech?

**Comment by artdude543** [comment]
I wonder if Fancy Block Particles could be causing this? @Sojumonkey could you disable the mod and try again? As I can't reproduce the issue but I have a hunch that would be the cause here.

**Comment by RandomLibrarian** [comment]
Disabling fancy particles did indeed fix the issue. Working fine now. Wierd how everything worked fine for a while then at age 2 the problem started. Thanks
