### ISSUE TITLE
Crash on craft table use if craftbook is opened

### ISSUE THREAD

**Issue by Pirog17000** [Chisel-Team/Chisel#677]
So crash happens if use crafting table with pre-opened craftbook.
Or, open crafting table and then click on craftbook.
Also from time to time crashes if left click with chisel on any block, even on stone.

Crashlog https://pastebin.com/9Ujrgcy5
Server config https://pastebin.com/kfFTn8ds

So I've disabled craft of some variations and it began happening.
Also, if I load same config to the client, client won't load at all, crashing.

`    at team.chisel.client.ClientProxy.preInit_impl(ClientProxy.java:85)
    at team.chisel.client.ClientProxy.registerModels(ClientProxy.java:69)`

`java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraftforge.oredict.ShapedOreRecipe@4257352c Name: chisel:antiblock`

**Comment by tterrag1098** [comment]
Same as #679
