### ISSUE TITLE
[1.12.2] Most chisel blocks don't display their color in JEI

### ISSUE THREAD

**Issue by Alan19** [Chisel-Team/Chisel#678]
JEI's color search does not display the colors of most chisel blocks.

![2018-04-21_11 14 14](https://user-images.githubusercontent.com/11682762/39085742-2f3aa42c-4555-11e8-93d1-83a4131db014.png)
![2018-04-21_11 14 20](https://user-images.githubusercontent.com/11682762/39085743-2f45d3ba-4555-11e8-84ba-348640bb9741.png)

**Comment by P3rf3ctXZer0** [comment]
Do you have foamfix installed? If so try Lawful and see if that fixes it.

**Comment by Alan19** [comment]
It doesn't. It still doesn't display the colors even if Chisel, JEI, and CTM are the only mods installed I think.

**Comment by P3rf3ctXZer0** [comment]
I would like your full mod please.

**Comment by Alan19** [comment]
1.12.1-CustomOreGen
  advancedmortars-1.12.2-1.6.20
  AdvancedRocketry-1.12.2-1.4.0-80
  AppleCore-mc1.12.2-3.1.1
  AppleSkin-mc1.12-1.0.9
  appliedenergistics2-rv5-stable-11
  Aroma1997Core-1.12.2-2.0.0.0.b150
  AromaBackup-1.12.2-2.1.1.3.b98
  artisanworktables-1.12.2-1.19.0-SNAPSHOT.4
  astralsorcery-1.12.2-1.8.10
  athenaeum-1.12.2-1.14.0
  AutoRegLib-1.3-17
  base-1.12.2-3.7.2
  Baubles-1.12-1.5.2
  BedBugs-1.12-1.0.1
  BetterAdvancements-1.12.2-0.0.7.42
  BetterBuildersWands-1.12-0.11.1.24569d0d70
  BetterFps-1.4.8
  BetterQuesting-3.5.256
  BiblioCraft[v2.4.3][MC1.12.0]
  BiomesOPlenty-1.12.2-7.0.1.2389-universal
  blockcraftery-0.1.3
  BloodMagic-1.12.2-2.2.12-97
  Botania r1.10-354
  ChatFlow-1.4-7
  Chisel-MC1.12.2-0.2.0.31
  chiselsandbits-14.16
  ChunkPregeneratorV1.12-1.8
  CoFHCore-1.12.2-4.4.1.12-universal
  CoFHWorld-1.12.2-1.1.1.12-universal
  ContentTweaker-1.12.2-4.5.0
  Controlling-3.0.6
  CosmeticArmorReworked-1.12.2-v1
  CraftingTweaks_1.12.2-8.1.9
  CraftTweaker2-1.12-4.1.8
  CTM-MC1.12-0.2.3.12
  CustomMainMenu-MC1.12.2-2.0.8
  cyberware-1.12.2-0.2.10.12
  CyclopsCore-1.12.2-0.11.5
  DimensionalDoors-3.0.9-287
  DrCyanosLootableBodies_1.12-2.4.0
  DungeonTactics-1.12.2-0.14.2
  DynamicSurroundings-1.12.2-3.4.9.13
  ElectroblobsWizardry-4.1.1-MC1.12.2
  elulib-0.1.12
  EnchantmentDescriptions-1.12.2-1.1.8
  Enchiridion-1.12.2-3.3.3
  EnderCore-1.12.2-0.5.22
  EnderIO-1.12.2-5.0.24
  EnderZoo-1.12.1-1.4.0.49
  Erebus-1.0.22
  EvilCraft-1.12.2-0.10.56
  extraalchemy-0.3.8.4-release
  foamfix-0.9.9.1-1.12.2-law
  forestry_1.12.2-5.8.0.290
  Forgelin-1.6.0
  Guide-API-1.12-2.1.5-60
  ImmersiveEngineering-0.12-82
  InventoryTweaks-1.64-dev
  IvToolkit-1.3.3-1.12
  jei_1.12.2-4.9.1.187
  jeibees-0.9.0.5-mc1.12.2
  journeymap-1.12.2-5.5.2
  librarianlib-1.12.2-4.9
  LibVulpes-1.12.2-0.2.8-31-universal
  llibrary-1.7.9-1.12
  Login_Shield-1.12.2-3-g7c6e7ac
  LootTweaker-1.12.2-0.0.7
  lostcities-1.12-2.0.7
  MagicBees-1.12.2-3.1.9
  MagnumOpus-1.12.2-0.0.19
  Mantle-1.12-1.3.2.24
  Mekanism-1.12.2-9.4.10.345
  MetalChests-v1.2.2.g3d3d54b
  modtweaker-4.0.5a
  moreoverlays-1.13-mc1.12.1
  Morpheus-1.12-3.3.2
  MTLib-3.0.4
  NaturesCompass-1.12.2-1.5.1
  NetherEx-1.12-2.1.14.15
  NetherPortalFix_1.12.1-5.3.13
  NoFov-MC1.12-1.0.1
  plustic-6.4.0.0
  PrimalCore-1.12.2-0.6.54
  Quark-r1.4-123
  QuickLeafDecay-MC1.12.1-1.2.4
  RecurrentComplex-1.4.7
  RedstoneFlux-1.12-2.0.1.2-universal
  Reliquary-1.12.2-1.3.4.763
  ResourceLoader-MC1.12.1-1.5.3
  ReWIRED-1.0.3
  rockhounding_core-1.12.2-3.08
  rockhounding_oretiers-1.12.2-3.05
  RoguelikeDungeons-1.12.2-1.8.0
  rustic-1.0.4
  StandardExpansion-3.4.141
  TConstruct-1.12.2-2.10.0.79
  tellme-1.12.2-0.5.6
  Thaumcraft-1.12.2-6.1.BETA13
  TheBetweenlands-3.3.8-universal
  theoneprobe-1.12-1.4.22
  topaddons-1.12.2-1.6.0
  TrashSlot_1.12.1-8.4.6
  twilightforest-1.12.2-3.7.424-universal
  ValkyrienWarfareRevamped-1.12.2-v0.9_alpha-full (1)
  VanillaFix-1.0.4-35
  VTweaks-1.12.2-1.4.12b
  Waystones_1.12.2-4.0.43
  wizardry-0.8.5

**Comment by Alan19** [comment]
Colors aren't displayed when only JEI, Chisel, and CTM installed

**Comment by P3rf3ctXZer0** [comment]
Forge version?

**Comment by Alan19** [comment]
I'm using 14.23.3.2689 for the modpack and 14.23.3.2702 for the pack with only Chisel, JEI, and CTM.

**Comment by P3rf3ctXZer0** [comment]
why are you using two separate versions?

**Comment by Alan19** [comment]
I haven't updated forge on the modpack yet

**Comment by P3rf3ctXZer0** [comment]
Update that first and make sure all your mods are up to date especially JEI.

**Comment by Alan19** [comment]
Only bookshelves and the vent laboratory blocks seem to have colors listed after updating forge and JEI

**Comment by tterrag1098** [comment]
I can't see why this wouldn't work, seems like a JEI issue. @mezz is there anything that needs to be done specifically to support this feature?

**Comment by mezz** [comment]
JEI looks at the texture sprites, it seems yours is very weird:
https://github.com/Chisel-Team/Chisel/blob/ed618047a3bb5133dbc02dd8b4325c1d37e67a57/src/main/java/team/chisel/client/TextureStitcher.java#L25

Relevant JEI code here, in debug I see `frameCount == 0` so I can't get anything from it.
https://github.com/mezz/JustEnoughItems/blob/677d286ae25772e812f1938a24bac1be2fd7125e/src/main/java/mezz/jei/color/ColorGetter.java#L149-L166

**Comment by Alan19** [comment]
Thanks for looking into it mezz!

**Comment by tterrag1098** [comment]
So vanilla's lazy copyFrom method doesn't actually copy the texture data...nice. I'll delegate those methods then.
