### ISSUE TITLE
Blood Magic-Chiseled Blood Runes Missing textures 1.12.2

### ISSUE THREAD

**Issue by Drogo01154** [Chisel-Team/Chisel#682]
I have recently been developing a modpack with the latest version of Blood Magic and Chisel. But there seem to be missing textures for the Chiseled Blood runes.

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-Team/Chisel/commit/de5e6a48a91f0bbd58ce7b37dc0962e71cb7045a
