### ISSUE TITLE
[1.12.2] RFTools Quarry Builder dropping Chisel blocks in-world

### ISSUE THREAD

**Issue by NielsPilgaard** [Chisel-Team/Chisel#685]
Hey! I've reported this in to RFTools aswell: https://github.com/McJty/RFTools/issues/1726

Issue description:
When mining an area with the Builder, with a Quarry Card, all blocks from the Chisel mod are dropped in-world, instead of being put in the inventory on top of the builder.

Steps to reproduce:
Place Chisel Marble, I made a 7x7x7, but that shouldn't matter.
Place Builder.
Use Quarry Card on builder, and set the area to the Marble cube.
Supply the Builder with power, and put a chest above it.
Run the Builder
-> Bug

Versions:

    Minecraft: 1.12.2
    Forge: 1.12.2-14.23.3.2673
    CompatLayer (only if on Minecraft 1.10 or 1.11):
    McJtyLib: 1.12-2.6.7
    RFTools:1.12-7.33
    Chisel-MC: 1.12.2-0.2.0.31

Possibly incompatible mods and versions:

Relevant logs, if any:
The latest.log has no information relating to RFTools or Chisel.

First reported in NillerMedDild/Enigmatica2Expert#43

**Comment by josephcsible** [comment]
Per the linked report, it looks like this is actually a bug in Tool Progression.

**Comment by NielsPilgaard** [comment]
Oh I see. Could you elaborate, so I can (hopefully) convey it to @Tyra314? :)

**Comment by josephcsible** [comment]
https://github.com/NillerMedDild/Enigmatica2Expert/issues/43#issuecomment-385866288

**Comment by NielsPilgaard** [comment]
Don't know how I missed that, thanks.
