### ISSUE TITLE
erroneous Blocks

### ISSUE THREAD

**Issue by xXDarkNovaXx** [Chisel-Team/Chisel#689]
I noticed that somehow some blocks are somehow faulty and not displayed correctly but there are several blocks that have this error.
Screenshot:
http://prntscr.com/jidhmz

I noticed that the big fan can not be displayed properly, you can adjust somehow in the Minecraft 1.7.10?
Screenshot:
http://prntscr.com/jids5t

I do not use a texture pack i have already disabled the shader but the problem still exists
Shader is Sildurs Vibrant 1.17
Minecraft 1.7.10

Translate by Google

**Comment by xXDarkNovaXx** [comment]
I noticed that the big fan can not be displayed properly, you can adjust somehow in the Minecraft 1.7.10?
Screenshot:
http://prntscr.com/jids5t

**Comment by tterrag1098** [comment]
1.7.10 is no longer receiving updates, sorry.
