### ISSUE TITLE
Crash when clicking in the Auto-Chisel GUI with Upgrades Disabled

### ISSUE THREAD

**Issue by LuigiHutch** [Chisel-Team/Chisel#69]
Chisel-2.9.3.9

See title ^: https://gist.github.com/LuigiHutch/7c10faa82eb3d76a73e3

**Comment by tterrag1098** [comment]
Thanks, that's an oversight with disableable features. Will fix soon.

**Comment by LuigiHutch** [comment]
Fixed :D
