### ISSUE TITLE
[Enhancement] Hide the Energy (FE) bar when is not needed

### ISSUE THREAD

**Issue by Insane96** [Chisel-Team/Chisel#696]
I have a pack with no mods that add energy so the FE bar is useless. Would be cool if could be hidden when not needed.

**Comment by tterrag1098** [comment]
I agree, this was originally planned but never implemented.

**Comment by tterrag1098** [comment]
There is no way for me to know if FE is "used" or not (the capability always exists, because it's from Forge), but I will tie the rendering of the power bar to the "autoChiselTakesPower" config. You can disable this for packs without any power generation.
