### ISSUE TITLE
FML does not represent CTM as a missing dependency

### ISSUE THREAD

**Issue by 1cedsoda** [Chisel-Team/Chisel#699]
I am using:
+ FMl 14.23.4.2707
+ Chisel 1.12.2 0.2.0.31

FML does not represent CTM as a missing dependency!
This causes [FATAL] errors when loading graphics:
#669 #692 #694 #695

**Comment by tterrag1098** [comment]
This will be fixed in the next version: https://github.com/Chisel-Team/Chisel/commit/5cb19a69e736fa8a21ad5e0c6931daba7679ece5
