### ISSUE TITLE
Add Existing Blocks to the Chisel [Question]

### ISSUE THREAD

**Issue by acanady** [Chisel-Team/Chisel#702]
So I want to know if there's a way to add existing blocks to the list of blocks able to be chiseled.  Let me give you the scenario. So i have project red right, it adds basalt. However, the project red basalt isn't seen as the same as Chisel's basalt, so I can't switch between the two in the Chisel. Is there some sort of JSON file that I can edit that would allow me to say, add ProjectRed's basalt to the Chisel so that I could move back and forth between the two? This isn't unlike how Astral Sorcery marble and Chisel marble works. They're two different types of marble but the Chisel let's you swap between the two. ProjectRed also adds marble, it too isn't recognized by the Chisel.

**Comment by tterrag1098** [comment]
ModTweaker supports this
