### ISSUE TITLE
[1.12.2] Game crashes when getting zapped by MrCrayFish's Furniture Mod's Electrical Fence when it is placed on any chiseled block.

### ISSUE THREAD

**Issue by SonicX8000** [Chisel-Team/Chisel#704]
Referenced Issue:
https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod/issues/70

Minecraft: 1.12.2
Forge: 14.23.4.2709

Mods:
Chisel-MC1.12-0.2.0.30
CTM-MC1.12-0.3.0.15
furniture-4.2.0-1.12.2

Crash Report:
https://pastebin.com/HvZvz9VK

---
When you place MrCrayFish's Furniture Mod's Electrical Fence on any chiseled block... the game will crash upon getting zapped by the fence. If it's on a non-chiseled block the game won't crash.

I've done a test without "CTM-MC1.12-0.3.0.15" which shows missing textures for the chiseled blocks and the same thing happens.

**Comment by tterrag1098** [comment]
He is passing the wrong state (his) into our `isOpaqueCube`, not a chisel bug.
