### ISSUE TITLE
Missing texture in Chisel mod 1.12.2

### ISSUE THREAD

**Issue by Rockefeller157** [Chisel-Team/Chisel#706]
Hello.
I have a problem with all versions of chisel for minecraft 1.12.2.
All blocks have the missing texture, except the bookshelves.

[https://cdn.discordapp.com/attachments/326223813253529611/464002882312601622/unknown.png](url)
[https://cdn.discordapp.com/attachments/326223813253529611/464003007172968468/unknown.png](url)

Thanks for your help.

**Comment by rchard2scout** [comment]
I had the same problem, it's fixed by adding [CTM](https://minecraft.curseforge.com/projects/ctm). See issue #699.

**Comment by AnimeShrek568** [comment]
Well, I added CTM, and it did not fix it. Is Chisel conflicting with one of my mods?
![GitHub](https://user-images.githubusercontent.com/54667580/63932474-ebe70300-ca5f-11e9-98a5-f51f093a7e74.png)

**Comment by tterrag1098** [comment]
This is CTM: https://minecraft.curseforge.com/projects/ctm

Not sure what you downloaded.

**Comment by LexWrites** [comment]
You need to put CTM in your resource pack folder.

**Comment by tterrag1098** [comment]
What the deleted comment said is not accurate. CTM is a mod (Connected Textures *Mod*) and is installed to the mods folder like any other mod.

**Comment by LexWrites** [comment]
That seems like the resource pack version of it. I have it too, but for it to work properly you have to get the mod version. 
Resource pack:
<img width="849" alt="Screen Shot 2020-05-09 at 2 57 39 PM" src="https://user-images.githubusercontent.com/65042143/81485865-8873be80-9205-11ea-8d63-6dd7b44a574e.png">

Mod:
<img width="835" alt="Screen Shot 2020-05-09 at 2 58 00 PM" src="https://user-images.githubusercontent.com/65042143/81485872-9590ad80-9205-11ea-9474-736104541fd2.png">

**Comment by tterrag1098** [comment]
There is no "resource pack version" of CTM. CTP is a resource pack that *uses* CTM, but it doesn't provide any features, because it's not a mod.
