### ISSUE TITLE
Crash when breaking chiseled block

### ISSUE THREAD

**Issue by brisingraerowing** [Chisel-Team/Chisel#708]
[Crash Log](https://gist.github.com/BrisingrAerowing/5833adaea645054a42b7cfea9bdfb031)

Happened when breaking a Chiseled Reinforced Stone Bricks from UCW. This seems similar to #704, but only references Chisel. I'm going to poke Asie about this as well.

**Comment by asiekierka** [comment]
JustEnoughIDs pops up a lot in these crash logs I see.

**Comment by brisingraerowing** [comment]
Looks like they're aware of the issue already. I'm probably going to reinstall NEID until this is fixed there.
