### ISSUE TITLE
Forge multipart and textures

### ISSUE THREAD

**Issue by Sunconure11** [Chisel-Team/Chisel#71]
It appears some blocks, such as marble, when you use multipart on them, have some issues with missing textures.

**Comment by T145** [comment]
I have experienced the same issue. I did some testing with the latest FMP and the earliest you can let modded MC load at now (1.1.1.321), and neither helped. I also went back to Cricket's Chisel 2 and performed the same tests, and recieved the same results:

![bug](http://i1064.photobucket.com/albums/u370/MegaT145/Bugs/Chisel%20amp%20FMP%20conflict.png)

[INpureCore](http://www.curse.com/mc-mods/minecraft/223792-inpurecore) is pretty much the best option to cull NEI of those multiparts. Out of sight, out of mind.

**Comment by tterrag1098** [comment]
There is nothing we can do to fix this.
