### ISSUE TITLE
Better Foliage and Chisels' Auto-Chisel texture issue

### ISSUE THREAD

**Issue by SanAndreaP** [Chisel-Team/Chisel#716]
Forge: 1.12.2-14.23.4.2738
Better Foliage: 2.1.10
Chisel: 1.12.2-0.2.0.31
CTM: 1.12.2-0.3.2.18

I'm not sure if this is a compat issue on the side of Better Foliage or Chisel, so I'm gonna post it here and on Better Foliages Issue Tracker (https://github.com/octarine-noise/BetterFoliage/issues/193). The problem is if both mods are installed, I get a weird Missing Texture block inside the Auto Chisel block itself:
![](https://i.imgur.com/OdpMU8H.png)

Disabling Better Foliage via configuration does nothing to fix this issue.

Here's the betterfoliage log:
https://gist.github.com/SanAndreasP/6ce05c704fc4caae17afc7b8b084e869

latest.log
https://gist.github.com/SanAndreasP/6e1c465d4e70f5b71e333152dc2b9b04

debug.log
https://gist.github.com/SanAndreasP/05d21cf58afae267f9017ac8ad312f80

**Comment by ChloeDawn** [comment]
Does this still happen when you remove OptiFine?

**Comment by SanAndreaP** [comment]
I don't have OptiFine

**Comment by ChloeDawn** [comment]
Oh, my bad, I misread one of the BetterFoliage log entries

**Comment by GmanAtheist** [comment]
OK, So. All was well in the world of Minecraft 1.12.2. Then I added Chisel-MC1.12.2-0.2.0.31 and shit hit the fan. Chisel blocks has no textures. Here is the list of mods I use. No crashes. Just that I love Chisel and have used it in MC 1.7.10 for years. I need it to work in MV 1.12.2. It is NOT Better foliage problem , as I removed it and still no Chisel textures.Can anyone please help. 
![snag-0000 07-08-2018 19 15 19 james1](https://user-images.githubusercontent.com/5624207/43794783-48a2fa32-9a77-11e8-8bf4-2329148292eb.jpg)
![snag-0001 07-08-2018 19 19 08 james1](https://user-images.githubusercontent.com/5624207/43794784-48bcfd60-9a77-11e8-8827-12389fb555a6.jpg)
![snag-0002 07-08-2018 19 19 24 james1](https://user-images.githubusercontent.com/5624207/43794785-48d607b0-9a77-11e8-9fb8-9b0f2cc9e10a.jpg)

**Comment by ChloeDawn** [comment]
@GmanAthiest install CTM, it's required by Chisel. It states that on the project page. Your issue is not the same as this ticket.

**Comment by GmanAtheist** [comment]
@InsomniaKitten . Thanks a lot. Yep. That sorted the problem. You are a star. Much appreciated. :-)

**Comment by ChloeDawn** [comment]
This is an issue that BetterFoliage appears to not support `forge:multi-layer` block models. Not sure the exact reason why they are not supported, but I know it is the fact that this block utilizes the Forge feature that it is broken. The blockstate JSON in question can be seen [here](https://github.com/Chisel-Team/Chisel/blob/2d484ec53042d434d56f0c265c8ee5050c411812/src/main/resources/assets/chisel/blockstates/auto_chisel.json).

**Comment by hron84** [comment]
@GmanAtheist I strongly recommend you to use Twitch client as it installs dependencies automagically.

**Comment by charliegc4** [comment]
After more than a year, any update?

I don't see why other mod's machines do not have an issue with Better Foliage, just the Chisel auto-chisel. Is there a way to fix it, even if it is temporary?

**Comment by tterrag1098** [comment]
You can disable mipmaps, other than that no. As described above, it affects any mod with a certain kind of model, including The Midnight which is linked just above your comment.

**Comment by charliegc4** [comment]
Why would I want to change my video settings for an otherwise nice display just for one machine? But I found a solution anyway; as this was THE ONLY machine that had this problem, and I don't use it that often, I put it behind a door, so my workshop looks nice. ;-)

And it saves having to place it when I need it and re-connect the conduits.
