### ISSUE TITLE
[1.12.2] Client Crash on Dedicated Server when Selecting Chisel

### ISSUE THREAD

**Issue by Xhale1** [Chisel-Team/Chisel#717]
Hey,

So me and two other people are getting client side crashes when selecting thee chisel on a dedicated server. All three of us tested it. We craft it, move it to the hotter, and all is good. We equip the chisel so that it's in use, then 3-5 seconds later, the game freezes for a second then crashes. It works perfectly fine in single player. It has no effect on the server.

For me, the crash happened at the exact moment I looked at spruce planks in the world, if that helps.

Here is a crash log: https://pastebin.com/HGmjNdEt

We are using the modpack Half Wit with Chisel 0.2.2.31 and CTM 0.3.2.18.

Thanks

**Comment by tterrag1098** [comment]
Duplicates Chisel-Team/ConnectedTexturesMod#72
