### ISSUE TITLE
[1.12.2] Marble and Limestone gen.

### ISSUE THREAD

**Issue by TheSnowyChickens** [Chisel-Team/Chisel#718]
Hello,
at first, I found a similar bug report for Quark, but this is not a report against Quark, and I remember back that I always created an issue for this topic, but I could not found it under the 500 already closed issues. :D 

So, now the bug:
![grafik](https://user-images.githubusercontent.com/29357962/43041733-c3a936cc-8d68-11e8-808b-e4b7f2e0b36c.png)

Marble and Limestone generating in the lush caves from Actually Additions.
This is a JED Biomes' o Plenty World

1.12.2
Forge 2739
Chisel 0.2.0.31
Actually Additions 137

EDIT: Im stupid, I reported this issue back then to Actually and not to chisel. Ups. :)
https://github.com/Ellpeck/ActuallyAdditions/issues/891 : I will re-open the issue on Actually's side, if I can re-open it at all.

**Comment by tterrag1098** [comment]
Chisel only replaces stone when generating, which means they are placing these caverns after we generate and not removing the blocks. It's on them to fix.
