### ISSUE TITLE
java.lang.NoClassDefFoundError: jline/internal/Preconditions

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [Chisel-Team/Chisel#719]
https://pastebin.com/DNjEQ5HK

**Comment by wamc2017** [comment]
Duplicate of https://github.com/Chisel-Team/ConnectedTexturesMod/issues/72

Update chisel to 0.3.2.35 and ctm to 0.3.2.18 ...

**Comment by Pythonic-Rainbow** [comment]
@tterrag1098  Chisel 0.3.2 not availble on CurseForge

**Comment by tterrag1098** [comment]
This was a CTM bug, not Chisel

**Comment by Pythonic-Rainbow** [comment]
So I only have to update CTM I guess? thanks
