### ISSUE TITLE
Add a way to obtain these two vanilla blocks in survival

### ISSUE THREAD

**Issue by LuigiHutch** [Chisel-Team/Chisel#72]
Im not sure how feasable this would be but, please as a way to obtain these two blocks in survival:

![2015-12-13_10 12 07](https://cloud.githubusercontent.com/assets/9326429/11766505/94b25e9a-a182-11e5-9aa5-70bd44e27941.png)
- These blocks are: minecraft:log 12 and minecraft:double_stone_slab 8.
- The wood block on the left is the variant where is has the bark all the way round it.
- I know factorization has a way to get the stone slab block but it would be nice if chisel added a way too.

Thanks for reading
 -LuigiHutch

**Comment by tehFoxx0rz** [comment]
I've made Chisel groups for all logs in my personal pack with Minetweaker, with all their rotations in including this one, basically turning the chisel into a log rotating tool on top of a way to get this log form.  Functionality like that could be neat.

**Comment by Drullkus** [comment]
I added chiselablility for the double_stone_slab:0 as well as double_stone_slab:8 in commit 8d35125.

**Comment by Drullkus** [comment]
Unable to do in 1.9 due to how blocks-items are handled.
