### ISSUE TITLE
[Suggestion] Add mineralogy granite, diorite, andesite, marble, basalt, and limestone

### ISSUE THREAD

**Issue by Trinsdar** [Chisel-Team/Chisel#720]
Could you add those blocks to their respective catagories, such as the basalt under basalt and such?

**Comment by tterrag1098** [comment]
Generally I leave this up to the mod to do - we have a simple API for registering variants. if I added compatibility for every mod with similar blocks I'd have more compatibility code than anything else.

**Comment by Bulldog83** [comment]
May be you can use OreDictionary for symilar stone types?

**Comment by tterrag1098** [comment]
We moved away from ore dictionary for things like this, most mods don't expect rock types to be converted. Best to just add support explicitly on their end.
