### ISSUE TITLE
errors in console on spongeforge 1.12.2

### ISSUE THREAD

**Issue by Pa4ok** [Chisel-Team/Chisel#724]
https://gist.github.com/Pa4ok/ade7328a8249b73ede12b4242a788aa5
Minecraft : 1.12.2                                                                                                                                                                                        
SpongeAPI : 7.1.0-SNAPSHOT-7105dfc                                                                                                                                                                         
SpongeForge : 1.12.2-2705-7.1.0-BETA-3371                                                                                                                                                                  Minecraft Forge : 14.23.4.2739
chisel: Chisel-MC1.12.2-0.2.0.31

**Comment by gudenau** [comment]
The log says to report it to the Sponge people.
```
[14:26:10] [Server thread/ERROR] [Sponge]: /* Sponge's tracking system is very dependent on knowing when
a change to any world takes place, however there are chances
where Sponge does not know of changes that mods may perform.
In cases like this, it is best to report to Sponge to get this
change tracked correctly and accurately. */
```
