### ISSUE TITLE
Tesselating Blocks Crash

### ISSUE THREAD

**Issue by CaveJohnsonn** [Chisel-Team/Chisel#725]
I'm playing FTB Continuum, with only the default mods installed, and I have gotten about 6 or 7 world crashes due to tesselating blocks. I'll post the pastebins below. Please help.

https://pastebin.com/257FJwwz
https://pastebin.com/JacjxunJ
https://pastebin.com/cxtUfxZa
https://pastebin.com/LQh4P1eE 

I won't post 'em all, but this is what I have. Sorry for it not being in format.

Edit: This one happened while I was placing some dust into the Immersive Engineering Arc Furnace, dunno if that specifically helps anything. https://pastebin.com/SFKLMfby

**Comment by tterrag1098** [comment]
> `CTM-MC1.12.2-0.3.1.16.jar`

You are outdated.
