### ISSUE TITLE
Performance issues/memory leak? with version 0.2.0.31

### ISSUE THREAD

**Issue by theland10** [Chisel-Team/Chisel#726]
I ran into an issue with version 0.2.0.31. I was having performance issues with my modpack and eventually tracked it down to Chisel 0.2.0.31. I have 16gb total in my system and I'm allocating 6gb to the pack. Soon after loading up a new world with 0.2.0.31 installed my java ram usage would go through the roof, using 10-11gb and taxing out my system causing the game to lock up. Rolling back to 0.2.0.30 solved the issue.

**Comment by tterrag1098** [comment]
There is very little difference between those two versions. If this is an issue, it seems more likely it would be with CTM, not Chisel.

**Comment by tterrag1098** [comment]
Closing due to lack of response.
