### ISSUE TITLE
Slabs show twice in NEI, Slabs for the top half and Slabs for the bottom half

### ISSUE THREAD

**Issue by LuigiHutch** [Chisel-Team/Chisel#73]
Chisel: 2.9.4.10 
NEI: 1.0.5.118

Slabs show twice in NEI, Slabs for the top half of the block and Slabs for the bottom half of the block.

See Image:
![2015-12-13_17 03 22](https://cloud.githubusercontent.com/assets/9326429/11768124/7b791d36-a1bb-11e5-8e67-c14202d770d2.png)

 -LuigiHutch

**Comment by Drullkus** [comment]
Outdated; We no longer have slabs
