### ISSUE TITLE
Animated Textures not Animating (and Ender Offset Wand issue)

### ISSUE THREAD

**Issue by brisingraerowing** [Chisel-Team/Chisel#731]
None of the animated textures (e.g. fans) are animating, and the Ender Offset wand is moving things by two blocks no matter where I click (tested with the large fan).

[Modlist](https://gist.github.com/BrisingrAerowing/6b8ef35f71c944e00a4c8ed3309cb4d3)

Chisel: 0.2.0.31
CTM: 0.3.2.18
Forge: 14.23.4.2757
MC: 1.12.2

**Comment by brisingraerowing** [comment]
Forget the EOW issue. User Error.

**Comment by JBSTheGamer** [comment]
i have that same problem it was animated before in my same world but now they are no longer animated

**Comment by tterrag1098** [comment]
VanillaFix is not supported due to the changes it makes to rendering and my own code.

**Comment by JBSTheGamer** [comment]
how do i fix my chisel textures to make it animate again since vanillafix broke the animating textures

**Comment by Andromander** [comment]
One solution I know of is to go to VanillaFix's config and turn off/set `textureFixes` to false.

**Comment by ZombieHDGaming** [comment]
It's been fixed on our end and everything is working fine now in my own testing pack and such. I'll release 1.0.10 within the next week with an appropriate fix for this to not be an issue anymore.

**Comment by JBSTheGamer** [comment]
thx it fixed it
