### ISSUE TITLE
Add back in missing blocks (iron bars, glass panes, asphalt, concrete)

### ISSUE THREAD

**Issue by darchitectlp** [Chisel-Team/Chisel#732]
Any chance of getting these readded? They were some of my favorites. The upward facing iron bar spikes in particular were great for garden edging, parapet tops and fence tops.

And I loved having speed-boosting concrete running through my base!

Thanks for making this mod.

**Comment by tterrag1098** [comment]
Concrete never went away. The others will be added soon, see #670 et al.
