### ISSUE TITLE
[1.12.2] IChisel don't work with a custom modtweaker recipe.

### ISSUE THREAD

**Issue by TheSnowyChickens** [Chisel-Team/Chisel#736]
https://github.com/jaredlll08/ModTweaker/issues/680#event-1841930385

There you can find all infos. :=)

**Comment by tterrag1098** [comment]
Sorry, could you be clearer about what exactly is happening? Is this about the GUI or in-world? I don't see how the iChisel could behave differently, it's all the same code for getting the variants.

**Comment by TheSnowyChickens** [comment]
Okay: ( CCBlock = Coal coke block )
- I added this script and I reload MC.

- In the Iron and Diamond Chisel, all is normal. I insert the CCBlock and I can chisel it to all 3 varients of the group.

- If I select the CCBlock in the IChisel, I get the visual preview (the window in the GUI) and I can chisel the CCBlock in the immersive and Thermal CCBlock, BUT not in the Chisel CCBlock.
I click on "chisel" with the Chisel CCBlock selected, but thats it... 

- here is a short Video, maybe this explain it better:
-> https://youtu.be/8oj8NZOqrZY

**Comment by tterrag1098** [comment]
You've created an extra group, there is no group called "blockCoalCoke", it is called "block_coal_coke". However you cannot add to this group, it's an oredictionary group. You just need to assign the oredict name "blockCoalCoke" to the other mod blocks.

**Comment by TheSnowyChickens** [comment]
Ah okay, Thermal and Immersive CCBlocks only uses 1 oreDic entry "blockFuelCoke" and not the "blockCoalCoke", so thats my mistake.

Ty
