### ISSUE TITLE
Slabs able to be placed inside the player

### ISSUE THREAD

**Issue by LuigiHutch** [Chisel-Team/Chisel#74]
Chisel: 2.9.4.10 

Chisel Slabs are able to be placed inside the player which can lead to some bad side affects. See GIF:
http://www.gfycat.com/DifferentBlackandwhiteGander

 -LuigiHutch

**Comment by codewarrior0** [comment]
This also causes slabs to be consumed on right-click, but no slab is placed in the world.

**Comment by Drullkus** [comment]
Slabs removed; Outdated
