### ISSUE TITLE
[1.12.2] Immersive Engineering and Chisel

### ISSUE THREAD

**Issue by HanJan00** [Chisel-Team/Chisel#741]
Minecraft 1.12.2
Forge       14.23.5.2769 (and previous versions)
Chisel       0.2.1.35
CTM         0.2.3.12
Immersive Engineering 0.12-86
JEI            4.13.1.220

If Chisel and IE is in one modpack installed some recipes of IE are not show (only blank placeholder) and not to craft. 
For example: Kinetic Dynamo, Thermoelectric Generator, some Scaffolding,  the structural  #arms

**Comment by dragonshardz** [comment]
This was a bug with CTM that has since been fixed.

**Comment by tterrag1098** [comment]
You're many versions behind, update before reporting bugs.
