### ISSUE TITLE
Chisel Blocks Textures Missing on Multiplayer Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#744]
Modlist On Server                                    
u-architecturecraft-1.12-3.80-r.jar       
u-armoryexpansion-0.2.0-r.jar             
u-Backups-1.12.2-1.4.3-r.jar              
u-BiomesOPlenty-1.12.2-7.0.1.2402-b.jar   
u-ChineseWorkshop-1.12.2_1.2.5-r.jar      
u-Chisel-MC1.12.2-0.2.1.35-b.jar          
u-coherent_villages_pre-release_v0.0.0.3-b.jar
u-conarm-1.12.2-1.2.0-r.jar               
u-CreativeCore_v1.9.35_mc1.12.2-r.jar     
u-ExactSpawn-1.12-1.1.6-r.jar             
u-foamfix-0.10.2-1.12.2-r.jar             
u-Hungering+Darkness-1.12.2-1.1.0-r.jar   
u-jei_1.12.2-4.13.1.220-r.jar             
u-JustEnoughIDs-1.0.2-26-r.jar            
u-LittleTiles_v1.5.0-pre115_mc1.12.2-r.jar
u-Maiden's+Marvelous+Materials-1.2-1.12.2-r.jar
u-Mantle-1.12-1.3.2.24-r.jar              
u-Novam+Terram+1.12.2+-+5.2-r.jar         
u-OnlinePicFrame_v1.4.21_mc1.12.2-r.jar   
u-Pam's+HarvestCraft+1.12.2za-r.jar       
u-pokecube-aio-1.12.2-1.7.1-r.jar         
u-pokecube-alternative-1.12.2-2.4.0-r.jar 
u-TConstruct-1.12.2-2.10.1.87-r.jar       
u-TinkeredHegemony-0.2.1-r.jar            
u-tinkersjei-1.0-r.jar                    
u-TinkerToolLeveling-1.12.2-1.0.5-r.jar   
u-tombstone-3.2.2-1.12-r.jar              
u-torohud-1.12.2-5-b.jar                  
u-walljump-1.12.2-1.2.0-r.jar      

![2018-10-16 13_53_11-nvidia geforce overlay](https://user-images.githubusercontent.com/10351221/47040304-8e99da00-d14b-11e8-8807-ad60b4ecc560.jpg)

**Comment by TehNut** [comment]
You're missing CTM

**Comment by P3rf3ctXZer0** [comment]
SERVERSIDE - the bug occurs serverside. Even if you have ctm clientside. Also a note if you add ctm serverside it just disables it.

**Comment by P3rf3ctXZer0** [comment]
My personal changelog

============================================================

**Initial Release - bug checking v0001**

Modlist Name                                                  
c-jeiintegration_1.12.2-1.5.1.36-r.jar    
c-noctrl-1.2-r.jar                        
u-tinkersjei-1.0-r.jar                    
u-torohud-1.12.2-5-b.jar                  
c-Xaeros_Minimap_1.15.9_Forge_1.12-r.jar  
u-architecturecraft-1.12-3.80-r.jar       
u-armoryexpansion-0.2.0-r.jar             
u-Backups-1.12.2-1.4.3-r.jar              
u-BiomesOPlenty-1.12.2-7.0.1.2402-b.jar               
u-ChineseWorkshop-1.12.2_1.2.5-r.jar             
u-coherent_villages_pre-release_v0.0.0.3-b.jar
u-conarm-1.12.2-1.2.0-r.jar               
u-CreativeCore_v1.9.35_mc1.12.2-r.jar     
u-ExactSpawn-1.12-1.1.6-r.jar             
u-foamfix-0.10.2-1.12.2-r.jar             
u-Hungering+Darkness-1.12.2-1.1.0-r.jar   
u-jei_1.12.2-4.13.1.220-r.jar             
u-JustEnoughIDs-1.0.2-26-r.jar            
u-LittleTiles_v1.5.0-pre115_mc1.12.2-r.jar
u-Maiden's+Marvelous+Materials-1.2-1.12.2-r.jar
u-Mantle-1.12-1.3.2.24-r.jar              
u-Novam+Terram+1.12.2+-+5.2-r.jar         
u-OnlinePicFrame_v1.4.21_mc1.12.2-r.jar   
u-Pam's+HarvestCraft+1.12.2za-r.jar       
u-pokecube-aio-1.12.2-1.7.1-r.jar         
u-pokecube-alternative-1.12.2-2.4.0-r.jar 
u-TConstruct-1.12.2-2.10.1.87-r.jar       
u-TinkeredHegemony-0.2.1-r.jar            
u-TinkerToolLeveling-1.12.2-1.0.5-r.jar   
u-tombstone-3.2.2-1.12-r.jar              
u-walljump-1.12.2-1.2.0-r.jar             

**Side notes for release**
Base pack I built with the intention of minimal possible conflicts. Seems that Chisel is working as intended. I am trying to discover what mode tends to actually break it. Hopefully after I realease this I can find out exactly why chisel is breaking.

10.16.2018 1:59pm
Chisel is still broken serverside. Removing mods til fix is provided.

**Removed Mods**
u-Chisel-MC1.12.2-0.2.1.35-b.jar   
c-CTM-MC1.12.2-0.3.2.18-b.jar

**Comment by tterrag1098** [comment]
I don't see how an issue with textures could be caused by *anything* serverside. You cannot see textures on a server. It's a server.

**Comment by P3rf3ctXZer0** [comment]
True and I get that but when using chisel on a server the client cannot see proper textures.

**Comment by P3rf3ctXZer0** [comment]
Testing with latest forge and ctm

**Comment by P3rf3ctXZer0** [comment]
Fixed using 

Chisel
https://minecraft.curseforge.com/projects/chisel/files/2619468

Ctm
https://minecraft.curseforge.com/projects/ctm/files/2629306

Forge
1.12.2 - 14.23.5.2772

Unlimited Chisel Works
https://minecraft.curseforge.com/projects/unlimited-chisel-works/files/2586932

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 thanks for the fix.

**Comment by P3rf3ctXZer0** [comment]
![2018-10-19 19_18_03-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/47248945-c1ee9a00-d3d3-11e8-8d8d-cbc5d361e00d.jpg)

**Comment by P3rf3ctXZer0** [comment]
I tpd and this is what I am greeted with.

**Comment by P3rf3ctXZer0** [comment]
Maybe missing a reload function when traveling inbetween dimensions.

**Comment by P3rf3ctXZer0** [comment]
Okay well - not sure why but the bug is fixed after rebooting the game. I cannot figure out what is causing it but extended play is a factor please help @tterrag1098 

Can confirm it is a completely clientside bug.

**Comment by P3rf3ctXZer0** [comment]
- I give other than a sudden lag spike I cannot make it happen :'(
