### ISSUE TITLE
Face culling logic may be inconsistent with vanilla

### ISSUE THREAD

**Issue by Brycey92** [Chisel-Team/Chisel#746]
**Mod version**
MC1.12.2-0.2.1.35

**Describe the bug**
When any nonsolid Secret Rooms block (trap doors, ghost blocks, and stairs) tries to copy a chisel block, and is directly touching blocks of the type copied, those blocks become invisible from inside the nonsolid block, allowing the user to x-ray.

**To reproduce**
1. Place one of the aforementioned blocks on any chisel block
2. Walk into the Secret Rooms block
3. Observe the x-ray

**Screenshots**
![image](https://user-images.githubusercontent.com/42786612/46920683-03d8a400-cfc0-11e8-8e64-efa2c824965b.png)

**Comment by tterrag1098** [comment]
I'm fairly sure this is a problem in SRM

**Comment by tterrag1098** [comment]
https://github.com/AbrarSyed/SecretRoomsMod-forge/issues/251

**Comment by Brycey92** [comment]
Thanks for doing the investigating and finding the matching issue!
