### ISSUE TITLE
asap request debug for chisel and ctm

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#747]
Please add the following logs. Do not worry about performance impact.

- Needs to have debug on texture load
- Texture unload debug
- debug on texture server sync
- debug on texture reload on dimensional unpack
- mod interaction and texture nbt logs
- debug also what happens on memory overflow

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 @minecreatr

**Comment by P3rf3ctXZer0** [comment]
I need to have those logs to understand when and how the bug is triggered.

**Comment by ZombieHDGaming** [comment]
You haven't exactly said what the bug is or the exact issue is for the need of these logs, because those are a lot of extra logs for something that may not help at all. Let's start with the actual bug, then we can see about a possible option, because this would honestly only be useful in select cases for something that could cause so much bloat and I doubt the devs would want to do that without a proper reason (From a perspective of another mod dev).

**Comment by P3rf3ctXZer0** [comment]
The problem is I cannot narrow the bug down even just using chisel - I have re tested this one mod over 160 times with less than 20 mods and as little as none. I cannot make the bug happen in any specific way. I am going to start recording gameplay so hopefully I can discover which moment the bug takes affect. I don't care if you released the modified release with the debug tools I need or not publically because I am just trying to figure out when and how the bug gets triggered. Its grating when you are working on an amazing structure and suddenly textures disappear. My original theory was it was caused during the death and respawn sequence but that proved only to take part only 20% of the time. Then I thought maybe its a time thing that only proved to be inconsistant - then I thought maybe its a ram overflow thing - nope that was inconsistant as well - honestly at my wits end.

**Comment by P3rf3ctXZer0** [comment]
Things I have tried
- no or less mods (no impact except lycanite makes the mod break without question in all tests)
- trying to overflow ticks (only in 10% of tests was I able to actually break the mod this way.)
- Increasing ram (nope still break)
- Maybe it was time released (no consistency )
- Maybe another mod is causing it ( no couldn't get it to trigger with or without mods consistently ) 
- Maybe its caused by teleportation ( no only 10 % of issue could be triggered )
- Maybe it was caused by a combination of actions (Dying respawning teleporting certain gui's no consistency.)

The only thing I can confirm is the bug exists and even if one player triggers it other players are not always affected.

**Comment by tterrag1098** [comment]
Textures do not "unload"
Textures do not "sync"
Textures do not change when switching dimensions
Textures do not have NBT
Chisel does not control memory or what happens when you run out.

**Comment by P3rf3ctXZer0** [comment]
If I make a video will you watch it? Will you help me figure out why the bug takes affect? @tterrag1098
