### ISSUE TITLE
Request - Hotkey to reload texture cache for chisel based mods clientside

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#748]
What this would do is allow a user to reload, unload and reload textures when textures seems to disappear. Users need a way to manually force a clientside check so they can restore missing textures. (Not sure forge can do it though because the only way I can ever restore the damn textures is by comepletely closing minecraft) Could use a coders perspective.

**Comment by Andromander** [comment]
It's already a feature, called `F3-T`. It's built into Vanilla.

**Comment by P3rf3ctXZer0** [comment]
Unfortunately before asking for this I was just taught this 3 mins ago.
