### ISSUE TITLE
Antiblocks Behaving Unusually?

### ISSUE THREAD

**Issue by SalmonSays** [Chisel-Team/Chisel#749]
I seem to have a recollection of anti-blocks behaving differently in the 1.7.10-ish days, and I'm not sure if this is an intended change or not. Pictured below are black anti-blocks in their current state per "Chisel-MC1.12.2-0.2.1.35":

![goqghff](https://user-images.githubusercontent.com/11697389/48410687-fb7da100-e704-11e8-83c6-b2dbac0501cc.png)

They have a gradient which is influenced by lighting. I could have sworn they were meant to behave like this:

![moz5zpq](https://user-images.githubusercontent.com/11697389/48410728-1cde8d00-e705-11e8-96ae-b57880b447e5.png)

Where outside lighting doesn't affect them and they act like a fullbright solid-color while not producing any environmental light.

The second set of pictured blocks are Mekanism's Black Plastic blocks, but unfortunately they only produce this effect for black and don't work the same way for any colored set. This fullbright effect was especially useful for black/white to simulate depths and with green to provide a perfectly-keyed and evenly lit greenscreen.

**Comment by tterrag1098** [comment]
Our antiblock models need to set the ambientocclusion flag to false. This will be part of the ongoing effort to port our models to the new CTM format.

**Comment by SalmonSays** [comment]
So for clarity am I to gather they will work the way I described eventually™?

**Comment by tterrag1098** [comment]
They are not intended to have any shading whatsoever, it is a bug. However fixing it will take some time since it's part of a long list of TODOs.

**Comment by SalmonSays** [comment]
Noted, and I appreciate the acknowledgement all the same- thanks for your efforts! ^^

**Comment by tterrag1098** [comment]
Fixed via https://github.com/Chisel-Team/Chisel/commit/cbc20a50e5180dbf5c630c6b2ce13df43a5cb72c and the conversion to CTM models.
