### ISSUE TITLE
VerifyError

### ISSUE THREAD

**Issue by derech1e** [Chisel-Team/Chisel#751]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/18/18 1:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CTM (ctm)
Caused by: java.lang.VerifyError: Inconsistent stackmap frames at branch target 116
Exception Details:
  Location:
    net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper.getTextures()Ljava/util/Collection; @116: invokestatic
  Reason:
    Type 'net/minecraftforge/client/model/IModel' (current frame, locals[1]) is not assignable to 'net/minecraft/util/ResourceLocation' (stack map, locals[1])
  Current Frame:
    bci: @14
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraftforge/client/model/IModel' }
    stack: { 'net/minecraftforge/client/model/IModel' }
  Stackmap Frame:
    bci: @116
    flags: { }
    locals: { 'net/minecraftforge/client/model/ModelLoader$VanillaModelWrapper', 'net/minecraft/util/ResourceLocation' }
    stack: { }
  Bytecode:
    0x0000000: 2ab4 0044 b600 9b4c 2bb8 00b5 4c2b c600
    0x0000010: 662a b400 44b4 00b8 c700 5c2b b600 9e12
    0x0000020: bab6 00bb 9900 102a b400 44b8 00bf b500
    0x0000030: b8a7 0043 2ab4 0044 2bbb 0080 59b7 0081
    0x0000040: 12c1 b600 872b b600 8a12 c3b6 0087 2ab4
    0x0000050: 0044 b600 8a12 c5b6 0087 b600 8db8 0093
    0x0000060: b900 c901 002a ba00 db00 00b6 00e1 c000
    0x0000070: 54b5 00b8 b800 e54d 2ab4 003d 2ab4 0044
    0x0000080: b800 e999 004a b200 efb9 00f2 0100 4e2d
    0x0000090: b900 6501 0099 0038 2db9 0069 0100 c000
    0x00000a0: a23a 042a b400 4419 04b6 00f6 3a05 bb00
    0x00000b0: 6b59 1905 b700 f93a 0619 0519 04b6 00bb
    0x00000c0: 9a00 0a2c 1906 b600 fc57 a7ff c52a b400
    0x00000d0: 44b4 0100 b901 0301 00b9 005d 0100 4e2d
    0x00000e0: b900 6501 0099 002a 2db9 0069 0100 c000
    0x00000f0: a23a 0419 0413 0105 b600 a69a 0011 2cbb
    0x0000100: 006b 5919 04b7 00f9 b600 fc57 a7ff d32c
    0x0000110: b601 09b0                              
  Stackmap Table:
    append_frame(@52,Object[#107])
    same_frame(@116)
    append_frame(@143,Object[#14],Object[#97])
    same_frame(@202)
    chop_frame(@205,1)
    append_frame(@223,Object[#97])
    same_frame(@268)
    chop_frame(@271,1)

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at team.chisel.ctm.client.util.TextureMetadataHandler.<clinit>(TextureMetadataHandler.java:102)
	at team.chisel.ctm.CTM.preInit(CTM.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262767912 bytes (250 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2775 Optifine OptiFine_1.12.2_HD_U_E2 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version           | Source                                        | Signature                                |
	|:----- |:-------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCH   | mcp            | 9.42              | minecraft.jar                                 | None                                     |
	| UCH   | FML            | 8.0.99.99         | forge-1.12.2-14.23.5.2775.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.5.2775      | forge-1.12.2-14.23.5.2775.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | openmodscore   | 0.12.1            | minecraft.jar                                 | None                                     |
	| UCH   | aquaculture    | 1.6.5             | Aquaculture-1.12.2-1.6.5.jar                  | None                                     |
	| UCH   | gorecore       | 1.12.2-0.4.5      | avatarmod-1.5.9.2-alpha.5.jar                 | None                                     |
	| UCH   | avatarmod      | unspecified       | avatarmod-1.5.9.2-alpha.5.jar                 | None                                     |
	| UCH   | backpack       | 3.0.2             | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| UCH   | ichunutil      | 7.0.2             | iChunUtil-1.12.2-7.0.2.jar                    | None                                     |
	| UCH   | backtools      | 7.0.0             | BackTools-1.12.2-7.0.0.jar                    | None                                     |
	| UCH   | baguettemod    | 1.6               | baguettemod-1.6.jar                           | None                                     |
	| UCH   | battletowers   | 1.6.3             | BattleTowers-1.12.2.jar                       | None                                     |
	| UCH   | biomesoplenty  | 7.0.1.2399        | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCH   | bookshelf      | 2.3.559           | Bookshelf-1.12.2-2.3.559.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCEE  | ctm            | MC1.12.2-0.3.2.18 | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
	| UC    | chisel         | MC1.12.2-0.2.1.34 | Chisel-MC1.12.2-0.2.1.34.jar                  | None                                     |
	| UC    | chiselsandbits | 14.23             | chiselsandbits-14.23.jar                      | None                                     |
	| UC    | chococraft     | 0.9.1.52          | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| UC    | cucumber       | 1.1.1             | Cucumber-1.12.2-1.1.1.jar                     | None                                     |
	| UC    | customspawner  | 3.11.4            | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| UC    | ptrmodellib    | 1.0.3             | PTRLib-1.0.3.jar                              | None                                     |
	| UC    | props          | 2.6.2             | Decocraft-2.6.2_1.12.2.jar                    | None                                     |
	| UC    | dimdoors       | 3.0.0-beta4       | Dimensional-Doors-Mod-1.12.2.jar              | None                                     |
	| UC    | dldungeonsjdg  | 1.9.3             | Doomlike-Dungeons-Mod-1.12.2.jar              | None                                     |
	| UC    | mocreatures    | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| UC    | durabilityshow | 5.0.0             | Durability+Show-1.12-5.0.0.jar                | None                                     |
	| UC    | eplus          | 5.0.164           | EnchantingPlus-1.12.2-5.0.164.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | gravestone     | 1.10.2            | gravestone-1.10.2.jar                         | None                                     |
	| UC    | placebo        | 1.4.0             | Placebo-1.12.2-1.4.0.jar                      | None                                     |
	| UC    | hexxitgear     | 2.7.0             | Hexxit+Gear-1.12.2-2.7.0.jar                  | None                                     |
	| UC    | llibrary       | 1.7.14            | llibrary-1.7.14-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UC    | iceandfire     | 1.5.2             | iceandfire-1.5.2.jar                          | None                                     |
	| UC    | infernalmobs   | 1.7.5             | InfernalMobs-1.12.2.jar                       | None                                     |
	| UC    | infinitylib    | 1.12.2-1.12.0     | infinitylib-1.12.0.jar                        | None                                     |
	| UC    | ironchest      | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar               | None                                     |
	| UC    | lootbags       | 2.5.7             | LootBags-1.12.2-2.5.7.jar                     | None                                     |
	| UC    | mantle         | 1.12-1.3.2.24     | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UC    | openmods       | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks     | 1.8               | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | tconstruct     | 1.12.2-2.10.1.87  | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
	| UC    | xreliquary     | 1.12.2-1.3.4.767  | Reliquary-1.12.2-1.3.4.767.jar                | None                                     |
	| UC    | roguelike      | 1.7.2             | RoguelikeDungeons-1.12.2-1.7.2.jar            | None                                     |
	| UC    | secretroomsmod | 5.3.2             | secretroomsmod-1.12.2-5.3.2.jar               | None                                     |
	| UC    | torohealthmod  | 1.12.2-11         | torohealth-1.12.2-11.jar                      | None                                     |
	| UC    | bspkrscore     | at_0.9            | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| UC    | treecapitator  | at_0.9            | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| UC    | twilightforest | 3.7.424           | twilightforest-1.12.2-3.7.424-universal.jar   | None                                     |
	| UC    | wawla          | 2.5.246           | Wawla-1.12.2-2.5.246.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
llibrary (llibrary-core-1.0.6-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.66.31' Renderer: 'AMD Radeon Pro 560 OpenGL Engine'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-1.66.31
	OpenGlRenderer: AMD Radeon Pro 560 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

This is the error...
Why is it so?

**Comment by Andromander** [comment]
Try updating CTM. Looks like you may be outdated.

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/84
