### ISSUE TITLE
There is a form to enable chisel (using techguns) into old maps?

### ISSUE THREAD

**Issue by lsyk4** [Chisel-Team/Chisel#757]
Hi!
I installed "techguns" mod into 1.12.2 version of MC.
That mod uses "Chisel" mod. The problem is that I temporary uninstall "Chisel" mod to try if is in conflict with other mod.
The problem is, when I reinstall the "Chisel" mod, some "Techguns" features that uses "Chisel" mod stop working.
There is a way to reenable the "Chisel" mod features in my maps?
Greetings

**Comment by tterrag1098** [comment]
Sounds like you have a problem with Techguns, not Chisel. Ask them?
