### ISSUE TITLE
[Suggestion] aging/weathering/mossing

### ISSUE THREAD

**Issue by Seth0067** [Chisel-Team/Chisel#761]
Just a thought, but may be a really cool feature for you guys.  Since many blocks in vanilla and modded often have variants for cracked, aged, mossy, etc, have you ever considered a system where a base block is automatically swapped based on external/game factors? Example:

Stone bricks:  
- x days after placement, there is a x% will turn into cracked bricks - check every day and perhaps this increments by one every day thereafter.
- if mined but not broken, turns into cracked bricks 50% of the time.
- when placed next to a liquid block (or adjacent to a block that is placed next to liquid) there is an x% chance per day this block will change to mossy bricks.

You may then create new items to revert blocks next to their pristine state (new tools, ticon modifiers, advanced machinery to automate, etc) because, hey, who doesn't like more work!

Would love to see this as it would enable seeing these blocks for players outside/not concerned with creative, create more immersion, etc.

**Comment by ChloeDawn** [comment]
This is simply a decoration mod, mechanics like that would be out of scope, better as their own mod. The [Erosion 2](https://minecraft.curseforge.com/projects/erosion) mod may interest you.

**Comment by Seth0067** [comment]
Fair enough Kitten, thanks for the feedback!
