### ISSUE TITLE
Block model error

### ISSUE THREAD

**Issue by Zarpyk** [Chisel-Team/Chisel#763]
![2019-01-20_13 50 38](https://user-images.githubusercontent.com/30746531/51439449-902eed00-1cba-11e9-83c8-c67208e2341b.png)
![2019-01-20_13 51 48](https://user-images.githubusercontent.com/30746531/51439450-902eed00-1cba-11e9-95a7-b4bf1c812d58.png)

**Comment by tterrag1098** [comment]
Isn't that a twilight forest block?

**Comment by Shadows-of-Fire** [comment]
Yes, it's a twilight forest block.  And it's apparently supposed to look like that (ignoring how glitchy it makes it look).

This can probably be closed since it has nothing to do with chisel.
