### ISSUE TITLE
chisel texture series (#) not able to reverse chisel back to original texture

### ISSUE THREAD

**Issue by jaxmacky** [Chisel-Team/Chisel#774]
Chisel-MC1.12.2-0.2.1.35.jar
MC 1.12.2

Base Block (Gold) not chiseling back when initially chiseled to "Large Ingots". 

Initial options have 23 variations, but once chiseled into Large Ingots, Small Ingots, Small Bricks, Cart, Coin<heads>, Heads<tails>, Dark Crate, Light Crate, Plates, Riveted Plates, Stars, Purple Space, Black Space, Simple and Gold Eye, variations drop to 15, and base block (Gold) is NOT one of them. 
![2019-05-10_01 12 23](https://user-images.githubusercontent.com/8409769/57507129-734b1380-72c3-11e9-974d-d57947c5f807.png)
![2019-05-10_01 12 37](https://user-images.githubusercontent.com/8409769/57507132-7514d700-72c3-11e9-9d92-070b161573cf.png)

**Comment by tterrag1098** [comment]
Probably caused by #630
