### ISSUE TITLE
[Suggestion] Add new variants for stone

### ISSUE THREAD

**Issue by CrossVas** [Chisel-Team/Chisel#775]
Heya,

It would be cool to see two new variants for stone block, especially stone slab texture: 
![image](https://user-images.githubusercontent.com/25727222/57574126-dbbd0080-743b-11e9-9552-ab8164e7b39c.png) - each side

and
 
![image](https://user-images.githubusercontent.com/25727222/57574128-e9728600-743b-11e9-9d81-5f701532a908.png) - each side

I know that player can obtain this by placing slabs. 
It isn't an option, it would be great to manipulate with them in the same way as with other regular *full* block.

Thanks!

**Comment by tterrag1098** [comment]
Added in 1.0.0
