### ISSUE TITLE
Bug - The return of flat textures bug.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#776]
Currently Running Forge Version
14.23.5.2838

::MODLIST::
c-betterhud-1.12.2-1.4.jar
c-CTM-MC1.12.2-0.3.3.22.jar
u-AppleCore-mc1.12.2-3.2.0.jar
u-AppleSkin-mc1.12-1.0.9.jar
u-architecturecraft-1.12-3.80.jar
u-armoryexpansion-1.2.4.jar
u-AutoRegLib-1.3-29.jar
u-binnie-mods-1.12.2-2.5.1.188.jar
u-BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
u-Born+In+A+Barn+V1.8-1.12-1.1.jar
u-BuildingGadgets-2.6.8.jar
u-Chisel-MC1.12.2-0.2.1.35.jar
u-chiselsandbits-14.32.jar
u-ColossalChests-1.12.2-1.7.1.jar
u-CommonCapabilities-1.12.2-2.3.0.jar
u-conarm-1.12.2-1.2.3.4.jar
u-Contracts+Mod-2.2.jar
u-CosmeticArmorReworked-1.12.2-v4a.jar
u-CreativeCore_v1.9.45_mc1.12.2.jar
u-Cucumber-1.12.2-1.1.3.jar
u-CyclopsCore-1.12.2-1.2.1.jar
u-effortlessbuilding-1.12.2-2.11.jar
u-EnderCore-1.12.2-0.5.57.jar
u-EnderIO-base-1.12.2-5.0.44.jar
u-EnderIO-conduits-1.12.2-5.0.44.jar
u-EnderIO-integration-forestry-1.12.2-5.0.44.jar
u-EnderIO-integration-tic-1.12.2-5.0.44.jar
u-EnderIO-machines-1.12.2-5.0.44.jar
u-ExtraBitManipulation-1.12.2-3.4.1.jar
u-FastFurnace-1.12.2-1.3.1.jar
u-FastWorkbench-1.12.2-1.7.1.jar
u-flatcoloredblocks-mc1.12-6.7.jar
u-Flopper-1.12.2-1.0.3.jar
u-FluidCows-1.1.19.jar
u-foamfix-0.10.5-1.12.2.jar
u-forestry_1.12.2-5.8.2.387.jar
u-FTBLib-5.4.1.99.jar
u-FTBUtilities-5.4.0.96.jar
u-FurnaceOverhaul-1.12.2-2.2.0.jar
u-GrimoireOfGaia3-1.12.2-1.6.9.3.jar
u-Guidebook-1.12.2-2.9.1.jar
u-HungerStrike-1.12-1.0.8.jar
u-jei_1.12.2-4.15.0.278.jar
u-JustEnoughIDs-1.0.2-26.jar
u-limelib-1.12.2-1.7.12.jar
u-LittleTiles_v1.5.0-pre135_mc1.12.2.jar
u-LootBags-1.12.2-2.5.8.5.jar
u-Mantle-1.12-1.3.3.49.jar
u-MysticalAgradditions-1.12.2-1.3.2.jar
u-MysticalAgriculture-1.12.2-1.7.5.jar
u-natura-1.12.2-4.3.2.69.jar
u-NomadicTents[1.12.2]-9.3.2.jar
u-NoMoreRecipeConflict-0.13(1.12.2).jar
u-OnlinePicFrame_v1.4.24_mc1.12.2.jar
u-Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar
u-phosphor-1.12.2-0.2.4+build46-universal.jar
u-Placebo-1.12.2-1.6.0.jar
u-Plants-1.12.2-2.10.7.jar
u-playerstorage-1.12.2-1.3.11.jar
u-pokecube-aio-1.12.2-1.13.1.jar
u-prefab-1.3.0.26.jar
u-Quark-r1.5-152.jar
u-QuickLeafDecay-MC1.12.1-1.2.4.jar
u-randomconfigs-1.12.2-1.3.2.3.jar
u-randomtweaks-1.12.2-2.5.0.5.jar
u-ScalingHealth-1.12.2-1.3.35+138.jar
u-SilentLib-1.12.2-3.0.13+167.jar
u-SilentsGems-1.12.2-2.8.17+319.jar
u-speedyhoppers-1.1.10.jar
u-TConstruct-1.12.2-2.12.0.135.jar
u-tellme-1.12.2-0.7.0-dev.20190410.193230.jar
u-thuttech-1.12.2-6.1.6.jar
u-TinkersComplement-1.12.2-0.3.2.jar
u-tinkersjei-1.2.jar
u-TinkerToolLeveling-1.12.2-1.1.0.jar
u-TreeChopper-1.12.2-1.2.4.jar
u-UnlimitedChiselWorks-0.2.1.jar
u-VeinMiner-1.12-0.38.2.647+b31535a.jar
u-WailaHarvestability-mc1.12-1.1.12.jar
u-walljump-1.12.2-1.2.3.jar
u-weirdinggadget-1.12.2-2.1.16-universal.jar
u-Xaeros_Minimap_1.16.9_Forge_1.12.jar

It is the same bug as before where textures just turn to solid colors. I have been away from the scene for about 3 months and I can safely say this bug did not exist three months ago.

This is the modlist when it was working just fine.

s-ADL-1.1.1.jar
s-quickteleports-1.0.0.jar
u-AbyssalCraft-1.12.2-1.9.6.jar
u-ActuallyAdditions-1.12.2-r146.jar
u-AdFinders-1.12.2-2.3.5.0-build.0274.jar
u-AppleCore-mc1.12.2-3.1.4.jar
u-AppleSkin-mc1.12-1.0.9.jar
u-apritree-1.12.2-2.0.4.jar
u-Aquaculture-1.12.2-1.6.8.jar
u-architecturecraft-1.12-3.80.jar
u-armoryexpansion-0.2.0.jar
u-AttributeFix-1.12.2-1.0.7.jar
u-AutoPickup-1.12-2.5.1.jar
u-AutoRegLib-1.3-26.jar
u-base-1.12.2-3.12.0.jar
u-Baubles-1.12-1.5.2.jar
u-BetterDiving-1.12.2-1.2.2.jar
u-BetterRecords-1.12.2-1.6.1.jar
u-binnie-mods-1.12.2-2.5.1.188.jar
u-BiomesOPlenty-1.12.2-7.0.1.2425.jar
u-Bookshelf-1.12.2-2.3.576.jar
u-Botania+r1.10-360.jar
u-BuildingGadgets-2.6.8.jar
u-Caliper-1.12.2-1.1.42.jar
u-CapabilityProxy-1.12.2-2.1.3.jar
u-champions-1.12.2-1.0.8.jar
u-ChineseWorkshop-1.12.2_1.2.5.jar
u-Chisel-MC1.12.2-0.2.1.35.jar
u-chiselsandbits-14.31.jar
u-ColossalChests-1.12.2-1.7.1.jar
u-CommonCapabilities-1.12.2-2.1.1.jar
u-conarm-1.12.2-1.2.3.jar
u-Controlled+Burn-1.12.2.016.jar
u-CosmeticArmorReworked-1.12.2-v4.jar
u-CraftTweaker2-1.12-4.1.15.jar
u-CreativeCore_v1.9.41_mc1.12.2.jar
u-Cucumber-1.12.2-1.1.3.jar
u-CyclopsCore-1.12.2-1.1.1.jar
u-DeathCounter-HYW-1.12.2-1.0.1-r.jar
u-DeathQuotes-1.2.0-mc1.12-forge-r.jar
u-DimensionalDoors-1.12.2-3.0.9-306.jar
u-DoomlikeDungeons-1.12.3-MC1.12.2.jar
u-EvilCraft-1.12.2-0.10.72.jar
u-ExtraBitManipulation-1.12.2-3.4.1.jar
u-extrautils2-1.12-1.9.9.jar
u-FastFurnace-1.12.2-1.2.2.jar
u-FastWorkbench-1.12.2-1.6.1.jar
u-flatcoloredblocks-mc1.12-6.7.jar
u-FluidCows-1.1.17.jar
u-foamfix-0.10.3-1.12.2.jar
u-forestry_1.12.2-5.8.2.385.jar
u-ForgeEndertech-1.12.2-4.4.12.0-build.0273.jar
u-Forgelin-1.8.2.jar
u-FTBLib-5.4.1.93.jar
u-FTBMoney-1.1.0.27.jar
u-FTBQuests-1.5.1.138.jar
u-FTBUtilities-5.4.0.88.jar
u-FunOres-1.12.2-1.6.3-124.jar
u-FurnaceOverhaul-1.12.2-2.2.0.jar
u-furniture-6.2.0-1.12.2.jar
u-FutureVersionsV1.2.1.jar
u-GrimoireOfGaia3-1.12.2-1.6.9.3.jar
u-Growable+Apricorns-2.0.0.jar
u-Guidebook-1.12.2-2.8.3.jar
u-hexlands-1.9.0.jar
u-HungerStrike-1.12-1.0.8.jar
u-IntegratedCrafting-1.12.2-1.0.6.jar
u-IntegratedDynamics-1.12.2-1.0.10.jar
u-IntegratedREST-1.12.2-1.1.1.jar
u-IntegratedTerminals-1.12.2-1.0.6.jar
u-IntegratedTunnels-1.12.2-1.6.8.jar
u-ItemFilters-1.0.1.8.jar
u-IvToolkit-1.3.3-1.12.jar
u-jeibees-0.9.0.5-mc1.12.2.jar
u-jei_1.12.2-4.15.0.271.jar
u-JustEnoughIDs-1.0.2-26.jar
u-landlust-1.12.2-0.3.6.jar
u-letsencryptcraft-1.10.2-1.2.0.jar
u-limelib-1.12.2-1.7.12.jar
u-LittleTiles_v1.5.0-pre130_mc1.12.2.jar
u-LootBags-1.12.2-2.5.8.5.jar
u-lostcities-1.12-2.0.17.jar
u-Lucky+Block+Pink+4+Year+Anniversary+Edition.jar
u-LuckyBlock_1-12_v7-5-0.jar
u-Maiden's+Marvelous+Materials-3.3.jar
u-Mantle-1.12-1.3.3.42.jar
u-Metallurgy-4-Reforged-0.1.1.jar
u-MineMenu-1.12.2-1.6.9-universal.jar
u-MineTraps-1.12.2-(v.1.0.3).jar
u-moartinkers-0.6.0.jar
u-modtweaker-4.0.16.jar
u-MTLib-3.0.5.jar
u-MysticalAgriculture-1.12.2-1.7.3.jar
u-natura-1.12.2-4.3.2.66.jar
u-NomadicTents[1.12.2]-9.1.1.jar
u-NoMoreRecipeConflict-0.13(1.12.2).jar
u-omlib-1.12.2-3.1.0-208.jar
u-OnlinePicFrame_v1.4.23_mc1.12.2.jar
u-openmodularturrets-1.12.2-3.1.0-306.jar
u-Pam's+HarvestCraft+1.12.2zb.jar
u-Pewter-1.4.3.jar
u-Pixelmon-1.12.2-7.0.5-universal.jar
u-Placebo-1.12.2-1.5.1.jar
u-Plants-1.12.2-2.10.6.jar
u-playerstorage-1.12.2-1.3.11.jar
u-plustic-7.0.5.2.jar
u-prefab-1.3.0.26.jar
u-Quark-r1.5-146.jar
u-QuickLeafDecay-MC1.12.1-1.2.4.jar
u-railcraft-12.0.0.jar
u-randompatches-1.12.2-1.15.0.2.jar
u-randomtweaks-1.12.2-2.4.3.2.jar
u-RebornCore-1.12.2-3.13.8.430-universal.jar
u-RecurrentComplex-1.4.8.2.jar
u-Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar
u-rockhounding_core-1.12.2-3.20.jar
u-rockhounding_rocks-1.12.2-3.20.jar
u-rockhounding_surface-1.12.2-3.14.jar
u-rope-ladder-1.0.jar
u-runecarved-1.12.2-1.2.1.jar
u-ScalingHealth-1.12.2-1.3.32-134.jar
u-SilentLib-1.12.2-3.0.13+167.jar
u-SilentsGems-1.12.2-2.8.16+317.jar
u-Simple-Void-World-1.12-1.2.0.9-universal.jar
u-SimpleDimensions-MC1.12-1.4-r.jar
u-SpiceOfLife-mc1.12-1.3.12.jar
u-StructuredCrafting-1.12.2-0.2.1.jar
u-StructureUtils-1.1.0.4.jar
u-taiga-1.12.2-1.3.4.jar
u-TConstruct-1.12.2-2.12.0.123.jar
u-TeamIslands-1.1.0.21.jar
u-TechReborn-1.12.2-2.21.2.960-universal.jar
u-tellme-1.12.2-0.6.0.jar
u-theoneprobe-1.12-1.4.28.jar
u-TinkersComplement-1.12.2-0.3.1.jar
u-tinkersjei-1.0.jar
u-TinkerToolLeveling-1.12.2-1.1.0.jar
u-tmel-1.12.2-1.3.2.2.jar
u-tombstone-3.3.4-1.12.jar
u-TreeChopper-1.12.2-1.2.4.jar
u-UnlimitedChiselWorks-0.2.0.jar
u-upsizer-mc1.12-4.0.1.jar
u-walljump-1.12.2-1.2.3.jar
u-Wawla-1.12.2-2.5.270.jar
u-worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar
u-worleycaves-1.3.0.jar
u-[1.12.2]+SecurityCraft+v1.8.12.jar

I was running forge 
forge-1.12.2-14.23.5.2823-universal

**Comment by P3rf3ctXZer0** [comment]
Just tested using older chisel - I think it is a forge bug ... :( I just tried with forge-1.12.2-14.23.5.2831-universal

**Comment by P3rf3ctXZer0** [comment]
Reverted Quark so I can test forge-1.12.2-14.23.5.2823-universal with prior working chisel

**Comment by P3rf3ctXZer0** [comment]
![2019-05-21 13_05_35-Window](https://user-images.githubusercontent.com/10351221/58119724-48b56080-7bc9-11e9-96aa-de48299032bd.jpg)

**Comment by P3rf3ctXZer0** [comment]
Seems after I open better hud or any interface mod.

**Comment by P3rf3ctXZer0** [comment]
Tired of dealing with this bug.

**Comment by P3rf3ctXZer0** [comment]
"I do not know de wae" Let me know when this mod goes to 1.14.x I am really sick of hoping this mod works.

**Comment by ChloeDawn** [comment]
Chisel != Unlimited Chisel Works. Report your issue [over there](https://github.com/asiekierka/UnlimitedChiselWorks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) first.

**Comment by P3rf3ctXZer0** [comment]
I just removed chisel works and it still happens. I don't think it has anything to do with that. If it helps I can only trigger it on mp and lan - however the trigger is unknown. Once triggered if I try and enter a single player after bug is triggered - it carries to sp.

**Comment by P3rf3ctXZer0** [comment]
Honestly I still strongly believe it is CTM and I have made my concerns known many a time only to get shutdown. I think there is some server sync issues with the CTM lib. I think even though it is a clientside mod it may be a good idea to add some server checks but then again I don't code. So technically its the blind leading the blind.

**Comment by Tamaized** [comment]
that made 0 sense

**Comment by P3rf3ctXZer0** [comment]
Good thing I am not a coder then XD All I know is cause an affect. Sorry I am not more help :(

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/issues/16 @InsomniaKitten @Tamaized I made it happen with a few mods.

**Comment by P3rf3ctXZer0** [comment]
I legit provided all information I can.
[config.zip](https://github.com/Chisel-Team/Chisel/files/3210950/config.zip) here are the mod configs. I am really lost what I need to do. I really want this mod to work.

**Comment by Andromander** [comment]
Can you actually reproduce it with *only* Chisel and CTM? You seem to be insistent that this is a Chisel or CTM issue, but there is no evidence to claim that this is true. Because there are more mods than just those two, there is still a non-zero chance that it is a conflict with another mod, or even a bad video driver.

**Comment by P3rf3ctXZer0** [comment]
Okay lets say it is another mod - what type of code would that mod have to mess with to cause this issue? I legit have only the mods I wanted to use with this mod and I cut it from 175 to 8.

**Comment by P3rf3ctXZer0** [comment]
@Thutmose Your mod Pokecube is at fault >_> again.

**Comment by P3rf3ctXZer0** [comment]
@ChiselTeam please do not close this issue till thut fixes his mod. It is an issue but you can label it mod conflict and under investigation. At least my last 4 hours were for something.

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 are blocks handled via tile entity or block states? @Thutmose of Pokecube would like to know.

**Comment by Drullkus** [comment]
ExtendedStates

**Comment by Thutmose** [comment]
Seems to be un-related to pokecube itself, instead is related to my mod that renders worn items on the player.

Here is what is happening:
after rendering ~~a worn item on the player~~  the worn items gui, ~~then transfering dimensions,~~ updated connected texture blocks will go to a flat coloured texture.

Pressing f3+t will reset the state to normal until you render the worn items (say press f5)

**Comment by Thutmose** [comment]
The bug is an interaction with this line of code:

https://github.com/Thutmose/ThutWearables/blob/1.12/src/main/java/thut/wearables/inventory/ContainerWearables.java#L157

So it is something on the side of chisel that responds badly to the sprite for the inventory slots.

Is there some other way I should be initializing these sprites for the inventory slots?

**Comment by tterrag1098** [comment]
You can't register sprites at any random point in time...and you DEFINITELY can't call initSprite randomly. Surprised this code doesn't break more. Register your sprites properly at load time.

**Comment by Thutmose** [comment]
It is very odd that it hadn't broken anything else, so where should these be registered at load time? is it during the TextureStitchEvent?

**Comment by P3rf3ctXZer0** [comment]
@tterrag1098 he is working to actually fix the problem can you please keep this issue open until it is actually fixed since you and him are the only ones who can actually fix it as I am no longer useful to this report?

**Comment by P3rf3ctXZer0** [comment]
![2019-06-06 08_44_26-@Thutmose - Discord](https://user-images.githubusercontent.com/10351221/59037778-91ab1d00-8837-11e9-99fb-17f9c7c2c176.jpg)
@LatvianModder @tterrag1098 @Drullkus Can someone please explain the best way to answer his question about this

**Comment by KnightMiner** [comment]
Yes, it's TextureStitchEvent, testing it is simple enough without needing a response.

If an example of mods using it is needed, many mods such as Thermal Expansion and Inspirations use it to register fluid textures.

**Comment by P3rf3ctXZer0** [comment]
ty for the help he will work on fixes and I will work on testing this issue is officially over :D thank you all for your patients and help.

**Comment by tterrag1098** [comment]
I closed the issue because it was confirmed to not be a chisel problem. You'll notice I didn't lock it, so you are free to continue discussing here or elsewhere. What @KnightMiner said is accurate, if you have arbitrary textures you needed loaded, use the event.

**Comment by Thutmose** [comment]
yep, I moved my code to there, and it fixed this issue, I am somewhat surprised that this is the first thing that was noticed to go wrong there.
