### ISSUE TITLE
Chiseling blocks in world should not extend past the floor or ceiling

### ISSUE THREAD

**Issue by aaronhowser1** [Chisel-Team/Chisel#777]
I base in caves a lot, so the walls are made of Stone. But so is the ground underneath the floor and above the ceiling. When I chisel the walls, it also chisels the entire surrounding caves which is super annoying and takes more durability.

**Comment by tterrag1098** [comment]
This is intended behavior of that mode, but I have considered adding one that only changes surface-level blocks, or altering the behavior.
