### ISSUE TITLE
Some blocks can be turned into ore blocks.

### ISSUE THREAD

**Issue by AutoJukebox** [Chisel-Team/Chisel#778]
For some reason, some blocks can be chiseled into ore blocks. Is this a bug or something that I have to disable.

Here is a video of the problem: https://i.imgur.com/unpnm2N.gif

Version: 1.12.2-0.2.1.35

Thanks!

**Comment by tterrag1098** [comment]
Sounds like mod integration gone wrong, that's not a recipe in base chisel.
