### ISSUE TITLE
Minecraft Crash on Mod Loading (Log Included)

### ISSUE THREAD

**Issue by Wackywee** [Chisel-Team/Chisel#785]
I'm not sure if it's CTM or Chisel that is causing the issue, but when both are removed the problem seems to go away. Any help is appreciated.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Quark Plugin (Quark-r1.5-168.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar)
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/22/19 12:31 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:866)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1910_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at thebetweenlands.common.registries.BlockRegistry.registerBlocks(BlockRegistry.java:866)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1910_BlockRegistry_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 259442336 bytes (247 MB) / 2147483648 bytes (2048 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_C7 125 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version                   | Source                                                        | Signature                                |
	|:----- |:-------------------------------------------- |:------------------------- |:------------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                                    | 1.12.2                    | minecraft.jar                                                 | None                                     |
	| LCH   | mcp                                          | 9.42                      | minecraft.jar                                                 | None                                     |
	| LCH   | FML                                          | 8.0.99.99                 | forge-1.12.2-14.23.5.2838.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                                        | 14.23.5.2838              | forge-1.12.2-14.23.5.2838.jar                                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ivtoolkit                                    | 1.3.3-1.12                | minecraft.jar                                                 | None                                     |
	| LCH   | com.elytradev.movingworld.common.asm.coremod |                           | minecraft.jar                                                 | None                                     |
	| LCH   | openmodscore                                 | 0.11.5                    | minecraft.jar                                                 | None                                     |
	| LCH   | opencomputers|core                           | 1.7.3.146                 | minecraft.jar                                                 | None                                     |
	| LCH   | dsurroundcore                                | 3.5.4.3                   | minecraft.jar                                                 | None                                     |
	| LCH   | malisiscore                                  | 1.12.2-6.4.0              | malisiscore-1.12.2-6.4.0.jar                                  | None                                     |
	| LCH   | cubicchunks                                  | 1.12.2-0.0.809.0          | CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar | None                                     |
	| LCH   | jei                                          | 4.15.0.268                | jei_1.12.2-4.15.0.268.jar                                     | None                                     |
	| LCH   | abyssalcraft                                 | 1.9.9                     | AbyssalCraft-1.12.2-1.9.9.jar                                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aether_legacy                                | 1.4.4                     | aether_legacy-1.12.2-v1.4.4.jar                               | None                                     |
	| LCH   | baubles                                      | 1.5.2                     | Baubles-1.12-1.5.2.jar                                        | None                                     |
	| LCH   | atum                                         | 2.0.11                    | Atum-1.12.2-2.0.11.jar                                        | None                                     |
	| LCH   | quark                                        | r1.5-168                  | Quark-r1.5-168.jar                                            | None                                     |
	| LCH   | autoreglib                                   | 1.3-31                    | AutoRegLib-1.3-31.jar                                         | None                                     |
	| LCH   | ctm                                          | MC1.12.2-0.3.3.22         | CTM-MC1.12.2-0.3.3.22.jar                                     | None                                     |
	| LCH   | chisel                                       | MC1.12.2-0.2.1.35         | Chisel-MC1.12.2-0.2.1.35.jar                                  | None                                     |
	| LCH   | endercore                                    | 1.12.2-0.5.59             | EnderCore-1.12.2-0.5.59.jar                                   | None                                     |
	| LCH   | thaumcraft                                   | 6.1.BETA26                | Thaumcraft-1.12.2-6.1.BETA26.jar                              | None                                     |
	| LCH   | codechickenlib                               | 3.2.2.353                 | CodeChickenLib-1.12.2-3.2.2.353-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                                 | 2.1.0                     | RedstoneFlux-1.12-2.1.0.6-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                                     | 4.6.3                     | CoFHCore-1.12.2-4.6.3.27-universal.jar                        | None                                     |
	| LCH   | brandonscore                                 | 2.4.16                    | BrandonsCore-1.12.2-2.4.16.207-universal.jar                  | None                                     |
	| LCH   | cofhworld                                    | 1.3.1                     | CoFHWorld-1.12.2-1.3.1.7-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalfoundation                            | 2.6.3                     | ThermalFoundation-1.12.2-2.6.3.27-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | draconicevolution                            | 2.3.23                    | Draconic-Evolution-1.12.2-2.3.23.345-universal.jar            | None                                     |
	| LCH   | thermalexpansion                             | 5.5.4                     | ThermalExpansion-1.12.2-5.5.4.43-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | enderio                                      | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderiointegrationtic                        | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | mantle                                       | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                                      | None                                     |
	| LCH   | twilightforest                               | 3.8.689                   | twilightforest-1.12.2-3.8.689-universal.jar                   | None                                     |
	| LCH   | tconstruct                                   | 1.12.2-2.12.0.157         | TConstruct-1.12.2-2.12.0.157.jar                              | None                                     |
	| LCH   | mmdlib                                       | 1.0.0-rc2                 | MMDLib-1.12-1.0.0-rc2.36.jar                                  | None                                     |
	| LCH   | basemetals                                   | 2.5.0-rc2                 | BaseMetals-1.12-2.5.0-rc2.332.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | forgelin                                     | 1.8.3                     | Forgelin-1.8.3.jar                                            | None                                     |
	| LCH   | betterfoliage                                | 2.2.0                     | BetterFoliage-MC1.12-2.2.0.jar                                | None                                     |
	| LCH   | biometweaker                                 | 3.2.354                   | BiomeTweaker-1.12.2-3.2.354.jar                               | bdea6e9d19f35da4858ffcc93210c6207dd590bd |
	| LCH   | biomesoplenty                                | 7.0.1.2439                | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar                 | None                                     |
	| LCH   | botania                                      | r1.10-361                 | Botania+r1.10-361.jar                                         | None                                     |
	| LCH   | chameleon                                    | 1.12-4.1.3                | Chameleon-1.12-4.1.3.jar                                      | None                                     |
	| LCH   | chesttransporter                             | 2.8.8                     | ChestTransporter-1.12.2-2.8.8.jar                             | None                                     |
	| LCH   | chickens                                     | 6.0.4                     | chickens-6.0.4.jar                                            | None                                     |
	| LCH   | chiselsandbits                               | 14.33                     | chiselsandbits-14.33.jar                                      | None                                     |
	| LCH   | sanlib                                       | 1.5.1                     | SanLib-1.12.2-1.5.1.jar                                       | df48348748b5e141b1d118e2302a8d5be930b708 |
	| LCH   | claysoldiers                                 | 3.0.0-beta.1.1            | ClaySoldiersMod-1.12.2-3.0.0-beta.1.1.jar                     | None                                     |
	| LCH   | controlling                                  | 3.0.7                     | Controlling-3.0.7.jar                                         | None                                     |
	| LCH   | crafttweaker                                 | 4.1.19                    | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
	| LCH   | cookingforblockheads                         | 6.4.71                    | CookingForBlockheads_1.12.2-6.4.71.jar                        | None                                     |
	| LCH   | ctgui                                        | 1.0.0                     | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
	| LCH   | crafttweakerjei                              | 2.0.3                     | CraftTweaker2-1.12-4.1.19.jar                                 | None                                     |
	| LCH   | dimdoors                                     | 3.0.9+287                 | DimensionalDoors-3.0.9-287.jar                                | None                                     |
	| LCH   | mocreatures                                  | 12.0.3                    | DrZharks MoCreatures Mod-12.0.3.jar                           | None                                     |
	| LCH   | enderiobase                                  | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderioconduits                              | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderioconduitsappliedenergistics            | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | opencomputers                                | 1.7.3.146                 | OpenComputers-MC1.12.2-1.7.3.146.jar                          | None                                     |
	| LCH   | enderioconduitsopencomputers                 | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | refinedstorage                               | 1.6.14                    | refinedstorage-1.6.14.jar                                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCH   | enderioconduitsrefinedstorage                | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderiointegrationforestry                   | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderiointegrationticlate                    | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | ftblib                                       | 5.4.3.129                 | FTBLib-5.4.3.129.jar                                          | None                                     |
	| LCH   | enderiomachines                              | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderiopowertools                            | 5.0.46                    | EnderIO-1.12.2-5.0.46.jar                                     | None                                     |
	| LCH   | enderstorage                                 | 2.4.2.126                 | EnderStorage-1.12.2-2.4.2.126-universal.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | extrautils2                                  | 1.0                       | extrautils2-1.12-1.9.9.jar                                    | None                                     |
	| LCH   | zerocore                                     | 1.12.2-0.1.2.8            | zerocore-1.12.2-0.1.2.8.jar                                   | None                                     |
	| LCH   | bigreactors                                  | 1.12.2-0.4.5.67           | ExtremeReactors-1.12.2-0.4.5.67.jar                           | None                                     |
	| LCH   | ferdinandsflowers                            | 1.10.1b                   | Ferdinand's+Flowers-1.10.1b-1.12.jar                          | None                                     |
	| LCH   | ichunutil                                    | 7.2.1                     | iChunUtil-1.12.2-7.2.1.jar                                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | generallaymansaestheticspyingscreen          | 7.0.0                     | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar          | None                                     |
	| LCH   | gravestone                                   | 1.10.1                    | gravestone-1.10.1.jar                                         | None                                     |
	| LCH   | hatchery                                     | 2.2.2                     | hatchery-1.12.2-2.2.2.jar                                     | None                                     |
	| LCH   | waila                                        | 1.8.24                    | Hwyla-1.8.24-B39_1.12.jar                                     | None                                     |
	| LCH   | incontrol                                    | 3.9.12                    | incontrol-1.12-3.9.12.jar                                     | None                                     |
	| LCH   | infinitylib                                  | 1.12.2-1.12.0             | infinitylib-1.12.0.jar                                        | None                                     |
	| LCH   | inventorytweaks                              | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironbackpacks                                | 1.12.2-3.0.8-12           | IronBackpacks-1.12.2-3.0.8-12.jar                             | None                                     |
	| LCH   | ironchest                                    | 1.12.2-7.0.67.844         | ironchest-1.12.2-7.0.69.845.jar                               | None                                     |
	| LCH   | journeymap                                   | 1.12.2-5.5.4              | journeymap-1.12.2-5.5.4.jar                                   | None                                     |
	| LCH   | jeresources                                  | 0.8.5.27                  | JustEnoughResources-1.12.2-0.8.5.27.jar                       | None                                     |
	| LCH   | lostcities                                   | 2.0.20                    | lostcities-1.12-2.0.20.jar                                    | None                                     |
	| LCH   | lycanitesmobs                                | 2.0.0.4 - MC 1.12.2       | lycanitesmobs-1.12.2-2.0.0.4.jar                              | None                                     |
	| LCH   | mcjtylib_ng                                  | 3.5.3                     | mcjtylib-1.12-3.5.3.jar                                       | None                                     |
	| LCH   | mjrlegendslib                                | 1.12.2-1.1.3              | MJRLegendsLib-1.12.2-1.1.3.jar                                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCH   | mob_grinding_utils                           | 0.3.6                     | MobGrindingUtils-0.3.6.jar                                    | None                                     |
	| LCH   | immersiveengineering                         | 0.12-89                   | ImmersiveEngineering-0.12-89.jar                              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCH   | morechickens                                 | 3.1.0                     | morechickens-1.12.2-3.1.0.jar                                 | None                                     |
	| LCH   | mousetweaks                                  | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                                 | None                                     |
	| LCH   | movingworld                                  | 1.12-6.342                | movingworld-1.12-6.342-full.jar                               | None                                     |
	| LCH   | llibrary                                     | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs                                  | 1.5.4                     | mowziesmobs-1.5.4.jar                                         | None                                     |
	| LCH   | natura                                       | 1.12.2-4.3.2.49           | natura-1.12.2-4.3.2.49.jar                                    | None                                     |
	| LCH   | naturescompass                               | 1.5.1                     | NaturesCompass-1.12.2-1.5.1.jar                               | None                                     |
	| LCH   | openmods                                     | 0.11.5                    | OpenModsLib-1.12.2-0.11.5.jar                                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | openblocks                                   | 1.7.6                     | OpenBlocks-1.12.2-1.7.6.jar                                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCH   | harvestcraft                                 | 1.12.2u                   | Pam's+HarvestCraft+1.12.2u.jar                                | None                                     |
	| LCH   | potioncore                                   | 1.6_for_1.12.2            | PotionCore-1.6_for_1.12.2.jar                                 | None                                     |
	| LCH   | psi                                          | r1.1-77                   | Psi-r1.1-77.jar                                               | None                                     |
	| LCH   | reccomplex                                   | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                                  | None                                     |
	| LCH   | rftools                                      | 7.71                      | rftools-1.12-7.71.jar                                         | None                                     |
	| LCH   | rftoolscontrol                               | 2.0.2                     | rftoolsctrl-1.12-2.0.2.jar                                    | None                                     |
	| LCH   | rftoolsdim                                   | 5.71                      | rftoolsdim-1.12-5.71.jar                                      | None                                     |
	| LCH   | roost                                        | 2.0.10                    | roost-1.12.2-2.0.10.jar                                       | None                                     |
	| LCH   | sanplayermodel                               | 1.1.1                     | SanLib-1.12.2-1.5.1.jar                                       | None                                     |
	| LCH   | simulatednights                              | 1.12-2.1.0                | simulatednights-1.12-2.1.0.jar                                | None                                     |
	| LCH   | soundfilters                                 | 0.11_for_1.12             | SoundFilters-0.11_for_1.12.jar                                | None                                     |
	| LCH   | stellarapi                                   | 1.12.2-0.4.2.9            | Stellar+API-1.12.2-0.4.2.9.jar                                | None                                     |
	| LCH   | stellarsky                                   | 1.12.2-0.5.2.8            | Stellar+Sky-1.12.2-0.5.2.8.jar                                | None                                     |
	| LCH   | storagedrawers                               | 1.12-5.3.5                | StorageDrawers-1.12.2-5.3.8.jar                               | None                                     |
	| LCH   | tellme                                       | 0.7.0-dev.20190610.165828 | tellme-1.12.2-0.7.0-dev.20190610.165828.jar                   | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | thermaldynamics                              | 2.5.5                     | ThermalDynamics-1.12.2-2.5.5.21-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769  | TinkerToolLeveling-1.12.2-1.1.0.jar                           | None                                     |
	| LCH   | toolbelt                                     | 1.9.8                     | ToolBelt-1.12.2-1.9.8.jar                                     | None                                     |
	| LCH   | treechopper                                  | 1.2.4                     | TreeChopper-1.12.2-1.2.4.jar                                  | None                                     |
	| LCH   | vc                                           | 5.9.13                    | ViesCraft-1.12.2-5.9.13.jar                                   | None                                     |
	| LCH   | worleycaves                                  | 1.4.1                     | worleycaves-1.4.1.jar                                         | None                                     |
	| LCH   | xtones                                       | 1.12-1.0.8-11             | Xtones-1.12-1.0.8-11.jar                                      | None                                     |
	| LCH   | orelib                                       | 3.5.2.2                   | OreLib-1.12.2-3.5.2.2.jar                                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround                                    | 3.5.4.3                   | DynamicSurroundings-1.12.2-3.5.4.3.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | thebetweenlands                              | 3.4.9                     | TheBetweenlands-3.4.9-universal.jar                           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UD    | cubicchunkscore                              | @@VERSION@@               | minecraft.jar                                                 | None                                     |

	Loaded coremods (and transformers): 
Quark Plugin (Quark-r1.5-168.jar)
  vazkii.quark.base.asm.ClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.59-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.809.0-all_bottomVoidFix-instaDeath.jar)
  
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.3.146.jar)
  li.cil.oc.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 430.64' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	[Psi] Active spell: None
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Necessary Textures, Lithos-Core+v1.23+for+1.12x.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-1.0.0
	OpenGlVersion: 4.6.0 NVIDIA 430.64
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by tterrag1098** [comment]
You ran out of block IDs. Not a chisel issue.

**Comment by Wackywee** [comment]
Is there a solution? It definitely doesn't seem like there is.

**Comment by tterrag1098** [comment]
The solution is to have less blocks. Beyond that I can't recommend anything.

**Comment by Wackywee** [comment]
you could recommend this https://www.curseforge.com/minecraft/mc-mods/notenoughids because it actually works

**Comment by tterrag1098** [comment]
Actually I intentionally DIDN'T recommend that because it can cause many issues.

**Comment by Wackywee** [comment]
Ehhhh, it's worth a shot? I seem to have been lucky then, being that I have 129 mods installed. Anyhow, great work on the mod, I didn't know it had so much in it
