### ISSUE TITLE
Chisel uses a non-standard JSON format that is causing errors in other plugins

### ISSUE THREAD

**Issue by nate2014jatc** [Chisel-Team/Chisel#786]
Related to https://github.com/webbukkit/DynmapBlockScan/issues/31
A fix or workaround would be awesome, given that a significant amount of my structures use Chiselled blocks, and now they're not even showing on the map.

[Example #1](https://maps.astragroup.info/?worldname=Gaia&mapname=surface&zoom=6&x=-3634&y=64&z=3004)

[Example #2](https://maps.astragroup.info/?worldname=Gaia&mapname=surface&zoom=6&x=-1199&y=64&z=2638)

**Comment by nate2014jatc** [comment]
[Example #1 in Game](https://cloud.astragroup.info/index.php/s/sJJ45WPqp9N6mR7)
[Example #2 in Game](https://cloud.astragroup.info/index.php/s/3s8pNLnBPTFT8cK)

**Comment by tterrag1098** [comment]
Chisel follows all the rules it needs to, all our blockstates and models are no different than any other mod. Dynmap needs to either fix it themselves or tell us *specifically* what the problem is.
