### ISSUE TITLE
Glass blocks and Bookshelves don't render correctly

### ISSUE THREAD

**Issue by Tschipp** [Chisel-Team/Chisel#790]
![image](https://user-images.githubusercontent.com/11649893/64461676-230f8100-d0fe-11e9-8c62-d41a57592a94.png)

On the left from the glass is a bookshelf block from chisel. The textures don't seem to be rendering correctly.
I'm using forge 2838 and chisel 0.2.1.35.
I'm not using optifine.

**Comment by tterrag1098** [comment]
Probably some other coremod messing with the render layer logic. Try removing coremods until it works? A mod list would be helpful.

**Comment by Tschipp** [comment]
Hey, so I figured out what the cause of this was. Apparently, it was one of my own mods that messed it up 😳 
![image](https://user-images.githubusercontent.com/11649893/83579826-9da8e800-a53a-11ea-96a6-362399808554.png)
As you can see, it completely ruins the uv mapping and texture overlay of lavastone (and others).

My mod wraps every model in the model registry in its own model, that just basically displays a red question mark when the user doesn't have a certain game stage. 
I *thought* I did it properly such that it always takes the values of the parent model, but apparently I messed it up somewhere. Since you know more about how the CTM models work, I'm asking for your assistance in fixing the bug.

This is my model (the rest of the code is also on github):
https://github.com/Tschipp/HardcoreItemStages/blob/master/src/main/java/tschipp/hardcoreitemstages/client/HardcoreItemStageModel.java#L31-L141

**Comment by Tschipp** [comment]
Closing this.
