### ISSUE TITLE
Give an option to disable chiseled ice melting

### ISSUE THREAD

**Issue by ccfb3ee765a58cae** [Chisel-Team/Chisel#794]
83bb7fd67764cad59ad163f92dcc0822e002a78c makes ice melt when exposed to light. I have a world with a lot of ice directly next to light sources, so this change can definitely screw up existing worlds. Maybe provide a config option for this?

For now I've just commented out [these lines of code](https://github.com/Chisel-Team/Chisel/blob/924ef5d5a2aa8f958e6a1128eea046ede11c98eb/src/main/java/team/chisel/common/block/BlockCarvableIce.java#L82-L84) in my local copy of the mod.

Some pre-destruction screenshots just to guilt you into adding this option for MC 1.12 (Don't worry, I made backups, my world is fine)

![](https://i.imgur.com/hZdv2Ie.png)

![](https://i.imgur.com/weEXnOe.png)

![](https://i.imgur.com/g2GEJep.png)

![](https://i.imgur.com/sY1S9as.png)

![](https://i.imgur.com/S1lONSP.png)

![](https://i.imgur.com/oeSSEWx.png)

![](https://i.imgur.com/A5gxMtP.png)

![](https://i.imgur.com/b1Xu09S.png)

![](https://i.imgur.com/Mr6Htmb.png)

**Comment by tterrag1098** [comment]
I want to maintain consistency with vanilla, so I'll make you a compromise. I'll make sure Chisel is compatible with mods like [Icy U Melting](https://www.curseforge.com/minecraft/mc-mods/icy-u-melting) which disable the random ticking of ice.
