### ISSUE TITLE
Antiblock lighing broke after update

### ISSUE THREAD

**Issue by syntience** [Chisel-Team/Chisel#795]
![2019-10-16_22 35 55](https://user-images.githubusercontent.com/23645173/66973275-7eba1c00-f065-11e9-8c39-918ad4d56264.png)
Chisel + optifine and some other mods, 1.12.2. After the recent update, lighting kind of broke with white antiblocks. Tried with different lighting sources and replacing blocks. Only applies to antiblocks from what i've seen.

**Comment by tterrag1098** [comment]
Fullbright does not support Optifine, never has. The logic here was not changed in the most recent update.

**Comment by syntience** [comment]
okay wait, but it definitely wasn't like this before. it was totally fine and now it suddenly doesn't work.

**Comment by syntience** [comment]
also, i don't have fullbright installed.

**Comment by tterrag1098** [comment]
"Fullbright" is not a mod, it's what makes antiblocks work. I can tell you with certainty that it does not work with optifine, see https://github.com/sp614x/optifine/issues/631

**Comment by syntience** [comment]
ah, ok. i have no idea why it looked fine earlier then. i'll just try messing with optifine or using a different block. sorry to bother you

**Comment by tterrag1098** [comment]
You must not have had Optifine installed? The code literally doesn't run when Optifine is present, because it bugs out way worse if I don't do that.

**Comment by syntience** [comment]
no, i definitely had optifine installed. i have no idea what it was, maybe the lighting source was different. i wish i had a screenshot, but the antiblocks definitely had smooth lighting even with optifine installed.

**Comment by syntience** [comment]
but after updating chisel and connected textures mod, the lighting broke

**Comment by syntience** [comment]
actually, i'm going to try reverting back to the old versions of the two mods i updated to see if i can get the lighting back to how it was, just out of curiosity

**Comment by syntience** [comment]
right nevermind, that didn't work. uh, i'll just take out optifine i guess. conflicts with thaumcraft too.

**Comment by syntience** [comment]
@tterrag1098 wait hold on, yeah here, it was the update
https://prnt.sc/pku4h8
http://prntscr.com/pku4kr
see, the lighting's fine, and i have optifine installed

this was with chisel 0.2.1.35 and optifine 1.12.2_HD_U_E3

**Comment by tterrag1098** [comment]
It's not working in that screenshot either (notice how the light in the center casts a "circle" on the blocks), it just has smooth lighting. I'm not sure why smooth lighting would break, because like I said the code in question literally doesn't run when Optifine is present. Sounds like an Optifine issue to me.

**Comment by syntience** [comment]
ok, i think i get what you're saying. probably. either way, that smooth lighting in the screenshot is what i'm looking for. pre-update had smooth lighting, post-update had that bad, blocky lighting. but if you don't know, i'll just try tampering with things or uninstalling optifine if i have to. thanks for your help
