### ISSUE TITLE
Chisel 1.0 - Option to disable block categories gone

### ISSUE THREAD

**Issue by brisingraerowing** [Chisel-Team/Chisel#796]
I am using Chisel 1.0 in a Medieval / Fantasy / Magic themed modpack, and I want to disable the more technical block types (like the Factory and Laboratory blocks), but the option isn't in the config file anymore. Is there another way to disable them?

**Comment by tterrag1098** [comment]
Config file was not changed, the feature system still exists just the same. What does your config look like?

**Comment by brisingraerowing** [comment]
[Here's the entire file](https://gist.github.com/BrisingrAerowing/06e25098c29c15b3e6bf8cd5d1c67ab5).

**Comment by NoxyNixie** [comment]
I can confirm that Chisel 1.0.0.42 does not allow you to disable block "features". I decided to completely scrap my `chisel.cfg` to see what the new config would look like and I found that the entire `features` section is completely gone indicating that this section is no longer being used at all.

**Comment by NoxyNixie** [comment]
`1.0.1.44` fixes this. Thanks much.
