### ISSUE TITLE
Nonfunctioning connected textures with resource pack

### ISSUE THREAD

**Issue by DannyDan4** [Chisel-Team/Chisel#799]
When running a resource pack in chisel version 1.0.1.44 and CTM version 1.0.0.29, some connected textures of chisel blocks become nonfunctional. Issue demonstrated with pureBDcraft x64 here:
![2019-11-10_18 29 36](https://user-images.githubusercontent.com/27591249/68552716-1baf7100-03e8-11ea-84d3-a228d5d46cf4.png)

**Comment by DannyDan4** [comment]
From top to bottom, circular bricks with CTM, sturdy factory blocks, lava brick (dent), and red antiblocks

**Comment by dansproject** [comment]
I'm having the exact same problem on project ozone 3 using sphax 64x

**Comment by tterrag1098** [comment]
The resource pack needs an update. See: Chisel-Team/ConnectedTexturesMod#111
