### ISSUE TITLE
Compat is adding end stones variants to the wrong group

### ISSUE THREAD

**Issue by ephys** [Chisel-Team/Chisel#8]
The end stone group is "end_Stone" but compatibility is adding blocks to the "end_stone" group, resulting in two different groups.

https://github.com/Chisel-Team/Chisel/blob/1.7/dev/src/main/java/team/chisel/Features.java#L707
https://github.com/Chisel-Team/Chisel/blob/74cdb6355c501cc30a88b3c99a72b3a22f0a98e8/src/main/java/team/chisel/compat/Compatibility.java#L92

**Comment by tterrag1098** [comment]
Love inconsistent naming...need to go through and clean everything up _sigh_
