### ISSUE TITLE
Chiseling "base" Sooty Marble

### ISSUE THREAD

**Issue by TrekGIneer22** [Chisel-Team/Chisel#801]
Is there a reason you need to craft Astral Sorcery Sooty Marble into bricks before you can chisel it?  You can chisel base Astral Sorcery Marble, just seem like an odd thing, and it leaves me with 1-3 leftover "base" blocks at times.

**Comment by tterrag1098** [comment]
Report this to astral sorcery, they are registering the variants, not us.

**Comment by TrekGIneer22** [comment]
so you don't have a config file of "available" options?
