### ISSUE TITLE
Glowstone chisel texture needs adjustment

### ISSUE THREAD

**Issue by RoguishType** [Chisel-Team/Chisel#802]
I've been playing Enigmatica Expert and building my base with glowstone. The textures for ALL chiseled glowstone are horrifically misaligned. It's VERY irksome because it's pinging my OCD something fierce and it's the only easily attainable light block and vanilla glowstone, while not OCD inducing is still rather ugly. 

https://puu.sh/EIFsi/66b044bde0.png

https://puu.sh/EIFry/452726020f.png

Just make the texture symmetrical please. That's all I want ;_;

**Comment by tterrag1098** [comment]
All the blocks with that variant are like that, so that it tiles correctly. This is the intended look AFAIK, so not a bug.

**Comment by Drullkus** [comment]
Textured as intended, will look better in JAPPA retexture
