### ISSUE TITLE
Bug with chiseled glass and only chiseled glass blocks to that.

### ISSUE THREAD

**Issue by SirAron111** [Chisel-Team/Chisel#805]
Bug with chiseled glass and only chiseled glass blocks to that.

Forge: 14.23.5.2847
Chisel:  Chisel - MC1.12.2-1.0.1.44
CTM: CTM - MC1.12.2-1.0.1.30 
Modpack for Mod list: Dimension Zero

I found a bug with Chisel Glass blocks (panes work fine) where the texture is not see trough but becomes solid. I removed all mods that mess with rendering and didn’t use Optifine. Problem remained! Couldn’t find out where it’s coming from. Here is a screenshot. And it’s not the texture pack; I tried it without it as well.
![2019-12-01_12 43 03](https://user-images.githubusercontent.com/39855956/69913787-ff2db400-143c-11ea-90c3-56d1c0bcfca2.png)

**Comment by tterrag1098** [comment]
Not a chisel issue, the resource pack is outdated, but fixed via https://github.com/Chisel-Team/Chisel/commit/60053ea423e724486988d91cbdc252104f8f5183

**Comment by Fulmetalmon** [comment]
> Not a chisel issue, the resource pack is outdated, but fixed via [60053ea](https://github.com/Chisel-Team/Chisel/commit/60053ea423e724486988d91cbdc252104f8f5183)

um if there is a way for me to fix the problem with that solution how would I go about doing that.

**Comment by tterrag1098** [comment]
The fix will be included in the next release whenever that is.
