### ISSUE TITLE
Presents spamming log with exceptions

### ISSUE THREAD

**Issue by Vexatos** [Chisel-Team/Chisel#81]
Only happens on Multiplayer: http://pastebin.com/R2fYumQD

You probably shouldn't call [`sendToDimension`](https://github.com/Chisel-Team/Chisel/blob/1.7/dev-3.0/src/main/java/team/chisel/block/tileentity/TileEntityPresent.java#L80) on the client side. I guess a `!worldObj.isRemote` check in `connectTo` should suffice to fix this.

**Comment by Drullkus** [comment]
Chiseled Chests removed
