### ISSUE TITLE
Chisel missing textures

### ISSUE THREAD

**Issue by VampireCow** [Chisel-Team/Chisel#810]
So I threw together a set of mods I really like and started playing but some of the chisel textures are missing and I have CTM installen and all.

What can I do or what did I do wrong?

Thanks in advance!
![NoTextures](https://user-images.githubusercontent.com/60562100/73602934-f90e9d80-457b-11ea-9fc1-2b4061925a0c.JPG)

**Comment by tterrag1098** [comment]
Uninstall your texture pack, if the issue is resolved report it to them.
