### ISSUE TITLE
Chisel Error with WorldEdit

### ISSUE THREAD

**Issue by ShidoB** [Chisel-Team/Chisel#813]
So,
I want to //set a chiseled block but it says "Can't figure out what block ....... refers to"

 ##
![javaw_ec67HtBsC2](https://user-images.githubusercontent.com/52756533/75070142-ef30e800-54f2-11ea-9a38-316ac1b9ae96.png)

![javaw_FqDRUWtpqc](https://user-images.githubusercontent.com/52756533/75070169-feb03100-54f2-11ea-842e-1b3821aef835.png)

I already tried to do the /info thing, but it gives me the wrong block.
Please help.

**Comment by tterrag1098** [comment]
worldedit (finally) no longer supports integer IDs. provide the proper registry name instead, in this case chisel:stonebrick2:5
