### ISSUE TITLE
"Minecraft failed to start"

### ISSUE THREAD

**Issue by mystericalmonkey** [Chisel-Team/Chisel#815]
"An error during startup prevented Minecraft from starting

The following mod(s) have been identified as potential causes:
Chisel"

It says to report it to the mod author, just wondering how I can fix it, here's the report:
https://paste.dimdev.org/jayijomuxu.mccrash

I don't know anything about code, hoping someone can help me out.

**Comment by Arildil** [comment]
I got the same error... It happens only if I have Chisel and CTM both installed...
It doesn't crash if one of them is missing.

I'll add the report, if it helps to find the problem.
[crash-2020-03-13_18.16.00-client.txt](https://github.com/Chisel-Team/Chisel/files/4330845/crash-2020-03-13_18.16.00-client.txt)

**Comment by tterrag1098** [comment]
Your chisel is severely out of date.

       | LCH   | chisel                    | MC1.12.2-0.2.0.31    | Chisel-Mod-1.12.2.jar                                        | None                                     |

Where did you get this file? I don't name my jars like that. Please update to the latest version of Chisel *from CurseForge* and nowhere else.

**Comment by Arildil** [comment]
I got both from CurseForge and I got that error...
Both recommended version for 1.12.2
