### ISSUE TITLE
Glass panes don't connect to the backs of stairs

### ISSUE THREAD

**Issue by tehFoxx0rz** [Chisel-Team/Chisel#82]
Unlike vanilla's: https://dl.dropboxusercontent.com/u/66131226/2015-12-26_12.26.27.png

Chisel's (same with stained ones and iron bars as well): https://dl.dropboxusercontent.com/u/66131226/2015-12-26_12.25.48.png

Oops, fixed link.

**Comment by tterrag1098** [comment]
That's the same link twice

**Comment by Drullkus** [comment]
Should be different due to new model system
