### ISSUE TITLE
Block of Iron (Simple) Side Texture Off By A Pixel

### ISSUE THREAD

**Issue by zth404** [Chisel-Team/Chisel#821]
I was building an underground base using the Block of Iron (Simple) and noticed the side textured looked pushed up a pixel. (This is using the latest version and the version before)

**Comment by tterrag1098** [comment]
What variant is "Simple"? That's not a variant I know of.

**Comment by zth404** [comment]
It’s ID is chisel:iron:14

**Comment by tterrag1098** [comment]
That's the intended look.
