### ISSUE TITLE
Smooth lighting antiblock bug with Optifine

### ISSUE THREAD

**Issue by syruppp** [Chisel-Team/Chisel#826]
After the recent Direwolf20 1.12 update, which updated Chisel from 0.2.1.35 to 1.0.2.45, Antiblocks appear to be bugged with smooth lighting.

https://i.imgur.com/usFjuTD.png

Latest 1.12.2 Optifine with latest BSL Shaders (tried older versions too; same result, and same with Sildur's). Appears to be every color.

**Comment by tterrag1098** [comment]
Does it occur without Optifine? If not report it to them.
