### ISSUE TITLE
Anti blocks affected by light?

### ISSUE THREAD

**Issue by Mathiousse** [Chisel-Team/Chisel#832]
Playing on MCEternal (1.12.2) and wanted to make a build with Antiblocks, and it seems that Antiblocks are affected by light and aren't glowing like they used to, is that normal or did i do something wrong?
[Here is an example](https://i.imgur.com/DOajYhD.png)

**Comment by tterrag1098** [comment]
Optifine bug, see https://github.com/sp614x/optifine/issues/631
