### ISSUE TITLE
missing particles for chisel blocks

### ISSUE THREAD

**Issue by FilmForge3D** [Chisel-Team/Chisel#833]
![2020-05-23_17 22 25](https://user-images.githubusercontent.com/65822131/82734736-32cb0600-9d1d-11ea-9111-2a991d4cabe2.png)
![2020-05-23_17 22 28](https://user-images.githubusercontent.com/65822131/82734737-33fc3300-9d1d-11ea-9edc-4d78bfabe982.png)
Affects all chisel blocks not only naturally generated ones. Survival only.

**Comment by tterrag1098** [comment]
Are you up to date?

**Comment by FilmForge3D** [comment]
Yes I'm up to date but I have a lot of mods installed.
Maybe you have an idea where to look for those particles that have been lost.

**Comment by WensenVos** [comment]
A bit late, but I encountered this exact same issue while working on two modpacks for v1.12.2. The solution for me was to remove AtomicStryker's MultiMine mod, which I think I see in your 2nd screenshot. 🐺
