### ISSUE TITLE
Walk faster on concrete

### ISSUE THREAD

**Issue by Bobos0528** [Chisel-Team/Chisel#838]
Whenever i walk on on concrete its faster than all other blocks. I have removed the mod from the folder and that fixes the issue.

**Comment by thedarkcolour** [comment]
That's intended I'm pretty sure

**Comment by ChloeDawn** [comment]
You can change the speed multiplier in the configuration if you don't want to move faster on it. Personally I've never understood why this feature exists in the mod.

**Comment by tterrag1098** [comment]
Working as intended.
