### ISSUE TITLE
[Enhancement] Chiseled bookshelves should support enchantment tables

### ISSUE THREAD

**Issue by hron84** [Chisel-Team/Chisel#84]
Based on our [previous coversation](https://twitter.com/tterrag1098/status/680469578569224192) chiseled bookshelves should provide their books for enchantment tables (both for vanilla and modded ones, like EnchantingPlus. OpenBlocks, or MFR)

**Comment by Drullkus** [comment]
I'm in full support of this.

**Comment by Drullkus** [comment]
This has existed for quite a while, I don't even seriously know when this was actually added, but it was definitely added before Aug 18th.

**Comment by tterrag1098** [comment]
Turns out this was even in AUTOMATIC_MAIDEN's code, so, whoops.
