### ISSUE TITLE
Chisel 1.12.2 missing texture

### ISSUE THREAD

**Issue by albatrosQc** [Chisel-Team/Chisel#842]
![9C2DDACD-A42E-4A9E-BD83-6D81F79BC751](https://user-images.githubusercontent.com/67439730/85858521-c6af4800-b789-11ea-889c-c84e656bdab5.png)
![84E38F75-80D2-4D3F-AA6A-F9DE49BB0B54](https://user-images.githubusercontent.com/67439730/85858524-c6af4800-b789-11ea-89ee-54d1ee10839b.png)
![5123C71E-3FA3-402F-AEF7-FA2FADEC998E](https://user-images.githubusercontent.com/67439730/85858525-c747de80-b789-11ea-9f8f-a939308a9103.png)

i only have the bookshelf texture and the other are missing i have read a thing said i need CTM i have instaled it but now my game crash at the launching please help me

**Comment by tterrag1098** [comment]
Post the crash log if you want help.

**Comment by albatrosQc** [comment]
I post it

**Comment by albatrosQc** [comment]
> Post the crash log if you want help. Done

**Comment by tterrag1098** [comment]
Update chisel.
