### ISSUE TITLE
1.12.2 Server config is lower in priority than client config.

### ISSUE THREAD

**Issue by SeagalKru** [Chisel-Team/Chisel#847]
Hello!
There is a line in the config of your mod:
----------------
# The factor that concrete_white increases your velocity. Default is 1.35, set to 1 for no change.
  D: concreteVelocityMult = 1.35 "
---------------
On the server, the parameter is "1", and on the client - 1.35 (default).
When entering the server, the parameter "1" is not perceived and my speed of movement through the blocks of your mod is 1.35 (client), but not "1" (server).
Is it possible to fix this ?!
Thank you!

**Comment by tterrag1098** [comment]
No not easily, that's just how movement works in the game.
