### ISSUE TITLE
1.10.2 - Tinkers Seared Stone to Bricks

### ISSUE THREAD

**Issue by AefRal** [Chisel-Team/Chisel#849]
I'm using Chisel-MC1.10.2-0.2.1.47 and TConstruct-1.10.2-2.6.5.

For the life of me I can't get Seared Stone to chisel into Seared Bricks.
I tried adding "B:seared=true" to the list under "features {" in config, but that didn't work.
All the variants of Seared Stone are listed as "tconstruct:seared".

Not sure why it's not working.

![2020-09-01_13 41 26](https://user-images.githubusercontent.com/68062495/91899836-f3d11880-ec5a-11ea-925c-f9b864401c09.png)
![2020-09-01_13 41 34](https://user-images.githubusercontent.com/68062495/91899839-f5024580-ec5a-11ea-8003-b5c4bd680403.png)

Any help is appreciated.

**Comment by tterrag1098** [comment]
You can't add features there, that's not how it works. To customize chisel use a mod like ModTweaker.
