### ISSUE TITLE
Chisel'd Obsidian Harvest Level

### ISSUE THREAD

**Issue by Shahelion** [Chisel-Team/Chisel#85]
Currently, only vanilla obsidian has the "obsidian" mining level required, the chisel variants only require a pickaxe.
![2016-01-04_14 13 48](https://cloud.githubusercontent.com/assets/6917535/12102106/85564020-b2ed-11e5-8ffb-f4c612770d16.png)
![2016-01-04_14 13 50](https://cloud.githubusercontent.com/assets/6917535/12102107/85567798-b2ed-11e5-9480-3580797d6084.png)
![2016-01-04_14 13 52](https://cloud.githubusercontent.com/assets/6917535/12102108/85571a36-b2ed-11e5-9ce9-ab4d831694dc.png)

**Comment by Drullkus** [comment]
Should be fixed? ¯\_(ツ)_/¯
