### ISSUE TITLE
Anti-Blocks bug again

### ISSUE THREAD

**Issue by Palladium346** [Chisel-Team/Chisel#861]
Idk what could be causing it, but I'll tell a tale here first. I was playing through my run of a modpack called "Levitated", and when I got to making and placing down the Antiblocks,I expected them to be fullbright without any shading. Unfortunately, the opposite happened. The blocks end up having shadows, but they were not smooth/fancy lighting shadows, they were fast shadows. It looked pretty dang awful and had to end up place torches almost everywhere to try and hide it. This is how it looks when I placed them down, and when I tried spamming torches. 
![2021-02-26_04 22 46](https://user-images.githubusercontent.com/76013813/109295899-26686200-77f5-11eb-993f-1627f2e50e80.png)
![2021-02-26_04 36 32](https://user-images.githubusercontent.com/76013813/109295914-2bc5ac80-77f5-11eb-88b7-2a7c62010401.png)
As you can see, it wasn't good. Idk if the Chisel or CTM mods in the modpack are outdated or something in the modpack itself is causing a conflict.

**Comment by Palladium346** [comment]
Okay, just looked into some things on the issues closed. I guess the Optifine I added breaks CTM, so I may have to remove that thing. Problem I will have though is more lag as I am using a kinda weak PC and Optifine was the one thing keeping Minecraft rolling smoothly. What should I do before this issue is closed? Remove Optifine and deal with the PC limitations, or some other option(s)?

**Comment by tanyan-tanyan** [comment]
I had a similar issue with my Optifine breaking liquids which caused them to look just like in your screenshot, however my version was 1.16.5. My problem was that I had enabled some options that broke this, as my friend was not seeing what I was seeing. He ended up giving me his optifine options file so I can copy it over and it worked like a charm. You could potentially try turning all optifine options off/resetting everything back to default and checking if anything changes. But yeah, the bottom line is, Optifine breaks almost everything that goes beyond vanilla.

**Comment by tterrag1098** [comment]
Optifine breaks our fullbright code in 1.12, there's nothing that can be done. This will not be an issue on 1.16+.
