### ISSUE TITLE
Error chisel con world edit

### ISSUE THREAD

**Issue by NewRaptor** [Chisel-Team/Chisel#862]
Tengo un  problema y  me preguntaba como era para poner  bloques de el chisel en world edir, porque cuando pongo la id numerica me da error y la id de nombre la desconozco, si pueden ayudarme lo agradeceria.

**Comment by tterrag1098** [comment]
You can use the ID that shows in F3, which looks like chisel:marble, or chisel:marble:2 to select variants.
