### ISSUE TITLE
Crash on trying to open the chisel gui

### ISSUE THREAD

**Issue by CritFlaw** [Chisel-Team/Chisel#868]
On the 1.16 alpha, when trying to click the iChisel (Or whatever it's called in 1.16) the client crashes.
https://pastebin.com/xDMjYrBc - with Optifine
https://pastebin.com/u2WnVCp6- without Optifine
Forge 36.1.30
Chisel Chisel-MC1.16.5-2.0.0-alpha.3

**Comment by Jones-009** [comment]
it is also the same with the offset tool. can you actually chisel mod blocks?

**Comment by Bass2style** [comment]
same crash here : https://pastebin.com/76XVLXTZ

**Comment by WGINC** [comment]
same here: https://pastebin.com/Cc7UQzhS

**Comment by aaronhowser1** [comment]
Same here, but it made no crash report.

**Comment by AlienXtream** [comment]
im guessing something changed quite significantly in 1.16+ with GUI rendering and the IChisel got overlooked

**Comment by UnhappyCodings** [comment]
same for me: https://pastebin.com/DhaY8FLS
Crash on open of Hitech Chisel

**Comment by f1den** [comment]
Opening again.
---- Minecraft Crash Report ---- // Hey, that tickles! Hehehe!  Time: 11/10/23 7:59 PM Description: Rendering screen  java.lang.NullPointerException: Rendering screen     at team.chisel.client.gui.GuiHitechChisel.func_230450_a_

using 2.0.1-alpha on 1.16.5

**Comment by aaronhowser1** [comment]
A partial crash report isn't really enough for them to go off of I think.
Better to upload the file or copy it to pastebin or something and link it.
Also should possibly maybe be it's own issue.

**Comment by f1den** [comment]
Upd
