### ISSUE TITLE
Glass Blocks / Panels not chiselable

### ISSUE THREAD

**Issue by Manello** [Chisel-Team/Chisel#895]
Hello! Whenever I place glas blocks or glas panels in the chisel menu I am not able to chisel them.
The same goes for applying the chisel with left click to a glas panel.

MC Version: 1.16.5
Chisel Version: 2.0.1-alpha4
CTM Version: CTM-MC1.16.1-1.1.2.6

**Comment by Manello** [comment]
Update: The same goes for torches! They are not chiselable.

**Comment by The-Quarker** [comment]
they have not added these blocks yet

**Comment by Manello** [comment]
Oh dang, well I hope they will be added soon!
