### ISSUE TITLE
Some aluminum stairs have no textures

### ISSUE THREAD

**Issue by BBoldt** [Chisel-Team/Chisel#9]
As seen here:
![](http://i.imgur.com/LXN6cWD.png)

and here:
![](http://i.imgur.com/UXz1nSi.png)
- Chisel-2.9.0.3

**Comment by TheCricket** [comment]
Known its just something I need to fix with the StairMaker

**Comment by BBoldt** [comment]
Okay, might as well have it open as an issue on github though in case anyone else comes looking here.

**Comment by TheCricket** [comment]
Done

**Comment by tterrag1098** [comment]
This was fixed in ab6fab4e64153fd06c8ae41f6940a876ed879266

**Comment by Bogdan-G** [comment]
Version 2.9.3.9, bug return:
![1](http://imgur.com/mpZ4i2G.png)
![2](http://imgur.com/IhzJq2L.png)

**Comment by BBoldt** [comment]
This issue never went away.

**Comment by TheCricket** [comment]
Waat

**Comment by Drullkus** [comment]
GOOD JOB

**Comment by Altairon73** [comment]
aluminium stairs still not working. Any updates on this issue?

**Comment by Drullkus** [comment]
[We've almost got it fixed in 1.8 :P](https://twitter.com/Drullkus/status/697529966968242176)

**Comment by Altairon73** [comment]
thats good but more people use 1.7.10 :)

**Comment by Bogdan-G** [comment]
1.8.x is not popular and buggy 1.8.9, popular 1.7.10, do not ignore the obvious.

**Comment by Drullkus** [comment]
@Bogdan-G Do you think we make mods just to be bossed around by the end users? I don't think so :P

Have fun though, you spoiled brat. 

![https://pbs.twimg.com/media/Ca4fzxHUMAEky0t.jpg](https://pbs.twimg.com/media/Ca4fzxHUMAEky0t.jpg)

**Comment by tterrag1098** [comment]
Aluminum stairs were never meant to be implemented they were just a test. We don't even have any textures for them in the 1.7 version. This is a non-issue and only exists a reminder for me to remove the code that creates them.
