### ISSUE TITLE
Change Version of chisel

### ISSUE THREAD

**Issue by DeButcher4** [Chisel-Team/Chisel#913]
Hey, i have a question.

I play my minecraft server world in Forge 1.12.2, and i would like to change to forge 1.16.5, but i have used the chisel mod. When i change de version, i  have put the mod in the correct version (1.16.5) but when i play the game, the marble block and all the block that i chisel disappear but the mod run. I would like to know how to use the chisel mod in version 1.16.5 but the marble and chiseled blocks of version 1.12.2 do not disappear.

Thank you

**Comment by Andrey-007** [comment]
Hi
2 Questions
1. Enter the game, are the blocks visible?
2. Break the blocks, they don't fall out?

**Comment by The-Quarker** [comment]
I've experienced that before and all I tell is that the blocks are replaced with air

**Comment by tterrag1098** [comment]
This is unfortunately just how it is. The flattening meant we had to change almost all of our block IDs, and there's not a good way to remap metadata values to separate blocks.
