### ISSUE TITLE
Concrete gives faster speed

### ISSUE THREAD

**Issue by MauveSkydiver32** [Chisel-Team/Chisel#918]
For the chisel mod it makes me go faster on concrete and I don’t know how to fix it,

**Comment by Targren** [comment]
Pretty sure that's intentional. 

Check the config file. In the version I have in front of me, it looks like this. 
 
```
    # The factor that concrete_white increases your velocity. Default is 1.35, set to 1 for no change.
    D:concreteVelocityMult=1.35
```

**Comment by ghost** [comment]
its literally a feature and is awesome. your a god damn psychopath if u turn it off
