### ISSUE TITLE
Weird chisel rendering issue

### ISSUE THREAD

**Issue by YarinQuapi** [Chisel-Team/Chisel#921]
Minecraft version: 1.16.5
Chisel version: 2.0.1-alpha4
Forge version: 36.2.26

Mods that may interfere with rendering:
Magnesium (+extras), Sulfuric, Optifine is NOT present

The problem:
When placing chiseled blocks there is a weird rendering issue where the blocks aren't properly connected or textured, can be fixed by using f3+a.

images demonstrating it below
![2022-02-28_19 20 54](https://user-images.githubusercontent.com/41652571/156029364-2ab12f5c-4b52-4a27-b362-36bf5cd7e440.png)
![2022-02-28_19 20 57](https://user-images.githubusercontent.com/41652571/156029373-3d8afc49-5c54-4f25-a894-2cf3f43dac1d.png)
![2022-02-28_19 20 59](https://user-images.githubusercontent.com/41652571/156029391-1bd81c02-3cab-4b96-80b3-d956d6a89efd.png)
.

**Comment by tterrag1098** [comment]
This is a bug caused by element mods (Sodium, Magnesium, etc.) and their attempt at concurrent rendering.

**Comment by YarinQuapi** [comment]
Any idea how I might fix that?

**Comment by Chaos02** [comment]
> Any idea how I might fix that?

not use any rendering modifying mod other than optifine/connected textures
This is probably more of a compatibility issue on their end

**Comment by tterrag1098** [comment]
Or report it to the mod actually causing the issue.

**Comment by YarinQuapi** [comment]
Yeah that's a good idea

> Or report it to the mod actually causing the issue.
