### ISSUE TITLE
Stone bricks texture "roughbricks.png" not available in-game

### ISSUE THREAD

**Issue by BlocklockCity** [Chisel-Team/Chisel#93]
I initially updated to 2.9.4.10 to try to fix this.  I let the config regenerate, checked in the creative inventory search and in NEI, but the roughbricks.png texture just doesn't seem to be used.

**Comment by Drullkus** [comment]
So wait... There's a missing texture for one of the stonebricks variants in-game? This should not be possible.

**Comment by TehNut** [comment]
No I think it's that the texture doesn't have a block

**Comment by BlocklockCity** [comment]
TehNut is correct, sorry for not being clear.

**Comment by Drullkus** [comment]
Old textures were abandoned
