### ISSUE TITLE
Chisel in Better MC

### ISSUE THREAD

**Issue by Tyriss** [Chisel-Team/Chisel#932]
Added Chisel in modpack "Better MC [FORGE] 1.16.5" and all connection looks so wierd. CTM installed 
![image](https://user-images.githubusercontent.com/110307335/181976115-cca5ffcc-6e97-41b0-bd35-a985ac625079.png)

**Comment by Leclowndu93150** [comment]
looks like a performance mod issue ig

**Comment by Tyriss** [comment]
Issue solved by removed rubidium
