### ISSUE TITLE
Suggestions for Re-chiseled

### ISSUE THREAD

**Issue by Nevrai** [Chisel-Team/Chisel#937]
I’ve really missed Chisel in newer versions, so I’ve been enjoying [Re-chiseled](https://www.curseforge.com/minecraft/mc-mods/rechiseled) a lot! Here’s just a few suggestions that I think would improve the mod quite a bit. Every feature listed below was part of the original Chisel mod and are the features I think should be implemented the most in Re-chiseled.

1. Add a button to disable rotating. Personally, the block/blocks rotating in the GUI makes it quite annoying to select blocks, as you have to either wait until they’re rotated to see them or keep rotating them manually every second or two. A simple button to disable the blocks rotating in the chisel GUI would be a simple addition, yet a much appreciated one.

2. Add a “chisel all” button, which chisels all blocks of the same type (has to be the same type of chiselled block—e.g., zag) in your inventory to whatever you selected. Perhaps you could achieve this by holding the sneak key whilst pressing the chisel button like in the original Chisel.

3. Add factory blocks. The factory blocks were one of my favourite blocks in the original Chisel mod. Some of them had animated textures, such as moving fans. I’d also love to see the antiblocks (solid-coloured blocks with no visible hitbox), lavastone blocks, as well as the other unique blocks that Chisel added, but factory blocks were by far my favourite. 1.18.2 and 1.19.2 are pretty lacking in terms of nice industrial-looking blocks.

**Comment by SirEndii** [comment]
This is not the repository of re-chiseled

**Comment by Nevrai** [comment]
Whoops
