### ISSUE TITLE
1.8.9 Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [Chisel-Team/Chisel#95]
http://pastebin.com/NHz1xC4U

**Comment by Drullkus** [comment]
A client class is being loaded on a server -.-

**Comment by cauliflower69** [comment]
Every other mod in the pack functions fine. We are at about 110 loaded mods. Only this mod crashes on load

**Comment by cauliflower69** [comment]
The pack is Requiem 1.8.9 on Technic. I'll double check the mods
