### ISSUE TITLE
no recipes

### ISSUE THREAD

**Issue by pasulj95** [Chisel-Team/Chisel#96]

**Comment by kwpugh** [comment]
No recipe for chisel and crashes if you try the iron ingot and stick.

**Comment by pasulj95** [comment]
http://imgur.com/a/F2NT5

**Comment by CubeTwo** [comment]
Same problem have no recipes http://imgur.com/a/Nqn7J
my mods and forge http://imgur.com/jdbKniY

**Comment by Alaric323** [comment]
Also, missing the majority of translations, at least in JEI.
![capture](https://cloud.githubusercontent.com/assets/4038592/12329110/bbe227a0-baac-11e5-9d9f-90dcfde495f2.PNG)

Not to mention that half of them can't be crafted cause we're missing items like certus quartz and copper, but I know you guys aren't to blame for that. :P

**Comment by minecreatr** [comment]
Recipes have not been implemented in 1.8.9 yet, that is one of the reasons it is alpha.

**Comment by minecreatr** [comment]
Recipes have not been implemented in 1.8.9 yet, that is one of the reasons it is alpha.

**Comment by tterrag1098** [comment]
It's still a bug though.
