### ISSUE TITLE
Branch Version Release Request - 1.8.9

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#97]
Hey I have been using this mod since 1.5.4 and I really enjoy it now that far more stable and high performance 1.8.9 is over shadowing 1.7.10 I was wondering if you could start transferring your mod to a 1.8.9 branch.

**Comment by Drullkus** [comment]
[Brrrruuuuuh](http://minecraft.curseforge.com/projects/chisel/files/2275174)

**Comment by P3rf3ctXZer0** [comment]
Hehe ... I didn't see that...

**Comment by alexbegt** [comment]
@Drullkus be nice to @DPxKnightxZero or no movies for u <3

**Comment by Drullkus** [comment]
@DPxKnightxZero I don't blame you, it's only been 10 hours since we released it, the word needs time to spread (help us by spreading it!)

It, however, is still riddled with bugs... :<

**Comment by P3rf3ctXZer0** [comment]
I will do my best to test and report things : D thanks for your continued support for your mod : D
