### ISSUE TITLE
1.8.9 - Server Startup Crash 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Chisel-Team/Chisel#99]
Crash Log -> https://gist.github.com/DPxKnightxZero/693cf5e9b3a17fb583b9
Full Client Log -> https://gist.github.com/DPxKnightxZero/42bfd2ebcd127fafac56

**Comment by alexbegt** [comment]
Dupe of #95, Fix waiting in PR for @minecreatr or @tterrag1098 to check.

**Comment by Drullkus** [comment]
Duplicate of #95

**Comment by P3rf3ctXZer0** [comment]
Roger
